"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "en.json",
    "translation": "%two_letters_code%.json",
    "languages_mapping": {
      "two_letters_code": {
        "pt-BR": "pt-br"
      }
    }
  },
  {
    "source": "v2/en.json",
    "translation": "v2/%two_letters_code%.json",
    "languages_mapping": {
      "two_letters_code": {
        "pt-BR": "pt-br"
      }
    }
  }
]
