export default {
  "Dashboard": "Dashboard",
  "Back to spaces": "Torna agli spazi",
  "Content": "Contenuto",
  "Commerce": "Commercio",
  "Assets": "Risorse",
  "Datasources": "Datasource",
  "Activities": "Attività",
  "Tasks": "Attività",
  "Components": "Componenti",
  "Apps": "App",
  "Settings": "Impostazioni",
  "Subscription": "Iscrizione",
  "Plugins": "Plugin",
  "Logout": "Logout",
  "Report a problem": "Segnala un problema",
  "Create new space": "Crea un nuovo spazio",
  "Search spaces...": "Cerca spazi...",
  "My organization": "La mia organizzazione",
  "Subscribe": "Iscriviti",
  "To": "A",
  "From": "Da",
  "Apply filter": "Applica filtro",
  "Filter": "Filtro",
  "Unknown user": "Utente sconosciuto",
  "Author": "Autore",
  "Action": "Azione",
  "Date": "Data",
  "Back": "Indietro",
  "Activity Details": "Dettagli attività",
  "Open": "Apri",
  "Restore this Story": "Ripristina questa Storia",
  "Categories": "Categorie",
  "Story": "Storia",
  "The item has been restored!": "L'elemento è stato ripristinato!",
  "All": "Tutti",
  "Search for apps, discover new field types and add functionalities to your Storyblok project.": "Cerca app, scopri nuovi tipi di campi e aggiungi funzionalità al tuo progetto Storyblok.",
  "My apps": "Le mie app",
  "Create new app": "Crea una nuova app",
  "Installed": "Installato",
  "App Directory": "Directory app",
  "There are no apps in this category.": "Non ci sono app in questa categoria",
  "Install": "Installa",
  "Choose the space to install this app": "Scegli lo spazio in cui installare questa app",
  "Can not move asset folder into folder without permissions.": "Impossibile spostare la cartella delle risorse in una cartella senza autorizzazioni.",
  "Can not move asset into folder without permissions.": "Impossibile spostare la risorsa nella cartella senza autorizzazioni.",
  "Can not move asset away from folder without permissions.": "Impossibile spostare la risorsa dalla cartella senza autorizzazioni.",
  "Define the new name of the folder.": "Definisci il nome della cartella.",
  "Trashbin": "Cestino",
  "Are you sure that you want to delete this folder?": "Sei sicuro di voler eliminare questa cartella?",
  "Add": "Aggiungi",
  "Asset folders are not included in the free plan but you can try them in the": "Le cartelle delle risorse non sono incluse nel piano gratuito ma puoi provarle nel",
  "New folder will be created in": "La nuova cartella verrà creata in",
  "trial period": "periodo di prova",
  "Can not create asset folder without permission for parent.": "Impossibile creare la cartella delle risorse senza autorizzazione per l'elemento genitore.",
  "Original": "Originale",
  "Done": "Fatto",
  "Cancel": "Cancella",
  "Insert": "Inserisci",
  "Add Asset(s)": "Aggiungi Risorsa(e)",
  "Close": "Chiudi",
  "items": "Elementi",
  "Delete": "Cancella",
  "Move to folder": "Sposta nella cartella",
  "Replace": "Sostituisci",
  "Unselect all": "Deseleziona tutto",
  "Restore": "Ripristina",
  "Tiles": "Riquadri",
  "List": "Lista",
  "No assets found": "Nessuna risorsa trovata",
  "Sort": "Ordina",
  "Default": "Predefinito",
  "View": "Visualizza",
  "Creation date (asc)": "Data di creazione (asc)",
  "Filename (asc)": "Nome file (asc)",
  "Creation date (desc)": "Data di creazione (desc)",
  "Filename (desc)": "Nome file (desc)",
  "Last updated date (asc)": "Data ultimo aggiornamento (asc)",
  "Last updated date (desc)": "Data ultimo aggiornamento (descrizione)",
  "You are not allowed to insert this filetype here.": "Non puoi inserire questo tipo di file qui.",
  "This key is already defined": "Questa chiave è già definita",
  "Key is in invalid format": "La chiave è in un formato non valido",
  "Something went wrong uploading some items": "Si è verificato un errore durante il caricamento di alcuni elementi",
  "Please choose a folder in the left sidebar": "Scegli una cartella nella barra laterale sinistra",
  "Define the new name of": "Definisci il nuovo nome di",
  "Something went wrong renaming the attribute": "Qualcosa è andato storto durante la modifica del nome dell'attributo",
  "Be aware! Changing the name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Stai attento! La modifica del nome può richiedere alcuni minuti per aggiornare tutti gli elementi di contenuto. Assicurati che i tuoi editor abbiano salvato il lavoro svolto e chiudi l'editor.",
  "Define the new name of the component group.": "Definisci il nuovo nome del gruppo di componenti.",
  "Save": "Salva",
  "Are you sure that you want to delete this component group?": "Sei sicuro di voler eliminare questo gruppo di componenti?",
  "Copy": "Copia",
  "New": "Nuovo",
  "Move to group": "Sposta nel gruppo",
  "Please choose a component group in the left sidebar": "Scegli un gruppo di componenti nella barra laterale sinistra",
  "Paste": "Incolla",
  "Add block": "Aggiungi blocco",
  "Creation of a component failed. Maybe it already exists.": "Creazione di un componente non riuscita. Forse esiste già.",
  "Are you sure you want to DELETE this component(s)?": "Sei sicuro di voler eliminare questo(i) componente(i)?",
  "new": "nuovo",
  "Type to search or to create a": "Digita per cercare o per creare un",
  "Create new": "Crea nuovo",
  "block": "blocco",
  "New Component": "Nuovo elemento",
  "Updated": "Aggiornato",
  "Name": "Nome",
  "Shortcuts: Esc, Control + S": "Scorciatoie: Esc, Control + S",
  "Next": "Successivo",
  "Define a name": "Scegli un nome",
  "Save schema": "Salva lo schema",
  "Act as content type (eg. blog-post)": "Agisci come tipo di contenuto (ad es. post blog)",
  "Define": "Definisci",
  "Nestable": "Impilabile",
  "Technical name": "Nome tecnico",
  "Edit field": "Modifica campo",
  "Config": "Configurazione",
  "Schema": "Schema",
  "Renaming": "Ridenominazione",
  "Change field name": "Cambia il nome del campo",
  "Used in the json as component name": "Utilizzato nel json come nome del componente",
  "Be aware! Changing the technical name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Stai attento! La modifica del nome tecnico può richiedere alcuni minuti per permettere che tutti gli elementi di contenuto siano aggiornati. Assicurati che i tuoi editor abbiano salvato il lavoro svolto e chiudi l'editor.",
  "Display name": "Mostra nome",
  "Preview template": "Anteprima template",
  "Screenshot or icon": "Screenshot o icona",
  "Used in the editor interface only": "Utilizzato solo nell'interfaccia dell'editor",
  "of this setting": "di questa impostazione",
  "Read the documentation": "Leggi la documentazione",
  "Load versions": "Carica versioni",
  "Versions": "Versioni",
  "has been added below": "è stato aggiunto di seguito",
  "Examples: news_items, body, columns, title, description or call_to_action_btn": "Esempi: news_items, body, columns, title, description or call_to_action_btt",
  "The component has been restored!": "Il componente è stato ripristinato!",
  "Do you really want to leave without saving your changes?": "Vuoi davvero uscire senza salvare le modifiche?",
  "Type": "Tipo",
  "Beta": "Beta",
  "Translatable": "Traducibile",
  "Allow empty paragraphs": "Consenti paragrafi vuoti",
  "Linktype": "Tipo di link",
  "Rich-text as default": "Rich-text di default",
  "Custom type": "Tipo di personalizzazione",
  "Category": "Categoria",
  "Section items": "Articoli della sezione",
  "Product": "Prodotto",
  "Customize toolbar": "Personalizza barra degli strumenti",
  "Toolbar items": "Elementi della barra degli strumenti",
  "Source": "Fonte",
  "CSS class options (label/value)": "Opzioni classe CSS (etichetta/valore)",
  "Datasource": "Datasource",
  "Stories": "Storie",
  "Self": "Personale",
  "Internal datasource": "Datasource interno",
  "Recommended to be checked, as UID is required for automatic link resolving.": "Da verificare (consigliato), poiché l'UID è necessario per la risoluzione dei collegamenti automatici.",
  "Use UID instead of ID": "Usa UID invece di ID",
  "In case you have a multi-language folder structure you can add the {0} placeholder and the path will be adapted dynamically. Examples: {0}/categories/, {0}/{1}/categories/": "Se disponi di una struttura di cartelle multilingue puoi aggiungere il placeholder {0} e il percorso verrà adattato in modo dinamico. Esempi: {0}/categories/, {0}/{1}/categories/",
  "External JSON": "JSON esterno",
  "Path to folder of stories": "Percorso della cartella delle storie",
  "Width": "Larghezza",
  "URL": "URL",
  "ratio": "ratio",
  "pixel": "pixel",
  "Allowed maximum": "Massimo consentito",
  "Options (name/value)": "Opzione (nome/valore)",
  "Component(s)": "Componente(i)",
  "Group(s)": "Gruppo(i)",
  "Required field(s) (comma separated)": "Campi obbligatori (separati da virgola)",
  "Required": "Obbligatorio",
  "Default asset folder": "Cartella delle risorse predefinita",
  "Choose an asset folder where the assets should be assigned to.": "Scegli una cartella a cui assegnare le risorse.",
  "With {level} the path will be replaced dynamically using parts of the current slug. Examples: {0}/categories/, {0}/{1}/categories/": "Con {level} il percorso verrà sostituito in modo dinamico usando parti dello slug corrente. Esempi: {0}/categories/, {0}/{1}/categories/",
  "Restrict to folder": "Limita a cartella",
  "Force folder restriction": "Forza le restrizioni relative alle cartelle",
  "Regex validation": "Convalida Regex",
  "Exclude from export": "Escludi dall'esportazione",
  "export app": "esporta app",
  "To use with the": "Da usare con",
  "Default value": "Valore predefinito",
  "Can be updated by preview window": "Può essere aggiornato dalla finestra di anteprima",
  "Loading...": "In fase di caricamento...",
  "Item": "Elemento",
  "Allow only specific components to be inserted": "Consenti di inserire solo componenti specifici",
  "Restrict to content types": "Limita a tipi di contenuto",
  "Keep original size": "Mantieni dimensioni originali",
  "Force crop": "Forza taglio",
  "Prepend https to url": "Anteponi https all'URL",
  "Height": "Altezza",
  "Maximum characters": "Numero massimo di caratteri",
  "Disable time selection": "Disabilita la selezione dell'ora",
  "Description": "Descrizione",
  "dimensions app": "dimensioni app",
  "Force overwrite by merge action": "Forza la sovrascrittura mediante azione di merge",
  "Id/Slug": "ID/Slug",
  "Enable RTL (Right to left)": "Abilita RTL (da destra a sinistra)",
  "Autosave": "Autosalvataggio",
  "API Url": "Url API",
  "Export": "Esporta",
  "Import/Export": "Importazione/Esportazione",
  "Dimensions": "Dimensioni",
  "Add Dimension": "Aggiungi Dimensione",
  "Import": "Importa",
  "A datasource in Storyblok is a collection of key-value pairs.": "Un datasource in Storyblok è una raccolta di coppie chiave-valore.",
  "Datasources can be used in a schema definition of a component for single or multiple choice options. You can also access": "I datasource possono essere utilizzati in una definizione dello schema di un componente per opzioni a scelta singola o multipla. Puoi anche accedere a",
  "datasource entries from the API": "dati datasource dall'API",
  "to use them for labels, categories or similar.": "per utilizzarli per etichette, categorie o simili.",
  "Unsaved Changes": "Modifiche non salvate",
  "Datasource entries": "Voci datasource",
  "Datasources are not included in the free plan": "I datasource non sono inclusi nel piano gratuito",
  "but you can try them in the": "ma puoi provarli nel",
  "Saved": "Salvato",
  "Select all": "Seleziona tutto",
  "The options could not be loaded.": "Non è stato possibile caricare le opzioni.",
  "New Datasource": "Nuovo Datasource",
  "The following component(s) can not be pasted here": "I seguenti componenti non possono essere incollati qui",
  "Please save first to continue editing child components.": "Salva per continuare a modificare i componenti figlio.",
  "Enabled?": "Abilitato?",
  "Asset manager": "Gestione risorse",
  "Loading": "Caricamento",
  "Upload new": "Carica nuovo",
  "Your file exceeds the maximum filesize limit of": "Il tuo file supera il limite massimo di dimensione del file",
  "Please reduce the size of your file.": "Riduci le dimensioni del file.",
  "Alt text": "Testo ALT",
  "Base64": "Base64",
  "Original Size": "Dimensione originale",
  "Image loading failed": "Caricamento dell'immagine non riuscito",
  "Quote": "Citazione",
  "Code Block": "Blocco codice",
  "Ordered List": "Lista ordinata",
  "Headline 2": "Titolo 2",
  "Headline 4": "Titolo 4",
  "Headline 3": "Titolo 3",
  "Headline 5": "Titolo 5",
  "Paragraph": "Paragrafo",
  "Help": "Aiuto",
  "Internal link": "Link interno",
  "Show only selected": "Mostra solo gli elementi selezionati",
  "more items found": "più articoli trovati",
  "Invoices": "Fatture",
  "Tip: Use Ctrl + S to save": "Suggerimento: usa Ctrl + S per salvare",
  "Input": "Input",
  "Publish": "Pubblica",
  "You are not allowed to edit this plugin but can see the code at Settings/Details.": "Non sei autorizzato a modificare questo plugin ma puoi vedere il codice in Impostazioni/Dettagli.",
  "Field type preview": "Anteprima del tipo di campo",
  "Options (key/value)": "Opzioni (chiave/valore)",
  "Space Id": "ID spazio",
  "Enable local dev mode": "Abilita la modalità di sviluppo locale",
  "Settings/Details": "Impostazioni/Dettagli",
  "Output": "Output",
  "for approval to make it available for all users.": "per l'approvazione per renderlo disponibile a tutti gli utenti.",
  "Submit the plugin": "Invia il plugin",
  "Code": "Codice",
  "You can copy the code of this plugin to create your own plugin.": "Puoi copiare il codice di questo plugin per creare il tuo.",
  "Assigned spaces": "Spazi assegnati",
  "If you assign this plugin to a space other developers can also use it in the schema definition. Without assigning it only you can add the plugin to the schemas.": "Se questo plug-in è assegnato a uno spazio, potrà essere utilizzato da altri sviluppatori nella definizione dello schema. Solo senza assegnarlo sarà possibile aggiungerlo agli schemi.",
  "Attention: All spaces using this plugin will not be able to use it any more if you click delete.": "Attenzione: tutti gli spazi che utilizzano questo plug-in non potranno più utilizzarlo se si clicca l'opzione \"Elimina\".",
  "Documentation": "Documentazione",
  "Danger zone": "Zona pericolosa",
  "What is a field type plugin?": "Che cos'è un plug-in tipo di campo?",
  "A field type plugin extends the Storyblok editor with your own custom field types.": "Un plug-in di tipo di campo estende l'editor Storyblok con i tuoi tipi di campi personalizzati.",
  "It is basically a": "È fondamentalmente un",
  "The properties that are passed to the field type are:": "Le titolarità che vengono passate al tipo di campo sono:",
  "component extended with a few helpers in the window.Storyblok.plugin mixin.": "componente esteso con alcuni helper in window.Storyblok.plugin mixin.",
  "Examples for field types are colorpickers, WYSYWYG editors or meta tags.": "Alcuni esempi di tipi di campo sono: colorpicker, editor WYSIWYG o metatag.",
  "Uid of the parent component": "Uid del componente genitore",
  "Options parsed from the schema options array": "Opzioni analizzate dall'array delle opzioni dello schema",
  "Schema options object": "Oggetto opzioni schema",
  "Current value of the fieldtype": "Valore corrente del tipo di campo",
  "Story id of the current story": "ID storia della storia attuale",
  "Space id of the current space": "ID spazio dello spazio corrente",
  "Api function to call the delivery api": "Funzione API per chiamare l'API di consegna",
  "Methods": "Metodi",
  "Draft token of the current space": "Token di bozza dello spazio corrente",
  "How to call the Storyblok api?": "In che modo va richiamata l'API Storyblok?",
  "Should be used to define the initial data of the plugin.": "Dovrebbe essere usato per definire i dati iniziali del plugin.",
  "Should be used to initialize the plugin. Examples: Load data from Storyblok or external sources, Load and initialize a WYSIWYG editor.": "Dovrebbe essere usato per inizializzare il plugin. Esempi: carica dati da Storyblok o fonti esterne, Carica e inizializza un editor WYSIWYG.",
  "To pass options that are configurable in the schema definition define the option keys in the \"Input\" box. The values will be available in the this.options object.": "Per passare le opzioni configurabili nella definizione dello schema, definire le chiavi di opzione nella casella \"Input\". I valori saranno disponibili nell'oggetto this.options.",
  "How to pass options?": "Come si passano le opzioni?",
  "In field types you can use this.api to get access to the Storyblok delivery api. You can use it for example to build a selectbox of stories.": "Nei tipi di campo puoi usare this.api per ottenere l'accesso all'API di consegna di Storyblok. Puoi usarlo, ad esempio, per costruire un riquadro di selezione delle storie.",
  "Folder/Content-item permissions": "Autorizzazioni per cartella/contenuto",
  "Item saved successfully!": "Articolo salvato con successo!",
  "Source of sync": "Fonte di sincronizzazione",
  "Preview": "Anteprima",
  "Preview url": "Anteprima url",
  "View on Jsfiddle": "Visualizza su Jsfiddle",
  "Download": "Scarica",
  "Admin": "Amministratore",
  "Permissions": "Permessi",
  "Editor": "Editor",
  "Advanced Rights": "Diritti avanzati",
  "Allow saving content": "Consenti il salvataggio dei contenuti",
  "Allow publishing content": "Consenti la pubblicazione di contenuti",
  "Allow saving datasources": "Consenti il salvataggio dei datasource",
  "Allow managing subscription": "Consenti la gestione dell'iscrizione",
  "Allow access to ecommerce app": "Consenti l'accesso all'app dell'e-commerce",
  "Deny access to visual composer": "Nega l'accesso al visual composer",
  "Field Permissions": "Autorizzazioni campi",
  "General": "Generale",
  "Allowed path": "Percorso consentito",
  "Your crawl URL": "L'URL del tuo crawler",
  "Crawler": "Crawler",
  "Enabled": "Abilitato",
  "Index": "Indice",
  "Crawl now": "Avvia analisi ora",
  "Information needed to access the search endpoint or to configure the search client.": "Informazioni necessarie per accedere all'endpoint di ricerca o per configurare il client di ricerca.",
  "Search Setup Guide": "Guida alla configurazione della ricerca",
  "Your tenant ID": "ID occupante",
  "See": "Visualizza",
  "Documents in index": "Documenti nell'indice",
  "Crawl requested at": "Scansione richiesta a",
  "Tenant ID": "ID occupante",
  "Documents": "Documenti",
  "Clear index": "Cancella indice",
  "Last crawled at": "Ultima analisi alle",
  "Crawl has been initiated": "La ricerca per indicizzazione è stata avviata",
  "In the first 14 days you can try out all Premium plan features!": "Nei primi 14 giorni puoi provare tutte le funzionalità del piano Premium!",
  "Index deletion has been initiated": "La cancellazione dell'indice è stata avviata",
  "API-Keys": "Chiavi API",
  "We would love to hear your thoughts about Storyblok on": "Ci piacerebbe sentire la tua opinione su Storyblok",
  "Renderer": "Renderer",
  "Backup": "Backup",
  "Users": "Utenti",
  "Workflow": "Flusso di lavoro",
  "Search": "Cerca",
  "Languages": "Lingue",
  "This is the page that the frontend-editor opens.": "Questa è la pagina che apre l'editor di front-end.",
  "Location (default environment)": "Posizione (ambiente predefinito)",
  "Insert your domain/location including the protocol. Example: http://www.example.com/": "Inserisci il tuo dominio, incluso il protocollo. Esempio: http://www.example.com/",
  "Provide this ID in your support tickets": "Fornisci questo ID nei tuoi ticket di supporto",
  "Your space ID": "ID del tuo spazio",
  "Preview urls": "Anteprima URL",
  "Define multiple domains/locations to quickly switch the preview urls in the story-editor.": "Definisci più domini/posizioni per cambiare rapidamente gli URL di anteprima nell'editor di storie.",
  "Add preview url": "Aggiungi l'anteprima dell'URL",
  "Webhooks": "WebHook",
  "Story published & unpublished": "Storia pubblicata e non pubblicata",
  "Story saved": "Storia salvata",
  "Branch deployed": "Branch distribuito",
  "Release merged": "Release dopo il merge",
  "Slack integration": "Integrazione Slack",
  "Loading... You will be redirect to Slack in a few seconds!": "In fase di caricamento... Sarai reindirizzato a Slack in pochi secondi!",
  "Get notified on your Slack channel if a new Story has been published!": "Ricevi una notifica sul tuo canale Slack quando viene pubblicata una nuova storia!",
  "With this integration you can choose a Slack channel where Storyblok posts messages whenever a user publishes new content.": "Con questa integrazione puoi scegliere un canale Slack in cui Storyblok pubblicherà dei messaggi ogni volta che un utente caricherà nuovi contenuti.",
  "Disconnect": "Disconnetti",
  "Cloud name": "Nome cloud",
  "Cloudinary integration": "Integrazione Cloudinary",
  "Api Key": "Chiave API",
  "Branches": "Branch",
  "Default content type": "Tipo di contenuto predefinito",
  "Content types": "Tipi di contenuto",
  "Name of the branch": "Nome del branch",
  "Branches are not included in the free plan": "I branch non sono inclusi nel piano gratuito",
  "Duplication": "Duplicazione",
  "This is useful if you want to offer your space for other users as a boilerplate or theme.": "Uutile se vuoi offrire il tuo spazio ad altri utenti (blocco di testo o tema).",
  "ATTENTION! Only check this checkbox if you are sure that you want all data of this space available for duplication.": "ATTENZIONE! Seleziona questa casella di controllo solo se sei sicuro di voler rendere disponibili tutti i dati di questo spazio per la duplicazione.",
  "Make this space duplicatable by all users": "Rendi questo spazio duplicabile da tutti gli utenti",
  "Content ownership": "titolarità dei contenuti",
  "Parent ID": "ID genitore",
  "Parent": "Genitore",
  "Image service": "Servizio immagini",
  "Content ownership client endpoint": "Endpoint client titolarità del contenuto",
  "List of paths to invalidate": "Elenco di percorsi da invalidare",
  "Delete this space": "Cancella questo spazio",
  "Invalidate": "Invalida",
  "Workflow webhooks": "WebHook del flusso di lavoro",
  "Owner": "Proprietario",
  "Workflow changed": "Flusso di lavoro modificato",
  "Transfer ownership": "Trasferisci la titolarità",
  "Transfer": "Trasferisci",
  "Attention! Transferring the ownership will remove all your rights to this space.": "Attenzione! Il trasferimento della titolarità rimuoverà tutti i tuoi diritti su questo spazio.",
  "The owner needs to add you as a collaborator if you want to have access again.": "Se vorrai avere di nuovo accesso, il proprietario dovrà aggiungerti come collaboratore.",
  "Collaborators": "Collaboratori",
  "Collaborator": "Collaboratore",
  "No user found with this email or username.": "Nessun utente trovato con questa e-mail o nome utente.",
  "Name of the role": "Nome del ruolo",
  "Role": "Ruolo",
  "Add a new user to your org": "Aggiungi un nuovo utente alla tua organizzazione",
  "Advanced rights and roles are not included in the free and basic plan": "Diritti e ruoli avanzati non sono inclusi nel piano gratuito e di base",
  "Use your Amazon S3 bucket to create backups.": "Usa il tuo bucket Amazon S3 per creare backup.",
  "Backup now": "Esegui subito il backup",
  "Backups content (stories) and compontents": "Contenuto di backup (storie) e componenti",
  "Define your S3-Bucket and AWS-ARN to enable backups.": "Definisci il tuo S3-Bucket e AWS-ARN per abilitare i backup.",
  "Daily backups": "Backup giornalieri",
  "Define the name of the S3-bucket where you want to store your backups.": "Definisci il nome del bucket S3 in cui desideri archiviare i backup.",
  "S3-bucket": "S3-bucket",
  "Activate automatic daily backups": "Attiva backup giornalieri automatici",
  "1. Read the": "1. Leggi il",
  "AWS Policy ARN": "AWS Policy ARN",
  "Show setup instructions": "Mostra le istruzioni di installazione",
  "tutorial on how to setup an Amazon IAM role": "tutorial su come impostare un ruolo Amazon IAM",
  "2. Create an Amazon IAM role with following access policy document:": "2. Crea un ruolo Amazon IAM con il seguente documento sulla politica di accesso:",
  "if not done yet.": "se non ancora fatto.",
  "The role should have the permission to access and create files on the S3 bucket you defined. You can for example use the following permission policy replacing YOUR_BUCKET with your bucket name:": "Il ruolo dovrebbe essere in possesso dell'autorizzazione per accedere e creare file sul bucket S3 che hai definito. Ad esempio, puoi utilizzare la seguente politica di autorizzazione sostituendo YOUR_BUCKET con il nome del tuo bucket:",
  "Restore spaces from backups on your Amazon S3 bucket.": "Ripristina gli spazi dai backup sul tuo bucket Amazon S3.",
  "Backup file": "File di backup",
  "Show latest backups": "Mostra i backup più recenti",
  "Latest five backups": "Ultimi cinque backup",
  "Restore now": "Ripristina ora",
  "The settings below only apply if you are using": "Le impostazioni seguenti si applicano solo se si sta utilizzando",
  "Attention! \"Restore now\" deletes old data and restores content (stories) and compontents from the backup file.": "Attenzione! \"Ripristina ora\" elimina i vecchi dati e ripristina il contenuto (storie) e i componenti dal file di backup.",
  "Rendering service": "Servizio di rendering",
  "Your domain": "Il tuo dominio",
  "To connect your domain to Storyblok you need to create a CNAME Record pointing to eu-domain.storyblok.com": "Per connettere il tuo dominio a Storyblok devi creare un record CNAME che indirizza a eu-domain.storyblok.com",
  "Routes": "Percorsi",
  "Add Route": "Aggiungi Percorso",
  "Please read the": "Per favore, consulta",
  "Add custom routes to define different page templates.": "Aggiungi percorsi personalizzati per definire diversi modelli di pagina.",
  "documentation about internationalization": "documentazione sull'internazionalizzazione",
  "before configuring languages.": "prima di configurare le lingue.",
  "Add languages to activate field level translations.": "Aggiungi lingue per attivare le traduzioni a livello di campo.",
  "Add Language": "Aggiungi lingua",
  "Label": "Etichetta",
  "The invalidation process has been initiated": "Il processo di annullamento è stato avviato",
  "The backup has been initiated": "Il backup è stato avviato",
  "Are you sure you want to delete your current content and overwrite it with this backup?": "Sei sicuro di voler eliminare il contenuto corrente e sovrascriverlo con questo backup",
  "The restore process has been initiated": "La procedura di ripristino è stata avviata",
  "Transfer was not successful. Make sure that the new owner exists.": "Il trasferimento non è andato a buon fine. Assicurati che il nuovo proprietario esista.",
  "The collaborator has been added": "Il collaboratore è stato aggiunto",
  "Please insert an email address": "Inserisci un indirizzo e-mail",
  "Branches sorted successfully!": "I branch sono stati ordinati correttamente!",
  "Create or join a space": "Crea o unisciti a uno spazio",
  "Create a new space": "Crea un nuovo spazio",
  "Play with a demo": "Prova una demo",
  "Duplicate a space": "Duplica uno spazio",
  "Join a space": "Entra in uno spazio",
  "Create space": "Crea spazio",
  "Headless (API/SDKs)": "Headless (API/SDK)",
  "what is that?": "che cos'è?",
  "Duplicate space": "Duplica spazio",
  "Choose the space for the duplication": "Scegli lo spazio per la duplicazione",
  "You do not have created any spaces yet.": "Non hai ancora creato alcuno spazio.",
  "You can test the editing interface and our visual composer without to write any code on your own.": "Puoi testare l'interfaccia di modifica e il nostro visual composer senza la necessità di scrivere alcun codice.",
  "Create Demo": "Crea una demo",
  "Insert the email of your space admin to let them add you as a collaborator of the space.": "Inserisci l'e-mail dell'amministratore del tuo spazio per consentirgli di aggiungerti come collaboratore dello stesso.",
  "Request access": "Richiedi accesso",
  "Email address of space admin": "Indirizzo e-mail dello spazio amministratore",
  "Success! You will get notified once the admin added you as a collaborator.": "Evviva! Riceverai una notifica non appena l'amministratore ti avrà aggiunto come collaboratore.",
  "Available Billing Information": "Informazioni di fatturazione disponibili",
  "No spaces with billing information available": "Nessuno spazio con informazioni di fatturazione disponibile",
  "Spaces": "Spazi",
  "Show More": "Mostra di più",
  "Apply": "Applica",
  "Show": "Mostra",
  "Billing Information of Space": "Informazioni di fatturazione dello spazio",
  "The information below will be applied to the fields of your current subscription process. You will be able to adopt them after applying them.": "Le informazioni di seguito verranno applicate ai campi della procedura di iscrizione corrente. Sarai in grado di utilizzarle dopo averle applicate.",
  "Company": "Azienda",
  "Country": "Paese",
  "Street / City / ZIP": "Via/Città/CAP",
  "Email": "E-mail",
  "Add or change preview urls": "Aggiungi o modifica gli URL di anteprima",
  "Your server address": "L'indirizzo del tuo server",
  "1. Download a preconfigured project": "1. Scarica un progetto preconfigurato",
  "Preferred by our users": "Preferito dai nostri utenti",
  "The downloaded package comes preconfigured with your api token": "Il pacchetto scaricato è già preconfigurato con i tuoi token API",
  "Tutorial": "Tutorial",
  "Other technologies": "Altre tecnologie",
  "2. Start your server": "2. Avvia il tuo server",
  "Start the server of the downloaded package and insert your server url here:": "Avvia il server del pacchetto scaricato e inserisci l'URL del server qui:",
  "Go": "Vai",
  "FAQ": "FAQ",
  "Can I build a full blown website with Storyblok?": "Posso creare un sito Web completo con Storyblok?",
  "Can I create a blog with Storyblok?": "Posso creare un blog con Storyblok?",
  "How does Storyblok work?": "Come funziona Storyblok?",
  "What is the Storyblok bridge?": "Cos'è il ponte Storyblok?",
  "Allow deploying content": "Consenti la distribuzione di contenuti",
  "General permissions": "Autorizzazioni generali",
  "Allow unpublishing content": "Consenti contenuti non pubblicati",
  "Allow deleting content": "Consenti l'eliminazione del contenuto",
  "Allow editing datasource keys & values": "Consenti la modifica di chiavi e valori del datasource",
  "Allow editing datasource values": "Consenti modifica dei valori del datasource",
  "Allow access to the tasks app": "Consenti l'accesso all'app delle attività",
  "Deny moving a story": "Nega lo spostamento di una storia",
  "Deny changing alternates group": "Nega cambio gruppo alternative",
  "Add languages the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Aggiungi le lingue a cui l'utente dovrebbe avere accesso (funge da whitelist). Se nessun elemento è selezionato, l'utente dispone dei diritti per modificare tutto il contenuto.",
  "Deny changing the slug of a story": "Nega la modifica della slug di una storia",
  "Add folders or content items the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Aggiungi cartelle o elementi di contenuto a cui l'utente dovrebbe avere accesso (funge da whitelist). Se nessun elemento è selezionato, l'utente dispone dei diritti per modificare tutto il contenuto.",
  "Component field permissions": "Autorizzazioni per i componenti",
  "Datasource permissions": "Autorizzazioni datasource",
  "Add component fields here to hide them in the interface.": "Aggiungi qui i campi dei componenti per nasconderli nell'interfaccia.",
  "Add datasources the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all datasources.": "Aggiungi i datasource a cui l'utente dovrebbe avere accesso (funge da whitelist). Se non viene selezionato alcun elemento, l'utente assume i diritti per modificare tutti i datasource.",
  "Asset Folder Permissions": "Autorizzazioni per la cartella delle risorse",
  "Add asset folders to restrict editing and upload access.": "Aggiungi cartelle di risorse per limitare l'accesso alla modifica e al caricamento.",
  "Start by selecting a space in the sidebar or create a new space.": "Inizia selezionando uno spazio nella barra laterale o crea un nuovo spazio.",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Sembra che tu non abbia ancora accesso a nessuno spazio. Contatta l'amministratore della tua organizzazione per essere aggiunto come collaboratore.",
  "Welcome!": "Benvenuto!",
  "Traffic": "Traffico",
  "Learn more about": "Scopri di più su",
  "Api requests": "Le richieste API",
  "Active Plan": "Piano attivo",
  "Usage": "Utilizzo",
  "Content activities": "Attività di contenuto",
  "No billing": "Nessuna fatturazione",
  "Change": "Modifica",
  "Billed": "Fatturato",
  "No recent changes": "Nessuna modifica recente",
  "Choose your plan": "Scegli il tuo piano",
  "Recent changes": "Modifiche recenti",
  "Custom": "Personalizza",
  "Compare": "Confronta",
  "user": "utente",
  "Got a custom plan or coupon code?": "Hai un piano personalizzato o un codice coupon?",
  "Custom plan": "Piano personalizzato",
  "Entered plan ids will be validated after pressing subscribe.": "Gli ID del piano immessi verranno convalidati dopo aver cliccato su \"Iscriviti\".",
  "Coupon code": "Codice coupon",
  "Entered coupon codes will be validated and applied after pressing subscribe.": "I codici coupon inseriti verranno convalidati e applicati dopo aver cliccato su \"Iscriviti\".",
  "Select seats": "Seleziona posti",
  "Confirm subscription": "Conferma iscrizione",
  "Min": "Min",
  "Max": "Massimo",
  "By clicking the button below the new subscription will start.": "Facendo clic sul pulsante in basso si avvierà una nuova iscrizione.",
  "Decide payment interval": "Stabilisci l'intervallo di pagamento",
  "Change subscription": "Cambia abbonamento",
  "Monthly": "Mensile",
  "Annually": "Una volta all'anno",
  "Define billing information": "Indica le informazioni di fatturazione",
  "Email address": "Indirizzo e-mail",
  "VAT-Number": "Partita IVA",
  "Reuse from another space": "Riutilizza da un altro spazio",
  "Order number": "Numero dell'ordine",
  "Street": "Via",
  "City": "Città",
  "Credit or debit card": "Carta di credito o debito",
  "ZIP": "ZIP",
  "Enter payment information": "Inserisci le informazioni di pagamento",
  "Update payment information": "Aggiorna informazioni di pagamento",
  "Update billing information": "Aggiornamento delle informazioni di fatturazione",
  "Information: Our payment provider validates card information when it is saved. As a result of this process, you may see a temporary authorization for $1 on your statement.": "Informazioni: il nostro fornitore di servizi di pagamento convalida i dati della carta al momento del salvataggio. Come risultato di questo processo, potresti veder comparire un'autorizzazione temporanea di 1 USD sul tuo estratto conto.",
  "Please provide all billing informations marked as required (*)": "Fornisci tutte le informazioni di fatturazione contrassegnate come obbligatorie (*)",
  "Your selected team sizes are not in the limits of your selected feature set. You can select another feature set to continue.": "Le dimensioni del team selezionato non rientrano nei limiti del set di funzionalità selezionato. Puoi selezionare un altro set di funzionalità per continuare.",
  "View invoices": "Visualizza fatture",
  "Summary": "Riepilogo",
  "Please provide a credit or debit card": "Fornisci una carta di credito o debito",
  "If your entered plan is not correct you will still be able to try it again.": "Se il piano inserito non è corretto, avrai comunque la possibilità di riprovare.",
  "You have entered a custom plan with a special offering and pricing": "Hai inserito un piano personalizzato con un'offerta e un prezzo speciali",
  "users": "utenti",
  "VAT reverse charge applies.": "Si applica l'inversione contabile all'IVA.",
  "VAT": "IVA",
  "Total": "Totale",
  "The benefits of the coupon code will be applied if available": "I vantaggi del codice coupon verranno applicati se disponibili",
  "Thanks! You are awesome!": "Grazie! Sei grande!",
  "We would love to hear what you think about Storyblok.": "Ci piacerebbe sapere cosa pensi di Storyblok.",
  "Chat with us or": "Chatta con noi o",
  "your feedback.": "il tuo feedback",
  "Tweet": "Tweet",
  "Star": "Segna con un asterisco",
  "Share": "Condividi",
  "Public access tokens are only for accessing the published version while preview tokens are for accessing the draft version also. Both are read-only tokens.": "I token di accesso pubblico servono solo per accedere alla versione pubblicata mentre i token di anteprima servono anche per accedere alla versione bozza. Entrambi sono token di sola lettura.",
  "Access level": "Livello di accesso",
  "Public": "Pubblico",
  "See API-Documentation": "Vedi documentazione API",
  "Theme": "Tema",
  "Branch": "Settore",
  "Choose branch": "Scegli sezione",
  "Create Token": "Crea Token",
  "Color": "Colore",
  "Define as default stage for new content items": "Definisci come fase predefinita per i nuovi elementi di contenuto",
  "Publishing rights": "Diritti di pubblicazione",
  "Stage transition rules": "Regole transizione fasi",
  "Allow users to publish or schedule the content": "Consenti agli utenti di pubblicare o programmare il contenuto",
  "Specific stage(s)": "Fase o fasi specifiche",
  "Next available stages": "Prossime fasi disponibili",
  "All stages": "Tutte le fasi",
  "All users": "Tutti gli utenti",
  "User(s)/Role(s) who can change the stage": "Utente(i)/Ruolo(i) che possono modificare la fase",
  "to the next available stage": "alla prossima fase disponibile",
  "Specific user(s)/role(s)": "Utente(i) specifico(i)/ ruolo(i)",
  "Role(s)": "Ruolo(i)",
  "User(s)": "Utente(i)",
  "Workflow stages": "Fasi del flusso di lavoro",
  "See workflow documentation": "Vedi la documentazione del flusso di lavoro",
  "Create": "Crea",
  "Choose an approver": "Scegli un responsabile dell'approvazione",
  "Workflow stages sorted successfully!": "Fasi del flusso di lavoro ordinate correttamente!",
  "Are you sure you want to delete this workflow stage?": "Sei sicuro di voler eliminare questa fase del flusso di lavoro?",
  "Send for approval": "Invia per l'approcazione",
  "Approval request has been sent successfully!": "La richiesta di approvazione è stata inviata con successo!",
  "Content items": "Articoli di contenuto",
  "Entry": "Voce",
  "Define schema": "Definire lo schema",
  "Folder": "Cartella",
  "You have not defined any schema for this block yet.": "Non hai ancora definito alcuno schema per questo blocco.",
  "Define presets": "Definisci preset",
  "Click \"Define schema\" to add the fields you need.": "Fai clic su \"Definisci schema\" per aggiungere i campi necessari.",
  "No valid fields defined in this section yet.": "In questa sezione non è stato ancora definito nessun campo valido.",
  "is already part of another section": "fa già parte di un'altra sezione",
  "Translate": "Traduci",
  "Choose to delete the values or add the schema keys.": "Sceglie di eliminare i valori o aggiungere le chiavi dello schema.",
  "items out of schema": "articoli fuori schema",
  "We have found values which are not part of the schema.": "Abbiamo trovato valori che non fanno parte dello schema.",
  "No changes found": "Non è stata trovata alcuna modifica",
  "Changes": "Modifiche",
  "Remove all": "Rimuovi tutto",
  "Select releases to deploy": "Seleziona le versioni da distribuire",
  "What is getting deployed?": "Cosa sta per essere rilasciato?",
  "All content that is currently on the source branch and the releases you select.": "Tutto il contenuto che si trova attualmente nel branch sorgente e nelle versioni selezionate.",
  "No releases found on the source branch": "Nessuna versione trovata sul branch di origine",
  "A newer version of this content item has been found in the database.": "Nel database è stata trovata una versione più recente di questo elemento di contenuto.",
  "Confirm": "Conferma",
  "Choose the conflict solution": "Scegli la soluzione del conflitto",
  "Copy over": "Copia su",
  "Opens newer version in a new window to let you copy over your changes.": "Apre la versione più recente in una nuova finestra per consentire di copiare le modifiche.",
  "Overwrite": "Sovrascrivi",
  "Slug": "Slug",
  "Overwrites newer version with your changes.": "Sovrascrive la versione più recente con le modifiche che hai apportato.",
  "Define as root for the folder": "Definire come root per la cartella",
  "Preset": "Preset",
  "Content type": "Tipo di contenuto",
  "Confirm deletion": "Conferma cancellazione",
  "Are you sure that you want to delete this item(s)?": "Sei sicuro di voler eliminare questo(i) elemento(i)?",
  "Include associated alternates": "Includi alternative associate",
  "Target-Folder": "Obiettivo-Cartella",
  "Is alternative version of the duplicate?": "È una versione alternativa del duplicato?",
  "Duplicate": "Duplica",
  "Schedule": "Programma",
  "duplicated": "duplicato",
  "You are not allowed to duplicate this story.": "Non ti è permesso duplicare questa storia.",
  "Open published": "Aperto pubblicato",
  "Send approval": "Invia approvazione",
  "Open draft": "Bozza incompleta",
  "Unpublish": "Rimuovi",
  "Draft json": "Bozza json",
  "Discard changes": "Non salvare le modifiche",
  "Start sync": "Avvia sincronizzazione",
  "Published json": "json pubblicato",
  "Status": "Status",
  "Tools": "Strumenti",
  "Real path": "Percorso reale",
  "Settings for the folder content": "Impostazioni per il contenuto della cartella",
  "Disable visual composer": "Disabilita il visual composer",
  "Clone to all": "Clona tutti",
  "Deny changing content type": "Nega la modifica del tipo di contenuto",
  "Merge to all": "Unisci con tutti",
  "Dimensions are only available if you are editing a content item in a subfolder.": "Le dimensioni sono disponibili solo se stai modificando un elemento di contenuto in una sottocartella.",
  "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).": "Crea una struttura di cartelle in cui la prima cartella definisce la tua dimensione (Esempio: de/home, en/home).",
  "Not created yet": "Non ancora creato",
  "Create clone": "Crea clone",
  "Merge": "Avvia il merge",
  "Something went wrong merging the alternate(s)": "Qualcosa è andato storto durante il merge delle alternative",
  "The alternate(s) have been created!": "La o le alternative sono state create!",
  "The alternate(s) have been merged!": "Il merge delle alternative è stato completato.",
  "Add preset": "Aggiungi preset",
  "Presets are blocks filled with the content you currently have in the selected block.": "I preset sono blocchi riempiti con il contenuto che hai attualmente nel blocco selezionato.",
  "Something went wrong creating the alternate(s)": "Qualcosa è andato storto durante la creazione della o delle alternativa(e)",
  "The saved presets are shown for all users at the selection of new blocks.": "I preset salvati vengono mostrati a tutti gli utenti al momento della selezione di nuovi blocchi.",
  "Existing presets": "Preset esistenti",
  "As default": "Come impostazione predefinita",
  "Release date (optional)": "Data di rilascio (opzionale)",
  "Branches to deploy": "Branch da installare",
  "When the release gets merged all content will be automatically deployed to the selected branches.": "Quando il merge sarà finalizzato, tutto il contenuto verrà automaticamente distribuito nei branch selezionati.",
  "Entry configuration": "Configurazione della voce",
  "Editmode": "Modalità di modifica",
  "Are you sure you want to delete this release?": "Sei sicuro di voler eliminare questa versione?",
  "Form only": "Solo modulo",
  "Visual": "Illustrazione",
  "Tags": "Etichette",
  "Sort by date": "Filtra per data",
  "First published date": "Prima data pubblicata",
  "Remove": "Rimuovi",
  "Alternative versions": "Versioni alternative",
  "Search for the content group of this story.": "Cerca il gruppo di contenuti di questa storia.",
  "Shortcut": "Scorciatoia",
  "Pin as shortcut in the mini-browser": "Appunta come scorciatoia nel mini-browser",
  "Current": "Attuale",
  "New release": "Nuova versione",
  "Skip this step": "Salta questo passaggio",
  "Move": "Sposta",
  "Next step": "Passaggio successivo",
  "We have already done that for you. Open the entry \"Home\" below to play around.": "Lo abbiamo già fatto per te. Apri la voce \"Home\" in basso per dare un'occhiata.",
  "Create a demo page": "Crea una pagina dimostrativa",
  "Create a new folder": "Crea una nuova cartella",
  "Create your first folder": "Crea la tua prima cartella",
  "and define a new content type during the folder set-up.": "e definisci un nuovo tipo di contenuto durante l'impostazione della cartella.",
  "Create your first entry": "Crea la tua prima voce",
  "Create entry": "Crea voce",
  "and define its fields by building its schema so you can fill it with content.": "e definisci i suoi campi costruendo il suo schema in modo da poterlo riempire di contenuto.",
  "Will be released at": "Sarà rilasciato il",
  "Show only items from this release": "Mostra solo gli elementi di questa versione",
  "Has been published at": "È stato pubblicato alle",
  "Last deployment": "Ultimo invio",
  "This branch has never been deployed": "Questo branch non è mai stato distribuito",
  "Release now": "Rilascia immediatamente",
  "Open preview": "Apri anteprima",
  "Deploy from source": "Distribuzione dalla fonte",
  "You are seeing deleted items": "Stai visualizzando elementi eliminati",
  "Name (desc)": "Nome (desc)",
  "Default sorting": "Ordinamento predefinito",
  "Name (asc)": "Nome (asc)",
  "Slug (desc)": "Slug (desc)",
  "releases": "release",
  "Slug (asc)": "Slug (asc)",
  "Created at": "Creato alle",
  "Updated at": "Aggiornato alle",
  "Deleted at": "Cancellato alle",
  "Are you sure you want to unpublish this item(s)?": "Sei sicuro di voler annullare la pubblicazione di questo/i articolo/i?",
  "The items have been updated!": "Gli articoli sono stati aggiornati!",
  "Are you sure you want to publish this item(s)?": "Sei sicuro di voler pubblicare questo(i) articolo(i)?",
  "Are you sure you want to restore this item(s)?": "Sei sicuro di voler ripristinare questo(i) articolo(i)?",
  "Something went wrong restoring some items": "Si è verificato un errore durante il ripristino di alcuni elementi",
  "Something went wrong updating item(s)": "Si è verificato un errore durante l'aggiornamento degli articoli",
  "No tools installed on this space": "Nessuno strumento installato su questo spazio",
  "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.": "Gli elementi eliminati non possono essere visualizzati. Clicca sulla casella dell'elemento e ripristina per visualizzare.",
  "The content has been released!": "Il contenuto è stato rilasciato!",
  "Do you really want to copy the content of the default language to the current and replace the existing field value?": "Vuoi davvero copiare il contenuto della lingua predefinita nella lingua corrente e sostituire il valore del campo esistente?",
  "Default language": "Lingua predefinita",
  "Install from the app store": "Installa dall'App store",
  "Draft updated at": "Bozza aggiornata alle",
  "Never": "Mai",
  "Published at": "Pubblicato alle",
  "Latest workflow changes": "Ultime modifiche al flusso di lavoro",
  "Last author": "Autore più recente",
  "None": "Nessuno",
  "Workflow stage": "Fase del flusso di lavoro",
  "set by": "impostato da",
  "Assigned to": "Assegnato a",
  "Update": "Aggiornamento",
  "Comments": "Commenti",
  "Load older comments": "Carica commenti più vecchi",
  "Edit": "Modifica",
  "Workflow stage and assignments": "Fase del flusso di lavoro e assegnazioni",
  "Add a comment": "Aggiungi un commento",
  "Assign to": "Assegna a ",
  "Notify users via email": "Notifica gli utenti tramite e-mail",
  "Submit": "Invia",
  "Lambda Function": "Funzione Lambda",
  "Task type": "Tipo di attività",
  "Webhook": "WebHook",
  "The payload of the request contains the task and the space id.": "Il payload della richiesta contiene l'attività e l'id dello spazio.",
  "Lambda Function (coming soon)": "Funzione Lambda (presto disponibile)",
  "Provide the endpoint where you want to send a POST request.": "Fornisci l'endpoint a cui desideri inviare una richiesta POST.",
  "Protected variable": "Variabile protetta",
  "Function code": "Codice funzione",
  "For example:": "Per esempio:",
  "Ok": "Ok",
  "Are you sure you want to delete this task?": "Sei sicuro di voler eliminare questa attività?",
  "Last execution": "Ultima esecuzione",
  "Currently running": "Attualmente in esecuzione",
  "Executed successfully!": "Eseguito con successo!",
  "Execute": "Esegui",
  "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.": "Scegli XML per software di traduzione come SDL Trados Studio o JSON per software di traduzione come LingoHub.",
  "Autosave enabled?": "Hai abilitato il salvataggio automatico?",
  "Empty": "Vuoto",
  "Choose a compatible XML or JSON generated from the export.": "Scegli un XML o JSON compatibile generato dall'esportazione.",
  "Desktop": "Desktop",
  "Tablet": "Tablet",
  "Tag": "Etichetta",
  "Mobile": "Mobile",
  "Select": "Seleziona",
  "Content type value": "Valore del tipo di contenuto",
  "Component": "Componente",
  "Assigned to me only": "Assegnato solo a me",
  "In folder": "Nella cartella",
  "element": "elemento",
  "Search in current folder only": "Cerca solo nella cartella corrente",
  "No results found": "Nessun risultato trovato",
  "Current version": "Versione corrente",
  "Start typing to search": "Inizia a digitare per avviare la ricerca",
  "Confirming invitation": "Conferma invito",
  "Please wait a couple of seconds": "Attendi qualche secondo per favore",
  "Unknown author": "Autore sconosciuto",
  "You are now a member of the organisation": "Ora sei un membro dell'organizzazione",
  "Go to spaces": "Vai agli spazi",
  "Invitation confirmed!": "Invito confermato!",
  "Please login first and then click the invitation link again.": "Effettua prima il login e poi fai di nuovo clic sul link di invito.",
  "Go to login": "Vai al login",
  "Login required.": "Login obbligatorio.",
  "Your invitation is not valid anymore.": "Il tuo invito non è più valido",
  "Please upgrade your Storyblok space. You have": "Aggiorna il tuo spazio Storyblok. Hai",
  "Something went wrong.": "Qualcosa è andato storto.",
  "collaborator(s) and your": "collaboratore(i) e il tuo",
  "Please contact your Storyblok space owner. You have": "Contatta il proprietario dello spazio Storyblok. Hai",
  "is over.": "sono terminate.",
  "Just a moment. A background task is still running.": "Solo un momento. È ancora in esecuzione un'attività in background.",
  "The Storyblok app has been updated!": "L'app di Storyblock è stata aggiornata!",
  "Please reload the window to get the newest version.": "Ricarica la finestra per ottenere la versione più recente.",
  "Reload window": "Ricarica finestra",
  "Manage": "Gestisci",
  "Toggle assistance mode": "Attiva/disattiva la modalità di assistenza",
  "Assisted spaces": "Spazi assistiti",
  "Logging in": "Login in corso",
  "Sales": "Vendite",
  "I have read and agree to the": "Ho letto e accetto la",
  "Logged in as": "Collegato come",
  "Catalogue": "Catalogo",
  "Initiating space": "Avvio dello spazio",
  "Configuration": "Configurazione",
  "There was an error confirming your account. Please try again.": "Si è verificato un errore durante la conferma del tuo account. Per favore riprova.",
  "Resend confirmation": "Rinvia conferma",
  "Confirmed successfully!": "Conferma riuscita!",
  "You have unsaved changes on this content item. Do you want to discard your changes?": "Hai modifiche non salvate su questo elemento di contenuto. Vuoi annullare le modifiche?",
  "No": "No",
  "To continue confirm that you have read and agree to the Terms and Privacy Policy.": "Per continuare, conferma di aver letto e accettato i Termini di utilizzo e l'Informativa sulla privacy.",
  "Yes": "Sì",
  "Invitation sent!": "Invito spedito!",
  "Shortcuts: Esc for No, Enter for Yes": "Scorciatoie: Esc per No, Invio per Sì",
  "Usertype": "Tipo di utente",
  "The user has been invited to your organisation and will be added once confirmed.": "L'utente è stato invitato nella tua organizzazione e verrà aggiunto una volta confermato.",
  "Normal": "Normale",
  "Member": "Membro",
  "Provide the 15 digit ID": "Fornisci l'ID di 15 cifre",
  "Is sandbox user?": "Sandbox è un utente?",
  "Owner: Can manage users and define owners": "Proprietario: può gestire gli utenti e definire i proprietari",
  "Admin: Can manage users": "Amministratore: può gestire gli utenti",
  "Member: Can not manage users": "Membro: non può gestire gli utenti",
  "Firstname": "Nome",
  "Disable": "Disabilita",
  "Lastname": "Cognome",
  "Are you sure you want to disable this user?": "Sei sicuro di voler disabilitare questo utente?",
  "It seems you do not have any": "Sembra che tu non abbia nessun",
  "Enable": "Abilita",
  "Type in all emails of the users you want to invite separated by a new line.": "Digita tutte le e-mail degli utenti che desideri invitare separate da una nuova riga.",
  "Invite others": "Invita altri",
  "yet.": "ancora",
  "Send": "Invia",
  "Done!": "Fatto!",
  "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).": "Il tuo invito è stato spedito! Non appena gli utenti si saranno registrati, potrai aggiungerli come collaboratori ai tuoi spazi.",
  "Please enter at least one email": "Inserisci almeno un'e-mail",
  "Invite more people": "Invita altre persone",
  " is not a valid email": " Non è un indirizzo e-mail valido",
  "from": "da",
  "Target": "Obiettivo",
  "Asset": "Risorsa",
  "Current window": "Finestra corrente",
  "Get started": "Inizia",
  "New window": "Nuova finestra",
  "terms of use": "termini di utilizzo",
  "Signup": "Iscrizione",
  "By clicking \"Signup\" you accept the": "Cliccando su \"Iscriviti\" accetti il",
  "Switch to login": "Passa al login",
  "Forgot password?": "Hai dimenticato la password?",
  "Already have an account?": "Hai già un account?",
  "No account yet?": "Non hai ancora un account?",
  "Signup here": "Iscriviti qui",
  "Login": "Login",
  "Resend": "Rinvia",
  "confirmation email": "e-mail di conferma",
  "Send password reset link": "Invia link per la reimpostazione della password",
  "Imprint": "Stampa",
  "Privacy policy": "Politica sulla riservatezza",
  "Are you a developer?": "Sei uno sviluppatore?",
  "Choose no if you want to join an existing project": "Scegli no se vuoi unirti a un progetto esistente",
  "No, I am not a dev": "No, non sono uno sviluppatore",
  "Yes, I am a dev": "Sì, sono uno sviluppatore",
  "Choose your own adventure": "Scegli la tua avventura",
  "Join an existing space": "Unisciti a uno spazio esistente",
  "What would you do like next?": "Cosa vorresti fare dopo?",
  "You are almost there": "Ci sei quasi",
  "Success!": "Evviva!",
  "Insert the email of your space admin to let them add you as a collaborator of the space": "Inserisci l'e-mail dell'amministratore del tuo spazio per consentirgli di aggiungerti come collaboratore dello stesso",
  "I received the email": "Ho ricevuto l'e-mail",
  "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.": "Riceverai una notifica via e-mail non appena l'amministratore ti avrà aggiunto come collaboratore. Fai clic sul pulsante in basso per continuare.",
  "It seems that the authentification code is wrong.": "Sembra che il codice di autenticazione sia sbagliato.",
  "My account": "Il mio account",
  "Please check the password confirmation.": "Controlla la conferma della password.",
  "You are logged in via a third party authentication provider.": "Hai effettuato l'accesso tramite un provider di autenticazione di terze parti.",
  "Profile picture": "Foto profilo",
  "Username": "Nome utente",
  "Your Storyblok ID for adding you as a collaborator to another project is": "Il tuo ID Storyblok per aggiungerti come collaboratore a un altro progetto è",
  "Recommended: 500px x 500px (JPG or PNG)": "Consigliato: 500 px x 500 px (JPG o PNG)",
  "Phone number": "Numero di telefono",
  "Your timezone": "Il tuo fuso orario",
  "Your language": "La tua lingua",
  "Current password": "Password corrente",
  "Insert your current password if you changed your username, email, phone number, password or security settings": "Inserisci la tua password attuale se hai cambiato nome utente, e-mail, numero di telefono, password o impostazioni di sicurezza",
  "New Password": "Nuova password",
  "Do you want to change your current password?": "Vuoi modificare la tua password attuale?",
  "Password confirmation": "Conferma della password",
  "Security Settings": "Impostazioni di sicurezza",
  "How do you want to login?": "Come preferisci effettuare l'accesso?",
  "Password only": "Solo password",
  "Two factor authentication via SMS": "l'autenticazione a due fattori via SMS",
  "Personal access tokens": "Token di accesso personale",
  "Two factor authentication via Email": "Autenticazione a due fattori via e-mail",
  "Storyblok Management API": "API di gestione di Storyblok",
  "Please copy this api key now. It will be visible only once.": "Copia subito questa chiave API. Sarà visibile solo una volta.",
  "Tokens that have been generated to access the": "Token che sono stati generati per accedere a",
  "Generate new Token": "Genera un nuovo Token",
  "Personal access tokens work like ordinary OAuth access tokens.": "I token di accesso personali funzionano come i token di accesso OAuth ordinari.",
  "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.": "Possono essere utilizzati per autenticarsi e avere pieno accesso all'API di gestione a livello di codice e non devono MAI essere esposti in pubblico.",
  "Privacy": "Privacy",
  "Show username instead of email as collaborator": "Mostra nome utente invece dell'e-mail come collaboratore",
  "Privacy Setting": "Impostazioni sulla privacy",
  "Download in German": "Scarica in tedesco",
  "Download in English": "Scarica in inglese",
  "Data processing agreement": "Accordo sul trattamento dei dati",
  "Read more about our": "Maggiori informazioni su",
  "Account deletion": "Cancellazione dell'account",
  "privacy policy here": "politica sulla privacy qui",
  "Yes, delete my account": "Sì, cancella il mio account",
  "Do you want to delete your account?": "Desideri cancellare il tuo account?",
  "Do you really want to delete your account? Type \"delete me\" and click confirm.": "Vuoi davvero cancellare il tuo account? Digita \"eliminami\" e fai clic su Conferma.",
  "User has been updated": "L'utente è stato aggiornato",
  "Not found": "Non trovato",
  "Please insert the code we sent to ": "Inserisci il codice che abbiamo inviato a ",
  "Add user": "Aggiungi utente",
  "It seems that you do not have access to this page.": "Sembra che tu non abbia accesso a questa pagina.",
  "Create a new organization": "Crea una nuova organizzazione",
  "Organisation name": "Nome dell'organizzazione",
  "Create org": "Crea organizzazione",
  "SO Settings": "Impostazioni SO",
  "Whitelabeling": "Whitelabeling",
  "Add SSO url": "Aggiungi url SSO",
  "Url to the editor": "URL per l'editor",
  "Provide the full url like": "Inserisci l'url completo come",
  "Logo-Url": "Url logo",
  "Provide the full url to the logo like": "Fornisci l'URL completo al logo come",
  "Not defined": "Non definito",
  "Organization updated successfully": "Organizzazione aggiornata con successo",
  "Disabled": "Disabilitato",
  "Please set your password": "Per favore imposta la password",
  "Set password": "Imposta password",
  "Password has been set. You can now login.": "La password è stata impostata. Ora puoi effettuare il login.",
  "Thank you": "Grazie",
  "Please confirm your billing information": "Conferma i dati di fatturazione",
  "Login failed. The login token may expired. Please try again.": "Login fallito. Il token di accesso potrebbe essere scaduto. Per favore riprova.",
  "Please enter all required information": "Per favore inserisci tutte le informazioni richieste",
  "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.": "Cerchiamo di mantenere i tuoi dati di fatturazione aggiornati. Conferma che le informazioni di seguito sono corrette o modificale di conseguenza.",
  "One last thing before you can comment": "Un'ultima cosa prima che tu possa commentare",
  "Profile picture (optional)": "Foto profilo (opzionale)",
  "Are you sure you want to delete this item?": "Sei sicuro di voler eliminare questo articolo?",
  "Help other collaborators to identify you better by providing your name and a profile picture.": "Aiuta altri collaboratori a riconoscerti fornendo il tuo nome e una foto profilo.",
  "Are you sure you want to delete this item(s)?": "Sei sicuro di voler eliminare questo(i) elemento(i)?"
}