export default {
  "Dashboard": "Dashboard",
  "Back to spaces": "Terug naar Spaces",
  "Content": "Content",
  "Commerce": "Commerce",
  "Assets": "Bestanden",
  "Datasources": "Gegevensbronnen",
  "Activities": "Activiteiten",
  "Tasks": "Taken",
  "Components": "Componenten",
  "Apps": "Apps",
  "My account": "Mijn account",
  "Settings": "Instellingen",
  "Subscription": "Abonnement",
  "Plugins": "Plugins",
  "Logout": "Uitloggen",
  "Report a problem": "Rapporteer een probleem",
  "Create new space": "Nieuwe Space aanmaken",
  "Search spaces...": "Doorzoek Spaces...",
  "My organization": "Mijn organisatie",
  "Subscribe": "Abonneren",
  "To": "Naar",
  "From": "Van",
  "Apply filter": "Filter toepassen",
  "Filter": "Filter",
  "Unknown user": "Onbekende gebruiker",
  "Author": "Auteur",
  "Action": "Actie",
  "Date": "Datum",
  "Back": "Terug",
  "Activity Details": "Activiteiten log",
  "Open": "Openen",
  "Restore this Story": "Deze Story herstellen",
  "Categories": "Categorieën",
  "Story": "Story",
  "The item has been restored!": "Het item is hersteld!",
  "All": "Alle",
  "My Apps": "Mijn apps",
  "Search for apps, discover new field types and add functionalities to your Storyblok project.": "Zoek naar apps, ontdek nieuwe veldtypen of voeg functionaliteiten toe aan je Storyblok project.",
  "My apps": "Mijn apps",
  "Create new app": "Nieuwe app aanmaken",
  "Installed": "Geïnstalleerd",
  "App Directory": "App Directory",
  "There are no apps in this category.": "Er zijn geen apps in deze categorie.",
  "Install": "Installeren",
  "Choose the space to install this app": "Kies een Space om deze app te installeren",
  "Can not move asset folder into folder without permissions.": "Kan de bestanden map niet zonder toestemming naar een map verplaatsen.",
  "Can not move asset into folder without permissions.": "Kan het bestand niet zonder toestemming naar een map verplaatsen.",
  "Can not move asset away from folder without permissions.": "Kan het bestand niet zonder toestemming uit de map verplaatsen.",
  "Define the new name of the folder.": "Geef de nieuwe naam op voor de map.",
  "Trashbin": "Prullenbak",
  "Are you sure that you want to delete this folder?": "Weet je zeker dat je deze map wilt verwijderen?",
  "Add": "Toevoegen",
  "Asset folders are not included in the free plan but you can try them in the": "Bestandsmappen zijn niet inbegrepen in het gratis abonnement, maar je kunt ze uitproberen in de",
  "New folder will be created in": "De nieuwe map wordt aangemaakt in",
  "trial period": "proefperiode",
  "Can not create asset folder without permission for parent.": "Kan de bestandsmap niet aanmaken zonder toestemming van de bovenliggende map.",
  "Updated successfully! Notice: It can take some time until the cache getting cleared.": "Succesvol gewijzigd! Opmerking: Het kan enige tijd duren voordat de cache wordt geleegd.",
  "Original": "Origineel",
  "Done": "Klaar",
  "Cancel": "Annuleren",
  "Insert": "Toevoegen",
  "Add Asset(s)": "Bestanden toevoegen",
  "Close": "Sluiten",
  "items": "items",
  "Delete": "Verwijderen",
  "Move to folder": "Verplaats naar map",
  "Replace": "Vervangen",
  "Unselect all": "Deselecteer alles",
  "Restore": "Herstellen",
  "Tiles": "Tegels",
  "List": "Lijst",
  "No assets found": "Geen bestanden gevonden",
  "Sort": "Sorteren",
  "Default": "Standaard",
  "View": "Weergave",
  "Creation date (asc)": "Aanmaakdatum (oplopend)",
  "Filename (asc)": "Bestandsnaam (oplopend)",
  "Creation date (desc)": "Aanmaakdatum (aflopend)",
  "Filename (desc)": "Bestandsnaam (aflopend)",
  "Last updated date (asc)": "Laatste aanpasdatum (oplopend)",
  "Last updated date (desc)": "Laatste aanpasdatum (aflopend)",
  "You are not allowed to insert this filetype here.": "Je hebt geen toestemming om dit bestandstype hier te plakken.",
  "This key is already defined": "Deze sleutel is al gedefinieerd",
  "Key is in invalid format": "Sleutel heeft een ongeldige indeling",
  "Something went wrong uploading some items": "Er ging iets fout bij het uploaden van sommige items",
  "Please choose a folder in the left sidebar": "Kies een map aan de linkerkant",
  "Define the new name of": "Geef een nieuwe naam op voor",
  "Something went wrong renaming the attribute": "Er ging iets fout bij het wijzigingen van de naam van het attribuut",
  "Be aware! Changing the name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Let op! Het wijzigen van de naam kan enkele minuten duren, omdat de items moeten worden bijgewerkt. Zorg er voor dat iedereen zijn wijzigingen heeft opgeslagen en de editor heeft verlaten.",
  "Define the new name of the component group.": "Geef een nieuwe naam op voor de component groep",
  "Save": "Opslaan",
  "Are you sure that you want to delete this component group?": "Weet je zeker dat je deze componenten groep wilt verwijderen?",
  "Copy": "Kopieren",
  "New": "Nieuw",
  "Move to group": "Naar groep verplaatsen",
  "Please choose a component group in the left sidebar": "Kies aan de linkerkant een componenten groep",
  "Paste": "Plakken",
  "Add block": "Blok toevoegen",
  "Creation of a component failed. Maybe it already exists.": "Aanmaken van het component mislukt. Miscchien bestaat deze al.",
  "Are you sure you want to DELETE this component(s)?": "Weet je zeker dat je deze componenten wilt verwijderen?",
  "new": "nieuw",
  "Type to search or to create a": "Type om te zoeken of creëer een",
  "Create new": "Creëer nieuw",
  "block": "Blok",
  "New Component": "Nieuw component",
  "Updated": "Bijgewerkt",
  "Name": "Naam",
  "Shortcuts: Esc, Control + S": "Sneltoetsen: Esc, Control+S",
  "Next": "Volgende",
  "Define a name": "Geef een naam op",
  "Save schema": "Schema opslaan",
  "Act as content type (eg. blog-post)": "Voordoen als content type (bijvoorbeeld: blog-post)",
  "Define": "Definiëren",
  "Nestable": "Nestbaar",
  "Technical name": "Technische naam",
  "Edit field": "Veld bewerken",
  "Config": "Configuratie",
  "Schema": "Schema",
  "Renaming": "Hernoemen",
  "Change field name": "Veldnaam bewerken",
  "Used in the json as component name": "Gebruikt in JSON als componentnaam",
  "Be aware! Changing the technical name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Let op! Het wijzigen van de technische naam kan enkele minuten duren, omdat de items moeten worden bijgewerkt. Zorg er voor dat iedereen zijn wijzigingen heeft opgeslagen en de editor heeft verlaten.",
  "Display name": "Schermnaam",
  "Preview template": "Voorbeeldsjabloon",
  "Screenshot or icon": "Schermafbeelding of icoon",
  "Used in the editor interface only": "Wordt alleen gebruikt in de editor interface",
  "of this setting": "van deze instelling",
  "Read the documentation": "Lees de documentatie",
  "Load versions": "Versies laden",
  "Versions": "Versies",
  "has been added below": "is hieronder toegevoegd",
  "Examples: news_items, body, columns, title, description or call_to_action_btn": "Bijvoorbeeld: news-items, body, columns, title, description of call-to-action",
  "The component has been restored!": "Het component is hersteld!",
  "Do you really want to leave without saving your changes?": "Weet je zeker dat je dit wilt verlaten, zonder de wijzigingen op te slaan?",
  "Type": "Type",
  "Beta": "Beta",
  "Translatable": "Vertaalbaar",
  "Allow empty paragraphs": "Lege alinea's toestaan",
  "Linktype": "Type koppeling",
  "Rich-text as default": "Rich-text als standaard",
  "Custom type": "Aangepast type",
  "Category": "Categorie",
  "Section items": "Sectie items",
  "Product": "Product",
  "Customize toolbar": "Werkbalk aanpassen",
  "Toolbar items": "Werkbalk items",
  "Source": "Bron",
  "CSS class options (label/value)": "CSS class opties (label/waarde)",
  "Datasource": "Gegevensbron",
  "Stories": "Stories",
  "Self": "Lokale opties",
  "Internal datasource": "Interne gegevensbron",
  "Recommended to be checked, as UID is required for automatic link resolving.": "Aanbevolen om goed te controleren, omdat de UID gebruikt wordt voor automatische koppelingen.",
  "Use UID instead of ID": "Gebruik UID in plaats van ID",
  "In case you have a multi-language folder structure you can add the {0} placeholder and the path will be adapted dynamically. Examples: {0}/categories/, {0}/{1}/categories/": "Als je een meertalige mappenstructuur gebruikt, kun je het jokerteken {0} gebruiken om het pad dynamisch aan te passen. Voorbeelden: {0}/categorieën/, {0}/{1}/categorieën/",
  "External JSON": "Externe JSON",
  "Path to folder of stories": "Locatie naar map met Stories",
  "Width": "Breedte",
  "URL": "Url",
  "ratio": "verhouding",
  "pixel": "pixel",
  "Allowed maximum": "Toegestane maximum",
  "Options (name/value)": "Opties (naam/waarde)",
  "Component(s)": "Componenten",
  "Group(s)": "Groepen",
  "Component group whitelist": "Whitelist van component groepen",
  "Required field(s) (comma separated)": "Verplichte velden (komma gescheiden)",
  "Required": "Verplicht",
  "Default asset folder": "Standaard bestandsmap",
  "Choose an asset folder where the assets should be assigned to.": "Kies een map waaraan het bestand moet worden toegewezen.",
  "With {level} the path will be replaced dynamically using parts of the current slug. Examples: {0}/categories/, {0}/{1}/categories/": "Met {n} wordt het pad dynamisch vervangen, met delen uit de huidige slug. Bijvoorbeeld: {0}/categorieën/ of {0}/{1}/categorieën/",
  "Restrict to folder": "Beperken tot map",
  "Force folder restriction": "Forceer mapbeperking",
  "Regex validation": "Regex validatie",
  "Exclude from export": "Uitsluiten van export",
  "export app": "exporteer app",
  "To use with the": "Voor gebruik met de",
  "Default value": "Standaardwaarde",
  "Can be updated by preview window": "Kan worden bijgewerkt via het voorbeeldvenster",
  "Loading...": "Bezig met laden...",
  "Item": "Item",
  "Allow only specific components to be inserted": "Laat alleen specifieke componenten toe",
  "Restrict to content types": "Beperken tot content typen",
  "Keep original size": "Oorspronkelijke grootte behouden",
  "Force crop": "Bijsnijden forceren",
  "Prepend https to url": "Voeg https toe aan url",
  "Height": "Hoogte",
  "Maximum characters": "Maximale tekens",
  "Disable time selection": "Tijdselectie uitschakelen",
  "Description": "Omschrijving",
  "dimensions app": "dimensies app",
  "Force overwrite by merge action": "Forceer overschrijven door samenvoeg actie",
  "Id/Slug": "Id/Slug",
  "Enable RTL (Right to left)": "RNL activeren (rechts naar links)",
  "Autosave": "Automatisch opslaan",
  "API Url": "API-url",
  "Export": "Exporteren",
  "Import/Export": "Import/Export",
  "Dimensions": "Dimensies",
  "Add Dimension": "Dimensie toevoegen",
  "Import": "Importeren",
  "A datasource in Storyblok is a collection of key-value pairs.": "Een gegevensbron in Storyblok is een verzameling van sleutel/waarde combinaties.",
  "Datasources can be used in a schema definition of a component for single or multiple choice options. You can also access": "Gegevensbronnen kunnen worden gebruikt in een schemadefinitie van een component, bij opties met één of meerdere keuzes. Je hebt ook toegang tot",
  "datasource entries from the API": "gegevensbron items uit de API",
  "to use them for labels, categories or similar.": "om ze te gebruiken voor labels, categorieën of vergelijkbaar.",
  "Unsaved Changes": "Niet-opgeslagen wijzigingen",
  "Datasource entries": "Gegevensbron items",
  "Datasources are not included in the free plan": "Gegevensbronnen zijn niet inbegrepen in het gratis abonnement",
  "but you can try them in the": "maar je kunt ze proberen in de",
  "Saved": "Opgeslagen",
  "Select all": "Selecteer alles",
  "The options could not be loaded.": "De opties konden niet worden geladen.",
  "New Datasource": "Nieuwe gegevensbron",
  "The following component(s) can not be pasted here": "De volgende component(en) kunnen hier niet worden geplakt",
  "Please save first to continue editing child components.": "Sla eerst op, voordat je verder gaat met het bewerken van onderliggende componenten.",
  "Enabled?": "Geactiveerd?",
  "Asset manager": "Bestanden manager",
  "Loading": "Bezig met laden",
  "Upload new": "Nieuwe uploaden",
  "Your file exceeds the maximum filesize limit of": "Het bestand overschrijdt de maximale bestandsgrootte van",
  "Please reduce the size of your file.": "Verklein de grootte van het bestand.",
  "Alt text": "Alternatieve tekst",
  "Base64": "Base64",
  "Original Size": "Oorspronkelijke grootte",
  "Image loading failed": "Laden van afbeelding mislukt",
  "Quote": "Quote",
  "Code Block": "Code blok",
  "Ordered List": "Geordende lijst",
  "Headline 2": "Kop 2",
  "Headline 4": "Kop 4",
  "Headline 3": "Kop 3",
  "Headline 5": "Kop 5",
  "Paragraph": "Alinea",
  "Help": "Help",
  "Internal link": "Interne koppeling",
  "Url": "Url",
  "Show only selected": "Toon alleen geselecteerde",
  "more items found": "meer items gevonden",
  "Invoices": "Facturen",
  "Tip: Use Ctrl + S to save": "Tip: Gebruik CTRL+S om op te slaan",
  "Input": "Input",
  "Publish": "Publiceren",
  "You are not allowed to edit this plugin but can see the code at Settings/Details.": "Je hebt geen toegang om deze plugin te bewerken, maar je kunt de code inzien bij Instellingen/Details",
  "Field type preview": "Voorbeeld van veldtype",
  "Options (key/value)": "Opties (sleutel/waarde)",
  "Space Id": "Space id",
  "Enable local dev mode": "Activeer lokale ontwikkelaarsmodus",
  "Settings/Details": "Instellingen/Details",
  "Output": "Output",
  "for approval to make it available for all users.": "op toestemming om het voor alle gebruikers beschikbaar te maken.",
  "Submit the plugin": "Plugin insturen",
  "Code": "Code",
  "You can copy the code of this plugin to create your own plugin.": "Je kunt de code van deze plugin kopiëren, om je eigen plugin te beginnen.",
  "Assigned spaces": "Toegewezen Spaces",
  "If you assign this plugin to a space other developers can also use it in the schema definition. Without assigning it only you can add the plugin to the schemas.": "Als je deze plugin toewijst aan deze Space, kunnen andere ontwikkelaars deze ook gebruiken in de schemadefinitie. Zonder toewijzing kan alleen jij deze plugin gebruiken.",
  "Attention: All spaces using this plugin will not be able to use it any more if you click delete.": "Let op: Als je op verwijderen klikt, kan de plugin niet meer in Spaces gebruikt worden.",
  "Documentation": "Documentatie",
  "Danger zone": "Gevarenzone",
  "What is a field type plugin?": "Wat is een veldtype plugin?",
  "A field type plugin extends the Storyblok editor with your own custom field types.": "Een veldtype plugin breidt de Storyblok editor uit met eigen aangepaste veldtypen.",
  "It is basically a": "Het is eigenlijk een",
  "The properties that are passed to the field type are:": "De eigenschappen die worden doorgegeven aan het veldtype zijn:",
  "component extended with a few helpers in the window.Storyblok.plugin mixin.": "component uitgebreidt met enkele helpers in de \"window.Storyblok.plugin\" mixin.",
  "Examples for field types are colorpickers, WYSIWYG editors or meta tags.": "Voorbeelden van veldtypen zijn colorpickers, WYSIWYG editors of meta tags.",
  "Uid of the parent component": "Uid van het bovenliggende component",
  "Options parsed from the schema options array": "Opties geparsed uit de reeks met schema opties",
  "Schema options object": "Schema opties object",
  "Current value of the fieldtype": "Huidige waarde van veldtype",
  "Story id of the current story": "Id van de huidige Story",
  "Space id of the current space": "Id van de huidige Space",
  "Api function to call the delivery api": "Functie om de API aan te roepen",
  "Methods": "Methoden",
  "Draft token of the current space": "Concepttoken van de huidige Space",
  "How to call the Storyblok api?": "Hoe kun je de Storyblok API aanroepen?",
  "Should be used to define the initial data of the plugin.": "Moet worden gebruikt om de initiële gegevens van de plugin te definiëren.",
  "Should be used to initialize the plugin. Examples: Load data from Storyblok or external sources, Load and initialize a WYSIWYG editor.": "Moet worden gebruikt om de plugin te initialiseren. Bijvoorbeeld: Laad gegevens in van Storyblok of externe bronnen. Of laad en initialiseer een WYSIWYG editor.",
  "To pass options that are configurable in the schema definition define the option keys in the \"Input\" box. The values will be available in the this.options object.": "Om configureerbare opties door te geven aan de schemadefinitie, geef je de waardes in het \"Input\" veld op. De waardes zijn dan beschikbaar in \"this.options\".",
  "How to pass options?": "Hoe geef je opties door?",
  "In field types you can use this.api to get access to the Storyblok delivery api. You can use it for example to build a selectbox of stories.": "In veldtypen kun je \"this.api\" gebruiken om toegang te krijgen tot de Storyblok API. Je kunt het bijvoorbeeld gebruiken om een dropdown menu met stories te genereren.",
  "Folder/Content-item permissions": "Rechten map/item",
  "Item saved successfully!": "Item succesvol opgeslagen!",
  "Add folders or content items the token should have access to (acts as whitelist). If no item is selected the token has rights to get all content.": "Voeg mappen of items toe, waartoe de token toegang heeft (werkt als whitelist). Als er geen items zijn geselecteerd, heeft de token toegang to alle content.",
  "Source of sync": "Bron voor synchronisatie",
  "Preview": "Voorbeeld",
  "Preview url": "Voorbeeld url",
  "View on Jsfiddle": "Bekijk op Jsfiddle",
  "Download": "Downloaden",
  "Admin": "Beheerder",
  "Permissions": "Rechten",
  "Editor": "Editor",
  "Advanced Rights": "Geavanceerde rechten",
  "Allow saving content": "Opslaan van content toestaan",
  "Allow publishing content": "Publiceren van content toestaan",
  "Allow saving datasources": "Opslaan van gegevensbronnen toestaan",
  "Allow managing subscription": "Bewerken van abonnement toestaan",
  "Allow access to ecommerce app": "Toegang tot e-commerce app toestaan",
  "Deny access to visual composer": "Toegang tot visuele editor weigeren",
  "Field Permissions": "Veldrechten",
  "General": "Algemeen",
  "Allowed path": "Toegestaan pad",
  "Your crawl URL": "De crawl url",
  "Crawler": "Crawler",
  "Enabled": "Geactiveerd",
  "Index": "Index",
  "Crawl now": "Nu crawlen",
  "Information needed to access the search endpoint or to configure the search client.": "Benodigde informatie om toegang te krijgen tot het zoeken, of om de client te configureren.",
  "Search Setup Guide": "Installatiehandleiding zoeken",
  "Your tenant ID": "De huurder ID",
  "See": "Bekijken",
  "Documents in index": "Documenten in index",
  "Crawl requested at": "Crawl aangevraagd om",
  "Tenant ID": "Huurder ID",
  "Documents": "Documenten",
  "Clear index": "Index legen",
  "Last crawled at": "Laatst gecrawled om",
  "Crawl has been initiated": "Crawl is gestart",
  "In the first 14 days you can try out all Premium plan features!": "In de eerste 14 dagen kun je alle Premium functionaliteiten uitproberen!",
  "Index deletion has been initiated": "Het verwijderen van de index is gestart",
  "Changing settings for the space is only allowed for the owner.": "Alleen de eigenaar kan de instellingen van de Space wijzigen.",
  "API-Keys": "API-sleutels",
  "We would love to hear your thoughts about Storyblok on": "We horen graag je mening over Storyblok via",
  "Renderer": "Renderer",
  "Backup": "Backup",
  "Users": "Gebruikers",
  "Workflow": "Werkstroom",
  "Search": "Zoeken",
  "Languages": "Talen",
  "This is the page that the frontend-editor opens.": "Dit is de pagina die de frontend-editor opent.",
  "Location (default environment)": "Internetadres (standaard omgeving)",
  "Insert your domain/location including the protocol. Example: http://www.example.com/": "Voeg je domein/internetadres toe, inclusief het protocol. Bijvoorbeeld: http://www.example.com/",
  "Provide this ID in your support tickets": "Gebruik dit ID in je supporttickets",
  "Your space ID": "De Space ID",
  "Preview urls": "Voorbeeld url's",
  "Define multiple domains/locations to quickly switch the preview urls in the story-editor.": "Voeg meerdere domeinen/internetadressen toe om snel te kunnen wisselen tussen locaties in de Story-editor.",
  "Add preview url": "Voorbeeld url toevoegen",
  "Webhooks": "Webhooks",
  "Story published &amp; unpublished": "Story gepubliceerd & niet-gepubliceerd",
  "Story saved": "Story opgeslagen",
  "Branch deployed": "Vertakking geplaatst",
  "Release merged": "Uitgave samengevoegd",
  "Slack integration": "Slack integratie",
  "Loading... You will be redirect to Slack in a few seconds!": "Bezig met laden...Je wordt binnen enkele seconden doorgestuurd naar Slack!",
  "Get notified on your Slack channel if a new Story has been published!": "Krijg een melding op je Slack kanaal als er een nieuwe Story is gepubliceerd!",
  "With this integration you can choose a Slack channel where Storyblok posts messages whenever a user publishes new content.": "Met deze integratie kun je een Slack kanaal kiezen waar Storyblok berichten heen stuurt, wanneer een gebruiker nieuwe content publiceert.",
  "Disconnect": "Verbinding verbreken",
  "Cloud name": "Cloud naam",
  "Cloudinary integration": "Cloudinary integratie",
  "Api Key": "API-sleutel",
  "Branches": "Vertakkingen",
  "Default content type": "Standaard content type",
  "Content types": "Content typen",
  "Name of the branch": "Naam van vertakking",
  "Branches are not included in the free plan": "Vertakkingen zijn niet inbegrepen in het gratis abonnement",
  "Duplication": "Dupliceren",
  "This is useful if you want to offer your space for other users as a boilerplate or theme.": "Dit is handig voor wanneer je deze Space met andere gebruikers wilt delen, als standaard of thema.",
  "ATTENTION! Only check this checkbox if you are sure that you want all data of this space available for duplication.": "Let op! Alleen aanvinken als je zeker weet dat je álle gegevens van deze Space wilt delen.",
  "Make this space duplicatable by all users": "Maak deze Space dupliceerbaar door alle gebruikers",
  "Content ownership": "Content eigenaar",
  "Parent ID": "ID van bovenliggend item",
  "Parent": "Bovenliggend item",
  "Image service": "Afbeeldingen dienst",
  "Content ownership client endpoint": "Client eigenaar",
  "List of paths to invalidate": "Lijst met paden om ongeldig te maken",
  "Delete this space": "Verwijder deze Space",
  "Invalidate": "Ongeldig maken",
  "Workflow webhooks": "Werkstroom webhooks",
  "Owner": "Eigenaar",
  "Workflow changed": "Werkstroom gewijzigd",
  "Transfer ownership": "Eigendom overdragen",
  "Transfer": "Overdragen",
  "Attention! Transferring the ownership will remove all your rights to this space.": "Let op! Je verliest alle rechten voor deze Space als je het eigendom overdraagt.",
  "The owner needs to add you as a collaborator if you want to have access again.": "De nieuwe eigenaar dient je als medewerker toe te voegen, als je weer toegang wilt krijgen.",
  "Collaborators": "Medewerkers",
  "Collaborator": "Medewerker",
  "No user found with this email or username.": "Geen gebruiker gevonden met dit e-mailadres of deze gebruikersnaam.",
  "Name of the role": "Naam van de rol",
  "Role": "Rol",
  "Add a new user to your org": "Voeg een nieuwe gebruiker toe aan de organisatie",
  "Advanced rights and roles are not included in the free and basic plan": "Geavanceerde rechten en rollen zijn niet inbegrepen in het proef- of basisabonnement",
  "Use your Amazon S3 bucket to create backups.": "Gebruik een Amazon S3 bucket om backups te maken.",
  "Backup now": "Nu backuppen",
  "Backups content (stories) and compontents": "Backup content (Stories) en componenten",
  "Define your S3-Bucket and AWS-ARN to enable backups.": "Stel je S3-Bucket en AWS-ARN in, om backups te maken.",
  "Daily backups": "Dagelijkse backups",
  "Define the name of the S3-bucket where you want to store your backups.": "Geef de naam op van de S3-Bucket waarin je de backups wilt opslaan.",
  "S3-bucket": "S3-Bucket",
  "Activate automatic daily backups": "Activeer automatische dagelijkse backups",
  "1. Read the": "1. Lees de",
  "AWS Policy ARN": "AWS-beleid ARN",
  "Show setup instructions": "Installatie instructies weergeven",
  "tutorial on how to setup an Amazon IAM role": "tutorial over het instellen van een Amazon IAM rol.",
  "2. Create an Amazon IAM role with following access policy document:": "2. Maak een Amazon IAM rol aan met het volgende document:",
  "if not done yet.": "indien nog niet gedaan.",
  "The role should have the permission to access and create files on the S3 bucket you defined. You can for example use the following permission policy replacing YOUR_BUCKET with your bucket name:": "De rol moet toegang hebben tot de S3-Bucket en bestanden kunnen lezen en schrijven. Je kunt bijvoorbeeld het volgende toestemmingsbeleid gebruiken door YOUR_BUCKET te vervangen met je eigen bucket naam:",
  "Restore spaces from backups on your Amazon S3 bucket.": "Herstel Spaces uit backups, uit je Amazon S3-Bucket.",
  "Backup file": "Backupbestand",
  "Show latest backups": "Laatste backups weergeven",
  "Latest five backups": "Laatste vijf backups",
  "Restore now": "Nu herstellen",
  "The settings below only apply if you are using": "De onderstaande instellingen zijn alleen van toepassing indien",
  "Attention! \"Restore now\" deletes old data and restores content (stories) and compontents from the backup file.": "Let op! \"Nu herstellen\" verwijdert oude gegevens en herstelt content (Stories) en componenten uit het backupbestand.",
  "Rendering service": "Rendering dienst",
  "Your domain": "Jouw domein",
  "To connect your domain to Storyblok you need to create a CNAME Record pointing to eu-domain.storyblok.com": "Om je domein te verbinden met Storyblok, heb je een CNAME-record nodig dat verwijst naar eu-domain.storyblok.com.",
  "Routes": "Routes",
  "Add Route": "Route toevoegen",
  "Please read the": "Lees de",
  "Add custom routes to define different page templates.": "Voeg aangepaste routes toe om verschillende paginasjablonen te definiëren.",
  "documentation about internationalization": "documentatie over meertaligheid",
  "before configuring languages.": "voordat je talen instelt.",
  "Add languages to activate field level translations.": "Voeg talen toe om vertalingen op veldniveau te activeren.",
  "Add Language": "Taal toevoegen",
  "Label": "Label",
  "The invalidation process has been initiated": "Het ongeldig maken proces is gestart",
  "The backup has been initiated": "De backup is gestart",
  "Are you sure you want to delete your current content and overwrite it with this backup?": "Weet je zeker dat je de huidige content wilt overschrijven met deze backup?",
  "The restore process has been initiated": "Het herstelproces is gestart",
  "Transfer was not successful. Make sure that the new owner exists.": "Overdracht mislukt. Zorg ervoor dat de nieuwe eigenaar bestaat.",
  "The collaborator has been added": "De medewerker is toegevoegd",
  "Please insert an email address": "Geef een e-mailadres op",
  "Branches sorted successfully!": "Vertakkingen succesvol gesorteerd!",
  "Create or join a space": "Maak of neem deel aan een Space",
  "Create a new space": "Maak een nieuwe Space",
  "Play with a demo": "Bekijk de demo",
  "Duplicate a space": "Dupliceer een Space",
  "Join a space": "Neem deel aan een Space",
  "Create space": "Space aanmaken",
  "Headless (API/SDKs)": "Headless (API/SDK's)",
  "what is that?": "wat is dat?",
  "Duplicate space": "Dupliceer Space",
  "Choose the space for the duplication": "Kies de Space voor duplicatie",
  "You do not have created any spaces yet.": "Je hebt nog geen Space aangemaakt.",
  "You can test the editing interface and our visual composer without to write any code on your own.": "Je kunt de editor interface en visuele editor testen zonder een regel code te hoeven schrijven.",
  "Create Demo": "Demo aanmaken",
  "Insert the email of your space admin to let them add you as a collaborator of the space.": "Voer het e-mailadres in van de beheerder en laat jezelf toevoegen als medewerker van de Space.",
  "Request access": "Toegang aanvragen",
  "Email address of space admin": "E-mailadres van Space beheerder",
  "Success! You will get notified once the admin added you as a collaborator.": "Succes! Je ontvangt een e-mail zodra de beheerder je heeft toegevoegd als medewerker.",
  "Available Billing Information": "Beschikbare factuurgegevens",
  "No spaces with billing information available": "Geen Spaces met factuurgegevens beschikbaar",
  "Spaces": "Spaces",
  "Show More": "Toon meer",
  "Apply": "Toepassen",
  "Show": "Tonen",
  "Billing Information of Space": "Factuurgegevens van Space",
  "The information below will be applied to the fields of your current subscription process. You will be able to adopt them after applying them.": "De onderstaande informatie wordt overgenomen in je huidige abonnement. Je kunt ze hierna nog wijzigen.",
  "Company": "Bedrijf",
  "Country": "Land",
  "Street / City / ZIP": "Adres / Stad / Postcode",
  "Email": "E-mailadres",
  "Add or change preview urls": "Bewerk of voeg voorbeeld url's toe",
  "Your server address": "Het serveradres",
  "1. Download a preconfigured project": "1. Download een vooraf geconfigureerd project",
  "Preferred by our users": "Voorkeur van onze gebruikers",
  "The downloaded package comes preconfigured with your api token": "De download wordt vooraf geconfigureerd met eigen API-token",
  "Tutorial": "Tutorial",
  "Other technologies": "Andere technologieën",
  "2. Start your server": "2. Start de server",
  "Start the server of the downloaded package and insert your server url here:": "Start de server uit het gedownloade bestand en voer hier het serveradres in:",
  "Go": "Ga",
  "FAQ": "Faq",
  "Can I build a full blown website with Storyblok?": "Kan ik een complete website maken met Storyblok?",
  "Can I create a blog with Storyblok?": "Kan ik een blog maken met Storyblok?",
  "How does Storyblok work?": "Hoe werkt Storyblok?",
  "What is the Storyblok bridge?": "Wat is een Storyblok Bridge?",
  "Allow deploying content": "Plaatsen van content toestaan",
  "General permissions": "Algemene rechten",
  "Allow unpublishing content": "Offline halen van content toestaan",
  "Allow deleting content": "Verwijderen van content toestaan",
  "Allow editing datasource keys & values": "Wijzigen van gegevensbronnen toestaan",
  "Allow editing datasource values": "Wijzigen van gegevensbron waardes toestaan",
  "Allow access to the tasks app": "Toegang tot taken toestaan",
  "Deny moving a story": "Verplaatsen van Story weigeren",
  "Deny changing alternates group": "Wijzigen alternatieve groepen weigeren",
  "Add languages the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Voeg talen toe, waartoe de gebruiker toegang heeft (werkt als witte lijst). Als er geen items zijn geselecteerd, kan de gebruiker alle content bewerken.",
  "Deny changing the slug of a story": "Wijzigen Story slug weigeren",
  "Add folders or content items the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Voeg folders of items toe, waartoe de gebruiker toegang heeft (werkt als whitelist). Als er geen items zijn geselecterd, kan de gebruiker alle content bewerken.",
  "Component field permissions": "Rechten componentvelden",
  "Datasource permissions": "Rechten gegevensbronnen",
  "Add component fields here to hide them in the interface.": "Voeg hier componentvelden toe, om ze te verbergen in de gebruikersinterface.",
  "Asset Folder Permissions": "Rechten bestandsmappen",
  "Start by selecting a space in the sidebar or create a new space.": "Begin met een Space aan de linkerkant of maak een nieuwe Space aan.",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Het lijkt erop dat je nog geen toegang hebt tot een Space. Neem contact op met de beheerder van je organisatie en laat je toevoegen als medewerker.",
  "Welcome!": "Welkom!",
  "Traffic": "Dataverbruik",
  "Learn more about": "Kom meer te weten over",
  "Api requests": "API-verzoeken",
  "Active Plan": "Huidige abonnement",
  "Usage": "Statistieken",
  "Content activities": "Content activiteiten",
  "No billing": "Geen facturering",
  "Change": "Wijzigen",
  "Billed": "Gefactureerd",
  "No recent changes": "Geen recente wijzigingen",
  "Choose your plan": "Kies je abonnement",
  "Recent changes": "Recente wijzigingen",
  "Custom": "Aangepast",
  "Compare": "Vergelijken",
  "user": "gebruiker",
  "Got a custom plan or coupon code?": "Heb je een aangepast abonnement of promotiecode?",
  "Custom plan": "Aangepast abonnement",
  "Entered plan ids will be validated after pressing subscribe.": "Ingevoerde abonnement id's worden gecontroleerd, nadat je op abonneren hebt geklikt.",
  "Coupon code": "Promotiecode",
  "Entered coupon codes will be validated and applied after pressing subscribe.": "Ingevoerde promotiecodes worden pas toegepast, nadat ze zijn gecontroleerd en je op abonneren hebt geklikt.",
  "Select seats": "Kies aantal gebruikers",
  "Confirm subscription": "Bevestig abonnement",
  "Min": "Minimum",
  "Max": "Maximum",
  "By clicking the button below the new subscription will start.": "Door op de onderstaande knop te klikken, wordt het nieuwe abonnement gestart.",
  "Decide payment interval": "Kies betalingstermijn",
  "Change subscription": "Wijzig abonnement",
  "Monthly": "Maandelijks",
  "Annually": "Jaarlijks",
  "Define billing information": "Geef factuurgegevens op",
  "Email address": "E-mailadres",
  "VAT-Number": "Btw-nummer",
  "Reuse from another space": "Overnemen vanuit andere Space",
  "Order number": "Ordernummer",
  "Street": "Adres",
  "City": "Stad",
  "Credit or debit card": "Creditcard of betaalpas",
  "ZIP": "Postcode",
  "Enter payment information": "Geef betalingsgegevens op",
  "Update payment information": "Wijzig betalingsgegevens",
  "Update Billing information": "Wijzig factuurgegevens",
  "Update billing information": "Wijzig factuurgegevens",
  "Information: Our payment provider validates card information when it is saved. As a result of this process, you may see a temporary authorization for $1 on your statement.": "Nb: Onze betalingsprovider controleert de kaartgegevens wanneer deze worden opgeslagen. Als resultaat van dit proces kun je een tijdelijke transactie zien van $1, op je bankafschrift.",
  "Please provide all billing informations marked as required (*)": "Vul alle factuurgegevens in die gemarkeerd zijn als verplichte velden (*)",
  "Your selected team sizes are not in the limits of your selected feature set. You can select another feature set to continue.": "De geselecteerde teamgrootte valt niet binnen de limieten van het geselecteerde abonnement. Je kunt een ander abonnement kiezen om door te gaan.",
  "View invoices": "Bekijk facturen",
  "Summary": "Overzicht",
  "Please provide a credit or debit card": "Geef een creditcard of betaalpas op",
  "If your entered plan is not correct you will still be able to try it again.": "Als het ingevoerde abonnement onjuist is kun je het nogmaals proberen.",
  "You have entered a custom plan with a special offering and pricing": "Je hebt een aangepast abonnement met een speciale aanbieding en prijzen ingevoerd",
  "users": "gebruikers",
  "VAT reverse charge applies.": "Btw-verleggingsregeling van toepassing.",
  "VAT": "btw",
  "Total": "Totaal",
  "The benefits of the coupon code will be applied if available": "De voordelen van de promotiecode worden toegepast indien beschikbaar",
  "Thanks! You are awesome!": "Bedankt! Je bent geweldig!",
  "We would love to hear what you think about Storyblok.": "We horen graag wat je van Storyblok vindt.",
  "Chat with us or": "Chat met ons of",
  "your feedback.": "jouw feedback.",
  "Tweet": "Tweet",
  "Star": "Ster",
  "Share": "Delen",
  "Public access tokens are only for accessing the published version while preview tokens are for accessing the draft version also. Both are read-only tokens.": "Openbare toegangstokens geven alleen toegang tot gepubliceerde versies, terwijl voorbeeldtokens ook toegang geven tot concept versies. Beide zijn alleen-lezen tokens.",
  "Access level": "Toegangsniveau",
  "Public": "Openbaar",
  "See API-Documentation": "Bekijk API documentatie",
  "Theme": "Thema",
  "Branch": "Vertakking",
  "Choose branch": "Kies vertakking",
  "Create Token": "Token aanmaken",
  "Color": "Kleur",
  "Define as default stage for new content items": "Stel als standaard fase in voor nieuwe items",
  "Publishing rights": "Publicatierechten",
  "Stage transition rules": "Faseovergang regels",
  "Allow users to publish or schedule the content": "Gebruikers toestaan inhoud te publiceren of publicaties in te plannen",
  "Specific stage(s)": "Specifieke fasen",
  "Next available stages": "Volgende beschikbare fasen",
  "All stages": "Alle fasen",
  "All users": "Alle gebruikers",
  "User(s)/Role(s) who can change the stage": "Gebruikers en rollen die de fase kunnen bewerken",
  "to the next available stage": "naar de volgende beschikbare fase",
  "Specific user(s)/role(s)": "Specifieke gebruikers of rollen",
  "Role(s)": "Rollen",
  "User(s)": "Gebruikers",
  "Workflow stages": "Werkstroom fasen",
  "See workflow documentation": "Bekijk werkstroom documentatie",
  "Create": "Aanmaken",
  "Choose an approver": "Kies iemand voor goedkeuring",
  "Workflow stages sorted successfully!": "Werkstroom fasen succesvol gesorteerd!",
  "Are you sure you want to delete this workflow stage?": "Weet je zeker dat je deze werkstroom fase wilt verwijderen?",
  "Send for approval": "Versturen ter goedkeuring",
  "Approval request has been sent successfully!": "Verzoek tot goedkeuring is succesvol verstuurd!",
  "Content items": "Items",
  "Entry": "Item",
  "Define schema": "Definieer schema",
  "Folder": "Map",
  "You have not defined any schema for this block yet.": "Je hebt nog geen schema voor dit blok gedefinieerd.",
  "Define presets": "Voorkeuren definiëren",
  "Click \"Define schema\" to add the fields you need.": "Klik op \"Definieer schema\" om de benodigde velden toe te voegen.",
  "No valid fields defined in this section yet.": "Er zijn nog geen geldige velden gedefinieerd in deze sectie.",
  "is already part of another section": "is al onderdeel van een andere sectie",
  "Translate": "Vertalen",
  "Choose to delete the values or add the schema keys.": "Kies er voor om de waardes te verwijderen of om schema sleutels toe te voegen.",
  "items out of schema": "items buiten het schema",
  "We have found values which are not part of the schema.": "We hebben waardes gevonden die geen deel uitmaken van het schema.",
  "No changes found": "Geen wijzigingen gevonden",
  "Changes": "Wijzigingen",
  "Remove all": "Alles verwijderen",
  "Select releases to deploy": "Selecteer uitgaven om te plaatsen",
  "What is getting deployed?": "Wat wordt er geplaatst?",
  "All content that is currently on the source branch and the releases you select.": "Alle content die zich momenteel in de bronvertakking bevindt en uit de geselecteerde uitgaven.",
  "No releases found on the source branch": "Geen uitgaven gevonden in de bronvertakking",
  "A newer version of this content item has been found in the database.": "Er is een nieuwere versie van dit item gevonden in de database.",
  "Confirm": "Bevestigen",
  "Choose the conflict solution": "Kies een conflictoplossing",
  "Copy over": "Kopieer over",
  "Opens newer version in a new window to let you copy over your changes.": "Opent nieuwere versie in een nieuw venster, zodat je de wijzigingen kunt overnemen.",
  "Overwrite": "Overschrijven",
  "Slug": "Slug",
  "Overwrites newer version with your changes.": "Overschrijft nieuwere versie met jouw wijzigingen.",
  "Define as root for the folder": "Instellen als root van de map",
  "Preset": "Voorkeursinstelling",
  "Content type": "Content type",
  "Confirm deletion": "Bevestig verwijdering",
  "Are you sure that you want to delete this item(s)?": "Weet je zeker dat je deze items wilt verwijderen?",
  "Include associated alternates": "Neem bijbehorende alternatieven op",
  "Target-Folder": "Doelmap",
  "Is alternative version of the duplicate?": "Is dit een alternatieve versie van het duplicaat?",
  "Duplicate": "Dupliceren",
  "Schedule": "Planning",
  "duplicated": "gedupliceerd",
  "You are not allowed to duplicate this story.": "Je hebt geen rechten om deze Story te dupliceren",
  "Open published": "Open gepubliceerde",
  "Send approval": "Goedkeuring versturen",
  "Open draft": "Open concept",
  "Unpublish": "Offline halen",
  "Draft json": "Concept JSON",
  "Discard changes": "Wijzigingen ongedaan maken",
  "Start sync": "Start synchronisatie",
  "Published json": "Gepubliceerde JSON",
  "Status": "Status",
  "Tools": "Tools",
  "Real path": "Echt pad",
  "Settings for the folder content": "Instellingen voor de mapinhoud",
  "Disable visual composer": "Visuele editor uitschakelen",
  "Clone to all": "Naar allen klonen",
  "Deny changing content type": "Wijzigen content type weigeren",
  "Merge to all": "Naar allen samenvoegen",
  "Dimensions are only available if you are editing a content item in a subfolder.": "Dimensies zijn alleen beschikbaar bij het bewerken van items in een submap.",
  "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).": "Maak een mappenstructuur aan waarbij de eerste map de dimensie definieert (bijvoorbeeld: nl/home of en/home).",
  "Not created yet": "Nog niet aangemaakt",
  "Create clone": "Kloon maken",
  "Merge": "Samenvoegen",
  "Something went wrong merging the alternate(s)": "Er is iets fout gegaan bij het samenvoegen van de alternatieven",
  "The alternate(s) have been created!": "De alternatieven zijn aangemaakt!",
  "The alternate(s) have been merged!": "De alternatieven zijn samengevoegd!",
  "Add preset": "Voorkeursinstelling toevoegen",
  "Presets are blocks filled with the content you currently have in the selected block.": "Voorkeursinstellingen zijn blokken gevuld met content uit het huidige geselecteerde blok.",
  "Something went wrong creating the alternate(s)": "Er is iets fout gegaan bij het aanmaken van de alternatieven",
  "The saved presets are shown for all users at the selection of new blocks.": "De opgeslagen voorkeursinstellingen zijn zichtbaar voor alle gebruikers, bij het selecteren van nieuwe blokken.",
  "Existing presets": "Bestaande voorkeursinstellingen",
  "As default": "Als standaard",
  "Release date (optional)": "Publicatiedatum (optioneel)",
  "Branches to deploy": "Vertakkingen voor plaatsing",
  "When the release gets merged all content will be automatically deployed to the selected branches.": "Wanneer de uitgave samengevoegd wordt, zal alle content automatisch in de vertakking geplaatst worden.",
  "Entry configuration": "Item configuratie",
  "Editmode": "Bewerkmodus ",
  "Are you sure you want to delete this release?": "Weet je zeker dat je deze uitgave wilt verwijderen?",
  "Form only": "Alleen formulier",
  "Visual": "Visueel",
  "Tags": "Tags",
  "Sort by date": "Sorteer op datum",
  "First published date": "Eerste publicatiedatum",
  "Real Path": "Echt pad",
  "Remove": "Verwijderen",
  "Alternative versions": "Alternatieve versies",
  "Search for the content group of this story.": "Zoek naar de content groep van deze Story",
  "Shortcut": "Snelkoppeling",
  "Pin as shortcut in the mini-browser": "Vastzetten als snelkoppeling in de mini-browser",
  "Current": "Huidige",
  "New release": "Nieuw uitgave",
  "Skip this step": "Deze stap overslaan",
  "Move": "Verplaatsen",
  "Next step": "Volgende stap",
  "We have already done that for you. Open the entry \"Home\" below to play around.": "We hebben dit al voor je gedaan. Open het item \"Home\" hieronder om het uit te proberen.",
  "Create a demo page": "Maak een demo pagina aan",
  "Create a new folder": "Maak een nieuwe map aan",
  "Create your first folder": "Maak je eerste map aan",
  "and define a new content type during the folder set-up.": "en definieer een nieuw content type tijdens het instellen van de map.",
  "Create your first entry": "Maak je eerste item aan",
  "Create entry": "Item aanmaken",
  "and define its fields by building its schema so you can fill it with content.": "en definieer de velden voor het schema, zodat je het kunt gaan vullen met content.",
  "Will be released at": "Wordt vrijgegeven op",
  "Show only items from this release": "Toon alleen items uit deze uitgave",
  "Has been published at": "Werd gepubliceerd op",
  "Last deployment": "Laatste plaatsing",
  "This branch has never been deployed": "Deze vertakking is nooit geplaatst",
  "Release now": "Nu vrijgeven",
  "Open preview": "Open preview",
  "Deploy from source": "Plaats vanuit bron",
  "You are seeing deleted items": "Je bekijkt nu verwijderde items",
  "Name (desc)": "Naam (aflopend)",
  "Default sorting": "Standaard sortering",
  "Name (asc)": "Naam (oplopend)",
  "Slug (desc)": "Slug (aflopend)",
  "releases": "uitgaven",
  "Slug (asc)": "Slug (oplopend)",
  "Created at": "Aangemaakt op",
  "Updated at": "Bijgewerkt op",
  "Deleted at": "Verwijderd op",
  "Are you sure you want to unpublish this item(s)?": "Weet je zeker dat je deze items offline wilt halen?",
  "The items have been updated!": "De items zijn bijgewerkt!",
  "Are you sure you want to publish this item(s)?": "Weet je zeker dat je deze items wilt publiceren?",
  "Are you sure you want to restore this item(s)?": "Weet je zeker dat je deze items wilt herstellen?",
  "Something went wrong restoring some items": "Er is iets fout gegaan bij het herstellen van sommige items",
  "Something went wrong updating item(s)": "Er is iets fout gegaan bij het bijwerken van sommige items",
  "No tools installed on this space": "Er zijn geen tools geïnstalleerd in deze Space",
  "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.": "Verwijderde items kunnen niet worden bekeken. Herstel een item om deze te bekijken.",
  "The content has been released!": "De content is vrijgegeven!",
  "Do you really want to copy the content of the default language to the current and replace the existing field value?": "Weet je zeker dat je de content van de huidige taal wilt vervangen met de standaard taal?",
  "Default language": "Standaard taal",
  "Install from the app store": "Installeer vanuit de app store",
  "Draft updated at": "Concept bijgewerkt op",
  "Never": "Nooit",
  "Published at": "Gepubliceerd op",
  "Latest workflow changes": "Laatste werkstroom wijzigingen",
  "Last author": "Laatste auteur",
  "None": "Geen",
  "Workflow stage": "Werkstroom fase",
  "set by": "ingesteld door",
  "Assigned to": "Toegewezen aan",
  "Update": "Bijwerken",
  "Comments": "Reacties",
  "Load older comments": "Laad oudere reacties",
  "Edit": "Bewerken",
  "Workflow stage and assignments": "Werkstroom fase en toewijzingen",
  "Add a comment": "Reactie toevoegen",
  "Assign to": "Toewijzen aan",
  "Notify users via email": "Gebruikers via e-mail op de hoogte stellen",
  "Submit": "Indienen",
  "Lambda Function": "Lambda-functie",
  "Task type": "Type taak",
  "Webhook": "Webhook",
  "The payload of the request contains the task and the space id.": "Het antwoord van het verzoek bevat de taak en de Space id.",
  "Lambda Function (coming soon)": "Lambda-functie (binnenkort beschikbaar)",
  "Provide the endpoint where you want to send a POST request.": "Geef het eindpunt op waarnaar je het POST-verzoek wilt versturen.",
  "Protected variable": "Beschermde variabele",
  "Function code": "Functie code",
  "For example:": "Bijvoorbeeld:",
  "Ok": "Ok",
  "Are you sure you want to delete this task?": "Weet je zeker dat je deze taak wilt verwijderen?",
  "Last execution": "Laatste uitgevoerd",
  "Currently running": "Momenteel actief",
  "Executed successfully!": "Succesvol uitgevoerd!",
  "Execute": "Uitvoeren",
  "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.": "Kies XML voor vertaalsoftware als SDL Trados Studio of JSON voor vertaalsoftware als LingoHub.",
  "Autosave enabled?": "Automatisch opslaan ingeschakeld?",
  "Empty": "Leeg",
  "Choose a compatible XML or JSON generated from the export.": "Kies een XML of JSON exportbestand",
  "Desktop": "Desktop",
  "Tablet": "Tablet",
  "Tag": "Tag",
  "Mobile": "Mobiel",
  "Select": "Selecteren",
  "Content type value": "Waarde content type",
  "Component": "Component",
  "Assigned to me only": "Alleen aan mij toegewezen",
  "In folder": "In map",
  "element": "item",
  "Search in current folder only": "Doorzoek alleen de huidige map",
  "No results found": "Geen resultaten gevonden",
  "Current version": "Huidige versie",
  "Start typing to search": "Type om te beginnen met zoeken",
  "Confirming invitation": "Uitnodiging bevestigen",
  "Please wait a couple of seconds": "Wacht enkele seconden",
  "Unknown author": "Onbekende auteur",
  "You are now a member of the organisation": "Je bent nu lid van de organisatie",
  "Go to spaces": "Ga naar Spaces",
  "Invitation confirmed!": "Uitnodiging bevestigd!",
  "Please login first and then click the invitation link again.": "Log eerst in en klik dan vervolgens weer op de link in de uitnodiging.",
  "Go to login": "Ga naar inloggen",
  "Login required.": "Inloggen vereist.",
  "Your invitation is not valid anymore.": "Je uitnodiging is niet meer geldig.",
  "Please upgrade your Storyblok space. You have": "Upgrade je Storyblok Space. Je hebt",
  "Something went wrong.": "Er is iets fout gegaan.",
  "collaborator(s) and your": "medewerkers en je",
  "Please contact your Storyblok space owner. You have": "Neem contact op met de eigenaar van de Storyblok Space. Je hebt",
  "is over.": "is voorbij.",
  "Just a moment. A background task is still running.": "Ogenblikje. Er is nog een achtergrondtaak actief.",
  "The Storyblok app has been updated!": "De Storyblok app is bijgewerkt!",
  "Please reload the window to get the newest version.": "Laad het venster opnieuw om de nieuwste versie te krijgen.",
  "Reload window": "Venster herladen",
  "Manage": "Beheren",
  "Toggle assistance mode": "Hulpmodus in-/uitschakelen",
  "Assisted spaces": "Spaces bijgestaan",
  "Logging in": "Bezig met inloggen",
  "Sales": "Verkoop",
  "I have read and agree to the": "Ik heb het gelezen en ga akkoord met",
  "Logged in as": "Ingelogd als",
  "Catalogue": "Catalogus",
  "Initiating space": "Bezig met initialiseren van Space",
  "Configuration": "Configuratie",
  "There was an error confirming your account. Please try again.": "Er is een fout opgetreden bij het bevestigen van je account. Probeer het nogmaals.",
  "Resend confirmation": "Bevestiging opnieuw versturen",
  "Confirmed successfully!": "Succesvol bevestigd!",
  "You have unsaved changes on this content item. Do you want to discard your changes?": "Je hebt nog niet-opgeslagen wijzigingen voor dit item. Wil je deze wijzigingen negeren?",
  "No": "Nee",
  "To continue confirm that you have read and agree to the Terms and Privacy Policy.": "Bevestig dat je de algemene voorwaarden hebt gelezen en hiermee akkoord gaat.",
  "Yes": "Ja",
  "Invitation sent!": "Uitnodiging verstuurd!",
  "Shortcuts: Esc for No, Enter for Yes": "Sneltoetsen: Esc voor Nee, Enter voor Ja",
  "Usertype": "Gebruikerstype",
  "The user has been invited to your organisation and will be added once confirmed.": "De gebruiker is uitgenodigd voor je organisatie en wordt na bevestiging toegevoegd.",
  "Normal": "Normaal",
  "Member": "Lid",
  "Provide the 15 digit ID": "Geef het 15-cijferige ID op",
  "Is sandbox user?": "Is sandbox gebruiker?",
  "Owner: Can manage users and define owners": "Eigenaar: Kan gebruikers beheren en eigenaren instellen",
  "Admin: Can manage users": "Beheerder: Kan gebruikers beheren",
  "Member: Can not manage users": "Lid: Kan geen gebruikers beheren",
  "Firstname": "Voornaam",
  "Disable": "Deactiveren",
  "Lastname": "Achternaam",
  "Are you sure you want to disable this user?": "Weet je zeker dat je deze gebruiker wilt deactiveren?",
  "It seems you do not have any": "Het lijkt erop dat je er geen hebt",
  "Enable": "Activeren",
  "Type in all emails of the users you want to invite separated by a new line.": "Type alle e-mailadressen in van gebruikers die je wilt uitnodigen, gescheiden met een nieuwe regel.",
  "Invite others": "Andere uitnodigen",
  "yet.": "nog niet.",
  "Send": "Versturen",
  "Done!": "Klaar!",
  "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).": "De uitnodiging is verstuurd! Nadat de gebruikers zich hebben aangemeld, kun je ze als medewerker toevoegen aan een Space.",
  "Please enter at least one email": "Geef tenminste één e-mailadres op",
  "Invite more people": "Meer personen uitnodigen",
  " is not a valid email": " is geen geldig e-mailadres",
  "from": "van",
  "Target": "Doel",
  "Asset": "Bestand",
  "Current window": "Huidig venster",
  "Get started": "Starten",
  "New window": "Nieuw venster",
  "terms of use": "algemene voorwaarden",
  "Signup": "Registreren",
  "By clicking \"Signup\" you accept the": "Door op \"Registreren\" te klikken, ga je akkoord met",
  "Switch to login": "Terug naar inloggen",
  "Forgot password?": "Wachtwoord vergeten?",
  "Already have an account?": "Heb je al een account?",
  "No account yet?": "Nog geen account?",
  "Signup here": "Hier registreren",
  "Login": "Inloggen",
  "Resend": "Opnieuw versturen",
  "confirmation email": "bevestigingsmail",
  "Send password reset link": "Stuur een link om het wachtwoord opnieuw in te stellen",
  "Imprint": "Impressum",
  "Privacy policy": "Privacybeleid",
  "Are you a developer?": "Ben je een ontwikkelaar?",
  "Choose no if you want to join an existing project": "Kies nee als je lid wilt worden van een bestaand project",
  "No, I am not a dev": "Nee, ik ben geen ontwikkelaar",
  "Yes, I am a dev": "Ja, ik ben een ontwikkelaar",
  "Choose your own adventure": "Kies je eigen avontuur",
  "Join an existing space": "Word lid van een bestaande Space",
  "What would you do like next?": "Wat zou je nu willen doen?",
  "You are almost there": "Je bent er bijna",
  "Success!": "Succes!",
  "Insert the email of your space admin to let them add you as a collaborator of the space": "Vul het e-mailadres in van de beheerder, zodat ze je kunnen toevoegen als medewerker van de Space",
  "I received the email": "Ik heb de e-mail ontvangen",
  "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.": "Je wordt per e-mail op de hoogte gebracht als de beheerder je heeft toegevoegd als medewerker. Klik vervolgens op deze knop om door te gaan.",
  "It seems that the authentification code is wrong.": "Het lijkt erop dat de authenticatiecode verkeerd is.",
  "My Account": "Mijn account",
  "Please check the password confirmation.": "Controleer de wachtwoordbevestiging.",
  "You are logged in via a third party authentication provider.": "Je bent ingelogd via een externe authenticatieprovider.",
  "Profile picture": "Profielfoto",
  "Username": "Gebruikersnaam",
  "Your Storyblok ID for adding you as a collaborator to another project is": "Het Storyblok ID waarmee je toegevoegd kan worden aan andere projecten is",
  "Recommended: 500px x 500px (JPG or PNG)": "Aanbevolen: 500x500 pixels (JPG of PNG)",
  "Phone number": "Telefoonnummer",
  "Your timezone": "Tijdzone",
  "Your language": "Taal",
  "Current password": "Huidig wachtwoord",
  "Insert your current password if you changed your username, email, phone number, password or security settings": "Voer je huidige wachtwoord in als je je gebruikersnaam, e-mailadres, telefoonnummer, wachtwoord of beveiligingsvoorkeur wijzigt",
  "New Password": "Nieuw wachtwoord",
  "Do you want to change your current password?": "Wil je je huidige wachtwoord wijzigen?",
  "Password confirmation": "Wachtwoordbevestiging",
  "Security Settings": "Beveiligingsinstellingen",
  "How do you want to login?": "Hoe wil je inloggen?",
  "Password only": "Alleen met wachtwoord",
  "Two factor authentication via SMS": "Tweefactorauthenticatie via SMS",
  "Personal access tokens": "Persoonlijke toegangstoken",
  "Two factor authentication via Email": "Tweefactorauthenticatie via e-mail",
  "Storyblok Management API": "Storyblok Management API",
  "Please copy this api key now. It will be visible only once.": "Kopieer deze API-sleutel. Deze zal maar één keer zichtbaar zijn.",
  "Tokens that have been generated to access the": "Gegenereerde tokens om toegang te krijgen tot",
  "Generate new Token": "Genereer nieuw token",
  "Personal access tokens work like ordinary OAuth access tokens.": "Persoonlijke toegangstokens werken als gewone OAuth toegangstokens.",
  "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.": "Ze kunnen worden gebruikt als authenticatiemethode, om volledige toegang te krijgen tot de API en moeten NOOIT publiekelijk gedeeld worden.",
  "Privacy": "Privacy",
  "Show username instead of email as collaborator": "Gebruikersnaam weergeven in plaats van e-mailadres",
  "Privacy Setting": "Privacy instellingen",
  "Download in German": "In het Duits downloaden",
  "Download in English": "In het Engels downloaden",
  "Data processing agreement": "Gegevensverwerking overeenkomst",
  "Read more about our": "Lees hier meer over onze",
  "Account deletion": "Account verwijderen",
  "privacy policy here": "privacybeleid",
  "Yes, delete my account": "Ja, verwijder mijn account",
  "Do you want to delete your account?": "Wil je je account verwijderen?",
  "Do you really want to delete your account? Type \"delete me\" and click confirm.": "Weet je zeker dat je je account wilt verwijderen? Type \"delete me\" en klik op bevestigen.",
  "User has been updated": "Gebruiker is bijgewerkt",
  "Not found": "Niet gevonden",
  "Please insert the code we sent to ": "Voer de code in die je van ons hebt ontvangen",
  "Add user": "Gebruiker toevoegen",
  "It seems that you do not have access to this page.": "Het lijkt er op dat je geen toegang hebt tot deze pagina.",
  "Create a new organization": "Nieuwe organisatie aanmaken",
  "Organisation name": "Naam van organistatie",
  "Create organization": "Organisatie aanmaken",
  "SO Settings": "SO instellingen",
  "Whitelabeling": "Whitelabeling",
  "Add SSO url": "Voeg SSO-url toe",
  "Url to the editor": "Url voor de editor",
  "Provide the full url like": "Geef de volledige url op, zoals",
  "Logo-Url": "Url van logo",
  "Provide the full url to the logo like": "Geef de volledige url op van het logo, zoals",
  "Not defined": "Niet gedefinieerd",
  "Organization updated successfully": "Organisatie succesvol bijgewerkt",
  "Disabled": "Uitgeschakeld",
  "Please set your password": "Stel je wachtwoord in",
  "Set password": "Wachtwoord instellen",
  "Password has been set. You can now login.": "Wachtwoord is ingesteld. Je kunt nu inloggen.",
  "Thank you": "Bedankt",
  "Please confirm your billing information": "Bevestig je factuurgegevens",
  "Login failed. The login token may expired. Please try again.": "Inloggen mislukt. Het inlogtoken is mogelijk verlopen. Probeer het nogmaals.",
  "Please enter all required information": "Vul alle verplichte informatie in",
  "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.": "We proberen de factuurgegevens actueel te houden. Bevestig dat onderstaande gegevens juist zijn of bewerk ze indien nodig.",
  "One last thing before you can comment": "Nog één laatste ding voordat je kunt reageren",
  "Profile picture (optional)": "Profielfoto (optioneel)",
  "Are you sure you want to delete this item?": "Weet je zeker dat je dit item wilt verwijderen?",
  "Help other collaborators to identify you better by providing your name and a profile picture.": "Help andere medewerkers je te identificeren door je naam en profielfoto op te geven.",
  "Are you sure you want to delete this item(s)?": "Weet je zeker dat je deze items wilt verwijderen?"
}
