export default {
  "Dashboard": "Kokpit",
  "Back to spaces": "Wróć do przestrzeni",
  "Content": "Treść",
  "Commerce": "Commerce",
  "Assets": "Zasoby",
  "Datasources": "Źródła danych",
  "Activities": "Activities",
  "Tasks": "Zadania",
  "Components": "Komponenty",
  "Apps": "Aplikacje",
  "Settings": "Ustawienia",
  "Subscription": "Subskrybcja",
  "Plugins": "Wtyczki",
  "Logout": "Wyloguj",
  "Report a problem": "Zgłoś problem",
  "Create new space": "Stwórz nową przestrzeń",
  "Search spaces...": "Szukaj przestrzeni...",
  "My organization": "Moja organizacja",
  "Subscribe": "Zasubskrybuj",
  "To": "Do",
  "From": "Z",
  "Apply filter": "Zastosuj filtr",
  "Filter": "Filtr",
  "Unknown user": "Nieznany użytkownik",
  "Author": "Autor",
  "Action": "Akcja",
  "Date": "Data",
  "Back": "Wstecz",
  "Activity Details": "Szczegóły Aktywności",
  "Open": "Otwórz",
  "Restore this Story": "Przywróć tę Historię",
  "Categories": "Kategorie",
  "Story": "Historia",
  "The item has been restored!": "Pozycja została przywrócona!",
  "All": "Wszystko",
  "Search for apps, discover new field types and add functionalities to your Storyblok project.": "Szukaj aplikacji, odkryj nowe typy pól i dodaj funkcjonalności do Twojego projektu Storyblok.",
  "My apps": "Moje aplikacje",
  "Create new app": "Stwórz nową aplikację",
  "Installed": "Zainstalowano",
  "App Directory": "Katalog Aplikacji",
  "There are no apps in this category.": "W tej kategorii nie ma żadnych aplikacji.",
  "Install": "Zainstaluj",
  "Choose the space to install this app": "Wybierz przestrzeń, w której chcesz zainstalować tę aplikację",
  "Can not move asset folder into folder without permissions.": "Brak uprawnień do przeniesienia katalogu zasobów do innego katalogu",
  "Can not move asset into folder without permissions.": "Brak uprawnień do przeniesienia zasobu do katalogu.",
  "Can not move asset away from folder without permissions.": "Brak uprawnień do przeniesienia zasobów poza katalog.",
  "Define the new name of the folder.": "Podaj nową nazwę katalogu.",
  "Trashbin": "Kosz",
  "Are you sure that you want to delete this folder?": "Jesteś pewien, że chcesz usunąć ten katalog?",
  "Add": "Dodaj",
  "Asset folders are not included in the free plan but you can try them in the": "Katalogi zasobów nie są zawarte w darmowym planie ale może wypróbować je w",
  "New folder will be created in": "Nowy katalog zostanie stworzony w",
  "trial period": "wersji próbnej",
  "Can not create asset folder without permission for parent.": "Nie można utworzyć katalogu zasobów bez uprawnień do katalogu nadrzędnego.",
  "Original": "Oryginał",
  "Done": "Gotowe",
  "Cancel": "Anuluj",
  "Insert": "Wstaw",
  "Add Asset(s)": "Dodaj zasób(oby)",
  "Close": "Zamknij",
  "items": "pozycje",
  "Delete": "Usuń",
  "Move to folder": "Przenieś do katalogu",
  "Replace": "Zastąp",
  "Unselect all": "Odznacz wszystko",
  "Restore": "Przywróć",
  "Tiles": "Kafelki",
  "List": "Lista",
  "No assets found": "Nie znaleziono żadnych zasobów",
  "Sort": "Sortuj",
  "Default": "Domyślne",
  "View": "Widok",
  "Creation date (asc)": "Data utworzenia (rosnąco)",
  "Filename (asc)": "Nazwa pliku (rosnąco)",
  "Creation date (desc)": "Data utworzenia (malejąco)",
  "Filename (desc)": "Nazwa pliku (malejąco)",
  "Last updated date (asc)": "Data ostatniej aktualizacji (rosnąco)",
  "Last updated date (desc)": "Data ostatniej aktualizacji (malejąco)",
  "You are not allowed to insert this filetype here.": "Nie możesz wstawić tutaj pliku tego typu.",
  "This key is already defined": "Taki klucz już istnieje",
  "Key is in invalid format": "Klucz jest w nieprawidłowym formacie",
  "Something went wrong uploading some items": "Coś poszło nie tak podczas przesyłania niektórych plików",
  "Please choose a folder in the left sidebar": "Proszę wybrać katalog paska po lewej",
  "Define the new name of": "Podaj nową nazwę dla",
  "Something went wrong renaming the attribute": "Coś poszło nie tak podczas zmieniania nazwy atrybutu",
  "Be aware! Changing the name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Uwaga! Zaktualizowanie nazwy dla wszystkich pozycji może zająć kilka minut. Upewnij się, że Twoi edytorzy zapisali swoją prace i wyszli z edytora.",
  "Define the new name of the component group.": "Podaj nową nazwę dla grupy komponentów.",
  "Save": "Zapisz",
  "Are you sure that you want to delete this component group?": "Jesteś pewien, że chcesz usunąć tę grupę komponentów?",
  "Copy": "Kopiuj",
  "New": "Nowa",
  "Move to group": "Przenieś do grupy",
  "Please choose a component group in the left sidebar": "Proszę wybrać grupę komponentów z paska po lewej",
  "Paste": "Wklej",
  "Add block": "Dodaj blok",
  "Creation of a component failed. Maybe it already exists.": "Nie udało się stworzyć komponentu. Być może już istnieje.",
  "Are you sure you want to DELETE this component(s)?": "Jesteś pewien, że chcesz USUNĄĆ ten komponent(y)?",
  "new": "nowy",
  "Type to search or to create a": "Pisz aby wyszukać lub stworzyć",
  "Create new": "Stwórz nowy",
  "block": "blok",
  "New Component": "Nowy Komponent",
  "Updated": "Zaktualizowano",
  "Name": "Nazwa",
  "Shortcuts: Esc, Control + S": "Skróty: Esc, Control + S",
  "Next": "Następny",
  "Define a name": "Zdefiniuj nazwę",
  "Save schema": "Zapisz schemat",
  "Act as content type (eg. blog-post)": "Użyj jako typu treści (np. blog-post)",
  "Define": "Zdefiniuj",
  "Nestable": "Zagnieżdżalny",
  "Technical name": "Nazwa programistyczna",
  "Edit field": "Edytuj pole",
  "Config": "Konfiguracja",
  "Schema": "Schemat",
  "Renaming": "Zmienianie nazwy",
  "Change field name": "Zmień nazwę pola",
  "Used in the json as component name": "Używane w JSON jako nazwa komponentu",
  "Be aware! Changing the technical name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Uwaga! Zaktualizowanie nazwy programistycznej dla wszystkich pozycji może zająć kilka minut. Upewnij się, że Twoi edytorzy zapisali swoją prace i wyszli z edytora.",
  "Display name": "Wyświetlana nazwa",
  "Preview template": "Szablon podglądu",
  "Screenshot or icon": "Zrzut ekranu lub ikona",
  "Used in the editor interface only": "Używane tylko w interfejsie edytora",
  "of this setting": "tego ustawienia",
  "Read the documentation": "Przeczytaj dokumentację",
  "Load versions": "Wczytaj wersje",
  "Versions": "Wersje",
  "has been added below": "został dodany pod spodem",
  "Examples: news_items, body, columns, title, description or call_to_action_btn": "Przykłady: news_items, body, columns, title, description lub call_to_action_btn",
  "The component has been restored!": "Komponent został przywrócony!",
  "Do you really want to leave without saving your changes?": "Jesteś pewien, że chcesz wyjść bez zapisywania zmian?",
  "Type": "Typ",
  "Beta": "Beta",
  "Translatable": "Przetłumaczalny",
  "Allow empty paragraphs": "Zazwól na puste paragrafy",
  "Linktype": "Typ linku",
  "Rich-text as default": "Bogaty format tekstu jako domyślny",
  "Custom type": "Typ niestandardowy",
  "Category": "Kategoria",
  "Section items": "Pozycje sekcji",
  "Product": "Produkt",
  "Customize toolbar": "Dostosuj pasek narzędzi",
  "Toolbar items": "Pozycje paska narzędzi",
  "Source": "Źródło",
  "CSS class options (label/value)": "Opcje klasy CSS (etykieta/wartość)",
  "Datasource": "Źródło danych",
  "Stories": "Historie",
  "Self": "Samego siebie",
  "Internal datasource": "Wewnętrzne źródło danych",
  "Recommended to be checked, as UID is required for automatic link resolving.": "Zalecene zaznaczenie, ponieważ UID jest wymagany do automatycznego rozstrzygania linków.",
  "Use UID instead of ID": "Użyj UID zamiast ID",
  "In case you have a multi-language folder structure you can add the {0} placeholder and the path will be adapted dynamically. Examples: {0}/categories/, {0}/{1}/categories/": "Jeżeli posiadasz wielo-językową strukturę katalogów, możesz użyć zastępczego symbolu {0}, a ścieżka dopasuje się dynamiczne. Przykłady: {0}/categories/, {0}/{1}/categories/",
  "External JSON": "Zewnętrzny JSON",
  "Path to folder of stories": "Ścieżka do katalogu z historiamii",
  "Width": "Szerokość",
  "URL": "URL",
  "ratio": "stosunek",
  "pixel": "pixel",
  "Allowed maximum": "Dozwolone maksimum",
  "Options (name/value)": "Opcje (nazwa/wartość)",
  "Component(s)": "Komponent(y)",
  "Group(s)": "Grupa(y)",
  "Required field(s) (comma separated)": "Wymagane pole(a) (rozdzielone przecinkiem)",
  "Required": "Wymagane",
  "Default asset folder": "Domyślny katalog z zasobami",
  "Choose an asset folder where the assets should be assigned to.": "Wybierz katalog z zasobami, do którego powinny zostać przypisane zasoby.",
  "With {level} the path will be replaced dynamically using parts of the current slug. Examples: {0}/categories/, {0}/{1}/categories/": "Używając {poziom} ścieżka zostanie automatycznie zastąpiona używając części aktywnego slugu. Przykłady: {0}/categories/, {0}/{1}/categories/",
  "Restrict to folder": "Ogranicz do katalogu",
  "Force folder restriction": "Wymuść ograniczenie katalogu",
  "Regex validation": "Walidacja wyrażeniem regularnym",
  "Exclude from export": "Wyklucz z eksportu",
  "export app": "eksportuj aplikację",
  "To use with the": "Do użycia z",
  "Default value": "Domyślna wartość",
  "Can be updated by preview window": "Może zostać zaktualizowane przez okno podglądowe",
  "Loading...": "Wczytywanie...",
  "Item": "Pozycja",
  "Allow only specific components to be inserted": "Zezwól na wstawianie tylko wybranych komponentów",
  "Restrict to content types": "Ogranicz do typów treści",
  "Keep original size": "Zachowaj oryginalny rozmiar",
  "Force crop": "Wymuść przycięcie",
  "Prepend https to url": "Dodaj przedrostek https do URL",
  "Height": "Wysokość",
  "Maximum characters": "Maksymalna liczba znaków",
  "Disable time selection": "Wyłącz wybór czasu",
  "Description": "Opis",
  "dimensions app": "aplikacja rozmiary",
  "Force overwrite by merge action": "Wymuś akcję nadpisanie przez scalenie",
  "Id/Slug": "Id/Slug",
  "Enable RTL (Right to left)": "Włącz RTL (Od prawej do lewej)",
  "Autosave": "Autozapis",
  "API Url": "Adres URL API",
  "Export": "Eksport",
  "Import/Export": "Import/Eksport",
  "Dimensions": "Wymiary",
  "Add Dimension": "Dodaj wymiar",
  "Import": "Import",
  "A datasource in Storyblok is a collection of key-value pairs.": "W Storyblok źródłem danych nazywany jest zbiór par w postaci klucz-wartość.",
  "Datasources can be used in a schema definition of a component for single or multiple choice options. You can also access": "Źródła Danych mogą być użyte w definiowaniu schematu komponentu dla pól z pojedynczym lub wielokrotnym wyborem. Możesz także uzyskać",
  "datasource entries from the API": "pozycję ze Źródła Danych z API",
  "to use them for labels, categories or similar.": "aby użyć je do etykiet, kategorii lub podobnych.",
  "Unsaved Changes": "Niezapisane zmiany",
  "Datasource entries": "Pozycje Źródła Danych",
  "Datasources are not included in the free plan": "Źródła Danych nie są zawarte w darmowym planie",
  "but you can try them in the": "ale możesz wypróbować je w",
  "Saved": "Zapisano",
  "Select all": "Zaznacz wszystko",
  "The options could not be loaded.": "Opcje nie mogły zostać wczytane.",
  "New Datasource": "Nowe Źródło Danych",
  "The following component(s) can not be pasted here": "Następujący komponent(y) nie mogą zostać tu wklejone",
  "Please save first to continue editing child components.": "Proszę zapisać przed przystąpieniem do edycji potomnych komponentów.",
  "Enabled?": "Włączone?",
  "Asset manager": "Menedżer zasobów",
  "Loading": "Wczytywanie",
  "Upload new": "Prześlij nowy",
  "Your file exceeds the maximum filesize limit of": "Twój plik przekracza maksymalny rozmiar wynoszący",
  "Please reduce the size of your file.": "Proszę zmniejszyć rozmiar swojego pliku.",
  "Alt text": "Alternatywny tekst",
  "Base64": "Base64",
  "Original Size": "Oryginalny rozmiar",
  "Image loading failed": "Wczytywanie obrazka nie powiodło się",
  "Quote": "Cytat",
  "Code Block": "Blok kodu",
  "Ordered List": "Uporządkowana Lista",
  "Headline 2": "Nagłówek 2",
  "Headline 4": "Nagłówek 4",
  "Headline 3": "Nagłówek 3",
  "Headline 5": "Nagłówek 5",
  "Paragraph": "Paragraf",
  "Help": "Pomoc",
  "Internal link": "Link wewnętrzny",
  "Show only selected": "Pokaż tylko zaznaczone",
  "more items found": "znaleziono więcej pozycji",
  "Invoices": "Faktury",
  "Tip: Use Ctrl + S to save": "Wskazówka: Użyj Ctrl + S żeby zapisać",
  "Input": "Wejście",
  "Publish": "Opublikuj",
  "You are not allowed to edit this plugin but can see the code at Settings/Details.": "Nie masz uprawnień do edycji tej wtyczki ale możesz zobaczyć kod w Ustawienia/Szczegóły",
  "Field type preview": "Podgląd typu pola",
  "Options (key/value)": "Opcje (klucz/wartość)",
  "Space Id": "ID Przestrzeni",
  "Enable local dev mode": "Włącz lokalny tryb dewelopera",
  "Settings/Details": "Ustawienia/Szczegóły",
  "Output": "Wyjście",
  "for approval to make it available for all users.": "na zgodę aby upublicznić je dla wszystkich użytkowników.",
  "Submit the plugin": "Prześlij wtyczkę",
  "Code": "Kod",
  "You can copy the code of this plugin to create your own plugin.": "Możesz skopiować kod tej wtyczki aby stworzyć swoją własną.",
  "Assigned spaces": "Przypisane przestrzenie",
  "If you assign this plugin to a space other developers can also use it in the schema definition. Without assigning it only you can add the plugin to the schemas.": "Jeżeli przypiszesz tę wtyczkę do przestrzeni to inni deweloperzy będą mogli użyć jej w definicji schematu. Bez przypisania tylko Ty możesz dodać wtyczkę do schematów.",
  "Attention: All spaces using this plugin will not be able to use it any more if you click delete.": "Uwaga: Wszystkie przestrzenie używające tej wtyczki nie będą mogły jej już używać jeżeli klikniesz usuń.",
  "Documentation": "Dokumentacja",
  "Danger zone": "Strefa niebezpieczeństwa",
  "What is a field type plugin?": "Czym jest wtyczka typu pole?",
  "A field type plugin extends the Storyblok editor with your own custom field types.": "Wtyczka typu pole rozszerza edytor Storyblok dodając Twoje własne, niestandardowe pola",
  "It is basically a": "Jest to w zasadzie",
  "The properties that are passed to the field type are:": "Właściwości, które są przekazywane do pola to:",
  "component extended with a few helpers in the window.Storyblok.plugin mixin.": "komponent rozszerzony kilkoma funkcjami pomocniczymi, zapisanymi w mixinie window.Storyblok.plugin.",
  "Examples for field types are colorpickers, WYSYWYG editors or meta tags.": "Przykładowe pola to narzędze do wybierania kolorów, edytor WYSIWYG, lub meta pola",
  "Uid of the parent component": "Uid komponentu-rodzica",
  "Options parsed from the schema options array": "Opcje uzyskane z tablicy opcji w schemacie",
  "Schema options object": "Obiekt opcji schematu",
  "Current value of the fieldtype": "Aktualna wartość typu pola",
  "Story id of the current story": "Id historii dla aktualnej historii",
  "Space id of the current space": "Id przestrzeni dla aktualnej przestrzeni",
  "Api function to call the delivery api": "Funkcja API do wywołania API dostaw",
  "Methods": "Metody",
  "Draft token of the current space": "Token szkicu aktualnej przestrzeni",
  "How to call the Storyblok api?": "Jak odwołać się do API Storyblok?",
  "Should be used to define the initial data of the plugin.": "Powinno zostać użyte aby zdefiniować wstępne dane wtyczki.",
  "Should be used to initialize the plugin. Examples: Load data from Storyblok or external sources, Load and initialize a WYSIWYG editor.": "Powinno zostać użyte aby zainicjalizować wtyczkę. Przykład: Wczytaj dane ze Storyblok lub zewnętrznych źródeł, Wczytaj i zainicjalizuj edytor WYSIWYG",
  "To pass options that are configurable in the schema definition define the option keys in the \"Input\" box. The values will be available in the this.options object.": "Aby przekazać opcję, które są konfigurowalne w definicji schematu, zdefiniuj klucze opcji w polu \"Wejście\"",
  "How to pass options?": "Jak przekazać opcje?",
  "In field types you can use this.api to get access to the Storyblok delivery api. You can use it for example to build a selectbox of stories.": "W polach możesz wykorzystać this.api aby uzyskać dostęp do API dostaw. Możesz wykorzystać je aby np. zbudować pole wyboru historii",
  "Folder/Content-item permissions": "Uprawnienia Katalogu/Pozycji treści",
  "Item saved successfully!": "Pozycja zapisana pomyślnie!",
  "Source of sync": "Źródło synchronizacji",
  "Preview": "Podgląd",
  "Preview url": "URL podglądu",
  "View on Jsfiddle": "Zobacz na Jsfiddle",
  "Download": "Pobierz",
  "Admin": "Admin",
  "Permissions": "Uprawnienia",
  "Editor": "Edytor",
  "Advanced Rights": "Zaawansowane Uprawnienia",
  "Allow saving content": "Zezwól na zapisywanie treści",
  "Allow publishing content": "Zezwól na publikowanie treści",
  "Allow saving datasources": "Zezwól na zapisywanie źródeł danych",
  "Allow managing subscription": "Zezwól na zarządzanie subskrybcją",
  "Allow access to ecommerce app": "Zezwól na dostęp do aplikacji ecommerce",
  "Deny access to visual composer": "Odmów dostępu do wizualnego kompozytora",
  "Field Permissions": "Uprawnienia pola",
  "General": "Ogólne",
  "Allowed path": "Dozwolona ścieżka",
  "Your crawl URL": "Twój adres URL indeksowania",
  "Crawler": "Robot indeksujący",
  "Enabled": "Włączony",
  "Index": "Indeks",
  "Crawl now": "Indeksuj teraz",
  "Information needed to access the search endpoint or to configure the search client.": "Informacje potrzebne aby uzyskać dostęp do endpointu wyszukiwania lub skonfigurowania klienta wyszukiwania.",
  "Search Setup Guide": "Poradnik konfiguracji wyszukiwania",
  "Your tenant ID": "Twój identyfikator dzierżawcy",
  "See": "Zobacz",
  "Documents in index": "Dokumenty w indeksie",
  "Crawl requested at": "Zażądano indeksowania o godzinie",
  "Tenant ID": "ID Dzierżawcy",
  "Documents": "Dokumenty",
  "Clear index": "Wyczyść indeks",
  "Last crawled at": "Ostatnio indeksowano o godzinie",
  "Crawl has been initiated": "Indeksowanie zostało rozpoczęte",
  "In the first 14 days you can try out all Premium plan features!": "Podczas pierwszych 14 dni możesz wypróbować wszystkie funkcje planu Premium!",
  "Index deletion has been initiated": "Usuwanie indeksu zostało rozpoczęte",
  "API-Keys": "Klucze API",
  "We would love to hear your thoughts about Storyblok on": "Bardzo chcielbyśmy usłyszeć Twoją opinie na temat Storyblok na",
  "Renderer": "Renderer",
  "Backup": "Kopia zapasowa",
  "Users": "Użytkownicy",
  "Workflow": "Przepływ pracy",
  "Search": "Wyszukiwanie",
  "Languages": "Języki",
  "This is the page that the frontend-editor opens.": "To jest strona, którą otwiera edytor frontend.",
  "Location (default environment)": "Lokalizacja (środowisko domyślne)",
  "Insert your domain/location including the protocol. Example: http://www.example.com/": "Wpisz swoją domenę/lokalizację uwzględniając protokół. Przykład: http://www.example.com/",
  "Provide this ID in your support tickets": "Podaj ten identyfikator w biletach pomocy technicznej",
  "Your space ID": "ID Twojej przestrzeni",
  "Preview urls": "Adresy URL podglądu",
  "Define multiple domains/locations to quickly switch the preview urls in the story-editor.": "Zdefiniuj wiele domen/lokalizacji aby szybko zmieniać adresy URL podglądu w edytorze historii.",
  "Add preview url": "Dodaj adres URL podglądu",
  "Webhooks": "Webhooks",
  "Story published &amp; unpublished": "Historia opublikowana &amp; nieopublikowana",
  "Story saved": "Historia zapisana",
  "Branch deployed": "Gałąź wdrożona",
  "Release merged": "Wydanie scalone",
  "Slack integration": "Integracja ze Slackiem",
  "Loading... You will be redirect to Slack in a few seconds!": "Wczytywanie... Za chwilę zostaniesz przekierowany na stronę Slacka!",
  "Get notified on your Slack channel if a new Story has been published!": "Otrzymaj powiadomienie na kanale w Slacku kiedy nowa Historia zostanie opublikowana!",
  "With this integration you can choose a Slack channel where Storyblok posts messages whenever a user publishes new content.": "Przy pomocy tej integracji możesz wybrać kanał na Slacku, w którym Storyblok będzie publikował wiadomości za każdym razem kiedy użytkownik opublikuje nowe treści.",
  "Disconnect": "Rozłącz",
  "Cloud name": "Nazwa chmury",
  "Cloudinary integration": "Integracja z Cloudinary",
  "Api Key": "Klucz API",
  "Branches": "Gałęzie",
  "Default content type": "Domyślny typ treści",
  "Content types": "Typy treści",
  "Name of the branch": "Nazwa gałęzi",
  "Branches are not included in the free plan": "Gałęzie nie są zawarte w darmowym planie",
  "Duplication": "Powielanie",
  "This is useful if you want to offer your space for other users as a boilerplate or theme.": "Jest to przydatne jeśli chcesz zaoferować swoją przestrzeń innym użytkowników jako boilerplate lub szablon.",
  "ATTENTION! Only check this checkbox if you are sure that you want all data of this space available for duplication.": "UWAGA! Zaznacz to pole wyboru tylko jeżeli jesteś pewien, że chcesz aby wszystkie dane z tej przestrzeni były dostępne do powielania.",
  "Make this space duplicatable by all users": "Zezwól na powielanie tej przestrzeni wszystkim użytkownikom",
  "Content ownership": "Prawo własności do treści",
  "Parent ID": "ID Rodzica",
  "Parent": "Rodzic",
  "Image service": "Serwis obrazków",
  "Content ownership client endpoint": "Kliencki endpoint do praw własności do treści",
  "List of paths to invalidate": "Lista ścieżek do unieważnienia",
  "Delete this space": "Usuń tą przestrzeń",
  "Invalidate": "Unieważnij",
  "Workflow webhooks": "Webhooki przepływu pracy",
  "Owner": "Właściciel",
  "Workflow changed": "Przepływ pracy zmieniony",
  "Transfer ownership": "Przenieś własność",
  "Transfer": "Przenieś",
  "Attention! Transferring the ownership will remove all your rights to this space.": "Uwaga! Przeniesienie własności odbierze Ci wszystkie prawa do tej przestrzeni.",
  "The owner needs to add you as a collaborator if you want to have access again.": "Właściciel będzie musiał dodać Cie jako współpracownika jeżeli chcesz znowu mieć dostęp.",
  "Collaborators": "Współpracownicy",
  "Collaborator": "Współpracownik",
  "No user found with this email or username.": "Nie znaleziono użytkownika z podanym adresem email lub nazwą.",
  "Name of the role": "Nazwa roli",
  "Role": "Role",
  "Add a new user to your org": "Dodaj nowego użytkownika do swojej organizacji",
  "Advanced rights and roles are not included in the free and basic plan": "Zaawansowane uprawnienia i role nie są zawarte w darmowym i podstawowym planie",
  "Use your Amazon S3 bucket to create backups.": "Użyj Amazon S3 bucket aby wykonywać kopie zapasowe.",
  "Backup now": "Wykonaj kopię zapasową teraz",
  "Backups content (stories) and compontents": "Wykonaj kopię treści (historii) oraz komponentów",
  "Define your S3-Bucket and AWS-ARN to enable backups.": "Podaj swój S3-Bucket i AWS-ARN żeby włączyć kopię zapasową.",
  "Daily backups": "Codziennie kopie zapasowe",
  "Define the name of the S3-bucket where you want to store your backups.": "Podaj nazwę S3-Bucket, w którym chcesz przechowywać kopię zapasową.",
  "S3-bucket": "S3-bucket",
  "Activate automatic daily backups": "Włącz codziennie kopie zapasowe",
  "1. Read the": "1. Przeczytaj",
  "AWS Policy ARN": "Polityka AWS ARN",
  "Show setup instructions": "Pokaż instrukcję instalacji",
  "tutorial on how to setup an Amazon IAM role": "poradnik na temat tworzenia roli Amazon IAM",
  "2. Create an Amazon IAM role with following access policy document:": "2. Stwórz rolę Amazon IAM z następującym dokumentem polityki dostępu:",
  "if not done yet.": "jeżeli jeszcze nie zostało zrobione.",
  "The role should have the permission to access and create files on the S3 bucket you defined. You can for example use the following permission policy replacing YOUR_BUCKET with your bucket name:": "Rola powinna mieć uprawnienia do dostępu i tworzenia plików w S3-Bucket, który podałeś. Możesz użyć następującej polityki dostępu, zmieniając YOUR_BUCKET na nazwę Twojego bucket'u:",
  "Restore spaces from backups on your Amazon S3 bucket.": "Przywróć przestrzenie z kopi zapasowych przechowywanych na Twoim Amazon S3-Bucket",
  "Backup file": "Plik kopii zapasowej",
  "Show latest backups": "Pokaż najnowsze kopie zapasowe",
  "Latest five backups": "Najnowsze pięć kopii zapasowych",
  "Restore now": "Przywróć teraz",
  "The settings below only apply if you are using": "Poniższe ustawienia obowiązują tylko w przypadku korzystania z",
  "Attention! \"Restore now\" deletes old data and restores content (stories) and compontents from the backup file.": "Uwaga! \"Przywróć teraz\" usuwa stare dane i przywraca treści (historie) i komponenty z kopii zapasowej",
  "Rendering service": "Usługa renderowania",
  "Your domain": "Twoja domena",
  "To connect your domain to Storyblok you need to create a CNAME Record pointing to eu-domain.storyblok.com": "Aby połączyć swoją domenę ze Storyblok musisz utworzyć rekord CNAME wskazujący na eu-domain.storyblok.com",
  "Routes": "Ścieżki",
  "Add Route": "Dodaj ścieżkę",
  "Please read the": "Proszę przeczytaj",
  "Add custom routes to define different page templates.": "Dodaj niestandardowe ścieżki aby zdefiniować różne szablony stron.",
  "documentation about internationalization": "dokumentacja dotycząca internacjonalizacji",
  "before configuring languages.": "przed konfigurowaniem języków.",
  "Add languages to activate field level translations.": "Dodaj języki aby aktywować tłumaczenia na poziomie pól.",
  "Add Language": "Dodaj Język",
  "Label": "Etykieta",
  "The invalidation process has been initiated": "Proces unieważniania został rozpoczęty",
  "The backup has been initiated": "Tworzenie kopii zapasowej zostało rozpoczęte",
  "Are you sure you want to delete your current content and overwrite it with this backup?": "Jesteś pewien, że chcesz usunąć aktualne treści i nadpisać je tą kopią zapasową?",
  "The restore process has been initiated": "Proces przywracania został rozpoczęty",
  "Transfer was not successful. Make sure that the new owner exists.": "Transfer się nie powiódł. Upewnij się, że nowy właściciel istnieje",
  "The collaborator has been added": "Współpracownik został dodany",
  "Please insert an email address": "Proszę wprowadzić adres email",
  "Branches sorted successfully!": "Gałęzie zostały pomyślnie posortowane!",
  "Create or join a space": "Stwórz lub dołącz do przestrzeni",
  "Create a new space": "Stwórz nową przestrzeń",
  "Play with a demo": "Wypróbuj demo",
  "Duplicate a space": "Powiel przestrzeń",
  "Join a space": "Dołącz do przestrzeni",
  "Create space": "Stwórz przestrzeń",
  "Headless (API/SDKs)": "Headless (API/SDKs)",
  "what is that?": "co to jest?",
  "Duplicate space": "Powiel przestrzeń",
  "Choose the space for the duplication": "Wybierz przestrzeń, którą chcesz powielić",
  "You do not have created any spaces yet.": "Nie utworzyłeś jeszcze żadnych przestrzeni.",
  "You can test the editing interface and our visual composer without to write any code on your own.": "Możesz wypróbować interfejs edytora lub nasz wizualny kompozytor, bez potrzeby pisania własnego kodu",
  "Create Demo": "Stwórz Demo",
  "Insert the email of your space admin to let them add you as a collaborator of the space.": "Wpisz adres email administratora Twojej przestrzeni aby mogli Cie dodać jako współpracownika przestrzeni.",
  "Request access": "Zażądaj dostępu",
  "Email address of space admin": "Adres email administratora przestrzeni",
  "Success! You will get notified once the admin added you as a collaborator.": "Sukces! Zostaniesz powiadomiony kiedy administrator doda Cię jako współpracownika.",
  "Available Billing Information": "Dostepne informacje rozliczeniowe",
  "No spaces with billing information available": "Brak dostępnych przestrzeni z informacjami rozliczeniowymi",
  "Spaces": "Przestrzenie",
  "Show More": "Pokaż więcej",
  "Apply": "Zastosuj",
  "Show": "Pokaż",
  "Billing Information of Space": "Informacje rozliczeniowe Przestrzeni",
  "The information below will be applied to the fields of your current subscription process. You will be able to adopt them after applying them.": "Poniższe informacje zostaną zastosowane do pól bieżącego procesu subskrypcji. Będziesz mógł je adoptować po ich zastosowaniu.",
  "Company": "Firma",
  "Country": "Kraj",
  "Street / City / ZIP": "Ulica / Miasto / Kod pocztowy",
  "Email": "Email",
  "Add or change preview urls": "Dodaj lub zmień adresy URL podglądu",
  "Your server address": "Adres Twojego serwera",
  "1. Download a preconfigured project": "1. Pobierz wstępnie skonfigurowany projekt",
  "Preferred by our users": "Preferowany przez naszych użytkowników",
  "The downloaded package comes preconfigured with your api token": "Pobrany pakiet jest wstępnie skonfigurowany z Twoim tokenem API",
  "Tutorial": "Poradnik",
  "Other technologies": "Inne technologie",
  "2. Start your server": "2. Uruchom swój serwer",
  "Start the server of the downloaded package and insert your server url here:": "Uruchom serwer z pobranej paczki i wstaw tutaj jego adres URL:",
  "Go": "Dalej",
  "FAQ": "FAQ",
  "Can I build a full blown website with Storyblok?": "Can I build a full blown website with Storyblok?",
  "Can I create a blog with Storyblok?": "Czy za pomocą Storyblok mogę zbudować pełną wersję witryny?",
  "How does Storyblok work?": "Jak działa Storyblok?",
  "What is the Storyblok bridge?": "Czym jest most Storyblok?",
  "Allow deploying content": "Zezwól na wdrażanie treści",
  "General permissions": "Ogólne uprawnienia",
  "Allow unpublishing content": "Zezwól na wycofywanie treści",
  "Allow deleting content": "Zezwól na usuwanie treści",
  "Allow editing datasource keys & values": "Zezwól na edycję kluczy i wartości w źródłach danych",
  "Allow editing datasource values": "Zezwól na edytowanie wartości w źródłach danych",
  "Allow access to the tasks app": "Zezwól na dostęp do aplikacji zadania",
  "Deny moving a story": "Odmów przenoszenia historii",
  "Deny changing alternates group": "Odmów zmieniania grupy alternatywne",
  "Add languages the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Dodaj języki, do których użytkownik powinien mieć dostęp (działa jak biała lista). Jeżeli nie wybierzesz żadnej pozycji, użytkownik będzie miał prawa do edycji całej treści",
  "Deny changing the slug of a story": "Odmów zmieniania slugu historii",
  "Add folders or content items the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Dodaj katalogi lub pozycje treści, do których użytkownik powinien mieć dostęp (działa jak biała lista). Jeżeli nie wybierzesz żadnej pozycji, użytkownik będzie miał prawa do edycji całej treści",
  "Component field permissions": "Uprawnienia pola komponentu",
  "Datasource permissions": "Uprawnienia źródła danych",
  "Add component fields here to hide them in the interface.": "Dodaj pola komponenty tutaj aby ukrać je w interfejsie",
  "Add datasources the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all datasources.": "Dodaj źródła danych, do których użytkownik powinien mieć dostęp (działa jako biała lista). Jeżeli ",
  "Asset Folder Permissions": "Uprawnienia Katologu z Zasobami",
  "Add asset folders to restrict editing and upload access.": "Dodaj katalogi z zasobami aby ograniczyć możliwość edycji i przesyłania.",
  "Start by selecting a space in the sidebar or create a new space.": "Rozpocznij wybierając przestrzeń z paska lub tworząc nową przestrzeń.",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Wygląda na to, że nie masz jeszcze dostępu do żadnej przestrzeni. Skontaktuj się z administratorem swojej organizacji i poproś o dodanie Cie jako współpracownika",
  "Welcome!": "Witaj!",
  "Traffic": "Ruch",
  "Learn more about": "Dowiedz się więcej o",
  "Api requests": "Żądania do API",
  "Active Plan": "Aktywny Plan",
  "Usage": "Użycie",
  "Content activities": "Aktywności związane z treścią",
  "No billing": "Brak informacji rozliczeniowych",
  "Change": "Zmień",
  "Billed": "Rozliczono",
  "No recent changes": "Brak zmian w ostatnim czasie",
  "Choose your plan": "Zmień swój plan",
  "Recent changes": "Najnowsze zmiany",
  "Custom": "Niestandardowy",
  "Compare": "Porównaj",
  "user": "użytkownik",
  "Got a custom plan or coupon code?": "Posiadasz niestandardowy plan lub kod promocyjny?",
  "Custom plan": "Niestandardowy plan",
  "Entered plan ids will be validated after pressing subscribe.": "Wprowadzone ID planów zostaną zweryfikowane po naciśnięciu subskrybuj.",
  "Coupon code": "Kod promocyjny",
  "Entered coupon codes will be validated and applied after pressing subscribe.": "Wprowadzone kody promocyjne zostaną zweryfikowane i zastosowane po naciśnięciu subskrybuj.",
  "Select seats": "Wybierz ilość miejsc",
  "Confirm subscription": "Zatwierdź subskrybcję",
  "Min": "Min",
  "Max": "Max",
  "By clicking the button below the new subscription will start.": "Po kliknięciu przycisku poniżej rozpocznie się nowa subskrypcja.",
  "Decide payment interval": "Wybierz okres płatności",
  "Change subscription": "Zmień subskrybcję",
  "Monthly": "Miesięcznie",
  "Annually": "Rocznie",
  "Define billing information": "Podaj informacje rozliczeniowe",
  "Email address": "Adres email",
  "VAT-Number": "Numer VAT",
  "Reuse from another space": "Użyj dane z innej przestrzeni",
  "Order number": "Numer zamówienia",
  "Street": "Ulica",
  "City": "Miasta",
  "Credit or debit card": "Karta kredytowa lub debetowa",
  "ZIP": "Kod pocztowy",
  "Enter payment information": "Wprowadź informacje o płatności",
  "Update payment information": "Zaktualizuj informacje o płatności",
  "Update billing information": "Zaktualizuj informacje rozliczeniowe",
  "Information: Our payment provider validates card information when it is saved. As a result of this process, you may see a temporary authorization for $1 on your statement.": "nformacje: nasz dostawca płatności sprawdza informacje o karcie po jej zapisaniu. W wyniku tego procesu na wyciągu może pojawić się tymczasowa autoryzacja na kwotę 1USD.",
  "Please provide all billing informations marked as required (*)": "Proszę uzupełnić wszystkie informacje rozliczeniowe oznaczone jako wymagane (*)",
  "Your selected team sizes are not in the limits of your selected feature set. You can select another feature set to continue.": "Wybrany przez Ciebie rozmiar zespołu nie mieści się w granicach dla wybranego planu. Możesz wybrać inny plan aby kontynuować.",
  "View invoices": "Zobacz faktury",
  "Summary": "Podsumowanie",
  "Please provide a credit or debit card": "Proszę podać kartę kredytową lub debetową",
  "If your entered plan is not correct you will still be able to try it again.": "Jeśli wprowadzony plan jest nieprawidłowy, nadal będziesz mógł spróbować ponownie.",
  "You have entered a custom plan with a special offering and pricing": "Wprowadziłeś niestandardowy plan ze specjalną ofertą i ceną",
  "users": "użytkowników",
  "VAT reverse charge applies.": "Obowiązuje odwrotne obciążenie VAT.",
  "VAT": "VAT",
  "Total": "Razem",
  "The benefits of the coupon code will be applied if available": "Korzyści z kodu promocyjnego zostaną zastosowane, jeśli są dostępne",
  "Thanks! You are awesome!": "Dzięki! Jesteś niesamowity!",
  "We would love to hear what you think about Storyblok.": "Bardzo chcielibyśmy usłyszeć, co myślisz o Storyblok.",
  "Chat with us or": "Napisz do nas na czacie lub",
  "your feedback.": "Twoją opinię.",
  "Tweet": "Tweet",
  "Star": "Gwiazdka",
  "Share": "Udostępnij",
  "Public access tokens are only for accessing the published version while preview tokens are for accessing the draft version also. Both are read-only tokens.": "Tokeny dostępu publicznego służą wyłącznie do uzyskiwania dostępu do opublikowanej wersji, podczas gdy tokeny podglądu mają również dostęp do wersji roboczej. Oba są tokenami tylko do odczytu.",
  "Access level": "Poziom dostępu",
  "Public": "Publiczny",
  "See API-Documentation": "Zobacz dokumentację API",
  "Theme": "Motyw",
  "Branch": "Gałąź",
  "Choose branch": "Wybierz gałąź",
  "Create Token": "Stwórz Token",
  "Color": "Kolor",
  "Define as default stage for new content items": "Zdefiniuj jako domyślny etap dla nowych elementów treści",
  "Publishing rights": "Uprawnienia publikowania",
  "Stage transition rules": "Uprawnienia przejść między etapami",
  "Allow users to publish or schedule the content": "Zezwól użytkownikom na publikowanie lub planowanie publikacji treści",
  "Specific stage(s)": "Określony etap(y)",
  "Next available stages": "Następny dostępny etap",
  "All stages": "Wszystkie etapy",
  "All users": "Wszyscy użytkownicy",
  "User(s)/Role(s) who can change the stage": "Użytkownicy/Role, które mogą zmienić etap",
  "to the next available stage": "do następnego dostępnego etapu",
  "Specific user(s)/role(s)": "Określeni użytkownicy/role",
  "Role(s)": "Rola(e)",
  "User(s)": "Użytkownik(cy)",
  "Workflow stages": "Etapy przepływu pracy",
  "See workflow documentation": "Zobacz dokumentację przepływu pracy",
  "Create": "Stwórz",
  "Choose an approver": "Wybierz osobę zatwierdzającą",
  "Workflow stages sorted successfully!": "Etapy przepływu pracy zostały pomyślnie posortowane!",
  "Are you sure you want to delete this workflow stage?": "Czy jesteś pewien, że chcesz usunąć ten etap przepływu pracy?",
  "Send for approval": "Wyślij do zatwierdzenia",
  "Approval request has been sent successfully!": "Prośba o zatwierdzenie została wysłana pomyślnie!",
  "Content items": "Elementy treści",
  "Entry": "Pozycja",
  "Define schema": "Zdefiniuj schemat",
  "Folder": "Katalog",
  "You have not defined any schema for this block yet.": "Nie zdefiniowałeś jeszcze żadnego schematu dla tego bloku.",
  "Define presets": "Zdefiniuj ustawienia wstępne",
  "Click \"Define schema\" to add the fields you need.": "Kliknij „Zdefiniuj schemat”, aby dodać potrzebne pola.",
  "No valid fields defined in this section yet.": "W tej sekcji nie zdefiniowano jeszcze poprawnych pól.",
  "is already part of another section": "jest już częścią innej sekcji",
  "Translate": "Przetłumacz",
  "Choose to delete the values or add the schema keys.": "Wybierz, aby usunąć wartości lub dodać klucze schematu.",
  "items out of schema": "elementy ze schematu",
  "We have found values which are not part of the schema.": "Znaleźliśmy wartości, które nie są częścią schematu.",
  "No changes found": "Nie znaleziono zmian",
  "Changes": "Zmiany",
  "Remove all": "Usuń wszystko",
  "Select releases to deploy": "Wybierz wersję do wdrożenia",
  "What is getting deployed?": "Co jest wdrażane?",
  "All content that is currently on the source branch and the releases you select.": "Cała treść, która obecnie znajduje się w gałęzi źródłowej i wybrane wersje.",
  "No releases found on the source branch": "Nie znaleziono wydań w gałęzi źródłowej",
  "A newer version of this content item has been found in the database.": "W bazie danych znaleziono nowszą wersję tego elementu treści.",
  "Confirm": "Potwierdź",
  "Choose the conflict solution": "Wybierz rozwiązanie konfliktu",
  "Copy over": "Przekopiuj",
  "Opens newer version in a new window to let you copy over your changes.": "Otwiera nowszą wersję w nowym oknie, umożliwiając kopiowanie wprowadzonych zmian.",
  "Overwrite": "Nadpisz",
  "Slug": "Slug",
  "Overwrites newer version with your changes.": "Zastępuje nowszą wersję wprowadzonymi zmianami.",
  "Define as root for the folder": "Zdefiniuj jako główny dla katalogu",
  "Preset": "Predefiniowane",
  "Content type": "Typ treści",
  "Confirm deletion": "Potwierdź usunięcie",
  "Are you sure that you want to delete this item(s)?": "Czy na pewno chcesz usunąć te elementy?",
  "Include associated alternates": "Uwzględnij powiązane alternatywy",
  "Target-Folder": "Katalog docelowy",
  "Is alternative version of the duplicate?": "Czy jest alternatywną wersją duplikatu?",
  "Duplicate": "Powiel",
  "Schedule": "Zaplanuj",
  "duplicated": "powielono",
  "You are not allowed to duplicate this story.": "Nie możesz powielać tej historii.",
  "Open published": "Otwórz opublikowane",
  "Send approval": "Zatwierdź",
  "Open draft": "Otwórz szkic",
  "Unpublish": "Cofnij publikację",
  "Draft json": "Szkic JSON",
  "Discard changes": "Odrzuć zmiany",
  "Start sync": "Rozpocznij synchronizację",
  "Published json": "Opublikowany JSON",
  "Status": "Status",
  "Tools": "Narzędzia",
  "Real path": "Prawdziwa ścieżka",
  "Settings for the folder content": "Settings for the folder content",
  "Disable visual composer": "Disable visual composer",
  "Clone to all": "Clone to all",
  "Deny changing content type": "Deny changing content type",
  "Merge to all": "Merge to all",
  "Dimensions are only available if you are editing a content item in a subfolder.": "Dimensions are only available if you are editing a content item in a subfolder.",
  "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).": "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).",
  "Not created yet": "Not created yet",
  "Create clone": "Create clone",
  "Merge": "Merge",
  "Something went wrong merging the alternate(s)": "Something went wrong merging the alternate(s)",
  "The alternate(s) have been created!": "The alternate(s) have been created!",
  "The alternate(s) have been merged!": "The alternate(s) have been merged!",
  "Add preset": "Add preset",
  "Presets are blocks filled with the content you currently have in the selected block.": "Presets are blocks filled with the content you currently have in the selected block.",
  "Something went wrong creating the alternate(s)": "Something went wrong creating the alternate(s)",
  "The saved presets are shown for all users at the selection of new blocks.": "The saved presets are shown for all users at the selection of new blocks.",
  "Existing presets": "Existing presets",
  "As default": "As default",
  "Release date (optional)": "Release date (optional)",
  "Branches to deploy": "Branches to deploy",
  "When the release gets merged all content will be automatically deployed to the selected branches.": "When the release gets merged all content will be automatically deployed to the selected branches.",
  "Entry configuration": "Entry configuration",
  "Editmode": "Editmode",
  "Are you sure you want to delete this release?": "Are you sure you want to delete this release?",
  "Form only": "Form only",
  "Visual": "Visual",
  "Tags": "Tags",
  "Sort by date": "Sort by date",
  "First published date": "First published date",
  "Remove": "Remove",
  "Alternative versions": "Alternative versions",
  "Search for the content group of this story.": "Search for the content group of this story.",
  "Shortcut": "Shortcut",
  "Pin as shortcut in the mini-browser": "Pin as shortcut in the mini-browser",
  "Current": "Current",
  "New release": "New release",
  "Skip this step": "Skip this step",
  "Move": "Move",
  "Next step": "Next step",
  "We have already done that for you. Open the entry \"Home\" below to play around.": "We have already done that for you. Open the entry \"Home\" below to play around.",
  "Create a demo page": "Create a demo page",
  "Create a new folder": "Create a new folder",
  "Create your first folder": "Create your first folder",
  "and define a new content type during the folder set-up.": "and define a new content type during the folder set-up.",
  "Create your first entry": "Create your first entry",
  "Create entry": "Create entry",
  "and define its fields by building its schema so you can fill it with content.": "and define its fields by building its schema so you can fill it with content.",
  "Will be released at": "Will be released at",
  "Show only items from this release": "Show only items from this release",
  "Has been published at": "Has been published at",
  "Last deployment": "Last deployment",
  "This branch has never been deployed": "This branch has never been deployed",
  "Release now": "Release now",
  "Open preview": "Open preview",
  "Deploy from source": "Deploy from source",
  "You are seeing deleted items": "You are seeing deleted items",
  "Name (desc)": "Name (desc)",
  "Default sorting": "Default sorting",
  "Name (asc)": "Name (asc)",
  "Slug (desc)": "Slug (desc)",
  "releases": "releases",
  "Slug (asc)": "Slug (asc)",
  "Created at": "Created at",
  "Updated at": "Updated at",
  "Deleted at": "Deleted at",
  "Are you sure you want to unpublish this item(s)?": "Are you sure you want to unpublish this item(s)?",
  "The items have been updated!": "The items have been updated!",
  "Are you sure you want to publish this item(s)?": "Are you sure you want to publish this item(s)?",
  "Are you sure you want to restore this item(s)?": "Are you sure you want to restore this item(s)?",
  "Something went wrong restoring some items": "Something went wrong restoring some items",
  "Something went wrong updating item(s)": "Something went wrong updating item(s)",
  "No tools installed on this space": "No tools installed on this space",
  "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.": "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.",
  "The content has been released!": "The content has been released!",
  "Do you really want to copy the content of the default language to the current and replace the existing field value?": "Do you really want to copy the content of the default language to the current and replace the existing field value?",
  "Default language": "Default language",
  "Install from the app store": "Install from the app store",
  "Draft updated at": "Draft updated at",
  "Never": "Never",
  "Published at": "Published at",
  "Latest workflow changes": "Latest workflow changes",
  "Last author": "Last author",
  "None": "None",
  "Workflow stage": "Workflow stage",
  "set by": "set by",
  "Assigned to": "Assigned to",
  "Update": "Update",
  "Comments": "Comments",
  "Load older comments": "Load older comments",
  "Edit": "Edit",
  "Workflow stage and assignments": "Workflow stage and assignments",
  "Add a comment": "Add a comment",
  "Assign to": "Assign to",
  "Notify users via email": "Notify users via email",
  "Submit": "Submit",
  "Lambda Function": "Lambda Function",
  "Task type": "Task type",
  "Webhook": "Webhook",
  "The payload of the request contains the task and the space id.": "The payload of the request contains the task and the space id.",
  "Lambda Function (coming soon)": "Lambda Function (coming soon)",
  "Provide the endpoint where you want to send a POST request.": "Provide the endpoint where you want to send a POST request.",
  "Protected variable": "Protected variable",
  "Function code": "Function code",
  "For example:": "For example:",
  "Ok": "Ok",
  "Are you sure you want to delete this task?": "Are you sure you want to delete this task?",
  "Last execution": "Last execution",
  "Currently running": "Currently running",
  "Executed successfully!": "Executed successfully!",
  "Execute": "Execute",
  "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.": "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.",
  "Autosave enabled?": "Autosave enabled?",
  "Empty": "Empty",
  "Choose a compatible XML or JSON generated from the export.": "Choose a compatible XML or JSON generated from the export.",
  "Desktop": "Desktop",
  "Tablet": "Tablet",
  "Tag": "Tag",
  "Mobile": "Mobile",
  "Select": "Select",
  "Content type value": "Content type value",
  "Component": "Component",
  "Assigned to me only": "Assigned to me only",
  "In folder": "In folder",
  "element": "element",
  "Search in current folder only": "Search in current folder only",
  "No results found": "No results found",
  "Current version": "Current version",
  "Start typing to search": "Start typing to search",
  "Confirming invitation": "Confirming invitation",
  "Please wait a couple of seconds": "Please wait a couple of seconds",
  "Unknown author": "Unknown author",
  "You are now a member of the organisation": "You are now a member of the organisation",
  "Go to spaces": "Go to spaces",
  "Invitation confirmed!": "Invitation confirmed!",
  "Please login first and then click the invitation link again.": "Please login first and then click the invitation link again.",
  "Go to login": "Go to login",
  "Login required.": "Login required.",
  "Your invitation is not valid anymore.": "Your invitation is not valid anymore.",
  "Please upgrade your Storyblok space. You have": "Please upgrade your Storyblok space. You have",
  "Something went wrong.": "Something went wrong.",
  "collaborator(s) and your": "collaborator(s) and your",
  "Please contact your Storyblok space owner. You have": "Please contact your Storyblok space owner. You have",
  "is over.": "is over.",
  "Just a moment. A background task is still running.": "Just a moment. A background task is still running.",
  "The Storyblok app has been updated!": "The Storyblok app has been updated!",
  "Please reload the window to get the newest version.": "Please reload the window to get the newest version.",
  "Reload window": "Reload window",
  "Manage": "Manage",
  "Toggle assistance mode": "Toggle assistance mode",
  "Assisted spaces": "Assisted spaces",
  "Logging in": "Logging in",
  "Sales": "Sales",
  "I have read and agree to the": "I have read and agree to the",
  "Logged in as": "Logged in as",
  "Catalogue": "Catalogue",
  "Initiating space": "Initiating space",
  "Configuration": "Configuration",
  "There was an error confirming your account. Please try again.": "There was an error confirming your account. Please try again.",
  "Resend confirmation": "Resend confirmation",
  "Confirmed successfully!": "Confirmed successfully!",
  "You have unsaved changes on this content item. Do you want to discard your changes?": "You have unsaved changes on this content item. Do you want to discard your changes?",
  "No": "No",
  "To continue confirm that you have read and agree to the Terms and Privacy Policy.": "To continue confirm that you have read and agree to the Terms and Privacy Policy.",
  "Yes": "Yes",
  "Invitation sent!": "Invitation sent!",
  "Shortcuts: Esc for No, Enter for Yes": "Shortcuts: Esc for No, Enter for Yes",
  "Usertype": "Usertype",
  "The user has been invited to your organisation and will be added once confirmed.": "The user has been invited to your organisation and will be added once confirmed.",
  "Normal": "Normal",
  "Member": "Member",
  "Provide the 15 digit ID": "Provide the 15 digit ID",
  "Is sandbox user?": "Is sandbox user?",
  "Owner: Can manage users and define owners": "Owner: Can manage users and define owners",
  "Admin: Can manage users": "Admin: Can manage users",
  "Member: Can not manage users": "Member: Can not manage users",
  "Firstname": "Firstname",
  "Disable": "Disable",
  "Lastname": "Lastname",
  "Are you sure you want to disable this user?": "Are you sure you want to disable this user?",
  "It seems you do not have any": "It seems you do not have any",
  "Enable": "Enable",
  "Type in all emails of the users you want to invite separated by a new line.": "Type in all emails of the users you want to invite separated by a new line.",
  "Invite others": "Invite others",
  "yet.": "yet.",
  "Send": "Send",
  "Done!": "Done!",
  "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).": "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).",
  "Please enter at least one email": "Please enter at least one email",
  "Invite more people": "Invite more people",
  " is not a valid email": " is not a valid email",
  "from": "from",
  "Target": "Target",
  "Asset": "Asset",
  "Current window": "Current window",
  "Get started": "Get started",
  "New window": "New window",
  "terms of use": "terms of use",
  "Signup": "Signup",
  "By clicking \"Signup\" you accept the": "By clicking \"Signup\" you accept the",
  "Switch to login": "Switch to login",
  "Forgot password?": "Forgot password?",
  "Already have an account?": "Already have an account?",
  "No account yet?": "No account yet?",
  "Signup here": "Signup here",
  "Login": "Login",
  "Resend": "Resend",
  "confirmation email": "confirmation email",
  "Send password reset link": "Send password reset link",
  "Imprint": "Imprint",
  "Privacy policy": "Privacy policy",
  "Are you a developer?": "Are you a developer?",
  "Choose no if you want to join an existing project": "Choose no if you want to join an existing project",
  "No, I am not a dev": "No, I am not a dev",
  "Yes, I am a dev": "Yes, I am a dev",
  "Choose your own adventure": "Choose your own adventure",
  "Join an existing space": "Join an existing space",
  "What would you do like next?": "What would you do like next?",
  "You are almost there": "You are almost there",
  "Success!": "Success!",
  "Insert the email of your space admin to let them add you as a collaborator of the space": "Insert the email of your space admin to let them add you as a collaborator of the space",
  "I received the email": "I received the email",
  "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.": "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.",
  "It seems that the authentification code is wrong.": "It seems that the authentification code is wrong.",
  "My account": "My account",
  "Please check the password confirmation.": "Please check the password confirmation.",
  "You are logged in via a third party authentication provider.": "You are logged in via a third party authentication provider.",
  "Profile picture": "Profile picture",
  "Username": "Username",
  "Your Storyblok ID for adding you as a collaborator to another project is": "Your Storyblok ID for adding you as a collaborator to another project is",
  "Recommended: 500px x 500px (JPG or PNG)": "Recommended: 500px x 500px (JPG or PNG)",
  "Phone number": "Phone number",
  "Your timezone": "Your timezone",
  "Your language": "Your language",
  "Current password": "Current password",
  "Insert your current password if you changed your username, email, phone number, password or security settings": "Insert your current password if you changed your username, email, phone number, password or security settings",
  "New Password": "New Password",
  "Do you want to change your current password?": "Do you want to change your current password?",
  "Password confirmation": "Password confirmation",
  "Security Settings": "Security Settings",
  "How do you want to login?": "How do you want to login?",
  "Password only": "Password only",
  "Two factor authentication via SMS": "Two factor authentication via SMS",
  "Personal access tokens": "Personal access tokens",
  "Two factor authentication via Email": "Two factor authentication via Email",
  "Storyblok Management API": "Storyblok Management API",
  "Please copy this api key now. It will be visible only once.": "Please copy this api key now. It will be visible only once.",
  "Tokens that have been generated to access the": "Tokens that have been generated to access the",
  "Generate new Token": "Generate new Token",
  "Personal access tokens work like ordinary OAuth access tokens.": "Personal access tokens work like ordinary OAuth access tokens.",
  "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.": "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.",
  "Privacy": "Privacy",
  "Show username instead of email as collaborator": "Show username instead of email as collaborator",
  "Privacy Setting": "Privacy Setting",
  "Download in German": "Download in German",
  "Download in English": "Download in English",
  "Data processing agreement": "Data processing agreement",
  "Read more about our": "Read more about our",
  "Account deletion": "Account deletion",
  "privacy policy here": "privacy policy here",
  "Yes, delete my account": "Yes, delete my account",
  "Do you want to delete your account?": "Do you want to delete your account?",
  "Do you really want to delete your account? Type \"delete me\" and click confirm.": "Do you really want to delete your account? Type \"delete me\" and click confirm.",
  "User has been updated": "User has been updated",
  "Not found": "Not found",
  "Please insert the code we sent to ": "Please insert the code we sent to ",
  "Add user": "Add user",
  "It seems that you do not have access to this page.": "It seems that you do not have access to this page.",
  "Create a new organization": "Create a new organization",
  "Organisation name": "Organisation name",
  "Create org": "Create org",
  "SO Settings": "SO Settings",
  "Whitelabeling": "Whitelabeling",
  "Add SSO url": "Add SSO url",
  "Url to the editor": "Url to the editor",
  "Provide the full url like": "Provide the full url like",
  "Logo-Url": "Logo-Url",
  "Provide the full url to the logo like": "Provide the full url to the logo like",
  "Not defined": "Not defined",
  "Organization updated successfully": "Organization updated successfully",
  "Disabled": "Disabled",
  "Please set your password": "Please set your password",
  "Set password": "Set password",
  "Password has been set. You can now login.": "Password has been set. You can now login.",
  "Thank you": "Thank you",
  "Please confirm your billing information": "Please confirm your billing information",
  "Login failed. The login token may expired. Please try again.": "Login failed. The login token may expired. Please try again.",
  "Please enter all required information": "Please enter all required information",
  "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.": "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.",
  "One last thing before you can comment": "One last thing before you can comment",
  "Profile picture (optional)": "Profile picture (optional)",
  "Are you sure you want to delete this item?": "Are you sure you want to delete this item?",
  "Help other collaborators to identify you better by providing your name and a profile picture.": "Help other collaborators to identify you better by providing your name and a profile picture.",
  "Are you sure you want to delete this item(s)?": "Are you sure you want to delete this item(s)?",
  "Loading user": "Loading user",
  "You are in a demo space.": "You are in a demo space.",
  "Submit to App-Store": "Submit to App-Store",
  "Browse apps": "Browse apps",
  "Submit to App-Directory": "Submit to App-Directory",
  "Active Subscriptions": "Active Subscriptions",
  "Total revenue": "Total revenue",
  "Finances": "Finances",
  "Hi there!": "Hi there!",
  "Choose to": "Choose to",
  "Perks": "Perks",
  "Team": "Team",
  "Entering Partner Portal": "Entering Partner Portal",
  "Signup as Partner": "Signup as Partner",
  "You are now unsubscribed.": "You are now unsubscribed.",
  "Seems that you do not have any tags yet.": "Seems that you do not have any tags yet.",
  "Create your first space": "Create your first space",
  "Install link": "Install link",
  "Name of the app": "Name of the app",
  "Id/Slug of the app": "Id/Slug of the app",
  "Allowed characters are letters, numbers and -.": "Allowed characters are letters, numbers and -.",
  "Oauth2 settings": "Oauth2 settings",
  "Client id": "Client id",
  "Secret": "Secret",
  "Url to your app": "Url to your app",
  "Oauth2 callback url": "Oauth2 callback url",
  "Field types": "Field types",
  "Select the Field-Type(s) that you would like to include in this app": "Select the Field-Type(s) that you would like to include in this app",
  "Images": "Images",
  "Screenshot (minimum 1000px)": "Screenshot (minimum 1000px)",
  "Icon (1024x1024px)": "Icon (1024x1024px)",
  "Sidebar Icon (white transparent SVG)": "Sidebar Icon (white transparent SVG)",
  "Your website": "Your website",
  "Url to your website": "Url to your website",
  "Your name": "Your name",
  "Video (optional)": "Video (optional)",
  "Url to Youtube video": "Url to Youtube video",
  "Intro": "Intro",
  "Short intro about what is your app about": "Short intro about what is your app about",
  "Attention! The deletion of this app will also delete all installations.": "Attention! The deletion of this app will also delete all installations.",
  "Delete this app": "Delete this app",
  "Uninstall": "Uninstall",
  "Requires plan": "Requires plan",
  "Try out in trial mode": "Try out in trial mode",
  "Approve app": "Approve app",
  "Website": "Website",
  "Last update": "Last update",
  "App content": "App content",
  "Field-Type/UI Extension": "Field-Type/UI Extension",
  "App submission": "App submission",
  "By committing your app the Storyblok app directory you accept the": "By committing your app the Storyblok app directory you accept the",
  "App Directory Agreement": "App Directory Agreement",
  "The review process take usually 2-3 days and you will get updated via email once the app is available in the app directory.": "The review process take usually 2-3 days and you will get updated via email once the app is available in the app directory.",
  "Confirm submission": "Confirm submission",
  "References": "References",
  "Unselect": "Unselect",
  "Clear trashcan": "Clear trashcan",
  "Move users to org": "Move users to org",
  "Is content type": "Is content type",
  "Add fields by dragging them to the tab.": "Add fields by dragging them to the tab.",
  "Drag and drop the field to the tab name to add it here. All fields that are not placed in custom tabs will be visible in the general tab. To remove the general tab place all fields in custom tabs.": "Drag and drop the field to the tab name to add it here. All fields that are not placed in custom tabs will be visible in the general tab. To remove the general tab place all fields in custom tabs.",
  "Manage tab": "Manage tab",
  "Rename": "Rename",
  "Move to right": "Move to right",
  "Move to left": "Move to left",
  "Hide empty option": "Hide empty option",
  "Restrict to content type": "Restrict to content type",
  "Enable email field": "Enable email field",
  "Enable asset selection": "Enable asset selection",
  "Enable anchor field on internal link": "Enable anchor field on internal link",
  "Minimum": "Minimum",
  "Maximum": "Maximum",
  "Define anchor": "Define anchor",
  "Choose to customize your experience": "Choose to customize your experience",
  "First name": "First name",
  "Last name": "Last name",
  "Job function": "Job function",
  "Marketing": "Marketing",
  "Information Technology": "Information Technology",
  "Development/Engineering/Programming": "Development/Engineering/Programming",
  "Human Resources": "Human Resources",
  "Procurement": "Procurement",
  "Security": "Security",
  "Other": "Other",
  "Business area": "Business area",
  "Accounting": "Accounting",
  "Marketing and Advertising": "Marketing and Advertising",
  "Automotive": "Automotive",
  "Agriculture": "Agriculture",
  "Chemicals": "Chemicals",
  "Construction": "Construction",
  "Consulting": "Consulting",
  "Consumer Products": "Consumer Products",
  "Education": "Education",
  "Finance": "Finance",
  "Food and Beverage": "Food and Beverage",
  "Gaming": "Gaming",
  "Government": "Government",
  "Healthcare": "Healthcare",
  "Hospitality": "Hospitality",
  "Insurance": "Insurance",
  "Legal": "Legal",
  "Manufacturing": "Manufacturing",
  "Media": "Media",
  "Oil and Energy": "Oil and Energy",
  "Pharmaceutical": "Pharmaceutical",
  "Real Estate": "Real Estate",
  "Retail": "Retail",
  "Sports": "Sports",
  "Technology": "Technology",
  "Telecommunications": "Telecommunications",
  "Transportation": "Transportation",
  "Utility": "Utility",
  "* Required fields": "* Required fields",
  "Continue": "Continue",
  "Personal settings": "Personal settings",
  "How would you describe your role?": "How would you describe your role?",
  "I am a content editor": "I am a content editor",
  "I am a developer or administrator": "I am a developer or administrator",
  "Add space to organization": "Add space to organization",
  "Add space": "Add space",
  "Unlink": "Unlink",
  "Create your first app": "Create your first app",
  "No invoices found": "No invoices found",
  "Space": "Space",
  "Invoice ID": "Invoice ID",
  "Amount": "Amount",
  "# of Spaces": "# of Spaces",
  "Revenue": "Revenue",
  "MRR": "MRR",
  "Nr. of spaces": "Nr. of spaces",
  "Active subscriptions": "Active subscriptions",
  "Total revenue share per month": "Total revenue share per month",
  "Welcome to the partner portal of Storyblok! We are excited to have you on board!": "Welcome to the partner portal of Storyblok! We are excited to have you on board!",
  "App type": "App type",
  "Sidebar": "Sidebar",
  "Fieldtype(s)": "Fieldtype(s)",
  "Add an existing space": "Add an existing space",
  "Member: Can manage spaces and apps": "Member: Can manage spaces and apps",
  "Owner: Can manage users, spaces, apps, partner account settings and see finances": "Owner: Can manage users, spaces, apps, partner account settings and see finances",
  "Stripe connect": "Stripe connect",
  "Connect your Stripe account to receive your revenue share each month.": "Connect your Stripe account to receive your revenue share each month.",
  "Partner details": "Partner details",
  "Define your business address and company information. * Required fields": "Define your business address and company information. * Required fields",
  "Billing email address": "Billing email address",
  "VAT number": "VAT number",
  "Company number": "Company number",
  "Bank information (for revenue share of enterprise plans)": "Bank information (for revenue share of enterprise plans)",
  "Plan": "Plan",
  "My spaces": "My spaces",
  "Field-types": "Field-types",
  "Partner Agreement": "Partner Agreement",
  "Current story object": "Current story object",
  "Partner portal": "Partner portal",
  "Show all": "Show all",
  "Show favorites only": "Show favorites only",
  "User ID": "User ID",
  "Single role": "Single role",
  "Multiple roles": "Multiple roles",
  "Individual permissions": "Individual permissions",
  "Organization": "Organization",
  "Maintenance mode (When enabled only admins can edit content)": "Maintenance mode (When enabled only admins can edit content)",
  "Storage": "Storage",
  "Store on the Storyblok S3 bucket": "Store on the Storyblok S3 bucket",
  "If unchecked the backup will be stored on your own S3 backup.": "If unchecked the backup will be stored on your own S3 backup.",
  "Preferred backup time": "Preferred backup time",
  "AWS Role ARN": "AWS Role ARN",
  "\"Restore now\" creates a new space with the restore date in the space name.": "\"Restore now\" creates a new space with the restore date in the space name.",
  "Your Unique Subdomain": "Your Unique Subdomain",
  "Your unique subdomain for your rendering service project with Storyblok. Replace this with your \"Location (default environment)\" to get started.": "Your unique subdomain for your rendering service project with Storyblok. Replace this with your \"Location (default environment)\" to get started.",
  "Publish translations individually (Beta)": "Publish translations individually (Beta)",
  "ATTENTION! When enabling, all languages needs to be published by going to each content item, selecting the language and clicking the Publish button.": "ATTENTION! When enabling, all languages needs to be published by going to each content item, selecting the language and clicking the Publish button.",
  "Beta version: Does not work yet together with releases and duplicating content.": "Beta version: Does not work yet together with releases and duplicating content.",
  "I have a developer": "I have a developer",
  "I am a developer": "I am a developer",
  "I want to talk": "I want to talk",
  "Thanks!": "Thanks!",
  "We received your request!": "We received your request!",
  "Invites sent!": "Invites sent!",
  "The invites got sent successfully.": "The invites got sent successfully.",
  "Invite your developer(s) to Storyblok so that they can create a project for you.": "Invite your developer(s) to Storyblok so that they can create a project for you.",
  "Email addresses": "Email addresses",
  "Send invites": "Send invites",
  "I need a developer": "I need a developer",
  "Inform us your project requirements to get offers from developers of our partner network.": "Inform us your project requirements to get offers from developers of our partner network.",
  "I want to...": "I want to...",
  "migrate a website or app to Storyblok": "migrate a website or app to Storyblok",
  "create a new website or app": "create a new website or app",
  "make an existing website or app editable in Storyblok": "make an existing website or app editable in Storyblok",
  "Budget": "Budget",
  "Less than $ 2.000": "Less than $ 2.000",
  "$ 2.000 to 5.000": "$ 2.000 to 5.000",
  "$ 5.000 to 20.000": "$ 5.000 to 20.000",
  "More than $ 20.000": "More than $ 20.000",
  "Project details": "Project details",
  "Switch to a developer account to create spaces for development of websites and apps. You can switch back to a content editor account in the my account section: "Switch to a developer account to create spaces for development of websites and apps. You can switch back to a content editor account in the my account section later.": later.",
  "Switch": "Switch",
  "Get in touch with someone at the Storyblok team to get a demo or discuss your requirements.": "Get in touch with someone at the Storyblok team to get a demo or discuss your requirements.",
  "Company name": "Company name",
  "Message": "Message",
  "Send message": "Send message",
  "Do you want to assign the space to your organization?": "Do you want to assign the space to your organization?",
  "No (for private spaces)": "No (for private spaces)",
  "Allow managing tags": "Allow managing tags",
  "Allow editing datasource keys": "Allow editing datasource keys",
  "Deny access to image editor": "Deny access to image editor",
  "Force user to create release": "Force user to create release",
  "Hide content if unauthorized": "Hide content if unauthorized",
  "Hide folders if unauthorized": "Hide folders if unauthorized",
  "Add branches the user should have the right to deploy to (acts as whitelist). If no item is selected the user has rights to deploy to all branches.": "Add branches the user should have the right to deploy to (acts as whitelist). If no item is selected the user has rights to deploy to all branches.",
  "Component/content-type permissions": "Component/content-type permissions",
  "Add the components or content types the user should not be able to select (acts as blacklist).": "Add the components or content types the user should not be able to select (acts as blacklist).",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.",
  "Start by selecting a space in the sidebar.": "Start by selecting a space in the sidebar.",
  "Details": "Details",
  "Your current plan is ": "Your current plan is ",
  "Pressing the button below will cancel your current subscription and remove all collaborators.": "Pressing the button below will cancel your current subscription and remove all collaborators.",
  "Cancel subscription": "Cancel subscription",
  "The starter plan is our free plan, so nothing we can cancel for you. If you are still receiving charges, let us know in our live-chat!": "The starter plan is our free plan, so nothing we can cancel for you. If you are still receiving charges, let us know in our live-chat!",
  "We are really sorry to see you go, but would love to understand why.": "We are really sorry to see you go, but would love to understand why.",
  "Set following stage after published": "Set following stage after published",
  "Attention! There are ": "Attention! There are ",
  " reference(s). Click to show.": " reference(s). Click to show.",
  "Undo (Ctrl+Z)": "Undo (Ctrl+Z)",
  "Redo (Ctrl+Y)": "Redo (Ctrl+Y)",
  "This block is not available any more.": "This block is not available any more.",
  "Go back to the root": "Go back to the root",
  "Please choose a release or create a new one to make your content changes.": "Please choose a release or create a new one to make your content changes.",
  "First published date (asc)": "First published date (asc)",
  "First published date (desc)": "First published date (desc)",
  "Published date (asc)": "Published date (asc)",
  "Published date (desc)": "Published date (desc)",
  "Tag list": "Tag list",
  "First published at": "First published at",
  "Translated name": "Translated name",
  "You can create a new tag at the config section of a content item.": "You can create a new tag at the config section of a content item.",
  "Assigned items": "Assigned items",
  "User dialog": "User dialog",
  "Containing content item": "Containing content item",
  "Containing asset": "Containing asset",
  "Clear all filters": "Clear all filters",
  "Load all": "Load all",
  "The user dialog JSON is invalid.": "The user dialog JSON is invalid.",
  "Edit App": "Edit App",
  "All apps": "All apps",
  "App installed successfully!": "App installed successfully!",
  "New App": "New App",
  "App approved successfully": "App approved successfully",
  "Your app has been submitted sucessfully.": "Your app has been submitted sucessfully.",
  "Please define a name": "Please define a name",
  "Trashcan cleared!": "Trashcan cleared!",
  "Type the domain to move all users with @domain.com to the org with that domain.": "Type the domain to move all users with @domain.com to the org with that domain.",
  "Define a name for the tab": "Define a name for the tab",
  "Are you sure you want to delete this tab?": "Are you sure you want to delete this tab?",
  "Define the anchor id of the link.": "Define the anchor id of the link.",
  "is not a valid email": "is not a valid email",
  "Are you sure that you want to remove this space from the organization?": "Are you sure that you want to remove this space from the organization?",
  "Space has been removed from organization": "Space has been removed from organization",
  "Space added successfully": "Space added successfully",
  "Organization created successfully": "Organization created successfully",
  "Are you sure you want to remove this language?": "Are you sure you want to remove this language?",
  "Are you sure you want to unsubscribe and remove all collaborators?": "Are you sure you want to unsubscribe and remove all collaborators?",
  "Please save the schema of this component first.": "Please save the schema of this component first.",
  "Character limit reached": "Character limit reached",
  "characters remaining": "characters remaining",
  "characters over limit": "characters over limit"
}
