export default {
  "Dashboard": "Dashboard",
  "Back to spaces": "Voltar para os espaços",
  "Content": "Conteúdo",
  "Commerce": "Commerce",
  "Assets": "Assets",
  "Datasources": "Datasources",
  "Activities": "Atividades",
  "Tasks": "Tarefas",
  "Components": "Componentes",
  "Apps": "Aplicações",
  "My account": "Minha conta",
  "Settings": "Configurações",
  "Subscription": "Inscrição",
  "Plugins": "Plugins",
  "Logout": "Sair",
  "Report a problem": "Reporte um problema",
  "Create new space": "Criar espaço",
  "Search spaces...": "Pesquisar espaços ...",
  "My organization": "Minha organização",
  "Subscribe": "Inscreva-se",
  "To": "Para",
  "From": "De",
  "Apply filter": "Aplique filter",
  "Filter": "Filtro",
  "Unknown user": "Usuário desconhecido",
  "Author": "Autor",
  "Action": "Ação",
  "Date": "Data",
  "Back": "Voltar",
  "Activity Details": "Detalhes ativos",
  "Open": "Abrir",
  "Restore this Story": "Restaurar esta história",
  "Categories": "Categorias",
  "Story": "História",
  "The item has been restored!": "O item foi restaurado!",
  "All": "Todos(as)",
  "My Apps": "Minhas Aplicações",
  "Search for apps, discover new field types and add functionalities to your Storyblok project.": "Pesquise aplicativos, descubra novos tipos de campos e adicione funcionalidades ao seu projeto Storyblok.",
  "My apps": "Meus aplicativos",
  "Create new app": "Criar novo aplicativo",
  "Installed": "Instalado",
  "App Directory": "Diretório de Aplicativos",
  "There are no apps in this category.": "Não há aplicativos neste diretório",
  "Install": "Instalar",
  "Choose the space to install this app": "Escolha o espaço para instalar este aplicativo",
  "Can not move asset folder into folder without permissions.": "Não foi possível mover a pasta em uma pasta sem permissões.",
  "Can not move asset into folder without permissions.": "Não foi possível mover o asset para uma pasta sem permissões.",
  "Can not move asset away from folder without permissions.": "Não é possível mover o ativo para longe da pasta sem permissões.",
  "Define the new name of the folder.": "Defina um novo nome para a pasta.",
  "Trashbin": "Lixeira",
  "Are you sure that you want to delete this folder?": "Você tem certeza em apagar esta pasta?",
  "Add": "Adicionar",
  "Asset folders are not included in the free plan but you can try them in the": " As pastas de assets não estão incluídas no plano gratuito, mas você pode experimentá-las no",
  "New folder will be created in": "Nova pasta criada em",
  "trial period": "período de teste",
  "Can not create asset folder without permission for parent.": "Não é possível criar a pasta do asset sem permissão para pai.",
  "Original": "Original",
  "Done": "Finalizado",
  "Cancel": "Cancelar",
  "Insert": "Inserir",
  "Add Asset(s)": "Adicionar Asset(s)",
  "Close": "Fechar",
  "items": "Itens",
  "Delete": "Deletar",
  "Move to folder": "Mover para pasta",
  "Replace": "Trocar",
  "Unselect all": "Desmarque todos",
  "Restore": "Restaurar",
  "Tiles": "Tiles",
  "List": "Lista",
  "No assets found": "Nenhum assets encontrados",
  "Sort": "Ordenar",
  "Default": "Padrão",
  "View": "Visualizar",
  "Creation date (asc)": "Data de criação (asc)",
  "Filename (asc)": "Nome do arquivo (asc)",
  "Creation date (desc)": "Data de criação (desc)",
  "Filename (desc)": "Nome do arquivo (desc)",
  "Last updated date (asc)": "Data de última atualização (asc)",
  "Last updated date (desc)": "Data de última atualização (desc)",
  "You are not allowed to insert this filetype here.": "Você não tem permissão para inserir esse tipo de arquivo aqui.",
  "This key is already defined": "Esta chave já foi definida",
  "Key is in invalid format": "Chave está num formato inválido",
  "Something went wrong uploading some items": "Ocorreu um erro ao enviar alguns itens",
  "Please choose a folder in the left sidebar": "Por favor, escolha uma pasta na barra lateral esquerda",
  "Define the new name of": "Defina um novo nome de",
  "Something went wrong renaming the attribute": "Ocorreu um erro ao renomear o atributo",
  "Be aware! Changing the name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Atenção! A alteração de nome pode levar alguns minutos para atualizar todos os itens de conteúdo. Verifique se os editores salvaram o trabalho atual e saiam do editor.",
  "Define the new name of the component group.": "Defina o novo nome do grupo de componentes.",
  "Save": "Salvar",
  "Are you sure that you want to delete this component group?": "Tem certeza de que deseja excluir este grupo de componentes?",
  "Copy": "Copiar",
  "New": "Novo",
  "Move to group": "Mover para grupo",
  "Please choose a component group in the left sidebar": "Escolha um grupo de componentes na barra lateral esquerda",
  "Paste": "Colar",
  "Add block": "Adicionar bloco",
  "Creation of a component failed. Maybe it already exists.": "Falha na criação de um componente. Talvez ele já exista.",
  "Are you sure you want to DELETE this component(s)?": "Tem certeza de que deseja EXCLUIR este(s) componente(s)?",
  "new": "novo",
  "Type to search or to create a": "Digite para pesquisar ou para criar a",
  "Create new": "Criar novo",
  "block": "bloco",
  "New Component": "Novo Componente",
  "Updated": "Atualizado",
  "Name": "Nome",
  "Shortcuts: Esc, Control + S": "Teclas de atalho: Esc, Control + S",
  "Next": "Próximo",
  "Define a name": "Defina um nome",
  "Save schema": "Salvar schema",
  "Act as content type (eg. blog-post)": "Atuar como tipo de conteúdo (por exemplo, blog-post)",
  "Define": "Defina",
  "Nestable": "Nestable",
  "Technical name": "Nome técnico",
  "Edit field": "Editar campo",
  "Config": "Configurar",
  "Schema": "Schema",
  "Renaming": "Renomeando",
  "Change field name": "Mudar nome do campo",
  "Used in the json as component name": "Usado no json como um nome de componente",
  "Be aware! Changing the technical name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Atenção! A alteração do nome técnico pode levar alguns minutos para atualizar todos os itens de conteúdo. Verifique se os editores salvaram o trabalho atual e saiam do editor.",
  "Display name": "Mostrar nome",
  "Preview template": "Modelo de visualização",
  "Screenshot or icon": "Printe da tela ou ícone",
  "Used in the editor interface only": "Utilizado apenas na interface do editor",
  "of this setting": "desta configuração",
  "Read the documentation": "Leia a documentação",
  "Load versions": "Carregar versões",
  "Versions": "Versões",
  "has been added below": "foi adicionado abaixo",
  "Examples: news_items, body, columns, title, description or call_to_action_btn": "Exemplos: : news_items, body, columns, title, description or call_to_action_btn",
  "The component has been restored!": "O componente foi restaurado!",
  "Do you really want to leave without saving your changes?": "Deseja realmente sair sem salvar as alterações?",
  "Type": "Tipo",
  "Beta": "Beta",
  "Translatable": "Traduzível",
  "Allow empty paragraphs": "Permitir",
  "Linktype": "LinkType",
  "Rich-text as default": "Rich-text como padrão",
  "Custom type": "Tipo customizado",
  "Category": "Categoria",
  "Section items": "Itens de seção",
  "Product": "Produto",
  "Customize toolbar": "Toolbar customizado",
  "Toolbar items": "Itens da barra de ferramentas",
  "Source": "Fonte",
  "CSS class options (label/value)": "Opções de classe CSS (label/value)",
  "Datasource": "Datasource",
  "Stories": "Histórias",
  "Self": "Self",
  "Internal datasource": "Datasource interno",
  "Recommended to be checked, as UID is required for automatic link resolving.": "É recomendável verificar, pois o UID é necessário para a resolução automática de links.",
  "Use UID instead of ID": "Usar UID ao invés de ID",
  "In case you have a multi-language folder structure you can add the {0} placeholder and the path will be adapted dynamically. Examples: {0}/categories/, {0}/{1}/categories/": "Caso você tenha uma estrutura de pastas em vários idiomas, adicione o espaço reservado {0} e o caminho será adaptado dinamicamente. Exemplos: {0}/categories/, {0}/{1}/categories/",
  "External JSON": "JSON externo",
  "Path to folder of stories": "Caminho para as pastas das histórias",
  "Width": "Largura",
  "URL": "URL",
  "ratio": "proporção",
  "pixel": "pixel",
  "Allowed maximum": "Máximo permitido",
  "Options (name/value)": "Opções (name/value)",
  "Component(s)": "Componente(s)",
  "Group(s)": "Grupo(s)",
  "Required field(s) (comma separated)": "Campos obrigatório(s) (separado por vírgulas)",
  "Required": "Obrigatórios",
  "Default asset folder": "Pasta padrão para os assets",
  "Choose an asset folder where the assets should be assigned to.": "Escolha uma pasta de assets à qual os assets devem ser atribuídos.",
  "With {level} the path will be replaced dynamically using parts of the current slug. Examples: {0}/categories/, {0}/{1}/categories/": "Com {level}, o caminho será substituído dinamicamente usando partes do slu atual. Exemplos: {0}/categories/, {0}/{1}/categories/",
  "Restrict to folder": "Restringir à pasta",
  "Force folder restriction": "Forçar restrição da pasta",
  "Regex validation": "Validação Regex",
  "Exclude from export": "Exclua da exportação",
  "export app": "exporte o aplicativo",
  "To use with the": "Para com o(a)",
  "Default value": "Valor padão",
  "Can be updated by preview window": "Pode ser atualizado pela janela de visualização",
  "Loading...": "Carregando...",
  "Item": "Item",
  "Allow only specific components to be inserted": "Permitir que apenas componentes específicos sejam inseridos",
  "Restrict to content types": "Restringir a tipos de conteúdos",
  "Keep original size": "Manter tamanho original",
  "Force crop": "Forçar corte",
  "Prepend https to url": "Anexar HTTPS ao URL",
  "Height": "Altura",
  "Maximum characters": "Caracteres máximos",
  "Disable time selection": "Disabilitar tempo de seleção",
  "Description": "Descrição",
  "dimensions app": "dimensões do aplicativo",
  "Force overwrite by merge action": "Forçar substituição por ação de mesclagem",
  "Id/Slug": "ID/Slug",
  "Enable RTL (Right to left)": "Habilitar RTL (Direita para Esquerda)",
  "Autosave": "Salvar automaticamente",
  "API Url": "API URL",
  "Export": "Exportar",
  "Import/Export": "Importar/Exportar",
  "Dimensions": "Dimensões",
  "Add Dimension": "Adicionar dimensão",
  "Import": "Importar",
  "A datasource in Storyblok is a collection of key-value pairs.": "Um datasource na Storyblok é uma coleção de pares chave-valor",
  "Datasources can be used in a schema definition of a component for single or multiple choice options. You can also access": "Datasources podem ser usadas em uma definição de esquema de um componente para opções de escolha única ou múltipla. Você também pode acessar",
  "datasource entries from the API": "Entradas de datasources vindos de API",
  "to use them for labels, categories or similar.": "para usá-los em labels, categorias ou similares.",
  "Unsaved Changes": "Mudanças não salvas",
  "Datasource entries": "Entradas dos Datasources",
  "Datasources are not included in the free plan": "Datasources não são incluídos no plano gratuito",
  "but you can try them in the": "mas você pode experimentá-los no",
  "Saved": "Salvo",
  "Select all": "Selecione todos",
  "The options could not be loaded.": "As opções não podem ser carregadas",
  "New Datasource": "Novo Datasource",
  "The following component(s) can not be pasted here": "O(s) seguinte(s) componente(s) não pode(m) ser copiado(s) aqui",
  "Please save first to continue editing child components.": "Por favor, salve primeiro para continuar editando os componentes filhos.",
  "Enabled?": "Habilitado?",
  "Asset manager": "Gerenciador de assets",
  "Loading": "Carregando",
  "Upload new": "Upload novo",
  "Your file exceeds the maximum filesize limit of": "Seu arquivo excede o tamanho limite",
  "Please reduce the size of your file.": "Por favor, reduza o tamanho de seu arquivo",
  "Alt text": "Texto alternativo",
  "Base64": "Base64",
  "Original Size": "Tamanho original",
  "Image loading failed": "O carregamento da imagem falhou",
  "Quote": "Quota",
  "Code Block": "Bloco de código",
  "Ordered List": "Lista ordenado",
  "Headline 2": "Cabeçalho 2",
  "Headline 4": "Cabeçalho 4",
  "Headline 3": "Cabeçalho 3",
  "Headline 5": "Cabeçalho 5",
  "Paragraph": "Parágrafo",
  "Help": "Ajuda",
  "Internal link": "Link interno",
  "Url": "Url",
  "Show only selected": "Exibir apenas os selecionados",
  "more items found": "mais itens encontrados",
  "Invoices": "Faturas",
  "Tip: Use Ctrl + S to save": "Dica: Use Ctrl + S para salvar",
  "Input": "Entrada",
  "Publish": "Publicar",
  "You are not allowed to edit this plugin but can see the code at Settings/Details.": "Você não tem permissão para editar este plug-in, mas pode ver o código em Configurações/Detalhes.",
  "Field type preview": "Visualização do tipo de campo",
  "Options (key/value)": "Opções (chave/valor)",
  "Space Id": "ID do espaço",
  "Enable local dev mode": "Habilitar modo de desenvolvimento local",
  "Settings/Details": "Configurações/Detalhes",
  "Output": "Saída",
  "for approval to make it available for all users.": "para aprovação para disponibilizá-lo para todos os usuários.",
  "Submit the plugin": "Submeter o plugin",
  "Code": "Código",
  "You can copy the code of this plugin to create your own plugin.": "Você pode copiar o código deste plugin para criar o seu próprio.",
  "Assigned spaces": "Espaços assinalados",
  "If you assign this plugin to a space other developers can also use it in the schema definition. Without assigning it only you can add the plugin to the schemas.": "Se você atribuir esse plug-in a um espaço, outros desenvolvedores também poderão usá-lo na definição de esquema. Sem a atribuição, você pode adicionar o plug-in aos esquemas.",
  "Attention: All spaces using this plugin will not be able to use it any more if you click delete.": "Atenção: Todos os espaços que usam este plug-in não poderão mais usá-lo se você clicar em excluir.",
  "Documentation": "Documentação",
  "Danger zone": "Zona de perigo",
  "What is a field type plugin?": "O que é um plugin de tipo de campo?",
  "A field type plugin extends the Storyblok editor with your own custom field types.": "Um plug-in de tipo de campo estende o editor da Storyblok com seus próprios tipos de campos personalizados.",
  "It is basically a": "É basicamente uma",
  "The properties that are passed to the field type are:": "As propriedades que são passadas para o tipo de campo são:",
  "component extended with a few helpers in the window.Storyblok.plugin mixin.": "componente estendido com alguns helper no mixin window.Storyblok.plugin.",
  "Examples for field types are colorpickers, WYSYWYG editors or meta tags.": "Exemplos de tipos de campo são paletas de cores, editores WYSYWYG ou metatags.",
  "Uid of the parent component": "UID do componente pai",
  "Options parsed from the schema options array": "Opções transformadas num array de opções de esquema",
  "Schema options object": "Objeto de opções do esquema",
  "Current value of the fieldtype": "Valor atual do tipo de campo",
  "Story id of the current story": "Id da história atual",
  "Space id of the current space": "ID do espaço atual",
  "Api function to call the delivery api": "Função da API para chamar a delivery api",
  "Methods": "Métodos",
  "Draft token of the current space": "Token de rascunho do espaço atual",
  "How to call the Storyblok api?": "Como chamar a API da Storyblok?",
  "Should be used to define the initial data of the plugin.": "Deve ser usado para definir os dados iniciais do plug-in.",
  "Should be used to initialize the plugin. Examples: Load data from Storyblok or external sources, Load and initialize a WYSIWYG editor.": "Deve ser usado para inicializar o plugin. Exemplos: carregar dados do Storyblok ou de fontes externas, carregar e inicializar um editor WYSIWYG.",
  "To pass options that are configurable in the schema definition define the option keys in the \"Input\" box. The values will be available in the this.options object.": "Para passar opções configuráveis ​​na definição de esquema, defina as teclas de opção na caixa \"Entrada\". Os valores estarão disponíveis no objeto this.options.",
  "How to pass options?": "Como passar opções?",
  "In fieldtypes you can use this.api to get access to the Storyblok delivery api. You can use it for example to build a selectbox of stories.": "Nos tipos de campo, você pode usar this.api para obter acesso à API de entrega do Storyblok. Você pode usá-lo, por exemplo, para criar uma caixa de seleção de histórias.",
  "Folder/Content-item permissions": "Permissões de pasta/item de conteúdo",
  "Item saved successfully!": "Itens salvos com sucesso!",
  "Source of sync": "Fonte da sincronização",
  "Preview": "Pré-visualização",
  "Preview url": "Pré-visualização da URL",
  "View on Jsfiddle": "Visualizar no Jsfiddle",
  "Download": "Baixar",
  "Admin": "Administrativo",
  "Permissions": "Permissões",
  "Editor": "Editor",
  "Advanced Rights": "Direitos Avançados",
  "Allow saving content": "Permitir salvar conteúdo",
  "Allow publishing content": "Permitir publicação de conteúdo",
  "Allow saving datasources": "Permitir datasources salvos",
  "Allow managing subscription": "Permitir gerenciamento de assinatura ",
  "Allow access to ecommerce app": "Permitir acesso ao app de ecommerce",
  "Deny access to visual composer": "Permitir acesso para o compositor visual",
  "Field Permissions": "Permissões de campo",
  "General": "Geral",
  "Allowed path": "Caminho permitido",
  "Your crawl URL": "A sua URL de rastreamento",
  "Crawler": "Crawler",
  "Enabled": "Habilitado",
  "Index": "Índice",
  "Crawl now": "Rastrear agora",
  "Information needed to access the search endpoint or to configure the search client.": "Informações necessárias para acessar o endpoint de pesquisa ou para configurar o cliente de pesquisa.",
  "Search Setup Guide": "Guia de configuração de pesquisa",
  "Your tenant ID": "Seu tenant ID",
  "See": "Veja",
  "Documents in index": "Documentos no índice",
  "Crawl requested at": "Rastreamento solicitado em",
  "Tenant ID": "Tenant ID",
  "Documents": "Documentos",
  "Clear index": "Limpar índices",
  "Last crawled at": "Último rastreamento às",
  "Crawl has been initiated": "O rastreamento foi inicializado",
  "In the first 14 days you can try out all Premium plan features!": "Nos primeiros 14 dias, você pode experimentar todos os recursos do plano Premium!",
  "Index deletion has been initiated": "A exclusão de índices foi iniciado",
  "API-Keys": "Chave de APIs",
  "We would love to hear your thoughts about Storyblok on": "Gostaríamos muito de ouvir seus pensamentos sobre a Storyblok em",
  "Renderer": "Renderer",
  "Backup": "Backup",
  "Users": "Usuários",
  "Workflow": "Fluxo de trabalho",
  "Search": "Pesquisar",
  "Languages": "Linguagens",
  "This is the page that the frontend-editor opens.": "Esta é a página que o editor de front-end abre.",
  "Location (default environment)": "Localização (ambiente padrão)",
  "Insert your domain/location including the protocol. Example: http://www.example.com/": "Insira seu domínio/endereço incluindo o protocolo. Exemplo: http://www.example.com/",
  "Provide this ID in your support tickets": "Forneça esse ID em seus tíquetes de suporte",
  "Your space ID": "Seu ID do espaço",
  "Preview urls": "URLs de visualização",
  "Define multiple domains/locations to quickly switch the preview urls in the story-editor.": "Defina vários domínios/endereços para alternar rapidamente as URLs de visualização no editor de histórias.",
  "Add preview url": "Adicionar URL de visualização",
  "Webhooks": "Webhooks",
  "Story published &amp; unpublished": "História publicada &amp; não publicada",
  "Story saved": "História salva",
  "Branch deployed": "Branch deployed",
  "Release merged": "Release merged",
  "Slack integration": "Integração com o Slack",
  "Loading... You will be redirect to Slack in a few seconds!": "Aguarde... Você será redirecionado para o Slack em poucos segundos!",
  "Get notified on your Slack channel if a new Story has been published!": "Seja notificado no seu canal do Slack se uma nova história for publicada!",
  "With this integration you can choose a Slack channel where Storyblok posts messages whenever a user publishes new content.": "Com essa integração, você pode escolher um canal do Slack onde a Storyblok publica mensagens sempre que um usuário publica um novo conteúdo.",
  "Disconnect": "Disconectado",
  "Cloud name": "Nome do Cloud",
  "Cloudinary integration": "Integração com o Cloudinary",
  "Api Key": "Chave da API",
  "Branches": "Branches",
  "Default content type": "Tipo de conteúdo padrão",
  "Content types": "Tipo de conteúdo",
  "Name of the branch": "Nome da branch",
  "Branches are not included in the free plan": "Branchs não são incluídos no plano gratuito",
  "Duplication": "Duplicação",
  "This is useful if you want to offer your space for other users as a boilerplate or theme.": "Isso é útil se você deseja oferecer seu espaço para outros usuários como um padrão ou tema.",
  "ATTENTION! Only check this checkbox if you are sure that you want all data of this space available for duplication.": "ATENÇÃO! Marque esta caixa de seleção apenas se tiver certeza de que deseja que todos os dados desse espaço estejam disponíveis para duplicação.",
  "Make this space duplicatable by all users": "Tornar esse espaço duplicável por todos os usuários",
  "Content ownership": "Proprietário do conteúdo",
  "Parent ID": "ID do pai",
  "Parent": "Pai",
  "Image service": "Serviço de imagem",
  "Content ownership client endpoint": "Endpoint do cliente proprietário do conteúdo",
  "List of paths to invalidate": "Lista de caminhos para invalidar",
  "Delete this space": "Exclua este espaço",
  "Invalidate": "Invalidado",
  "Workflow webhooks": "Fluxo de trabalho dos webhooks",
  "Owner": "Proprietário",
  "Workflow changed": "Fluxo de trabalho mudado",
  "Transfer ownership": "Transferir a propriedade",
  "Transfer": "Transferir",
  "Attention! Transfering the ownership will remove all your rights to this space.": "Atenção! A transferência da propriedade removerá todos os seus direitos sobre este espaço.",
  "The owner needs to add you as a collaborator if you want to have access again.": "O proprietário precisa adicioná-lo como colaborador se você deseja ter acesso novamente.",
  "Collaborators": "Colaboradores",
  "Collaborator": "Colaborador",
  "No user found with this email or username.": "Nenhum usuário encontrado com este email ou nome de usuário.",
  "Name of the role": "Nome da regra",
  "Role": "Regra",
  "Add a new user to your org": "Adicione um novo usuário à sua organização",
  "Advanced rights and roles are not included in the free and basic plan": "Acessos e funções avançados não estão incluídos no plano gratuito e básico",
  "Use your Amazon S3 bucket to create backups.": "Use seu bucket do Amazon S3 para criar backups.",
  "Backup now": "Faça backup agora",
  "Backups content (stories) and compontents": "Conteúdo de backup (histórias) e componentes",
  "Define your S3-Bucket and AWS-ARN to enable backups.": "Defina seu S3-Bucket e AWS-ARN para ativar os backups.",
  "Daily backups": "Backups diários",
  "Define the name of the S3-bucket where you want to store your backups.": "Defina o nome do S3-bucket em que deseja armazenar seus backups.",
  "S3-bucket": "S3-bucket",
  "Activate automatic daily backups": "Ativar backups diários automáticos",
  "1. Read the": "1. Leia a",
  "AWS Policy ARN": "ARN da política da AWS",
  "Show setup instructions": "Mostrar instruções de configuração",
  "tutorial on how to setup an Amazon IAM role": "tutorial sobre como configurar uma função do Amazon IAM",
  "2. Create an Amazon IAM role with following access policy document:": "2. Crie uma função do Amazon IAM com o seguinte documento de política de acesso:",
  "if not done yet.": "se ainda não estiver pronto.",
  "The role should have the permission to access and create files on the S3 bucket you defined. You can for example use the following permission policy replacing YOUR_BUCKET with your bucket name:": "A função deve ter permissão para acessar e criar arquivos no bucket S3 que você definiu. Você pode, por exemplo, usar a seguinte política de permissão substituindo YOUR_BUCKET pelo nome do seu bucket:",
  "Restore spaces from backups on your Amazon S3 bucket.": "Restaure os espaços dos backups no seu bucket do Amazon S3.",
  "Backup file": "Arquivo de backup",
  "Show latest backups": "Mostrar backups mais recentes",
  "Latest five backups": "Últimos cinco backups",
  "Restore now": "Restaurar agora",
  "The settings below only apply if you are using": "As configurações abaixo se aplicam apenas se você estiver usando",
  "Attention! \"Restore now\" deletes old data and restores content (stories) and compontents from the backup file.": "Atenção! \"Restaurar agora\" exclui dados antigos e restaura o conteúdo (histórias) e os componentes do arquivo de backup.",
  "Rendering service": "Renderizar serviço",
  "Your domain": "Seu domínio",
  "To connect your domain to Storyblok you need to create a CNAME Record pointing to eu-domain.storyblok.com": "Para conectar seu domínio à Storyblok, você precisa criar um registro CNAME apontando para eu-domínio.storyblok.com",
  "Routes": "Rotas",
  "Add Route": "Adicionar rota",
  "Please read the": "Por favor, leia o",
  "Add custom routes to define different page templates.": "Adicione rotas personalizadas para definir diferentes modelos de página.",
  "documentation about internationalization": "documentação sobre internacionalização",
  "before configuring languages.": "antes de configurar os idiomas.",
  "Add languages to activate field level translations.": "Adicione idiomas para ativar as traduções a nível de campo.",
  "Add Language": "Adicionar linguagem",
  "Label": "Label",
  "The invalidation process has been initiated": "O processo de invalidação foi iniciado",
  "The backup has been initiated": "O backup foi iniciado",
  "Are you sure you want to delete your current content and overwrite it with this backup?": "Tem certeza de que deseja excluir o conteúdo atual e substituí-lo por esse backup?",
  "The restore process has been initiated": "O processo de restauração foi iniciado",
  "Transfering was not successfull. Make sure that the new owner exists.": "A transferência não foi bem sucedida. Verifique se o novo proprietário existe.",
  "The collaborator has been added": "O colaborador foi adicionado",
  "Please insert a email": "Por favor, insira um email",
  "Branches sorted successfully!": "Branchs classificados com sucesso!",
  "Create or join a space": "Criar ou ingressar em um espaço",
  "Create a new space": "Criar um novo espaço",
  "Play with a demo": "Acesse com uma demonstração",
  "Duplicate a space": "Duplicar um espaço",
  "Join a space": "Junte-se a um espaço",
  "Create space": "Criar espaço",
  "Headless (API/SDKs)": "Headless (API/SDKs)",
  "what is that?": "o que é isso?",
  "Duplicate space": "Espaço duplicado",
  "Choose the space for the duplication": "Escolha o espaço para a duplicação",
  "You do not have created any spaces yet.": "Você ainda não criou nenhum espaço.",
  "You can test the editing interface and our visual composer without to write any code on your own.": "Você pode testar a interface de edição e nosso compositor visual sem escrever nenhum código por conta própria.",
  "Create Demo": "Criar demonstração",
  "Insert the email of your space admin to let them add you as a collaborator of the space.": "Insira o email do administrador do espaço para permitir que você o adicione como colaborador do espaço.",
  "Request access": "Solicitar acesso",
  "Email address of space admin": "Endereço de email do administrador do espaço",
  "Success! You will get notified once the admin added you as a collaborator.": "Sucesso! Você será notificado assim que o administrador adicionar você como colaborador.",
  "Available Billing Information": "Informações de cobrança disponíveis",
  "No spaces with billing information available": "Não há espaços com informações de cobrança disponíveis",
  "Spaces": "Espaços",
  "Show More": "Visualizar mais",
  "Apply": "Aplicação",
  "Show": "Visualizar",
  "Billing Information of Space": "Informações de faturamento do espaço",
  "The information below will be applied to the fields of your current subscription process. You will be able to adopt them after applying them.": "As informações abaixo serão aplicadas aos campos do seu processo de assinatura atual. Você poderá adotá-los após aplicá-los.",
  "Company": "Companhia",
  "Country": "País",
  "Street / City / ZIP": "Endereço / Cidade / Código Postal",
  "Email": "Email",
  "Add or change preview urls": "Adicione ou mude as URLs de visualização",
  "Your server address": "O endereço do seu server",
  "1. Download a preconfigured project": "1. Baixe seu projeto pré-configurado",
  "Preferred by our users": "Preferido por nossos usuários",
  "The downloaded package comes preconfigured with your api token": "O pacote baixado vem pré-configurado com seu token da API",
  "Tutorial": "Tutorial",
  "Other technologies": "Outras tecnologias",
  "2. Start your server": "2. Inicie seu servidor",
  "Start the server of the downloaded package and insert your server url here:": "Inicie o servidor do pacote baixado e insira o URL do servidor aqui:",
  "Go": "Abrir",
  "FAQ": "FAQ",
  "Can I build a full blown website with Storyblok?": "Posso criar um site completo com o Storyblok?",
  "Can I create a blog with Storyblok?": "Eu posso criar um blog com a Storyblok?",
  "How does Storyblok work?": "Como a Storyblok funciona?",
  "What is the Storyblok bridge?": "O que é a Storyblok Brigde?",
  "Allow deploying content": "Permitir a implantação de conteúdo",
  "General permissions": "Permissões gerais",
  "Allow unpublishing content": "Permitir conteúdo não publicado",
  "Allow deleting content": "Permitir exclusão de conteúdo",
  "Allow editing datasource keys & values": "Permitir a edição de chaves e valores dos datasources",
  "Allow editing datasource values": "Permitir a edição de valores de datasources",
  "Allow access to the tasks app": "Permitir acesso ao aplicativo de tarefas",
  "Deny moving a story": "Negar move uma história",
  "Deny changing alternates group": "Negar alteração de grupo alternativo",
  "Add languages the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Adicione idiomas aos quais o usuário deve ter acesso (atua como lista de permissões). Se nenhum item for selecionado, o usuário terá direitos para editar todo o conteúdo.",
  "Deny changing the slug of a story": "Negar alterar o slug de uma história",
  "Add folders or content items the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Adicione pastas ou itens de conteúdo aos quais o usuário deve ter acesso (atua como lista de permissões). Se nenhum item for selecionado, o usuário terá direitos para editar todo o conteúdo.",
  "Component field permissions": "Permissões de campo do componente",
  "Datasource permissions": "Permissões aos datasources",
  "Add component fields here to hide them in the interface.": "Adicione campos de componentes aqui para ocultá-los na interface.",
  "Add datasources the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all datasources.": "Adicione datasources às quais o usuário deve ter acesso (atua como lista de permissões). Se nenhum item for selecionado, o usuário terá direitos para editar todas os datasources.",
  "Asset Folder Permissions": "Permissões de pasta de assets",
  "Add asset folders to restrict editing and upload access.": "Adicione pastas de assets para restringir o acesso de edição e upload.",
  "Start by selecting a space in the sidebar or create a new space.": "Comece selecionando um espaço na barra lateral ou crie um novo espaço.",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Parece que você ainda não tem acesso a nenhum espaço. Entre em contato com o administrador da sua organização para ser adicionado como colaborador.",
  "Welcome!": "Bem vindo!",
  "Traffic": "Tráfego",
  "Learn more about": "Leia mais sobre",
  "Api requests": "Pedidos de API",
  "Active Plan": "Plano ativo",
  "Usage": "Uso",
  "Content activities": "Atividades de conteúdo",
  "No billing": "Sem cobrança",
  "Change": "Mudar",
  "Billed": "Faturada",
  "No recent changes": "Nenhuma alteração recente",
  "Choose your plan": "Escolha seu plano",
  "Recent changes": "Mudanças recentes",
  "Custom": "Customizado",
  "Compare": "Comparar",
  "user": "Usuário",
  "Got a custom plan or coupon code?": "Tem um plano personalizado ou código de cupom?",
  "Custom plan": "Plano customizado",
  "Entered plan ids will be validated after pressing subscribe.": "Os IDs de plano inseridos serão validados após finalizar a assinatura.",
  "Coupon code": "Código do cupom",
  "Entered coupon codes will be validated and applied after pressing subscribe.": "Os códigos de cupom inseridos serão validados e aplicados depois de finalizar a inscrição.",
  "Select seats": "Selecionar assentos",
  "Confirm subscription": "Confirmar inscrição",
  "Min": "Mínimo",
  "Max": "Máximo",
  "By clicking the button below the new subscription will start.": "Ao clicar no botão abaixo, a nova assinatura será iniciada.",
  "Decide payment interval": "Decidir intervalo de pagamento",
  "Change subscription": "Mudar inscrição",
  "Monthly": "Mensalmente",
  "Annually": "Anualmente",
  "Define billing information": "Definir informação de cobrança",
  "Email address": "Endereço de email",
  "VAT-Number": "Número de VAT",
  "Reuse from another space": "Reutilizar de outro espaço",
  "Ordernumber": "Número do pedido",
  "Street": "Rua",
  "City": "Cidade",
  "Credit or debit card": "Cartão de crédito ou débito",
  "ZIP": "Código Postal",
  "Enter payment information": "Entre com sua informação de pagamento",
  "Update payment information": "Atualizar informações de pagamento",
  "Update Billing information": "Atualizar informações de cobrança",
  "Update billing information": "Atualizar informações de cobrança",
  "Information: Our payment provider validates card information when it is saved. As a result of this process, you may see a temporary authorization for $1 on your statement.": "Informações: nosso provedor de pagamentos valida as informações do cartão quando são salvas. Como resultado desse processo, você poderá receber uma autorização temporária de R$ 1 no seu extrato.",
  "Please provide all billing informations marked as required (*)": "Forneça todas as informações de cobrança marcadas como necessárias (*)",
  "Your selected team sizes are not in the limits of your selected feature set. You can select another feature set to continue.": "O tamanho da sua equipe selecionada não está dentro dos limites do seu conjunto de recursos. Você pode selecionar outro conjunto de recursos para continuar.",
  "View invoices": "Visualizar faturas",
  "Summary": "Sumário",
  "Please provide a credit or debit card": "Forneça um cartão de crédito ou débito",
  "If your entered plan is not correct you will still be able to try it again.": "Se o seu plano inserido não estiver correto, você ainda poderá tentar novamente.",
  "You have entered a custom plan with a special offering and pricing": "Você inseriu um plano personalizado com uma oferta e preços especiais",
  "users": "usuários",
  "VAT reverse charge applies.": "Aplica-se a cobrança reversa do VAT.",
  "VAT": "VAT",
  "Total": "Total",
  "The benefits of the coupon code will be applied if available": "Os benefícios do código do cupom serão aplicados, se disponíveis",
  "Thanks! You are awesome!": "Obrigado! Você é demais!",
  "We would love to hear what you think about Storyblok.": "Gostaríamos muito de ouvir o que você pensa sobre a Storyblok.",
  "Chat with us or": "Converse conosco ou",
  "your feedback.": "seu feedback.",
  "Tweet": "Tweet",
  "Star": "Estrela",
  "Share": "Compartilhar",
  "Public access tokens are only for accessing the published version while preview tokens are for accessing the draft version also. Both are read-only tokens.": "Os tokens de acesso público são apenas para acessar a versão publicada, enquanto os tokens de visualização também são para acessar a versão de rascunho. Ambos são tokens de somente leitura.",
  "Access level": "Nível de acesso",
  "Public": "Público",
  "See API-Documentation": "Veja a documentação da API",
  "Theme": "Tema",
  "Branch": "Branch",
  "Choose branch": "Escolher uma branch",
  "Create Token": "Criar token",
  "Color": "Cor",
  "Define as default stage for new content items": "Definir como estágio padrão para novos itens de conteúdo",
  "Publishing rights": "Direitos de publicação",
  "Stage transition rules": "Regras de transição de estágio",
  "Allow users to publish or schedule the content": "Permitir aos usuário(s) publicar ou agendar o conteúdo",
  "Specific stage(s)": "Estágios específico(s)",
  "Next available stages": "Próximos estágios disponíveis",
  "All stages": "Todos os estágios",
  "All users": "Todos os usuários",
  "User(s)/Role(s) who can change the stage": "Usuário(s)/Função (ões) que pode mudar de cenário",
  "to the next available stage": "para o próximo estágio disponível",
  "Specific user(s)/role(s)": "Usuário(s) específico(s)/função(ões)",
  "Role(s)": "Regra(s)",
  "User(s)": "Usuário(s)",
  "Workflow stages": "Etapas do fluxo de trabalho",
  "See workflow documentation": "Veja a documentação do fluxo de trabalho",
  "Create": "Criar",
  "Choose an approver": "Escolha um aprovador",
  "Workflow stages sorted successfully!": "Etapas do fluxo de trabalho classificadas com sucesso!",
  "Are you sure you want to delete this workflow stage?": "Tem certeza de que deseja excluir este estágio do fluxo de trabalho?",
  "Send for approval": "Enviar para aprovação",
  "Approval request has been sent successfully!": "A solicitação de aprovação foi enviada com sucesso!",
  "Content items": "Itens de conteúdo",
  "Entry": "Entrada",
  "Define schema": "Definir esquema",
  "Folder": "Pasta",
  "You have not defined any schema for this block yet.": "Você ainda não definiu nenhum esquema para este bloco.",
  "Define presets": "Definir predefinições",
  "Click \"Define schema\" to add the fields you need.": "Clique em \"Definir esquema\" para adicionar os campos necessários.",
  "No valid fields defined in this section yet.": "Ainda não existem campos válidos definidos nesta seção.",
  "is already part of another section": "já faz parte de outra seção",
  "Translate": "Traduzir",
  "Choose to delete the values or add the schema keys.": "Escolha excluir os valores ou adicionar as chaves do esquema.",
  "items out of schema": "itens fora do esquema",
  "We have found values which are not part of the schema.": "Encontramos valores que não fazem parte do esquema.",
  "No changes found": "Nenhuma mudança encontrada",
  "Changes": "Mudanças",
  "Remove all": "Remover todos",
  "Select releases to deploy": "Selecione releases para implantar",
  "What is getting deployed?": "O que está sendo implantado?",
  "All content that is currently on the source branch and the releases you select.": "Todo o conteúdo que está atualmente na branch de origem e os releases que você seleciona.",
  "No releases found on the source branch": "Nenhuma release encontrada na branch de origem",
  "A newer version of this content item has been found in the database.": "Uma versão mais recente deste item de conteúdo foi encontrada no banco de dados.",
  "Confirm": "Confirmar",
  "Choose the conflict solution": "Escolha a solução de conflito",
  "Copy over": "Copiar",
  "Opens newer version in a new window to let you copy over your changes.": "Abre uma versão mais recente em uma nova janela para permitir que você copie suas alterações.",
  "Overwrite": "Sobrescrever",
  "Slug": "Slug",
  "Overwrites newer version with your changes.": "Substitui a versão mais recente pelas suas alterações.",
  "Define as root for the folder": "Definir como raiz para a pasta",
  "Preset": "Predefinição",
  "Content type": "Tipo de conteúdo",
  "Confirm deletion": "Confirmar exclusão",
  "Are you sure that you want to delete this item(s)?": "Tem certeza de que deseja excluir este(s) item(ns)?",
  "Include associated alternates": "Incluir alternativas associadas",
  "Target-Folder": "Pasta de destino",
  "Is alternative version of the duplicate?": "É a versão alternativa da duplicata?",
  "Duplicate": "Duplicar",
  "Schedule": "Agendar",
  "duplicated": "duplicado",
  "You are not allowed to duplicate this story.": "Você não tem permissão para duplicar esta história.",
  "Open published": "Publicação aberta ",
  "Send approval": "Enviar aprovação",
  "Open draft": "Rascunho aberto",
  "Unpublish": "Cancelar publicação",
  "Draft json": "Rascunhar JSON",
  "Discard changes": "Descartar mudanças",
  "Start sync": "Começar sincronização",
  "Published json": "JSON publicado",
  "Status": "Status",
  "Tools": "Ferramentas",
  "Real path": "Caminho real",
  "Settings for the folder content": "Configurações para o conteúdo da pasta",
  "Disable visual composer": "Desativar compositor visual",
  "Clone to all": "Clone para todas",
  "Deny changing content type": "Negar alteração do tipo de conteúdo",
  "Merge to all": "Mesclar para todos",
  "Dimensions are only available if you are editing a content item in a subfolder.": "As dimensões estão disponíveis apenas se você estiver editando um item de conteúdo em uma subpasta.",
  "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).": "Crie uma estrutura de pastas onde a primeira pasta defina sua dimensão (Exemplo: de/home, en/home).",
  "Not created yet": "Ainda não criado",
  "Create clone": "Criar clone",
  "Merge": "Mesclar",
  "Something went wrong merging the alternate(s)": "Ocorreu um erro ao mesclar as alternativa(s)",
  "The alternate(s) have been created!": "A(s) alternativa(s) foram criadas!",
  "The alternate(s) have been merged!": "A(s) alternativa(s) foram mescladas!",
  "Add preset": "Adicionar predefinição",
  "Presets are blocks filled with the content you currently have in the selected block.": "Predefinições são blocos preenchidos com o conteúdo que você possui atualmente no bloco selecionado.",
  "Something went wrong creating the alternate(s)": "Ocorreu um erro ao criar o(s) alternativo(s)",
  "The saved presets are shown for all users at the selection of new blocks.": "As predefinições salvas são mostradas para todos os usuários na seleção de novos blocos.",
  "Existing presets": "Predefinições existentes",
  "As default": "Como padrão",
  "Release date (optional)": "Data de release (opcional)",
  "Branches to deploy": "Branchs para implantação",
  "When the release gets merged all content will be automatically deployed to the selected branches.": "Quando a versão for mesclada, todo o conteúdo será implantado automaticamente nas branchs selecionadas.",
  "Entry configuration": "Configuração de entrada",
  "Editmode": "Modo de edição",
  "Are you sure you want to delete this release?": "Tem certeza de que deseja excluir esta versão?",
  "Form only": "Somente formulário",
  "Visual": "Visual",
  "Tags": "Tags",
  "Sort by date": "Classificar por data",
  "First published date": "Primeira data de publicação",
  "Real Path": "Caminho",
  "Remove": "Remover",
  "Alternative versions": "Versões alternativas",
  "Search for the content group of this story.": "Pesquise o grupo de conteúdo desta história.",
  "Shortcut": "Atalho",
  "Pin as shortcut in the mini-browser": "Fixar como atalho no mini-navegador",
  "Current": "Atual",
  "New release": "Novo lançamento",
  "Skip this steps": "Pule estas etapas",
  "Move": "Mover",
  "Next steps": "Próxima etapas",
  "We have already done that for you. Open the entry \"Home\" below to play around.": "Já fizemos isso por você. Abra a entrada \"Página inicial\" abaixo para navegar.",
  "Create a demo page": "Crie uma página de demonstração",
  "Create a new folder": "Criar nova pasta",
  "Create your first folder": "Criar sua primeira entrada",
  "and define a new content type during the folder set-up.": "e defina um novo tipo de conteúdo durante a configuração da pasta.",
  "Create your first entry": "Criar sua primeira entrada",
  "Create entry": "Criar entrada",
  "and define its fields by building its schema so you can fill it with content.": "e defina seus campos criando seu esquema para que você possa preenchê-lo com conteúdo.",
  "Will be released at": "Será lançado em",
  "Show only items from this release": "Mostrar apenas itens desta versão",
  "Has been published at": "Foi publicado em",
  "Last deployment": "Última implantação",
  "This branch has never been deployed": "Esta branch nunca foi implantada",
  "Release now": "Liberar agora",
  "Open preview": "Abrir visualização",
  "Deploy from source": "Implantar do código",
  "You are seeing deleted items": "Você está vendo itens excluídos",
  "Name (desc)": "Nome (desc)",
  "Default sorting": "Classificação padrão",
  "Name (asc)": "Nome (asc)",
  "Slug (desc)": "Slug (desc)",
  "releases": "releases",
  "Slug (asc)": "Slug (asc)",
  "Created at": "Criado em",
  "Updated at": "Atualizado em",
  "Deleted at": "Deletado em",
  "Are you sure you want to unpublish this item(s)?": "Tem certeza de que deseja cancelar a publicação deste(s) item(ns)?",
  "The items have been updated!": "Os itens foram atualizados!",
  "Are you sure you want to publish this item(s)?": "Tem certeza de que deseja publicar este(s) item(ns)?",
  "Are you sure you want to restore this item(s)?": "Tem certeza de que deseja restaurar esses itens?",
  "Something went wrong restoring some items": "Ocorreu um erro ao restaurar alguns itens",
  "Something went wrong updating item(s)": "Ocorreu um erro ao atualizar item(s)",
  "No tools installed on this space": "Nenhuma ferramenta instalada neste espaço",
  "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.": "Itens excluídos não podem ser visualizados. Clique na caixa de seleção do item e restaure para visualizar.",
  "The content has been released!": "O conteúdo foi liberado!",
  "Do you really want to copy the content of the default language to the current and replace the existing field value?": "Deseja realmente copiar o conteúdo do idioma padrão para o atual e substituir o valor do campo existente?",
  "Default language": "Linguagem padrão",
  "Install from the app store": "Instalar a partir da loja de aplicativos",
  "Draft updated at": "Rascunho atualizado em",
  "Never": "Nunca",
  "Published at": "Publicado em",
  "Latest workflow changes": "Últimas alterações no fluxo de trabalho",
  "Last author": "Último autor",
  "None": "Nenhum",
  "Workflow stage": "Estágio fluxo de trabalho",
  "set by": "definido pela",
  "Assigned to": "Atribuído a",
  "Update": "Atualizar",
  "Comments": "Comentário",
  "Load older comments": "Carregar comentários antigos",
  "Edit": "Editar",
  "Workflow stage and assignments": "Estágio e atribuições do fluxo de trabalho",
  "Add a comment": "Adicionar um comentário",
  "Assign to": "Atribuir a",
  "Notify users via email": "Notificar usuários por email",
  "Submit": "Submeter",
  "Lambda Function": "Função Lambda",
  "Task type": "Tipo de tarefa",
  "Webhook": "Webhook",
  "The payload of the request contains the task and the space id.": "A carga útil da solicitação contém a tarefa e o ID do espaço.",
  "Lambda Function (coming soon)": "Função Lambda (em breve)",
  "Provide the endpoint where you want to send a POST request.": "Forneça o terminal para o qual deseja enviar uma solicitação POST.",
  "Protected variable": "Variável protegida",
  "Function code": "Código da função",
  "For example:": "Por exemplo",
  "Ok": "Ok",
  "Are you sure you want to delete this task?": "Tem certeza de que deseja excluir esta tarefa?",
  "Last execution": "Última execução",
  "Currently running": "Atualmente em execução",
  "Executed successfully!": "Executado com sucesso!",
  "Execute": "Executar",
  "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.": "Escolha XML para software de tradução como SDL Trados Studio ou JSON para software de tradução como LingoHub.",
  "Autosave enabled?": "Autosave habilitado?",
  "Empty": "Vazio",
  "Choose a compatible XML or JSON generated from the export.": "Escolha um XML ou JSON compatível gerado a partir da exportação.",
  "Desktop": "Desktop",
  "Tablet": "Tablet",
  "Tag": "Tag",
  "Mobile": "Mobile",
  "Select": "Selecionar",
  "Content type value": "Valor do tipo de conteúdo",
  "Component": "Componente",
  "Assigned to me only": "Atribuído apenas a mim",
  "In folder": "Na pasta",
  "element": "elemento",
  "Search in current folder only": "Pesquisar apenas na pasta atual",
  "No results found": "Nenhum resultado encontrado",
  "Current version": "Versão atual",
  "Start typing to search": "Comece a digitar para pesquisar",
  "Confirming invitation": "Confirmando convite",
  "Please wait a couple of seconds": "Aguarde alguns segundos",
  "Unknown author": "Autor desconhecido",
  "You are now a member of the organisation": "Agora você é membro da organização",
  "Go to spaces": "Ir para os espaços",
  "Invitation confirmed!": "Convite confirmado!",
  "Please login first and then click the invitation link again.": "Faça o login primeiro e clique no link do convite novamente.",
  "Go to login": "Ir para o login",
  "Login required.": "É necessário fazer login.",
  "Your invitation is not valid anymore.": "Seu convite não é mais válido.",
  "Please upgrade your Storyblok space. You have": "Atualize seu espaço Storyblok. Você tem",
  "Something went wrong.": "Algo deu errado.",
  "collaborator(s) and your": "colaborador(es) e seu",
  "Please contact your Storyblok space owner. You have": "Entre em contato com o proprietário do espaço Storyblok. Você tem",
  "is over.": "está acabado.",
  "Just a moment. A background task is still running.": "Um momento. Uma tarefa em segundo plano ainda está em execução.",
  "The Storyblok app has been updated!": "O app Storyblok foi atualizado!",
  "Please reload the window to get the newest version.": "Atualize a janela para obter a versão mais recente.",
  "Reload window": "Recarregar a página",
  "Manage": "Gerir",
  "Toggle assitance mode": "Alternar modo de assistência",
  "Assisted spaces": "Espaços assistidos",
  "Logging in": "Fazendo login",
  "Sales": "Vendas",
  "I have read and agree to the": "Eu li e concordo com o",
  "Logged in as": "Logado como",
  "Catalogue": "Catalogar",
  "Initiating space": "Iniciando espaço",
  "Configuration": "Configuração",
  "There was an error confirming your account. Please try again.": "Ocorreu um erro ao confirmar sua conta. Por favor, tente novamente.",
  "Resend confirmation": "Reenviar confirmação",
  "Confirmed successfully!": "Confirmação bem sucedida!",
  "You have unsaved changes on this content item. Do you want to discard your changes?": "Você possui alterações não salvas neste item de conteúdo. Deseja descartar suas alterações?",
  "No": "Não",
  "To continue confirm that you have read and agree to the Terms and Privacy Policy.": "Para continuar, confirme que você leu e concorda com os Termos e Política de Privacidade.",
  "Yes": "Sim",
  "Invitation sent!": "Convite enviado!",
  "Shortcuts: Esc for No, Enter for Yes": "Teclas de atalho: Esc para Não, Enter para Sim",
  "Usertype": "Tipo de usuário",
  "The user has been invited to your organisation and will be added once confirmed.": "O usuário foi convidado para sua organização e será adicionado uma vez confirmado.",
  "Normal": "Normal",
  "Member": "Membro",
  "Provide the 15 digit ID": "Forneça o ID de 15 dígitos",
  "Is sandbox user?": "É um usuário sandbox?",
  "Owner: Can manage users and define owners": "Proprietário: pode gerenciar usuários e definir proprietários",
  "Admin: Can manage users": "Admin: pode gerenciar usuários",
  "Member: Can not manage users": "Membro: não pode gerenciar usuários",
  "Firstname": "Primeiro nome",
  "Disable": "Desabilitar",
  "Lastname": "Último nome",
  "Are you sure you want to disable this user?": "Tem certeza de que deseja desativar este usuário?",
  "It seems you do not have any": "Parece que você não tem nenhum",
  "Enable": "Habilitar",
  "Type in all emails of the users you want to invite separated by a new line.": "Digite todos os emails dos usuários que você deseja convidar, separados por uma nova linha.",
  "Invite others": "Convide outros",
  "yet.": "ainda.",
  "Send": "Enviar",
  "Done!": "Feito!",
  "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).": "O seu convite foi enviado! Assim que os usuários se inscreverem, você poderá adicioná-los como colaboradores ao(s) seu(s) espaço(s).",
  "Please enter at least one email": "Insira ao menos um email",
  "Invite more people": "Convide mais pessoas",
  " is not a valid email": " não é um email válido",
  "from": "de",
  "Target": "Alvo",
  "Asset": "Asset",
  "Current window": "Janela atual",
  "Get started": "Iniciar",
  "New window": "Nova janela",
  "terms of use": "termos de uso",
  "Signup": "Inscrever-se",
  "By clicking \"Signup\" you accept the": "Ao clicar em \"Inscrição\", você aceita o",
  "Switch to login": "Mudar para login",
  "Forgot password?": "Esqueceu sua senha?",
  "Already have an account?": "Já possui uma conta?",
  "No account yet?": "Ainda não tem uma conta?",
  "Signup here": "Assine aqui",
  "Login": "Login",
  "Resend": "Reenviar",
  "confirmation email": "email de confirmação",
  "Send password reset link": "Enviar link de reset de senha",
  "Imprint": "Imprimir",
  "Privacy policy": "Política de privacidade",
  "Are you a developer?": "Você é um desenvolvedor",
  "Choose no if you want to join an existing project": "Escolha se deseja se juntar a um projeto existente",
  "No, I am not a dev": "Não, não sou um dev",
  "Yes, I am a dev": "Sim, eu sou um dev",
  "Choose your own adventure": "Escolha sua própria aventura",
  "Join an existing space": "Junte-se a um espaço existente",
  "What would you do like next?": "O que você gostaria de fazer a seguir?",
  "You are almost there": "Você está quase lá",
  "Success!": "Sucesso",
  "Insert the email of your space admin to let them add you as a collaborator of the space": "Insira o email do administrador do espaço para permitir que você o adicione como colaborador do espaço",
  "I received the email": "Eu recebi o email",
  "You will get notified per email once the admin added you as a collaborator. Click then on the button bellow to continue.": "Você será notificado por e-mail assim que o administrador o adicionar como colaborador. Clique no botão abaixo para continuar.",
  "It seems that the authentification code is wrong.": "Parece que o código de autenticação está errado.",
  "My Account": "Minha conta",
  "Please check the password confirmation.": "Verifique sua confirmação de senha.",
  "You are logged in via a third party authentication provider.": "Você está conectado através de um provedor de autenticação de terceiros.",
  "Profile picture": "Imagem de perfil",
  "Username": "Nome de usuário",
  "Your Storyblok ID for adding you as a collaborator to another project is": "Seu ID da Storyblok para adicionar você como colaborador a outro projeto é",
  "Recommended: 500px x 500px (JPG or PNG)": "Recomendado: 500px x 500px (JPG or PNG)",
  "Phone number": "Número de telefone",
  "Your timezone": "Seu timezone",
  "Your language": "Seu idioma",
  "Current password": "Senha atual",
  "Insert your current password if you changed your username, email, phone number, password or security settings": "Insira sua senha atual se você alterou seu nome de usuário, email, número de telefone, senha ou configurações de segurança",
  "New Password": "Nova senha",
  "Do you want to change your current password?": "Deseja alterar sua senha atual?",
  "Password confirmation": "Confirmação da senha",
  "Security Settings": "Configuração de segurança",
  "How do you want to login?": "Como você deseja acessar?",
  "Password only": "Apenas senhas",
  "Two factor authentication via SMS": "Autenticação de dois fatores via SMS",
  "Personal access tokens": "Tokens de acesso pessoal",
  "Two factor authentication via Email": "Autenticação de dois fatores via Email",
  "Storyblok Management API": "Storyblok Management API",
  "Please copy this api key now. It will be visible only once.": "Copie esta API token agora. Ela estará visível apenas uma vez.",
  "Tokens that have been generated to access the": "Tokens que foram gerados para acessar o",
  "Generate new Token": "Gerar novo token",
  "Personal access tokens work like ordinary OAuth access tokens.": "Os tokens de acesso pessoal funcionam como tokens de acesso comuns do OAuth.",
  "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.": "Eles podem ser usados ​​para se autenticar para ter acesso completo à API de gerenciamento programaticamente e NUNCA devem ser expostos.",
  "Privacy": "Privacidade",
  "Show username instead of email as collaborator": "Mostrar nome de usuário em vez de email como colaborador",
  "Privacy Setting": "Configuração de privacidade",
  "Download in German": "Baixar em Alemão",
  "Download in English": "Baixar em Inglês",
  "Data processing agreement": "Contrato de processamento de dados",
  "Read more about our": "Leia mais sobre nosso",
  "Account deletion": "Exclusão de conta",
  "privacy policy here": "política de privacidade aqui",
  "Yes, delete my account": "Sim, exclua minha conta",
  "Do you want to delete your account?": "Deseja excluir sua conta?",
  "Do you really want to delete your account? Type \"delete me\" and click confirm.": "Deseja realmente excluir sua conta? Digite \"delete me\" e clique em confirmar.",
  "User has been updated": "Usuário foi atualizado",
  "Not found": "Não encontrado",
  "Please insert the code we sent to ": "Insira o código que enviamos para",
  "Add user": "Adicionar usuário",
  "It seems that you do not have access to this page.": "Parece que você não tem acesso a esta página.",
  "Create a new organization": "Criar uma nova organização",
  "Organisation name": "Nome da organização",
  "Create org": "Criar organização",
  "SO Settings": "Configurações de SO",
  "Whitelabeling": "Whitelabeling",
  "Add SSO url": "Adicionar uma URL de SSO",
  "Url to the editor": "URL para o editor",
  "Provide the full url like": "Forneça A URL completa como",
  "Logo-Url": "Logo-URL",
  "Provide the full url to the logo like": "Forneça o URL completo para a logotipa, como",
  "Not defined": "Não definido",
  "Organization updated successfully": "Organização atualizada com sucesso",
  "Disabled": "Desabilitada",
  "Please set your password": "Defina sua senha",
  "Set password": "Definir senha",
  "Password has been set. You can now login.": "Senha definida. Você pode logar agora.",
  "Thank you": "Obrigado",
  "Please confirm your billing information": "Confirme sua informação de cobrança",
  "Login failed. The login token may expired. Please try again.": "Falha na autenticação. O token de login pode ter expirado. Por favor, tente novamente.",
  "Please enter all required information": "Entre com todas as informações necessárias",
  "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.": "Tentamos manter suas informações de faturamento atualizadas. Confirme se as informações abaixo estão corretas ou altere-as de acordo.",
  "One last thing before you can comment": "Uma última coisa antes que você possa comentar",
  "Profile picture (optional)": "Foto de perfil (opcional)",
  "Are you sure you want to delete this item?": "Tem certeza de que deseja excluir este item?",
  "Help other collaborators to identify you better by providing your name and a profile picture.": "Ajude outros colaboradores a identificá-lo melhor, fornecendo seu nome e uma foto do perfil.",
  "Are you sure you want to delete this item(s)?": "Tem certeza de que deseja excluir este(s) item(ns)?"
}