export default {
  "Dashboard": "Панель управления",
  "Back to spaces": "Вернуться к областям",
  "Content": "Содержание",
  "Commerce": "Commerce",
  "Assets": "Ресурсы",
  "Datasources": "Источники данных",
  "Activities": "Активность",
  "Tasks": "Задачи",
  "Components": "Компоненты",
  "Apps": "Приложения",
  "Settings": "Настройки",
  "Subscription": "Подписка",
  "Plugins": "Плагины",
  "Logout": "Выход",
  "Report a problem": "Сообщить о проблеме",
  "Create new space": "Создать новую область",
  "Search spaces...": "Поиск областей...",
  "My organization": "Моя организация",
  "Subscribe": "Оформить подписку",
  "To": "К",
  "From": "От",
  "Apply filter": "Применить фильтр",
  "Filter": "Фильтр",
  "Unknown user": "Неизвестный пользователь",
  "Author": "Автор",
  "Action": "Действие",
  "Date": "Дата",
  "Back": "Назад",
  "Activity Details": "Детали активности",
  "Open": "Открыто",
  "Restore this Story": "Восстановить эту историю",
  "Categories": "Категории",
  "Story": "История",
  "The item has been restored!": "Этот объект восстановлен",
  "All": "Все",
  "Search for apps, discover new field types and add functionalities to your Storyblok project.": "Ищите приложения, открывайте новые типы полей и добавляйте новый функционал в ваш Storyblok проект.",
  "My apps": "Мои приложения",
  "Create new app": "Создать новое приложение",
  "Installed": "Установлено",
  "App Directory": "Каталог приложений",
  "There are no apps in this category.": "В этой категории нет приложений.",
  "Install": "Установить",
  "Choose the space to install this app": "Выберите область для установки этого приложения",
  "Can not move asset folder into folder without permissions.": "Невозможно переместить папку ресурсов в папку, к которой у вас нет прав.",
  "Can not move asset into folder without permissions.": "Невозможно переместить ресурсы в папку, к которой у вас нет прав.",
  "Can not move asset away from folder without permissions.": "Невозможно переместить ресурсы из папки, к которой у вас нет прав.",
  "Define the new name of the folder.": "Задайте имя папки.",
  "Trashbin": "Корзина",
  "Are you sure that you want to delete this folder?": "Вы уверены, что хотите удалить эту папку?",
  "Add": "Добавить",
  "Asset folders are not included in the free plan but you can try them in the": "Папки ресурсов не включены в бесплатный план, но вы можете использовать их в",
  "New folder will be created in": "Новая папка будет создана в",
  "trial period": "пробный период",
  "Can not create asset folder without permission for parent.": "Вы не можете создать папку ресурсов без прав на родительскую папку.",
  "Original": "Оригинал",
  "Done": "Готово",
  "Cancel": "Отмена",
  "Insert": "Вставить",
  "Add Asset(s)": "Добавить ресур(ы)",
  "Close": "Закрыть",
  "items": "Объекты",
  "Delete": "Удалить",
  "Move to folder": "Переместить в папку",
  "Replace": "Заменить",
  "Unselect all": "Снять выделение со всех",
  "Restore": "Восстановить",
  "Tiles": "Плитки",
  "List": "Список",
  "No assets found": "Ресурсов не найдено",
  "Sort": "Сортировка",
  "Default": "По умолчанию",
  "View": "Просмотр",
  "Creation date (asc)": "По дате создания (по возрастанию)",
  "Filename (asc)": "Имя файла (по возрастанию)",
  "Creation date (desc)": "По дате создания (по убыванию)",
  "Filename (desc)": "Имя файла (по убыванию)",
  "Last updated date (asc)": "По дате обновления (по возрастанию)",
  "Last updated date (desc)": "По дате обновления (по убыванию)",
  "You are not allowed to insert this filetype here.": "Вам запрещено вставлять сюда такой тип файла.",
  "This key is already defined": "Такой ключ уже занят",
  "Key is in invalid format": "Ключ имеет неверный формат",
  "Something went wrong uploading some items": "Что-то пошло не так при загрузки некоторых объектов",
  "Please choose a folder in the left sidebar": "Выберите папку в левом сайдбаре",
  "Define the new name of": "Задайте новое имя для",
  "Something went wrong renaming the attribute": "Что-то пошло не так при переименовании атрибута",
  "Be aware! Changing the name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Будьте в курсе! Изменение имени может занять несколько минут, чтобы обновить все объекты. Убедитесь, что ваши редакторы сохранили свою работу и выйдите из редактора.",
  "Define the new name of the component group.": "Задайте имя для группы компонентов.",
  "Save": "Сохранить",
  "Are you sure that you want to delete this component group?": "Вы уверены, что хотите удалить группу компонентов?",
  "Copy": "Копировать",
  "New": "Новый",
  "Move to group": "Переместить в группу",
  "Please choose a component group in the left sidebar": "Выберите группу компонентов в левом сайдбаре",
  "Paste": "Вставить",
  "Add block": "Добавить блок",
  "Creation of a component failed. Maybe it already exists.": "При создании компонента произошла ошибка. Возможно он уже существует.",
  "Are you sure you want to DELETE this component(s)?": "Вы уверены, что хотите УДАЛИТЬ этот компонент(ы)?",
  "new": "новый",
  "Type to search or to create a": "Тип для поиска или создания",
  "Create new": "Создать новый",
  "block": "блок",
  "New Component": "Новый компонент",
  "Updated": "Обновлено",
  "Name": "Имя",
  "Shortcuts: Esc, Control + S": "Сокращение: Esc, Control + S",
  "Next": "Следующий",
  "Define a name": "Задать имя",
  "Save schema": "Сохранить схему",
  "Act as content type (eg. blog-post)": "Задать как тип контента (например, пост блога)",
  "Define": "Задать",
  "Nestable": "Вкладываемые",
  "Technical name": "Техническое имя",
  "Edit field": "Редактировать поле",
  "Config": "Конфигурация",
  "Schema": "Схема",
  "Renaming": "Переименование",
  "Change field name": "Изменить имя поля",
  "Used in the json as component name": "Используется в json имени компонента",
  "Be aware! Changing the technical name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Будьте в курсе! Изменение технического имени может занять несколько минут, чтобы обновить все объекты. Убедитесь, что ваши редакторы сохранили свою работу и выйдите из редактора.",
  "Display name": "Отображаемое имя",
  "Preview template": "Предосмотр шаблона",
  "Screenshot or icon": "Скриншот или иконка",
  "Used in the editor interface only": "Используется только для интерфейса ректора",
  "of this setting": "этого параметра",
  "Read the documentation": "Читать документацию",
  "Load versions": "Загрузить версии",
  "Versions": "Версии",
  "has been added below": "был добавлен ниже",
  "Examples: news_items, body, columns, title, description or call_to_action_btn": "Примеры: news_items, body, columns, title, description or call_to_action_btn",
  "The component has been restored!": "Этот компонент восстановлен!",
  "Do you really want to leave without saving your changes?": "Вы уверены, что хотите уйти без сохранения изменений?",
  "Type": "Тип",
  "Beta": "Бета",
  "Translatable": "Переводимый",
  "Allow empty paragraphs": "Разрешить пустые параграфы",
  "Linktype": "Тип ссылки",
  "Rich-text as default": "Rich-text по умолчанию",
  "Custom type": "Пользовательский тип",
  "Category": "Категория",
  "Section items": "Пункты раздела",
  "Product": "Продукт",
  "Customize toolbar": "Настроить панель инструментов",
  "Toolbar items": "Пункты панели инструментов",
  "Source": "Источник",
  "CSS class options (label/value)": "CSS класс опции (ярлык/значение)",
  "Datasource": "Источник данных",
  "Stories": "Истории",
  "Self": "Свой",
  "Internal datasource": "Внутренний источник данных",
  "Recommended to be checked, as UID is required for automatic link resolving.": "Рекомендуется отметить как UID, это нужно для автоматического разрешения конфликтов ссылок.",
  "Use UID instead of ID": "Использовать UID вместо ID",
  "In case you have a multi-language folder structure you can add the {0} placeholder and the path will be adapted dynamically. Examples: {0}/categories/, {0}/{1}/categories/": "В том случае, если у вас мультиязычная структура папок вы можете добавить в путь ярлык {0} для динамичной генерации. Примеры: {0}/categories/, {0}/{1}/categories/",
  "External JSON": "Внешний JSON",
  "Path to folder of stories": "Путь до папки с историями",
  "Width": "Ширина",
  "URL": "URL",
  "ratio": "соотношение",
  "pixel": "пиксель",
  "Allowed maximum": "Допустимый максимум",
  "Options (name/value)": "Опции (имя/значение)",
  "Component(s)": "Компонент(ы)",
  "Group(s)": "Группа(ы)",
  "Required field(s) (comma separated)": "Требуемое поле(я) (разделенные запятой)",
  "Required": "Требуется",
  "Default asset folder": "Папка ресурсов по умолчанию",
  "Choose an asset folder where the assets should be assigned to.": "Выберите папку ресурсов, к которой нужно привязать эти ресурсы.",
  "With {level} the path will be replaced dynamically using parts of the current slug. Examples: {0}/categories/, {0}/{1}/categories/": "С {уровнем} в пути, который будет динамически заменен используя части текущего ярлыка. Примеры: {0}/categories/, {0}/{1}/categories/",
  "Restrict to folder": "Ограничить папкой",
  "Force folder restriction": "Принудительное ограничение папки",
  "Regex validation": "Regex валидация",
  "Exclude from export": "Исключить из экспорта",
  "export app": "экспортировать приложение",
  "To use with the": "Использовать вместе с",
  "Default value": "Значение по умолчанию",
  "Can be updated by preview window": "Будет обновлено в окне предосмотра",
  "Loading...": "Загрузка...",
  "Item": "Объект",
  "Allow only specific components to be inserted": "Разрешить вставку только определенных компонентов",
  "Restrict to content types": "Ограничить типами контента",
  "Keep original size": "Сохранить оригинальный размер",
  "Force crop": "Принудительная обрезка",
  "Prepend https to url": "Добавить https к url",
  "Height": "Высота",
  "Maximum characters": "Максимум знаков",
  "Disable time selection": "Отключить выбор времени",
  "Description": "Описание",
  "dimensions app": "размеры приложения",
  "Force overwrite by merge action": "Принудительно перезаписать действием слияния",
  "Id/Slug": "Ид/Ярлык",
  "Enable RTL (Right to left)": "Включить RTL (Справа налево)",
  "Autosave": "Автосохранение",
  "API Url": "API Url",
  "Export": "Экспорт",
  "Import/Export": "Импорт/Экспорт",
  "Dimensions": "Размеры",
  "Add Dimension": "Добавить размер",
  "Import": "Импорт",
  "A datasource in Storyblok is a collection of key-value pairs.": "Источник данных в Storyblok это коллекция пар ключ-значение.",
  "Datasources can be used in a schema definition of a component for single or multiple choice options. You can also access": "Источники данных могут использоваться для схемы компонента для одного или нескольких опций выборы. Вам также доступны",
  "datasource entries from the API": "записи источника данных из API",
  "to use them for labels, categories or similar.": "для использования их для ярлыков, категорий или аналогичного.",
  "Unsaved Changes": "Несохраненные изменения",
  "Datasource entries": "Записи источника данных",
  "Datasources are not included in the free plan": "Источники данных не включены в бесплатный тариф",
  "but you can try them in the": "но вы можете воспользоваться ими в",
  "Saved": "Сохранено",
  "Select all": "Выбрать все",
  "The options could not be loaded.": "Параметры не могут быть загружены.",
  "New Datasource": "Новый источник данных",
  "The following component(s) can not be pasted here": "Следующий компонент(ы) не могут быть расположены здесь",
  "Please save first to continue editing child components.": "Сохранитесь, прежде чем редактировать дочерние компоненты.",
  "Enabled?": "Включено?",
  "Asset manager": "Управление ресурсами",
  "Loading": "Загрузка",
  "Upload new": "Загрузить новый",
  "Your file exceeds the maximum filesize limit of": "Ваш файл превышает максимальный размер файла в ",
  "Please reduce the size of your file.": "Уменьшите размер вашего файла.",
  "Alt text": "Alt текст",
  "Base64": "Base64",
  "Original Size": "Оригинальный размер",
  "Image loading failed": "Загрузка изображения не удалась",
  "Quote": "Цитата",
  "Code Block": "Блок кода",
  "Ordered List": "Нумерованный список",
  "Headline 2": "Заголовок 2",
  "Headline 4": "Заголовок 4",
  "Headline 3": "Заголовок 3",
  "Headline 5": "Заголовок 5",
  "Paragraph": "Параграф",
  "Help": "Помощь",
  "Internal link": "Внутренняя ссылка",
  "Show only selected": "Показать только выбранные",
  "more items found": "найдено больше объектов",
  "Invoices": "Счета",
  "Tip: Use Ctrl + S to save": "Совет: Используйте Ctrl + S для сохранения",
  "Input": "Ввод",
  "Publish": "Опубликовать",
  "You are not allowed to edit this plugin but can see the code at Settings/Details.": "Вам не разрешено редактировать этот плагин, но вы можете смотреть код в Настройки/Детали.",
  "Field type preview": "Предосмотр типа поля",
  "Options (key/value)": "Параметры (ключ/значение)",
  "Space Id": "Ид области",
  "Enable local dev mode": "Включить локальный режим разработки",
  "Settings/Details": "Настройки/Детали",
  "Output": "Вывод",
  "for approval to make it available for all users.": "для утверждения, чтобы сделать его доступным для всех пользователей.",
  "Submit the plugin": "Отправить плагин",
  "Code": "Код",
  "You can copy the code of this plugin to create your own plugin.": "Вы можете скопировать код этого плагина, чтобы создать свой собственный.",
  "Assigned spaces": "Привязанные области",
  "If you assign this plugin to a space other developers can also use it in the schema definition. Without assigning it only you can add the plugin to the schemas.": "Если вы привяжите этот плагин к области, то другие разработчики тоже смогут использовать его для определения схемы. Без привязки только вы сможете добавить плагин к схемам.",
  "Attention: All spaces using this plugin will not be able to use it any more if you click delete.": "Внимание: Все области использующие этот плагин больше не смогут его использовать, если вы нажмете «Удалить».",
  "Documentation": "Документация",
  "Danger zone": "Опасная зона",
  "What is a field type plugin?": "Что такое плагин типов полей?",
  "A field type plugin extends the Storyblok editor with your own custom field types.": "Плагин типов полей расширяет редактор Storyblok вашими собственными типами полей.",
  "It is basically a": "Это в основном",
  "The properties that are passed to the field type are:": "Свойства, которые передаются типу поля:",
  "component extended with a few helpers in the window.Storyblok.plugin mixin.": "компонент расширен с помощью нескольких хелперов в window.Storyblok.plugin миксине.",
  "Examples for field types are colorpickers, WYSYWYG editors or meta tags.": "Примеры для таких типов полей, как colorpickers, WYSYWYG редакторы или мета теги.",
  "Uid of the parent component": "Uid родительского компонента",
  "Options parsed from the schema options array": "Параметры получены из массива параметров схемы",
  "Schema options object": "Объект параметров схемы",
  "Current value of the fieldtype": "Текущее значение типа поля",
  "Story id of the current story": "Идентификатор текущей истории",
  "Space id of the current space": "Идентификатор текущей области",
  "Api function to call the delivery api": "Api функция для вызова api доставки",
  "Methods": "Методы",
  "Draft token of the current space": "Черновой токен текущей области",
  "How to call the Storyblok api?": "Как обратиться к Storyblok api?",
  "Should be used to define the initial data of the plugin.": "Должен использоваться для определения начальных данных плагина.",
  "Should be used to initialize the plugin. Examples: Load data from Storyblok or external sources, Load and initialize a WYSIWYG editor.": "Должен использоваться для инициализации плагина. Примеры: Загрузка данных их Storyblok или внешних источников, загружает и инициализирует WYSIWYG редактор.",
  "To pass options that are configurable in the schema definition define the option keys in the \"Input\" box. The values will be available in the this.options object.": "Чтобы передать параметры, которые можно настроить в определении схемы, задайте ключи параметров в поле \"Ввода\". Значения будут доступны в объекте this.options.",
  "How to pass options?": "Как передать параметры?",
  "In field types you can use this.api to get access to the Storyblok delivery api. You can use it for example to build a selectbox of stories.": "В типах полей вы можете использовать this.api, чтобы получить доступ к Storyblok delivery api. К примеру, вы можете использовать это для генерации списка опций из историй.",
  "Folder/Content-item permissions": "Разрешения на папку/объект",
  "Item saved successfully!": "Объект успешно сохранен!",
  "Source of sync": "Источник синхронизации",
  "Preview": "Предосмотр",
  "Preview url": "Url предосмотра",
  "View on Jsfiddle": "Смотреть на Jsfiddle",
  "Download": "Загрузить",
  "Admin": "Администратор",
  "Permissions": "Разрешения",
  "Editor": "Редактор",
  "Advanced Rights": "Расширенные права",
  "Allow saving content": "Разрешить сохранять контент",
  "Allow publishing content": "Разрешить публиковать контент",
  "Allow saving datasources": "Разрешить сохранять источники данных",
  "Allow managing subscription": "Разрешить управлять подпиской",
  "Allow access to ecommerce app": "Разрешить доступ к приложениям электронной коммерции",
  "Deny access to visual composer": "Запретить доступ к визуальному редактору",
  "Field Permissions": "Разрешенные поля",
  "General": "Общие",
  "Allowed path": "Разрешенные пути",
  "Your crawl URL": "URL вашего сканера",
  "Crawler": "Сканер",
  "Enabled": "Включено",
  "Index": "Индекс",
  "Crawl now": "Сканировать сейчас",
  "Information needed to access the search endpoint or to configure the search client.": "Информация, нужная для получения доступа к точке поиска или для конфигурации поискового клиента.",
  "Search Setup Guide": "Руководство по настройке поиска",
  "Your tenant ID": "Идентификатор вашего арендатора",
  "See": "Смотреть",
  "Documents in index": "Документы в индексе",
  "Crawl requested at": "Сканирование запрошено в",
  "Tenant ID": "Идентификатор арендатора",
  "Documents": "Документы",
  "Clear index": "Очистить индекс",
  "Last crawled at": "Последнее сканирование",
  "Crawl has been initiated": "Сканер запущен",
  "In the first 14 days you can try out all Premium plan features!": "В течение 14 дней вы можете пользоваться всеми преимуществами премиум плана!",
  "Index deletion has been initiated": "Удаление индекса запущено",
  "API-Keys": "API ключи",
  "We would love to hear your thoughts about Storyblok on": "Мы хотели бы услышать ваши мысли о Storyblok",
  "Renderer": "Отрисовщик",
  "Backup": "Резервная копия",
  "Users": "Пользователи",
  "Workflow": "Рабочий процесс",
  "Search": "Поиск",
  "Languages": "Языки",
  "This is the page that the frontend-editor opens.": "Это страница, которую открывает редактор интерфейса.",
  "Location (default environment)": "Местоположение (окружение по умолчанию)",
  "Insert your domain/location including the protocol. Example: http://www.example.com/": "Вставьте имя вашего домена включая протокол. Пример: http://www.example.com/",
  "Provide this ID in your support tickets": "Укажите этот идентификатор в своих запросах поддержки",
  "Your space ID": "Идентификатор вашей области",
  "Preview urls": "Url'ы предосмотра",
  "Define multiple domains/locations to quickly switch the preview urls in the story-editor.": "Укажите несколько доменов/мест для быстрого переключения URL-адресов предварительного просмотра в редакторе историй.",
  "Add preview url": "Добавить url предосмотра",
  "Webhooks": "Вебхуки",
  "Story published &amp; unpublished": "История опубликована &amp; неопубликованна",
  "Story saved": "История сохранена",
  "Branch deployed": "Ветка опубликована",
  "Release merged": "Выпуск объединен",
  "Slack integration": "Интеграция со Slack",
  "Loading... You will be redirect to Slack in a few seconds!": "Загрузка... Вы будете перенаправлены на Slack через несколько секунд!",
  "Get notified on your Slack channel if a new Story has been published!": "Отправлять уведомление в ваш Slack канал когда публикуется новая история!",
  "With this integration you can choose a Slack channel where Storyblok posts messages whenever a user publishes new content.": "С этой интеграцией вы сможете выбрать Slack канал, в который Storyblok отправит сообщение о новых публикациях.",
  "Disconnect": "Отключить",
  "Cloud name": "Имя облака",
  "Cloudinary integration": "Интеграция Cloudinary",
  "Api Key": "Api ключ",
  "Branches": "Ветки",
  "Default content type": "Тип контента по умолчанию",
  "Content types": "Типы контента",
  "Name of the branch": "Имя ветки",
  "Branches are not included in the free plan": "Ветки не включены в бесплатный тариф",
  "Duplication": "Дублирование",
  "This is useful if you want to offer your space for other users as a boilerplate or theme.": "Это полезно, если вам нужно предложить вашу область другим пользователям как шаблон или тему.",
  "ATTENTION! Only check this checkbox if you are sure that you want all data of this space available for duplication.": "ВНИМАНИЕ! Отмечая этот пункт вы даете доступ ко всем данным этой области и она становится доступной для дублирования.",
  "Make this space duplicatable by all users": "Сделать эту область дублируемой для всех пользователей",
  "Content ownership": "Владение контентом",
  "Parent ID": "Родительский идентификатор",
  "Parent": "Родитель",
  "Image service": "Сервис изображений",
  "Content ownership client endpoint": "Клиентская конечная точка владения контентом",
  "List of paths to invalidate": "Список путей для инвалидации",
  "Delete this space": "Удалить эту область",
  "Invalidate": "Инвалидировать",
  "Workflow webhooks": "Вебхуки рабочего окружения",
  "Owner": "Владелец",
  "Workflow changed": "Рабочее окружение изменено",
  "Transfer ownership": "Предать владение",
  "Transfer": "Передать",
  "Attention! Transferring the ownership will remove all your rights to this space.": "Внимание! Передавая владение этой областью вы теряете все права на эту область.",
  "The owner needs to add you as a collaborator if you want to have access again.": "Владельцу нужно добавить вас как сотрудника, если вам снова понадобится доступ.",
  "Collaborators": "Работники",
  "Collaborator": "Работник",
  "No user found with this email or username.": "Не найдено пользователей с таким email или ником.",
  "Name of the role": "Имя роли",
  "Role": "Роль",
  "Add a new user to your org": "Добавить нового пользователя в вашу организацию",
  "Advanced rights and roles are not included in the free and basic plan": "Разширенные права и роли не включены в бесплатный и базовый тарифы",
  "Use your Amazon S3 bucket to create backups.": "Используйте ваш Amazon S3 bucket для создания резервных копий.",
  "Backup now": "Сделать резервную копию",
  "Backups content (stories) and compontents": "Создает резервную копию контента(историй) и компонентов",
  "Define your S3-Bucket and AWS-ARN to enable backups.": "Укажите ваш S3-Bucket и AWS-ARN для включения резервного копирования.",
  "Daily backups": "Ежедневное резервное копирование",
  "Define the name of the S3-bucket where you want to store your backups.": "Укажите имя S3-bucket в котором хотите хранить резервные копии.",
  "S3-bucket": "S3-bucket",
  "Activate automatic daily backups": "Активировать ежедневное резервное копирование",
  "1. Read the": "1. Прочитайте",
  "AWS Policy ARN": "Политику AWS ARN",
  "Show setup instructions": "Показать инструкции по настройке",
  "tutorial on how to setup an Amazon IAM role": "руководство по настройке Amazon IAM ролей",
  "2. Create an Amazon IAM role with following access policy document:": "2. Создайте Amazon IAM роль со следующими доступами:",
  "if not done yet.": "если еще не сделали.",
  "The role should have the permission to access and create files on the S3 bucket you defined. You can for example use the following permission policy replacing YOUR_BUCKET with your bucket name:": "Роль должна иметь права на доступ и создание файлов в S3 bucket, который вы указали. Вы можете использовать этот пример заменив YOUR_BUCKET вашем именем:",
  "Restore spaces from backups on your Amazon S3 bucket.": "Восстановить области из S3 bucket.",
  "Backup file": "Файл резервной копии",
  "Show latest backups": "Показать последние резервные копии",
  "Latest five backups": "Последние 5 резервных копий",
  "Restore now": "Восстановить",
  "The settings below only apply if you are using": "Настройки ниже применяются только если вы используете",
  "Attention! \"Restore now\" deletes old data and restores content (stories) and compontents from the backup file.": "Внимание! \"Восстановить\" удаляет старые данные и восстанавливает контент(истории) и компоненты из файла резервной копии.",
  "Rendering service": "Сервис отрисовки",
  "Your domain": "ваш домен",
  "To connect your domain to Storyblok you need to create a CNAME Record pointing to eu-domain.storyblok.com": "Для подключения вашего домена к Storyblok вам нужно создать CNAME запись со значением eu-domain.storyblok.com",
  "Routes": "Маршруты",
  "Add Route": "Добавить маршрут",
  "Please read the": "Пожалуйста прочитайте",
  "Add custom routes to define different page templates.": "Добавить пользовательские маршруты для различных шаблонов страниц.",
  "documentation about internationalization": "документация о интернационализации",
  "before configuring languages.": "перед настройкой язывок.",
  "Add languages to activate field level translations.": "Добавьте языки для активации перевода полей.",
  "Add Language": "Добавить язык",
  "Label": "Ярлык",
  "The invalidation process has been initiated": "Процесс признания недействительным начат",
  "The backup has been initiated": "Начато резервное копирование",
  "Are you sure you want to delete your current content and overwrite it with this backup?": "Вы уверены, что хотите удалить текущий контент и перезаписать его данными из резервной копии?",
  "The restore process has been initiated": "Процесс восстановления запущен",
  "Transfer was not successful. Make sure that the new owner exists.": "Передача владения не удалась. Проверьте существует ли новый владелец.",
  "The collaborator has been added": "Работник добавлен",
  "Please insert an email address": "Вставьте email адреса",
  "Branches sorted successfully!": "Ветки отсортированны!",
  "Create or join a space": "Создайте или войдите в область",
  "Create a new space": "Создать новую область",
  "Play with a demo": "Попробовать с демо",
  "Duplicate a space": "Дублировать область",
  "Join a space": "Войти в область",
  "Create space": "Создать область",
  "Headless (API/SDKs)": "Безголовый (API/SDKs)",
  "what is that?": "Что это значит?",
  "Duplicate space": "Дублировать область",
  "Choose the space for the duplication": "Выбрать область для дублирования",
  "You do not have created any spaces yet.": "у вас еще нет созданных областей.",
  "You can test the editing interface and our visual composer without to write any code on your own.": "Вы можете тестировать визуальный редактор без написания собственного кода.",
  "Create Demo": "Создать демо",
  "Insert the email of your space admin to let them add you as a collaborator of the space.": "Вставьте email вашего администратора области, чтобы дать ему права работника в этой области.",
  "Request access": "Запросить доступ",
  "Email address of space admin": "Email адреса администраторов области",
  "Success! You will get notified once the admin added you as a collaborator.": "Успешно! Вас оповестят, когда администраторы добавят вас как работника.",
  "Available Billing Information": "Доступная платежная информация",
  "No spaces with billing information available": "Нет областей с доступной платежной информацией",
  "Spaces": "Области",
  "Show More": "Показать больше",
  "Apply": "Применить",
  "Show": "Показать",
  "Billing Information of Space": "Платежная информация области",
  "The information below will be applied to the fields of your current subscription process. You will be able to adopt them after applying them.": "Информация ниже будет применена к полям вашего текущего процесса подписки. Вы сможете исправить их после их применения.",
  "Company": "Компания",
  "Country": "Страна",
  "Street / City / ZIP": "Улица / Город / Индекс",
  "Email": "Email",
  "Add or change preview urls": "Добавить или изменить url'ы предосмотра",
  "Your server address": "Адрес вашего сервера",
  "1. Download a preconfigured project": "1. Скачайте настроенный проект",
  "Preferred by our users": "Настроенные нашими пользователями",
  "The downloaded package comes preconfigured with your api token": "Загружаемый пакет включает настройки с вашим api ключом",
  "Tutorial": "Руководство",
  "Other technologies": "Другие технологии",
  "2. Start your server": "2. Запустите ваш сервер",
  "Start the server of the downloaded package and insert your server url here:": "Запустите вас сервер с загруженным пакетом и вставьте ссылку вашего сервера:",
  "Go": "Вперед",
  "FAQ": "ЧАВО",
  "Can I build a full blown website with Storyblok?": "Могу ли я создать полноценный сайт с помощью Storyblok?",
  "Can I create a blog with Storyblok?": "Могу ли я создать блог с помощью Storyblok?",
  "How does Storyblok work?": "Как работает Storyblok?",
  "What is the Storyblok bridge?": "Что такое Storyblok мост?",
  "Allow deploying content": "Разрешить развертывание контента",
  "General permissions": "Общие разрешения",
  "Allow unpublishing content": "Разрешить снятия контента с публикации",
  "Allow deleting content": "Разрешить удаление контента",
  "Allow editing datasource keys & values": "Разрешить редактирование ключей и значений в источниках данных",
  "Allow editing datasource values": "Разрешить редактировать значения в источниках данных",
  "Allow access to the tasks app": "Разрешить доступ к приложения Задачи",
  "Deny moving a story": "Запретить перемещение истории",
  "Deny changing alternates group": "Запретить изменения альтернативных групп",
  "Add languages the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Добавьте языки, к которым пользователь должен иметь доступ (действует как белый список). Если ни один элемент не выбран, то у пользователя есть права на редактирование всего содержимого.",
  "Deny changing the slug of a story": "Запретить изменение ярлыка истории",
  "Add folders or content items the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Добавьте папки или объекты, к которым пользователь должен иметь доступ (действует как белый список). Если ни один элемент не выбран, то у пользователя есть права на редактирование всего содержимого.",
  "Component field permissions": "Разрешения на поля компонента",
  "Datasource permissions": "Разрешения источников данных",
  "Add component fields here to hide them in the interface.": "Добавьте поля компонента здесь, чтобы скрыть их из интерфейса.",
  "Add datasources the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all datasources.": "Добавьте источники данных, к которым пользователь должен иметь доступ (действует как белый список). Если ни один элемент не выбран, то у пользователя есть права на редактирование все источники данных.",
  "Asset Folder Permissions": "Разрешения папки ресурсов",
  "Add asset folders to restrict editing and upload access.": "Добавить папки ресурсов, чтобы ограничить редактирование и доступ к загрузке.",
  "Start by selecting a space in the sidebar or create a new space.": "Начните с выбора области на боковой панели или создайте новую область.",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Похоже, у вас еще нет доступа ни к одной области. Свяжитесь с администратором вашей организации, чтобы он добавил вас как работника.",
  "Welcome!": "Добро пожаловать!",
  "Traffic": "Трафик",
  "Learn more about": "Изучить больше о",
  "Api requests": "Api запросы",
  "Active Plan": "Текущий план",
  "Usage": "Использование",
  "Content activities": "Активность",
  "No billing": "Нет выписок",
  "Change": "Изменить",
  "Billed": "Выписано",
  "No recent changes": "Нет недавних изменений",
  "Choose your plan": "Выбрать план",
  "Recent changes": "Недавние изменения",
  "Custom": "Индивидуальный",
  "Compare": "Сравнить",
  "user": "пользователь",
  "Got a custom plan or coupon code?": "Нужен индивидуальный план или есть код купона?",
  "Custom plan": "Индивидуальный план",
  "Entered plan ids will be validated after pressing subscribe.": "Введенные идентификаторы плана будут применены после нажатия кнопки «Подписаться»..",
  "Coupon code": "Код купона",
  "Entered coupon codes will be validated and applied after pressing subscribe.": "Введенные коды купонов будут применены после нажатия кнопки «Подписаться».",
  "Select seats": "Выбрать места",
  "Confirm subscription": "Подтвердить подписку",
  "Min": "Минимум",
  "Max": "Максимум",
  "By clicking the button below the new subscription will start.": "По нажатию кнопки ниже новая подписка начнет действовать.",
  "Decide payment interval": "Определите интервал оплаты",
  "Change subscription": "Изменить подписку",
  "Monthly": "Месячная",
  "Annually": "Годовая",
  "Define billing information": "Укажите платежную информацию",
  "Email address": "Email адрес",
  "VAT-Number": "номер НДС",
  "Reuse from another space": "Заполнить из другой области",
  "Order number": "Номер заказа",
  "Street": "Улица",
  "City": "Город",
  "Credit or debit card": "Кредитная или дебетовая карта",
  "ZIP": "Индекс",
  "Enter payment information": "Введите информацию о платеже",
  "Update payment information": "Обновить информацию о платеже",
  "Update billing information": "Обновите платежную информацию",
  "Information: Our payment provider validates card information when it is saved. As a result of this process, you may see a temporary authorization for $1 on your statement.": "Информация: Наш провайдер проверяет данные карты при ее сохранении. В результате этого процесса вы можете увидеть временное списание на 1 доллар в своих расходах.",
  "Please provide all billing informations marked as required (*)": "Пожалуйста, предоставьте всю платежную информацию, отмеченную как обязательная (*)",
  "Your selected team sizes are not in the limits of your selected feature set. You can select another feature set to continue.": "Размеры выбранных вами команд не входят в выбранный вами набора функций. Вы можете выбрать другой набор функций, чтобы продолжить.",
  "View invoices": "Смотреть счета",
  "Summary": "Итог",
  "Please provide a credit or debit card": "Пожалуйста, предоставьте кредитную или дебетовую карту",
  "If your entered plan is not correct you will still be able to try it again.": "Если введенный вами план неверен, вы все равно сможете попробовать его снова.",
  "You have entered a custom plan with a special offering and pricing": "Вы ввели индивидуальный план со специальным предложением и ценами",
  "users": "пользователи",
  "VAT reverse charge applies.": "Применяется обратный НДС.",
  "VAT": "НДС",
  "Total": "Всего",
  "The benefits of the coupon code will be applied if available": "Преимущества кода купона будут применяться при наличии",
  "Thanks! You are awesome!": "Спасибо! Вы прекрасны!",
  "We would love to hear what you think about Storyblok.": "Мы хотели бы услышать, что вы думаете о Storyblok.",
  "Chat with us or": "Чат с нами или",
  "your feedback.": "вашу обратную связь.",
  "Tweet": "Твит",
  "Star": "Звезда",
  "Share": "Поделиться",
  "Public access tokens are only for accessing the published version while preview tokens are for accessing the draft version also. Both are read-only tokens.": "окены общего доступа предназначены только для доступа к опубликованной версии, а токены предварительного просмотра - для доступа к черновой версии. Оба являются токенами только для чтения.",
  "Access level": "Уровень доступа",
  "Public": "Публичный",
  "See API-Documentation": "Смотрите документацию к API",
  "Theme": "Тема",
  "Branch": "Ветка",
  "Choose branch": "Выбрать ветку",
  "Create Token": "Создать токен",
  "Color": "Цвет",
  "Define as default stage for new content items": "Установить как значение по умолчанию для новых объектов",
  "Publishing rights": "Права на публикацию",
  "Stage transition rules": "Права смены стадии",
  "Allow users to publish or schedule the content": "Разрешить всем пользователям публиковать или планировать контент",
  "Specific stage(s)": "Конкретный этап(ы)",
  "Next available stages": "Следующий доступный этап",
  "All stages": "Все этапы",
  "All users": "Все пользователи",
  "User(s)/Role(s) who can change the stage": "Пользователь(и)/Роль(и), которые могуть изменить этап",
  "to the next available stage": "к следующему доступному этапу",
  "Specific user(s)/role(s)": "Конкретный пользователь(и)/роль(и)",
  "Role(s)": "Роль(и)",
  "User(s)": "Пользователь(и)",
  "Workflow stages": "Стадии рабочего окружения",
  "See workflow documentation": "Смотреть документацию рабочего окружения",
  "Create": "Создать",
  "Choose an approver": "Выберите утверждающего",
  "Workflow stages sorted successfully!": "Стадии рабочего окружения отсортированы!",
  "Are you sure you want to delete this workflow stage?": "Вы уверены, что хотите удалить стадию рабочего окружения?",
  "Send for approval": "Отправить на утверждение",
  "Approval request has been sent successfully!": "Запрос на утверждение отправлен!",
  "Content items": "Объекты контента",
  "Entry": "Запись",
  "Define schema": "Задать схему",
  "Folder": "Папка",
  "You have not defined any schema for this block yet.": "У вас еще нет заданных схем для этого блока.",
  "Define presets": "Задать значения по умолчанию",
  "Click \"Define schema\" to add the fields you need.": "Кликните \"Задать схему\" для добавления нужных полей.",
  "No valid fields defined in this section yet.": "Для этого раздела еще не заданы валидные поля.",
  "is already part of another section": "уже является частью другого раздела",
  "Translate": "Перевести",
  "Choose to delete the values or add the schema keys.": "Выберите, чтобы удалить значения или добавить ключи схемы.",
  "items out of schema": "элементы вне схемы",
  "We have found values which are not part of the schema.": "Мы нашли значения, которые не являются частью схемы.",
  "No changes found": "Не найдены изменения",
  "Changes": "Изменения",
  "Remove all": "Убрать все",
  "Select releases to deploy": "Выберите версии для развертывания",
  "What is getting deployed?": "Что развертывается?",
  "All content that is currently on the source branch and the releases you select.": "Весь контент, который в данный момент находится в исходной ветке и выбранной вами версии.",
  "No releases found on the source branch": "Нет версий в ветке-источнике",
  "A newer version of this content item has been found in the database.": "Более новая этого контента версия найдена в базе данных.",
  "Confirm": "Подтвердить",
  "Choose the conflict solution": "Выберите решение конфликта",
  "Copy over": "Скопировать",
  "Opens newer version in a new window to let you copy over your changes.": "Открывает новую версию в новом окне, чтобы позволить вам скопировать ваши изменения.",
  "Overwrite": "Перезаписать",
  "Slug": "Ярлык",
  "Overwrites newer version with your changes.": "Перезаписывает новую версию вашими изменениями.",
  "Define as root for the folder": "Задать как корень для папки",
  "Preset": "Пресет",
  "Content type": "Тип контента",
  "Confirm deletion": "Подтвердить удаление",
  "Are you sure that you want to delete this item(s)?": "Вы уверены, что хотите удалить этот элемент(ы)?",
  "Include associated alternates": "Включить связанные альтернативы",
  "Target-Folder": "Целевая папка",
  "Is alternative version of the duplicate?": "Альтернативная версия дубликата?",
  "Duplicate": "Дублировать",
  "Schedule": "Запланировать",
  "duplicated": "дублировано",
  "You are not allowed to duplicate this story.": "Вам не разрешено дублировать эту историю.",
  "Open published": "Открыть опубликованное",
  "Send approval": "Отправить подтверждение",
  "Open draft": "Открыть черновик",
  "Unpublish": "Снять с публикации",
  "Draft json": "Черновой json",
  "Discard changes": "Отменить изменения",
  "Start sync": "Начать синхронизацию",
  "Published json": "Опубликованный json",
  "Status": "Статус",
  "Tools": "Инструменты",
  "Real path": "Настроящий путь",
  "Settings for the folder content": "Настройки паки контента",
  "Disable visual composer": "Отключить визуальный редактор",
  "Clone to all": "Клонировать всем",
  "Deny changing content type": "Запретить менять тип контента",
  "Merge to all": "Слияние со всеми",
  "Dimensions are only available if you are editing a content item in a subfolder.": "Размеры доступны, только если вы редактируете элемент содержимого в подпапке.",
  "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).": "Создайте структуру папок, где первая папка определяет ваше измерение (Пример: de/home, en/home).",
  "Not created yet": "Еще не создано",
  "Create clone": "Создать клон",
  "Merge": "Объединить",
  "Something went wrong merging the alternate(s)": "Что-то пошло не так, при объединении альтернатив(ы)",
  "The alternate(s) have been created!": "Альтернатива(ы) была создана!",
  "The alternate(s) have been merged!": "Альтернатива(ы) была объединена!",
  "Add preset": "Добавить пресет",
  "Presets are blocks filled with the content you currently have in the selected block.": "Пресеты - это блоки, заполненные содержимым, которое у вас есть в выбранном блоке.",
  "Something went wrong creating the alternate(s)": "Что-то пошло не так при создании альтернатив(ы)",
  "The saved presets are shown for all users at the selection of new blocks.": "Сохраненные пресеты показываются всем пользователям при выборе новых блоков.",
  "Existing presets": "Существующие пресеты",
  "As default": "По умолчанию",
  "Release date (optional)": "Дата выпуска (опционально)",
  "Branches to deploy": "Ветки для развертывания",
  "When the release gets merged all content will be automatically deployed to the selected branches.": "Когда релиз объединен, весь контент будет автоматически развернут в выбранных ветвях.",
  "Entry configuration": "Конфигурация входа",
  "Editmode": "Режим редактирования",
  "Are you sure you want to delete this release?": "Вы уверены, что хотите удалить эту версию?",
  "Form only": "Только форма",
  "Visual": "Визуально",
  "Tags": "Теги",
  "Sort by date": "Сортировка по дате",
  "First published date": "Сперва опубликованые даты",
  "Remove": "Убрать",
  "Alternative versions": "Альтернативные версии",
  "Search for the content group of this story.": "Поиск группы контента этой истории.",
  "Shortcut": "Сокращение",
  "Pin as shortcut in the mini-browser": "Закрепить сокращение в мини-браузере",
  "Current": "Текущий",
  "New release": "Новая версия",
  "Skip this step": "Пропустить этот шаг",
  "Move": "Переместить",
  "Next step": "Следующий шаг",
  "We have already done that for you. Open the entry \"Home\" below to play around.": "Мы уже сделали это для вас. Откройте страницу \"Домой\" ниже, чтобы попробовать.",
  "Create a demo page": "Создать демо страницу",
  "Create a new folder": "Создать новую папку",
  "Create your first folder": "Создайте свою первую папку",
  "and define a new content type during the folder set-up.": "и задайте новый тип контента во время настройки папки.",
  "Create your first entry": "Создайте свою первую запись",
  "Create entry": "Создать запись",
  "and define its fields by building its schema so you can fill it with content.": "и задайте ее поля, создав схему, чтобы вы могли наполнить ее содержимым.",
  "Will be released at": "Будет выпущен на",
  "Show only items from this release": "Показать элементы из этой версии",
  "Has been published at": "Была опубликована на",
  "Last deployment": "Последнее развертывание",
  "This branch has never been deployed": "Эта ветка еще не была развернута",
  "Release now": "Выпустить сейчас",
  "Open preview": "Открыть предосмотр",
  "Deploy from source": "Выполнить развертывание из источника",
  "You are seeing deleted items": "Вы видите удаленные элементы",
  "Name (desc)": "Имя (по убыванию)",
  "Default sorting": "Сортировка по умолчанию",
  "Name (asc)": "Имя (по возрастанию)",
  "Slug (desc)": "Ярлык (по убыванию)",
  "releases": "версии",
  "Slug (asc)": "Ярлык (по возрастанию)",
  "Created at": "Создано",
  "Updated at": "Обновлено",
  "Deleted at": "Удалено",
  "Are you sure you want to unpublish this item(s)?": "Вы уверены, что хотите снять с публикации этот элемент(ы)?",
  "The items have been updated!": "Элементы были обновлены!",
  "Are you sure you want to publish this item(s)?": "Вы уверены, что хотите опубликовать этот элемент(ы)?",
  "Are you sure you want to restore this item(s)?": "Вы уверены, что хотите восстановить этот элемент(ы)?",
  "Something went wrong restoring some items": "Что-то пошло не так при востановлении элементов",
  "Something went wrong updating item(s)": "Что-то пошло не так при обновлении элементов",
  "No tools installed on this space": "Нет установленых иструментов в этой области",
  "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.": "Нельзя просмотривать удаленные элементы. Выберите элементы и восстановите их, чтобы просматривать",
  "The content has been released!": "Этот контент был выпущен!",
  "Do you really want to copy the content of the default language to the current and replace the existing field value?": "Вы уверены, что хотите скопировать контент из языка по умолчанию и заменить текущее значение поля?",
  "Default language": "Язык по умолчанию",
  "Install from the app store": "Установить из центра приложений",
  "Draft updated at": "Черновик обновлен",
  "Never": "Никогда",
  "Published at": "Опубликовано",
  "Latest workflow changes": "Последние изменения рабочей области",
  "Last author": "Последний автор",
  "None": "Ничего",
  "Workflow stage": "Стадия рабочего окружения",
  "set by": "установлено",
  "Assigned to": "Привязано к",
  "Update": "Обновить",
  "Comments": "Комментарии",
  "Load older comments": "Загрузить более ранние комментарии",
  "Edit": "Редактировать",
  "Workflow stage and assignments": "Стадия рабочего окружения и привязки",
  "Add a comment": "Добавить комментарий",
  "Assign to": "Привязать к",
  "Notify users via email": "Уведомить пользователей по email",
  "Submit": "Отправить",
  "Lambda Function": "Lambda функция",
  "Task type": "Тип задачи",
  "Webhook": "Вебхук",
  "The payload of the request contains the task and the space id.": "Полезная нагрузка запроса содержит задачу и идентификатор пространства.",
  "Lambda Function (coming soon)": "Lambda функция (скоро)",
  "Provide the endpoint where you want to send a POST request.": "Укажите точку входа, куда хотите отправлять POST запрос.",
  "Protected variable": "Защищеная переменая",
  "Function code": "Код функции",
  "For example:": "К примеру:",
  "Ok": "Ок",
  "Are you sure you want to delete this task?": "Вы уверены, что хотите удалить эту задачу?",
  "Last execution": "Последнее выполнение",
  "Currently running": "Запущены сейчас",
  "Executed successfully!": "Успешное выполнение!",
  "Execute": "Выполнить",
  "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.": "Выберите XML для программного перевода, такого как SDL Trados Studio или JSON для программного перевода, такого как LingoHub.",
  "Autosave enabled?": "Автосохранение включено?",
  "Empty": "Пусто",
  "Choose a compatible XML or JSON generated from the export.": "Выберите совместимый XML или JSON, сгенерированный из экспорта.",
  "Desktop": "ПК",
  "Tablet": "Планшет",
  "Tag": "TaТегg",
  "Mobile": "Мобильный",
  "Select": "Выбрать",
  "Content type value": "Значение типа поля",
  "Component": "Компонент",
  "Assigned to me only": "Привязано только ко мне",
  "In folder": "В папке",
  "element": "элемент",
  "Search in current folder only": "Искать только в текущей папке",
  "No results found": "Ничего не найдено",
  "Current version": "Текущая версия",
  "Start typing to search": "Начните писать, что искать",
  "Confirming invitation": "Принять приглашение",
  "Please wait a couple of seconds": "Пожалуйста, подождите несколько секунд",
  "Unknown author": "Неизвестный автор",
  "You are now a member of the organisation": "Теперь вы член этой организации",
  "Go to spaces": "Перейти к областям",
  "Invitation confirmed!": "Приглашение принято!",
  "Please login first and then click the invitation link again.": "Сначала войдите, а потом нажмите на ссылку приглашения снова.",
  "Go to login": "Перейти ко входу",
  "Login required.": "Требуется логин.",
  "Your invitation is not valid anymore.": "Ваше приглашение больше не действует.",
  "Please upgrade your Storyblok space. You have": "Улучшите свою Storyblok область. У вас есть",
  "Something went wrong.": "Что-то пошло не так.",
  "collaborator(s) and your": "сотрудник(ов) и ваш",
  "Please contact your Storyblok space owner. You have": "Свяжитесь с владельцем области Storyblok. У вас есть",
  "is over.": "закончилось.",
  "Just a moment. A background task is still running.": "Подождите секунду. Задача выполняется в фоновом режиме.",
  "The Storyblok app has been updated!": "Storyblok приложение было обновлено!",
  "Please reload the window to get the newest version.": "Обновите вкладку, чтобы воспользоваться новой версией.",
  "Reload window": "Обновить вкладку",
  "Manage": "Кправлять",
  "Toggle assistance mode": "Переключить режим ассистента",
  "Assisted spaces": "Вспомогательные пространства",
  "Logging in": "Залогинен в",
  "Sales": "Продажи",
  "I have read and agree to the": "Я прочитал и согласен",
  "Logged in as": "Вы вошли как",
  "Catalogue": "Каталог",
  "Initiating space": "Инициализация области",
  "Configuration": "Конфигурация",
  "There was an error confirming your account. Please try again.": "Произошла ошибка при подтверждении вашего аккаунта. Попробуйте еще раз.",
  "Resend confirmation": "Переотправить подтверждение",
  "Confirmed successfully!": "Успешно подтверждено!",
  "You have unsaved changes on this content item. Do you want to discard your changes?": "У вас есть несохраненные изменения. Вы уверены, что хотите отменить изменения?",
  "No": "Нет",
  "To continue confirm that you have read and agree to the Terms and Privacy Policy.": "Для продолжения подтвердите, что вы прочитали и согласны с Условиями и Политикой конфиденциальности.",
  "Yes": "Да",
  "Invitation sent!": "Приглашение отправлено!",
  "Shortcuts: Esc for No, Enter for Yes": "Сокращение: Esc для Нет, Enter для Да",
  "Usertype": "Тип пользователя",
  "The user has been invited to your organisation and will be added once confirmed.": "Пользователь был приглашен в вашу организацию и будет добавлен после подтверждения.",
  "Normal": "Обычный",
  "Member": "Участник",
  "Provide the 15 digit ID": "Укажите 15-ти значный идентификатор",
  "Is sandbox user?": "Пользователь песочницы?",
  "Owner: Can manage users and define owners": "Владелец: Может управлять или указывать пользователей",
  "Admin: Can manage users": "Администратор: Может управлять пользователями",
  "Member: Can not manage users": "Участник: Не может управлять пользователями",
  "Firstname": "Имя",
  "Disable": "Отключить",
  "Lastname": "Фамилия",
  "Are you sure you want to disable this user?": "Вы уверены, что хотите отключить пользователя?",
  "It seems you do not have any": "Похоже, у вас ничего нет",
  "Enable": "Включить",
  "Type in all emails of the users you want to invite separated by a new line.": "Введите все электронные письма пользователей, которых вы хотите пригласить, отделив их новой строкой.",
  "Invite others": "Пригласить еще",
  "yet.": "еще.",
  "Send": "Отправить",
  "Done!": "Готово!",
  "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).": "Ваше приглашение было отправлено! Как только пользователи зарегистрируются вы сможете добавить их в качестве сотрудников в свою область(и).",
  "Please enter at least one email": "Ввеедите не меньше одного email",
  "Invite more people": "Пригласить еще людей",
  " is not a valid email": " это некорректный email",
  "from": "из",
  "Target": "Цель",
  "Asset": "Ресурс",
  "Current window": "Текущее окно",
  "Get started": "Начать",
  "New window": "Новое окно",
  "terms of use": "условия использования",
  "Signup": "Регистрация",
  "By clicking \"Signup\" you accept the": "Нажимая \"Регистрация\" вы принимаете",
  "Switch to login": "Перейти ко входу",
  "Forgot password?": "Забыли пароль?",
  "Already have an account?": "Уже есть аккаунт?",
  "No account yet?": "Еще нет аккаунта?",
  "Signup here": "Зарегистрироваться",
  "Login": "Войти",
  "Resend": "Отправить еще раз",
  "confirmation email": "подтверждение email",
  "Send password reset link": "Отпраить ссылку на восстановление пароля",
  "Imprint": "Выходные данные",
  "Privacy policy": "Политика конфиденциальности",
  "Are you a developer?": "Вы разработчик?",
  "Choose no if you want to join an existing project": "Выберите нет, если хотите присоединиться к существующему проекту",
  "No, I am not a dev": "Нет, я не разработчик",
  "Yes, I am a dev": "Да, я разработчик",
  "Choose your own adventure": "Выберите собственное приключение",
  "Join an existing space": "Войти в существующую область",
  "What would you do like next?": "Что дальше?",
  "You are almost there": "Вы почти у цели",
  "Success!": "Успешно!",
  "Insert the email of your space admin to let them add you as a collaborator of the space": "Вставьте email администратора вашей области, чтобы он добавил вас как работника в эту область",
  "I received the email": "Я получил письмо",
  "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.": "Вы получите уведомление по электронной почте, как только администратор добавит вас в качестве сотрудника. Нажмите на кнопку ниже, чтобы продолжить.",
  "It seems that the authentification code is wrong.": "Похоже, что код аутентификации неверен.",
  "My account": "Мой аккаунт",
  "Please check the password confirmation.": "Проверьте подтверждение пароля.",
  "You are logged in via a third party authentication provider.": "Вы вошли через стороннего провайдера авторизации.",
  "Profile picture": "Изображение профиля",
  "Username": "Имя пользователя",
  "Your Storyblok ID for adding you as a collaborator to another project is": "Ваш Storyblok идентификатор для добавления вас как сотрудника в другую область",
  "Recommended: 500px x 500px (JPG or PNG)": "Рекомендуемый размер: 500px x 500px (JPG или PNG)",
  "Phone number": "Номер телефона",
  "Your timezone": "Ваш часовой пояс",
  "Your language": "Вас язык",
  "Current password": "Текущий пароль",
  "Insert your current password if you changed your username, email, phone number, password or security settings": "Вставьте ваш текущий пароль, если вы меняете email, номер телефона, пароль или настройки безопасности",
  "New Password": "Новый пароль",
  "Do you want to change your current password?": "Вы уверены, что хотите изменить текущий пароль?",
  "Password confirmation": "Подтверждение пароля",
  "Security Settings": "Настройки безопасности",
  "How do you want to login?": "Как выхотите входить?",
  "Password only": "Только с паролем",
  "Two factor authentication via SMS": "Двухфакторная авторизация через СМС",
  "Personal access tokens": "Личный токен доступа",
  "Two factor authentication via Email": "Двухфакторная авторизация через Email",
  "Storyblok Management API": "Storyblok API управления",
  "Please copy this api key now. It will be visible only once.": "Скопируйте этот api ключ сейчас. Он будет видим только разово.",
  "Tokens that have been generated to access the": "Токены были сгенерированы для доступа к",
  "Generate new Token": "Сгенерировать новый токен",
  "Personal access tokens work like ordinary OAuth access tokens.": "Персональные токены доступа работают как обычные токены доступа OAuth.",
  "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.": "Их можно использовать для аутентификации, чтобы получить полный доступ к API управления программным способом, и НИКОГДА не нужно публиковать его.",
  "Privacy": "Конфиденциальность",
  "Show username instead of email as collaborator": "Показывать имя пользователя вместо электронной почты в качестве сотрудника",
  "Privacy Setting": "Настройки конфиденциальности",
  "Download in German": "Скачать на немецком",
  "Download in English": "Скачать на английском",
  "Data processing agreement": "Соглашение об обработке данных",
  "Read more about our": "Прочитать больше о нашей",
  "Account deletion": "Удаление аккаунта",
  "privacy policy here": "политике конфиденциальности здесь",
  "Yes, delete my account": "Да, удалить мой аккаунт",
  "Do you want to delete your account?": "Вы уверены, что хотите удалить ваш аккаунт?",
  "Do you really want to delete your account? Type \"delete me\" and click confirm.": "Вы уверены, что хотите удалить ваш аккаунт? Напишите \"delete me\" и нажмите подтвердить.",
  "User has been updated": "Пользователь был обновлен",
  "Not found": "Не найдено",
  "Please insert the code we sent to ": "Вставьте полученный код ",
  "Add user": "Добавить пользователя",
  "It seems that you do not have access to this page.": "Похоже у вас нет доступа к этой странице.",
  "Create a new organization": "Создать новую организацию",
  "Organisation name": "Имя организации",
  "Create org": "Создать организацию",
  "SO Settings": "Настройки SO",
  "Whitelabeling": "Чистая маркировка",
  "Add SSO url": "Добавить SSO url",
  "Url to the editor": "Url для редактора",
  "Provide the full url like": "Задайте полный url",
  "Logo-Url": "ссылка на логотип",
  "Provide the full url to the logo like": "Задайте полный url до логотипа",
  "Not defined": "Не задано",
  "Organization updated successfully": "Организация успешно обновлена",
  "Disabled": "Отключено",
  "Please set your password": "Установите ваш пароль",
  "Set password": "Установить пароль",
  "Password has been set. You can now login.": "Пароль установлен. Теперь вы можете войти.",
  "Thank you": "Спасибо",
  "Please confirm your billing information": "Подтвердите вашу платежную информацию",
  "Login failed. The login token may expired. Please try again.": "При входе произошла ошибка. Токен входа истек. Попробуйте еще раз.",
  "Please enter all required information": "Введите всю требуемую информацию",
  "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.": "Мы стараемся обновлять вашу платежную информацию для счетов. Подтвердите, что приведенная ниже информация верна или измените ее.",
  "One last thing before you can comment": "Последнее, что вы можете прокомментировать",
  "Profile picture (optional)": "Изображение профиля (опционально)",
  "Are you sure you want to delete this item?": "Вы уверены, что хотите удалить этот элемент?",
  "Help other collaborators to identify you better by providing your name and a profile picture.": "Помогите другим сотрудникам правильно вас узнавать, добавьте имя и изображение профиля.",
  "Are you sure you want to delete this item(s)?": "Вы уверены, что хотите удалить этот элемент(ы)?",
  "Loading user": "Загрузка пользователя",
  "You are in a demo space.": "Вы вошли в демо область.",
  "Submit to App-Store": "Отправить в центр приложений",
  "Browse apps": "Выбрать приложения",
  "Submit to App-Directory": "Отправить в центр приложений",
  "Active Subscriptions": "Активные подписки",
  "Total revenue": "Общий доход",
  "Finances": "Финансы",
  "Hi there!": "Всем привет!",
  "Choose to": "Выбрать для",
  "Perks": "Надбавки",
  "Team": "Команда",
  "Entering Partner Portal": "Вход на портал парнеров",
  "Signup as Partner": "Зарегистрироваться как партнер",
  "You are now unsubscribed.": "Теперь вы отписались.",
  "Seems that you do not have any tags yet.": "Похоже, что у вас еще нет тегов.",
  "Create your first space": "Создайте свою первую область",
  "Install link": "Ссылка на установку",
  "Name of the app": "Имя приложения",
  "Id/Slug of the app": "Ид/Ярлык приложения",
  "Allowed characters are letters, numbers and -.": "Допустимы символы, буквы, цифры и -.",
  "Oauth2 settings": "Настройки Oauth2",
  "Client id": "Идентификатор клиента",
  "Secret": "Секретный ключ",
  "Url to your app": "Url на ваше приложение",
  "Oauth2 callback url": "Oauth2 callback ссылка",
  "Field types": "Типы полей",
  "Select the Field-Type(s) that you would like to include in this app": "Выберите типы полей, которые хотите включить в приложение",
  "Images": "Изображения",
  "Screenshot (minimum 1000px)": "Скриншот (минимум 1000px)",
  "Icon (1024x1024px)": "Иконка (1024x1024px)",
  "Sidebar Icon (white transparent SVG)": "Иконка бокового меню (white transparent SVG)",
  "Your website": "Вас сайт",
  "Url to your website": "Ссылка на ваш сайт",
  "Your name": "Ваше имя",
  "Video (optional)": "Видео (опциаонально)",
  "Url to Youtube video": "Ссылка на Youtube видео",
  "Intro": "Вступление",
  "Short intro about what is your app about": "короткое вступление для чего ваше приложение",
  "Attention! The deletion of this app will also delete all installations.": "Внимание! Удаление этого приложения удалит все устаноки.",
  "Delete this app": "Удалить это приложение",
  "Uninstall": "Удалить",
  "Requires plan": "Требуемый тариф",
  "Try out in trial mode": "Попробуйте на пробном периоде",
  "Approve app": "Утвердить приложение",
  "Website": "Сайт",
  "Last update": "Последнее обновление",
  "App content": "Контент приложения",
  "Field-Type/UI Extension": "Типы полей/Расширения интерфейса",
  "App submission": "Отправка приложения",
  "By committing your app the Storyblok app directory you accept the": "Передав свое приложение в каталог приложений Storyblok, вы принимаете",
  "App Directory Agreement": "Соглашение центра приложений",
  "The review process take usually 2-3 days and you will get updated via email once the app is available in the app directory.": "Процесс рассмотрения обычно занимает 2-3 дня, и вы получите обновление по электронной почте, как только приложение будет доступно в каталоге приложений.",
  "Confirm submission": "Подтвердить отправку",
  "References": "Исходники",
  "Unselect": "Снять выделение",
  "Clear trashcan": "Очистить корзину",
  "Move users to org": "Переместить пользователей в организацию",
  "Is content type": "Это тип контента",
  "Add fields by dragging them to the tab.": "Добавьте поля, перетаскивая их во вкладку.",
  "Drag and drop the field to the tab name to add it here. All fields that are not placed in custom tabs will be visible in the general tab. To remove the general tab place all fields in custom tabs.": "Перетащите поле на имя вкладки, чтобы добавить его туда. Все поля, не размещенные на пользовательских вкладках, будут видны на вкладке «Общие». Чтобы удалить вкладку «Общие», переместите все поля в пользовательские вкладки.",
  "Manage tab": "Управлять вкладками",
  "Rename": "Переименовать",
  "Move to right": "Переместить вправо",
  "Move to left": "Переместить влево",
  "Hide empty option": "Скрыть пустые опции",
  "Restrict to content type": "Ограничить тип контента",
  "Enable email field": "Включить поле email",
  "Enable asset selection": "Включить выбор ресурсов",
  "Enable anchor field on internal link": "Включить поле якоря для внутренних ссылок",
  "Minimum": "Минимум",
  "Maximum": "Максимум",
  "Define anchor": "Задать якорь",
  "Choose to customize your experience": "Выберите, чтобы настроить свой опыт",
  "First name": "Имя",
  "Last name": "Фамилия",
  "Job function": "Должность",
  "Marketing": "Маркетинг",
  "Information Technology": "Информационные технологии",
  "Development/Engineering/Programming": "Разработка/Инжиниринг/Программирование",
  "Human Resources": "Человеческие ресурсы",
  "Procurement": "Закупки",
  "Security": "Безопасность",
  "Other": "Другое",
  "Business area": "Сфера бизнеса",
  "Accounting": "Учет",
  "Marketing and Advertising": "Маркетинг и реклама",
  "Automotive": "Автомобили",
  "Agriculture": "Сельское хозяйство",
  "Chemicals": "Химикаты",
  "Construction": "Строительство",
  "Consulting": "Консультации",
  "Consumer Products": "Потребительские товары",
  "Education": "Образование",
  "Finance": "Финансы",
  "Food and Beverage": "Еда и напитки",
  "Gaming": "Развлечения",
  "Government": "Правительство",
  "Healthcare": "Здравоохранение",
  "Hospitality": "Гостевой бизнес",
  "Insurance": "Страхование",
  "Legal": "Юриспруденция",
  "Manufacturing": "Производство",
  "Media": "Медиа",
  "Oil and Energy": "Энергетика",
  "Pharmaceutical": "Фармацевтика",
  "Real Estate": "Недвижимость",
  "Retail": "Продажи",
  "Sports": "Спорт",
  "Technology": "Технологии",
  "Telecommunications": "Телекоммуникации",
  "Transportation": "Транспортировка",
  "Utility": "Помощь",
  "* Required fields": "* Обязательные поля",
  "Continue": "Продолжить",
  "Personal settings": "Личные настройки",
  "How would you describe your role?": "Как можете описать вашу роль?",
  "I am a content editor": "Я редактор контента",
  "I am a developer or administrator": "Я разработчик или администратор",
  "Add space to organization": "Добавить область к организации",
  "Add space": "Добавить область",
  "Unlink": "Разъединить",
  "Create your first app": "Создайте ваше первое приложение",
  "No invoices found": "Счетов не найдено",
  "Space": "Область",
  "Invoice ID": "Идентификатор счета",
  "Amount": "Колличество",
  "# of Spaces": "# областей",
  "Revenue": "Доход",
  "MRR": "Ежемесячный доход",
  "Nr. of spaces": "Номер области",
  "Active subscriptions": "Активные подписки",
  "Total revenue share per month": "Общая доля дохода за месяц",
  "Welcome to the partner portal of Storyblok! We are excited to have you on board!": "Добро пожаловать на партнерский портал Storyblok! Мы рады, что вы на борту!",
  "App type": "Тип приложения",
  "Sidebar": "Боковое меню",
  "Fieldtype(s)": "Тип(ы) полей",
  "Add an existing space": "Добавить в существующую область",
  "Member: Can manage spaces and apps": "Пользователь: Может управлять областями и приложениями",
  "Owner: Can manage users, spaces, apps, partner account settings and see finances": "Владелец: Может управлять пользователями, областями, приложениями, настройками партнерского аккаунта и видеть финансы",
  "Stripe connect": "Подключить Stripe",
  "Connect your Stripe account to receive your revenue share each month.": "Connect your Stripe account to receive your revenue share each month.",
  "Partner details": "Partner details",
  "Define your business address and company information. * Required fields": "Define your business address and company information. * Required fields",
  "Billing email address": "Billing email address",
  "VAT number": "VAT number",
  "Company number": "Company number",
  "Bank information (for revenue share of enterprise plans)": "Bank information (for revenue share of enterprise plans)",
  "Plan": "Plan",
  "My spaces": "My spaces",
  "Field-types": "Field-types",
  "Partner Agreement": "Partner Agreement",
  "Current story object": "Current story object",
  "Partner portal": "Partner portal",
  "Show all": "Show all",
  "Show favorites only": "Show favorites only",
  "User ID": "User ID",
  "Single role": "Single role",
  "Multiple roles": "Multiple roles",
  "Individual permissions": "Individual permissions",
  "Organization": "Organization",
  "Maintenance mode (When enabled only admins can edit content)": "Maintenance mode (When enabled only admins can edit content)",
  "Storage": "Storage",
  "Store on the Storyblok S3 bucket": "Store on the Storyblok S3 bucket",
  "If unchecked the backup will be stored on your own S3 backup.": "If unchecked the backup will be stored on your own S3 backup.",
  "Preferred backup time": "Preferred backup time",
  "AWS Role ARN": "AWS Role ARN",
  "\"Restore now\" creates a new space with the restore date in the space name.": "\"Restore now\" creates a new space with the restore date in the space name.",
  "Your Unique Subdomain": "Your Unique Subdomain",
  "Your unique subdomain for your rendering service project with Storyblok. Replace this with your \"Location (default environment)\" to get started.": "Your unique subdomain for your rendering service project with Storyblok. Replace this with your \"Location (default environment)\" to get started.",
  "Publish translations individually (Beta)": "Publish translations individually (Beta)",
  "ATTENTION! When enabling, all languages needs to be published by going to each content item, selecting the language and clicking the Publish button.": "ATTENTION! When enabling, all languages needs to be published by going to each content item, selecting the language and clicking the Publish button.",
  "Beta version: Does not work yet together with releases and duplicating content.": "Beta version: Does not work yet together with releases and duplicating content.",
  "I have a developer": "I have a developer",
  "I am a developer": "I am a developer",
  "I want to talk": "I want to talk",
  "Thanks!": "Thanks!",
  "We received your request!": "We received your request!",
  "Invites sent!": "Invites sent!",
  "The invites got sent successfully.": "The invites got sent successfully.",
  "Invite your developer(s) to Storyblok so that they can create a project for you.": "Invite your developer(s) to Storyblok so that they can create a project for you.",
  "Email addresses": "Email addresses",
  "Send invites": "Send invites",
  "I need a developer": "I need a developer",
  "Inform us your project requirements to get offers from developers of our partner network.": "Inform us your project requirements to get offers from developers of our partner network.",
  "I want to...": "I want to...",
  "migrate a website or app to Storyblok": "migrate a website or app to Storyblok",
  "create a new website or app": "create a new website or app",
  "make an existing website or app editable in Storyblok": "make an existing website or app editable in Storyblok",
  "Budget": "Budget",
  "Less than $ 2.000": "Less than $ 2.000",
  "$ 2.000 to 5.000": "$ 2.000 to 5.000",
  "$ 5.000 to 20.000": "$ 5.000 to 20.000",
  "More than $ 20.000": "More than $ 20.000",
  "Project details": "Project details",
  "Switch to a developer account to create spaces for development of websites and apps. You can switch back to a content editor account in the my account section: "Switch to a developer account to create spaces for development of websites and apps. You can switch back to a content editor account in the my account section later.": later.",
  "Switch": "Switch",
  "Get in touch with someone at the Storyblok team to get a demo or discuss your requirements.": "Get in touch with someone at the Storyblok team to get a demo or discuss your requirements.",
  "Company name": "Company name",
  "Message": "Message",
  "Send message": "Send message",
  "Do you want to assign the space to your organization?": "Do you want to assign the space to your organization?",
  "No (for private spaces)": "No (for private spaces)",
  "Allow managing tags": "Allow managing tags",
  "Allow editing datasource keys": "Allow editing datasource keys",
  "Deny access to image editor": "Deny access to image editor",
  "Force user to create release": "Force user to create release",
  "Hide content if unauthorized": "Hide content if unauthorized",
  "Hide folders if unauthorized": "Hide folders if unauthorized",
  "Add branches the user should have the right to deploy to (acts as whitelist). If no item is selected the user has rights to deploy to all branches.": "Add branches the user should have the right to deploy to (acts as whitelist). If no item is selected the user has rights to deploy to all branches.",
  "Component/content-type permissions": "Component/content-type permissions",
  "Add the components or content types the user should not be able to select (acts as blacklist).": "Add the components or content types the user should not be able to select (acts as blacklist).",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Похоже, у вас еще нет доступа ни к одной области. Свяжитесь с администратором вашей организации, чтобы он добавил вас как работника.",
  "Start by selecting a space in the sidebar.": "Start by selecting a space in the sidebar.",
  "Details": "Details",
  "Your current plan is ": "Your current plan is ",
  "Pressing the button below will cancel your current subscription and remove all collaborators.": "Pressing the button below will cancel your current subscription and remove all collaborators.",
  "Cancel subscription": "Cancel subscription",
  "The starter plan is our free plan, so nothing we can cancel for you. If you are still receiving charges, let us know in our live-chat!": "The starter plan is our free plan, so nothing we can cancel for you. If you are still receiving charges, let us know in our live-chat!",
  "We are really sorry to see you go, but would love to understand why.": "We are really sorry to see you go, but would love to understand why.",
  "Set following stage after published": "Set following stage after published",
  "Attention! There are ": "Attention! There are ",
  " reference(s). Click to show.": " reference(s). Click to show.",
  "Undo (Ctrl+Z)": "Undo (Ctrl+Z)",
  "Redo (Ctrl+Y)": "Redo (Ctrl+Y)",
  "This block is not available any more.": "This block is not available any more.",
  "Go back to the root": "Go back to the root",
  "Please choose a release or create a new one to make your content changes.": "Please choose a release or create a new one to make your content changes.",
  "First published date (asc)": "First published date (asc)",
  "First published date (desc)": "First published date (desc)",
  "Published date (asc)": "Published date (asc)",
  "Published date (desc)": "Published date (desc)",
  "Tag list": "Tag list",
  "First published at": "First published at",
  "Translated name": "Translated name",
  "You can create a new tag at the config section of a content item.": "You can create a new tag at the config section of a content item.",
  "Assigned items": "Assigned items",
  "User dialog": "User dialog",
  "Containing content item": "Containing content item",
  "Containing asset": "Containing asset",
  "Clear all filters": "Clear all filters",
  "Load all": "Load all",
  "The user dialog JSON is invalid.": "The user dialog JSON is invalid.",
  "Edit App": "Edit App",
  "All apps": "All apps",
  "App installed successfully!": "App installed successfully!",
  "New App": "New App",
  "App approved successfully": "App approved successfully",
  "Your app has been submitted sucessfully.": "Your app has been submitted sucessfully.",
  "Please define a name": "Please define a name",
  "Trashcan cleared!": "Trashcan cleared!",
  "Type the domain to move all users with @domain.com to the org with that domain.": "Type the domain to move all users with @domain.com to the org with that domain.",
  "Define a name for the tab": "Define a name for the tab",
  "Are you sure you want to delete this tab?": "Are you sure you want to delete this tab?",
  "Define the anchor id of the link.": "Define the anchor id of the link.",
  "is not a valid email": "is not a valid email",
  "Are you sure that you want to remove this space from the organization?": "Are you sure that you want to remove this space from the organization?",
  "Space has been removed from organization": "Space has been removed from organization",
  "Space added successfully": "Space added successfully",
  "Organization created successfully": "Organization created successfully",
  "Are you sure you want to remove this language?": "Are you sure you want to remove this language?",
  "Are you sure you want to unsubscribe and remove all collaborators?": "Are you sure you want to unsubscribe and remove all collaborators?",
  "Please save the schema of this component first.": "Please save the schema of this component first.",
  "Character limit reached": "Character limit reached",
  "characters remaining": "characters remaining",
  "characters over limit": "characters over limit"
}
