export default {
  "Dashboard": "Панель управления",
  "Back to spaces": "Вернуться к областям",
  "Content": "Содержание",
  "Commerce": "Commerce",
  "Assets": "Ресурсы",
  "Datasources": "Источники данных",
  "Activities": "Активность",
  "Tasks": "Задачи",
  "Components": "Компоненты",
  "Apps": "Приложения",
  "Settings": "Настройки",
  "Subscription": "Подписка",
  "Plugins": "Плагины",
  "Logout": "Выход",
  "Report a problem": "Сообщить о проблеме",
  "Create new space": "Создать новую область",
  "Search spaces...": "Поиск областей...",
  "My organization": "Моя организация",
  "Subscribe": "Оформить подписку",
  "To": "К",
  "From": "От",
  "Apply filter": "Применить фильтр",
  "Filter": "Фильтр",
  "Unknown user": "Неизвестный пользователь",
  "Author": "Автор",
  "Action": "Действие",
  "Date": "Дата",
  "Back": "Назад",
  "Activity Details": "Детали активности",
  "Open": "Открыто",
  "Restore this Story": "Восстановить эту историю",
  "Categories": "Категории",
  "Story": "История",
  "The item has been restored!": "Этот объект восстановлен",
  "All": "Все",
  "Search for apps, discover new field types and add functionalities to your Storyblok project.": "Ищите приложения, открывайте новые типы полей и добавляйте новый функционал в ваш Storyblok проект.",
  "My apps": "Мои приложения",
  "Create new app": "Создать новое приложение",
  "Installed": "Установлено",
  "App Directory": "Каталог приложений",
  "There are no apps in this category.": "В этой категории нет приложений.",
  "Install": "Установить",
  "Choose the space to install this app": "Выберите область для установки этого приложения",
  "Can not move asset folder into folder without permissions.": "Невозможно переместить папку ресурсов в папку, к которой у вас нет прав.",
  "Can not move asset into folder without permissions.": "Невозможно переместить ресурсы в папку, к которой у вас нет прав.",
  "Can not move asset away from folder without permissions.": "Невозможно переместить ресурсы из папки, к которой у вас нет прав.",
  "Define the new name of the folder.": "Задайте имя папки.",
  "Trashbin": "Корзина",
  "Are you sure that you want to delete this folder?": "Вы уверены, что хотите удалить эту папку?",
  "Add": "Добавить",
  "Asset folders are not included in the free plan but you can try them in the": "Папки ресурсов не включены в бесплатный план, но вы можете использовать их в",
  "New folder will be created in": "Новая папка будет создана в",
  "trial period": "пробный период",
  "Can not create asset folder without permission for parent.": "Вы не можете создать папку ресурсов без прав на родительскую папку.",
  "Original": "Оригинал",
  "Done": "Готово",
  "Cancel": "Отмена",
  "Insert": "Вставить",
  "Add Asset(s)": "Добавить ресур(ы)",
  "Close": "Закрыть",
  "items": "Объекты",
  "Delete": "Удалить",
  "Move to folder": "Переместить в папку",
  "Replace": "Заменить",
  "Unselect all": "Снять выделение со всех",
  "Restore": "Восстановить",
  "Tiles": "Плитки",
  "List": "Список",
  "No assets found": "Ресурсов не найдено",
  "Sort": "Сортировка",
  "Default": "По умолчанию",
  "View": "Просмотр",
  "Creation date (asc)": "По дате создания (по возрастанию)",
  "Filename (asc)": "Имя файла (по возрастанию)",
  "Creation date (desc)": "По дате создания (по убыванию)",
  "Filename (desc)": "Имя файла (по убыванию)",
  "Last updated date (asc)": "По дате обновления (по возрастанию)",
  "Last updated date (desc)": "По дате обновления (по убыванию)",
  "You are not allowed to insert this filetype here.": "Вам запрещено вставлять сюда такой тип файла.",
  "This key is already defined": "Такой ключ уже занят",
  "Key is in invalid format": "Ключ имеет неверный формат",
  "Something went wrong uploading some items": "Что-то пошло не так при загрузки некоторых объектов",
  "Please choose a folder in the left sidebar": "Выберите папку в левом сайдбаре",
  "Define the new name of": "Задайте новое имя для",
  "Something went wrong renaming the attribute": "Что-то пошло не так при переименовании атрибута",
  "Be aware! Changing the name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Будьте в курсе! Изменение имени может занять несколько минут, чтобы обновить все объекты. Убедитесь, что ваши редакторы сохранили свою работу и выйдите из редактора.",
  "Define the new name of the component group.": "Задайте имя для группы компонентов.",
  "Save": "Сохранить",
  "Are you sure that you want to delete this component group?": "Вы уверены, что хотите удалить группу компонентов?",
  "Copy": "Копировать",
  "New": "Новый",
  "Move to group": "Переместить в группу",
  "Please choose a component group in the left sidebar": "Выберите группу компонентов в левом сайдбаре",
  "Paste": "Вставить",
  "Add block": "Добавить блок",
  "Creation of a component failed. Maybe it already exists.": "При создании компонента произошла ошибка. Возможно он уже существует.",
  "Are you sure you want to DELETE this component(s)?": "Вы уверены, что хотите УДАЛИТЬ этот компонент(ы)?",
  "new": "новый",
  "Type to search or to create a": "Тип для поиска или создания",
  "Create new": "Создать новый",
  "block": "блок",
  "New Component": "Новый компонент",
  "Updated": "Обновлено",
  "Name": "Имя",
  "Shortcuts: Esc, Control + S": "Сокращение: Esc, Control + S",
  "Next": "Следующий",
  "Define a name": "Задать имя",
  "Save schema": "Сохранить схему",
  "Act as content type (eg. blog-post)": "Задать как тип контента (например, пост блога)",
  "Define": "Задать",
  "Nestable": "Вкладываемые",
  "Technical name": "Техническое имя",
  "Edit field": "Редактировать поле",
  "Config": "Конфигурация",
  "Schema": "Схема",
  "Renaming": "Переименование",
  "Change field name": "Изменить имя поля",
  "Used in the json as component name": "Используется в json имени компонента",
  "Be aware! Changing the technical name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Будьте в курсе! Изменение технического имени может занять несколько минут, чтобы обновить все объекты. Убедитесь, что ваши редакторы сохранили свою работу и выйдите из редактора.",
  "Display name": "Отображаемое имя",
  "Preview template": "Предосмотр шаблона",
  "Screenshot or icon": "Скриншот или иконка",
  "Used in the editor interface only": "Используется только для интерфейса ректора",
  "of this setting": "этого параметра",
  "Read the documentation": "Читать документацию",
  "Load versions": "Загрузить версии",
  "Versions": "Версии",
  "has been added below": "был добавлен ниже",
  "Examples: news_items, body, columns, title, description or call_to_action_btn": "Примеры: news_items, body, columns, title, description or call_to_action_btn",
  "The component has been restored!": "Этот компонент восстановлен!",
  "Do you really want to leave without saving your changes?": "Вы уверены, что хотите уйти без сохранения изменений?",
  "Type": "Тип",
  "Beta": "Бета",
  "Translatable": "Переводимый",
  "Allow empty paragraphs": "Разрешить пустые параграфы",
  "Linktype": "Тип ссылки",
  "Rich-text as default": "Rich-text по умолчанию",
  "Custom type": "Пользовательский тип",
  "Category": "Категория",
  "Section items": "Пункты раздела",
  "Product": "Продукт",
  "Customize toolbar": "Настроить панель инструментов",
  "Toolbar items": "Пункты панели инструментов",
  "Source": "Источник",
  "CSS class options (label/value)": "CSS класс опции (ярлык/значение)",
  "Datasource": "Источник данных",
  "Stories": "Истории",
  "Self": "Свой",
  "Internal datasource": "Внутренний источник данных",
  "Recommended to be checked, as UID is required for automatic link resolving.": "Рекомендуется отметить как UID, это нужно для автоматического разрешения конфликтов ссылок.",
  "Use UID instead of ID": "Использовать UID вместо ID",
  "In case you have a multi-language folder structure you can add the {0} placeholder and the path will be adapted dynamically. Examples: {0}/categories/, {0}/{1}/categories/": "В том случае, если у вас мультиязычная структура папок вы можете добавить в путь ярлык {0} для динамичной генерации. Примеры: {0}/categories/, {0}/{1}/categories/",
  "External JSON": "Внешний JSON",
  "Path to folder of stories": "Путь до папки с историями",
  "Width": "Ширина",
  "URL": "URL",
  "ratio": "соотношение",
  "pixel": "пиксель",
  "Allowed maximum": "Допустимый максимум",
  "Options (name/value)": "Опции (имя/значение)",
  "Component(s)": "Компонент(ы)",
  "Group(s)": "Группа(ы)",
  "Required field(s) (comma separated)": "Требуемое поле(я) (разделенные запятой)",
  "Required": "Требуется",
  "Default asset folder": "Папка ресурсов по умолчанию",
  "Choose an asset folder where the assets should be assigned to.": "Выберите папку ресурсов, к которой нужно привязать эти ресурсы.",
  "With {level} the path will be replaced dynamically using parts of the current slug. Examples: {0}/categories/, {0}/{1}/categories/": "С {уровнем} в пути, который будет динамически заменен используя части текущего ярлыка. Примеры: {0}/categories/, {0}/{1}/categories/",
  "Restrict to folder": "Ограничить папкой",
  "Force folder restriction": "Принудительное ограничение папки",
  "Regex validation": "Regex валидация",
  "Exclude from export": "Исключить из экспорта",
  "export app": "экспортировать приложение",
  "To use with the": "Использовать вместе с",
  "Default value": "Значение по умолчанию",
  "Can be updated by preview window": "Будет обновлено в окне предосмотра",
  "Loading...": "Загрузка...",
  "Item": "Объект",
  "Allow only specific components to be inserted": "Разрешить вставку только определенных компонентов",
  "Restrict to content types": "Ограничить типами контента",
  "Keep original size": "Сохранить оригинальный размер",
  "Force crop": "Принудительная обрезка",
  "Prepend https to url": "Добавить https к url",
  "Height": "Высота",
  "Maximum characters": "Максимум знаков",
  "Disable time selection": "Отключить выбор времени",
  "Description": "Описание",
  "dimensions app": "размеры приложения",
  "Force overwrite by merge action": "Принудительно перезаписать действием слияния",
  "Id/Slug": "Ид/Ярлык",
  "Enable RTL (Right to left)": "Включить RTL (Справа налево)",
  "Autosave": "Автосохранение",
  "API Url": "API Url",
  "Export": "Экспорт",
  "Import/Export": "Импорт/Экспорт",
  "Dimensions": "Размеры",
  "Add Dimension": "Добавить размер",
  "Import": "Импорт",
  "A datasource in Storyblok is a collection of key-value pairs.": "Источник данных в Storyblok это коллекция пар ключ-значение.",
  "Datasources can be used in a schema definition of a component for single or multiple choice options. You can also access": "Источники данных могут использоваться для схемы компонента для одного или нескольких опций выборы. Вам также доступны",
  "datasource entries from the API": "записи источника данных из API",
  "to use them for labels, categories or similar.": "для использования их для ярлыков, категорий или аналогичного.",
  "Unsaved Changes": "Несохраненные изменения",
  "Datasource entries": "Записи источника данных",
  "Datasources are not included in the free plan": "Источники данных не включены в бесплатный тариф",
  "but you can try them in the": "но вы можете воспользоваться ими в",
  "Saved": "Сохранено",
  "Select all": "Выбрать все",
  "The options could not be loaded.": "Параметры не могут быть загружены.",
  "New Datasource": "Новый источник данных",
  "The following component(s) can not be pasted here": "Следующий компонент(ы) не могут быть расположены здесь",
  "Please save first to continue editing child components.": "Сохранитесь, прежде чем редактировать дочерние компоненты.",
  "Enabled?": "Включено?",
  "Asset manager": "Управление ресурсами",
  "Loading": "Загрузка",
  "Upload new": "Загрузить новый",
  "Your file exceeds the maximum filesize limit of": "Ваш файл превышает максимальный размер файла в ",
  "Please reduce the size of your file.": "Уменьшите размер вашего файла.",
  "Alt text": "Alt текст",
  "Base64": "Base64",
  "Original Size": "Оригинальный размер",
  "Image loading failed": "Загрузка изображения не удалась",
  "Quote": "Цитата",
  "Code Block": "Блок кода",
  "Ordered List": "Нумерованный список",
  "Headline 2": "Заголовок 2",
  "Headline 4": "Заголовок 4",
  "Headline 3": "Заголовок 3",
  "Headline 5": "Заголовок 5",
  "Paragraph": "Параграф",
  "Help": "Помощь",
  "Internal link": "Внутренняя ссылка",
  "Show only selected": "Показать только выбранные",
  "more items found": "найдено больше объектов",
  "Invoices": "Счета",
  "Tip: Use Ctrl + S to save": "Совет: Используйте Ctrl + S для сохранения",
  "Input": "Ввод",
  "Publish": "Опубликовать",
  "You are not allowed to edit this plugin but can see the code at Settings/Details.": "Вам не разрешено редактировать этот плагин, но вы можете смотреть код в Настройки/Детали.",
  "Field type preview": "Предосмотр типа поля",
  "Options (key/value)": "Параметры (ключ/значение)",
  "Space Id": "Ид области",
  "Enable local dev mode": "Включить локальный режим разработки",
  "Settings/Details": "Настройки/Детали",
  "Output": "Вывод",
  "for approval to make it available for all users.": "для утверждения, чтобы сделать его доступным для всех пользователей.",
  "Submit the plugin": "Отправить плагин",
  "Code": "Код",
  "You can copy the code of this plugin to create your own plugin.": "Вы можете скопировать код этого плагина, чтобы создать свой собственный.",
  "Assigned spaces": "Привязанные области",
  "If you assign this plugin to a space other developers can also use it in the schema definition. Without assigning it only you can add the plugin to the schemas.": "Если вы привяжите этот плагин к области, то другие разработчики тоже смогут использовать его для определения схемы. Без привязки только вы сможете добавить плагин к схемам.",
  "Attention: All spaces using this plugin will not be able to use it any more if you click delete.": "Внимание: Все области использующие этот плагин больше не смогут его использовать, если вы нажмете «Удалить».",
  "Documentation": "Документация",
  "Danger zone": "Опасная зона",
  "What is a field type plugin?": "Что такое плагин типов полей?",
  "A field type plugin extends the Storyblok editor with your own custom field types.": "Плагин типов полей расширяет редактор Storyblok вашими собственными типами полей.",
  "It is basically a": "Это в основном",
  "The properties that are passed to the field type are:": "Свойства, которые передаются типу поля:",
  "component extended with a few helpers in the window.Storyblok.plugin mixin.": "компонент расширен с помощью нескольких хелперов в window.Storyblok.plugin миксине.",
  "Examples for field types are colorpickers, WYSYWYG editors or meta tags.": "Примеры для таких типов полей, как colorpickers, WYSYWYG редакторы или мета теги.",
  "Uid of the parent component": "Uid родительского компонента",
  "Options parsed from the schema options array": "Параметры получены из массива параметров схемы",
  "Schema options object": "Объект параметров схемы",
  "Current value of the fieldtype": "Текущее значение типа поля",
  "Story id of the current story": "Идентификатор текущей истории",
  "Space id of the current space": "Идентификатор текущей области",
  "Api function to call the delivery api": "Api функция для вызова api доставки",
  "Methods": "Методы",
  "Draft token of the current space": "Черновой токен текущей области",
  "How to call the Storyblok api?": "Как обратиться к Storyblok api?",
  "Should be used to define the initial data of the plugin.": "Должен использоваться для определения начальных данных плагина.",
  "Should be used to initialize the plugin. Examples: Load data from Storyblok or external sources, Load and initialize a WYSIWYG editor.": "Должен использоваться для инициализации плагина. Примеры: Загрузка данных их Storyblok или внешних источников, загружает и инициализирует WYSIWYG редактор.",
  "To pass options that are configurable in the schema definition define the option keys in the \"Input\" box. The values will be available in the this.options object.": "Чтобы передать параметры, которые можно настроить в определении схемы, задайте ключи параметров в поле \"Ввода\". Значения будут доступны в объекте this.options.",
  "How to pass options?": "Как передать параметры?",
  "In field types you can use this.api to get access to the Storyblok delivery api. You can use it for example to build a selectbox of stories.": "В типах полей вы можете использовать this.api, чтобы получить доступ к Storyblok delivery api. К примеру, вы можете использовать это для генерации списка опций из историй.",
  "Folder/Content-item permissions": "Разрешения на папку/объект",
  "Item saved successfully!": "Объект успешно сохранен!",
  "Source of sync": "Источник синхронизации",
  "Preview": "Предосмотр",
  "Preview url": "Url предосмотра",
  "View on Jsfiddle": "Смотреть на Jsfiddle",
  "Download": "Загрузить",
  "Admin": "Администратор",
  "Permissions": "Разрешения",
  "Editor": "Редактор",
  "Advanced Rights": "Расширенные права",
  "Allow saving content": "Разрешить сохранять контент",
  "Allow publishing content": "Разрешить публиковать контент",
  "Allow saving datasources": "Разрешить сохранять источники данных",
  "Allow managing subscription": "Разрешить управлять подпиской",
  "Allow access to ecommerce app": "Разрешить доступ к приложениям электронной коммерции",
  "Deny access to visual composer": "Запретить доступ к визуальному редактору",
  "Field Permissions": "Разрешенные поля",
  "General": "Общие",
  "Allowed path": "Разрешенные пути",
  "Your crawl URL": "URL вашего сканера",
  "Crawler": "Сканер",
  "Enabled": "Включено",
  "Index": "Индекс",
  "Crawl now": "Сканировать сейчас",
  "Information needed to access the search endpoint or to configure the search client.": "Информация, нужная для получения доступа к точке поиска или для конфигурации поискового клиента.",
  "Search Setup Guide": "Руководство по настройке поиска",
  "Your tenant ID": "Идентификатор вашего арендатора",
  "See": "Смотреть",
  "Documents in index": "Документы в индексе",
  "Crawl requested at": "Сканирование запрошено в",
  "Tenant ID": "Идентификатор арендатора",
  "Documents": "Документы",
  "Clear index": "Очистить индекс",
  "Last crawled at": "Последнее сканирование",
  "Crawl has been initiated": "Сканер запущен",
  "In the first 14 days you can try out all Premium plan features!": "В течение 14 дней вы можете пользоваться всеми преимуществами премиум плана!",
  "Index deletion has been initiated": "Удаление индекса запущено",
  "API-Keys": "API ключи",
  "We would love to hear your thoughts about Storyblok on": "Мы хотели бы услышать ваши мысли о Storyblok",
  "Renderer": "Отрисовщик",
  "Backup": "Резервная копия",
  "Users": "Пользователи",
  "Workflow": "Рабочий процесс",
  "Search": "Поиск",
  "Languages": "Языки",
  "This is the page that the frontend-editor opens.": "Это страница, которую открывает редактор интерфейса.",
  "Location (default environment)": "Местоположение (окружение по умолчанию)",
  "Insert your domain/location including the protocol. Example: http://www.example.com/": "Вставьте имя вашего домена включая протокол. Пример: http://www.example.com/",
  "Provide this ID in your support tickets": "Укажите этот идентификатор в своих запросах поддержки",
  "Your space ID": "Идентификатор вашей области",
  "Preview urls": "Url'ы предосмотра",
  "Define multiple domains/locations to quickly switch the preview urls in the story-editor.": "Укажите несколько доменов/мест для быстрого переключения URL-адресов предварительного просмотра в редакторе историй.",
  "Add preview url": "Добавить url предосмотра",
  "Webhooks": "Вебхуки",
  "Story published &amp; unpublished": "История опубликована &amp; неопубликованна",
  "Story saved": "История сохранена",
  "Branch deployed": "Ветка опубликована",
  "Release merged": "Выпуск объединен",
  "Slack integration": "Интеграция со Slack",
  "Loading... You will be redirect to Slack in a few seconds!": "Загрузка... Вы будете перенаправлены на Slack через несколько секунд!",
  "Get notified on your Slack channel if a new Story has been published!": "Отправлять уведомление в ваш Slack канал когда публикуется новая история!",
  "With this integration you can choose a Slack channel where Storyblok posts messages whenever a user publishes new content.": "С этой интеграцией вы сможете выбрать Slack канал, в который Storyblok отправит сообщение о новых публикациях.",
  "Disconnect": "Отключить",
  "Cloud name": "Имя облака",
  "Cloudinary integration": "Интеграция Cloudinary",
  "Api Key": "Api ключ",
  "Branches": "Ветки",
  "Default content type": "Тип контента по умолчанию",
  "Content types": "Типы контента",
  "Name of the branch": "Имя ветки",
  "Branches are not included in the free plan": "Ветки не включены в бесплатный тариф",
  "Duplication": "Дублирование",
  "This is useful if you want to offer your space for other users as a boilerplate or theme.": "Это полезно, если вам нужно предложить вашу область другим пользователям как шаблон или тему.",
  "ATTENTION! Only check this checkbox if you are sure that you want all data of this space available for duplication.": "ВНИМАНИЕ! Отмечая этот пункт вы даете доступ ко всем данным этой области и она становится доступной для дублирования.",
  "Make this space duplicatable by all users": "Сделать эту область дублируемой для всех пользователей",
  "Content ownership": "Владение контентом",
  "Parent ID": "Родительский идентификатор",
  "Parent": "Родитель",
  "Image service": "Сервис изображений",
  "Content ownership client endpoint": "Клиентская конечная точка владения контентом",
  "List of paths to invalidate": "Список путей для инвалидации",
  "Delete this space": "Удалить эту область",
  "Invalidate": "Инвалидировать",
  "Workflow webhooks": "Вебхуки рабочего окружения",
  "Owner": "Владелец",
  "Workflow changed": "Рабочее окружение изменено",
  "Transfer ownership": "Предать владение",
  "Transfer": "Передать",
  "Attention! Transferring the ownership will remove all your rights to this space.": "Внимание! Передавая владение этой областью вы теряете все права на эту область.",
  "The owner needs to add you as a collaborator if you want to have access again.": "Владельцу нужно добавить вас как сотрудника, если вам снова понадобится доступ.",
  "Collaborators": "Работники",
  "Collaborator": "Работник",
  "No user found with this email or username.": "Не найдено пользователей с таким email или ником.",
  "Name of the role": "Имя роли",
  "Role": "Роль",
  "Add a new user to your org": "Добавить нового пользователя в вашу организацию",
  "Advanced rights and roles are not included in the free and basic plan": "Разширенные права и роли не включены в бесплатный и базовый тарифы",
  "Use your Amazon S3 bucket to create backups.": "Используйте ваш Amazon S3 bucket для создания резервных копий.",
  "Backup now": "Сделать резервную копию",
  "Backups content (stories) and compontents": "Создает резервную копию контента(историй) и компонентов",
  "Define your S3-Bucket and AWS-ARN to enable backups.": "Укажите ваш S3-Bucket и AWS-ARN для включения резервного копирования.",
  "Daily backups": "Ежедневное резервное копирование",
  "Define the name of the S3-bucket where you want to store your backups.": "Укажите имя S3-bucket в котором хотите хранить резервные копии.",
  "S3-bucket": "S3-bucket",
  "Activate automatic daily backups": "Активировать ежедневное резервное копирование",
  "1. Read the": "1. Прочитайте",
  "AWS Policy ARN": "Политику AWS ARN",
  "Show setup instructions": "Показать инструкции по настройке",
  "tutorial on how to setup an Amazon IAM role": "руководство по настройке Amazon IAM ролей",
  "2. Create an Amazon IAM role with following access policy document:": "2. Создайте Amazon IAM роль со следующими доступами:",
  "if not done yet.": "если еще не сделали.",
  "The role should have the permission to access and create files on the S3 bucket you defined. You can for example use the following permission policy replacing YOUR_BUCKET with your bucket name:": "Роль должна иметь права на доступ и создание файлов в S3 bucket, который вы указали. Вы можете использовать этот пример заменив YOUR_BUCKET вашем именем:",
  "Restore spaces from backups on your Amazon S3 bucket.": "Восстановить области из S3 bucket.",
  "Backup file": "Файл резервной копии",
  "Show latest backups": "Показать последние резервные копии",
  "Latest five backups": "Последние 5 резервных копий",
  "Restore now": "Восстановить",
  "The settings below only apply if you are using": "Настройки ниже применяются только если вы используете",
  "Attention! \"Restore now\" deletes old data and restores content (stories) and compontents from the backup file.": "Внимание! \"Восстановить\" удаляет старые данные и восстанавливает контент(истории) и компоненты из файла резервной копии.",
  "Rendering service": "Сервис отрисовки",
  "Your domain": "ваш домен",
  "To connect your domain to Storyblok you need to create a CNAME Record pointing to eu-domain.storyblok.com": "Для подключения вашего домена к Storyblok вам нужно создать CNAME запись со значением eu-domain.storyblok.com",
  "Routes": "Маршруты",
  "Add Route": "Добавить маршрут",
  "Please read the": "Пожалуйста прочитайте",
  "Add custom routes to define different page templates.": "Добавить пользовательские маршруты для различных шаблонов страниц.",
  "documentation about internationalization": "документация о интернационализации",
  "before configuring languages.": "перед настройкой язывок.",
  "Add languages to activate field level translations.": "Добавьте языки для активации перевода полей.",
  "Add Language": "Добавить язык",
  "Label": "Ярлык",
  "The invalidation process has been initiated": "Процесс признания недействительным начат",
  "The backup has been initiated": "Начато резервное копирование",
  "Are you sure you want to delete your current content and overwrite it with this backup?": "Вы уверены, что хотите удалить текущий контент и перезаписать его данными из резервной копии?",
  "The restore process has been initiated": "Процесс восстановления запущен",
  "Transfer was not successful. Make sure that the new owner exists.": "Передача владения не удалась. Проверьте существует ли новый владелец.",
  "The collaborator has been added": "Работник добавлен",
  "Please insert an email address": "Вставьте email адреса",
  "Branches sorted successfully!": "Ветки отсортированны!",
  "Create or join a space": "Создайте или войдите в область",
  "Create a new space": "Создать новую область",
  "Play with a demo": "Попробовать с демо",
  "Duplicate a space": "Дублировать область",
  "Join a space": "Войти в область",
  "Create space": "Создать область",
  "Headless (API/SDKs)": "Безголовый (API/SDKs)",
  "what is that?": "Что это значит?",
  "Duplicate space": "Дублировать область",
  "Choose the space for the duplication": "Выбрать область для дублирования",
  "You do not have created any spaces yet.": "у вас еще нет созданных областей.",
  "You can test the editing interface and our visual composer without to write any code on your own.": "Вы можете тестировать визуальный редактор без написания собственного кода.",
  "Create Demo": "Создать демо",
  "Insert the email of your space admin to let them add you as a collaborator of the space.": "Вставьте email вашего администратора области, чтобы дать ему права работника в этой области.",
  "Request access": "Запросить доступ",
  "Email address of space admin": "Email адреса администраторов области",
  "Success! You will get notified once the admin added you as a collaborator.": "Успешно! Вас оповестят, когда администраторы добавят вас как работника.",
  "Available Billing Information": "Доступная платежная информация",
  "No spaces with billing information available": "Нет областей с доступной платежной информацией",
  "Spaces": "Области",
  "Show More": "Показать больше",
  "Apply": "Применить",
  "Show": "Показать",
  "Billing Information of Space": "Платежная информация области",
  "The information below will be applied to the fields of your current subscription process. You will be able to adopt them after applying them.": "Информация ниже будет применена к полям вашего текущего процесса подписки. Вы сможете исправить их после их применения.",
  "Company": "Компания",
  "Country": "Страна",
  "Street / City / ZIP": "Улица / Город / Индекс",
  "Email": "Email",
  "Add or change preview urls": "Добавить или изменить url'ы предосмотра",
  "Your server address": "Адрес вашего сервера",
  "1. Download a preconfigured project": "1. Скачайте настроенный проект",
  "Preferred by our users": "Настроенные нашими пользователями",
  "The downloaded package comes preconfigured with your api token": "Загружаемый пакет включает настройки с вашим api ключом",
  "Tutorial": "Руководство",
  "Other technologies": "Другие технологии",
  "2. Start your server": "2. Запустите ваш сервер",
  "Start the server of the downloaded package and insert your server url here:": "Запустите вас сервер с загруженным пакетом и вставьте ссылку вашего сервера:",
  "Go": "Вперед",
  "FAQ": "ЧАВО",
  "Can I build a full blown website with Storyblok?": "Могу ли я создать полноценный сайт с помощью Storyblok?",
  "Can I create a blog with Storyblok?": "Могу ли я создать блог с помощью Storyblok?",
  "How does Storyblok work?": "Как работает Storyblok?",
  "What is the Storyblok bridge?": "Что такое Storyblok мост?",
  "Allow deploying content": "Разрешить развертывание контента",
  "General permissions": "Общие разрешения",
  "Allow unpublishing content": "Разрешить снятия контента с публикации",
  "Allow deleting content": "Разрешить удаление контента",
  "Allow editing datasource keys & values": "Разрешить редактирование ключей и значений в источниках данных",
  "Allow editing datasource values": "Разрешить редактировать значения в источниках данных",
  "Allow access to the tasks app": "Разрешить доступ к приложения Задачи",
  "Deny moving a story": "Запретить перемещение истории",
  "Deny changing alternates group": "Запретить изменения альтернативных групп",
  "Add languages the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Добавьте языки, к которым пользователь должен иметь доступ (действует как белый список). Если ни один элемент не выбран, то у пользователя есть права на редактирование всего содержимого.",
  "Deny changing the slug of a story": "Запретить изменение ярлыка истории",
  "Add folders or content items the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Добавьте папки или объекты, к которым пользователь должен иметь доступ (действует как белый список). Если ни один элемент не выбран, то у пользователя есть права на редактирование всего содержимого.",
  "Component field permissions": "Разрешения на поля компонента",
  "Datasource permissions": "Разрешения источников данных",
  "Add component fields here to hide them in the interface.": "Добавьте поля компонента здесь, чтобы скрыть их из интерфейса.",
  "Add datasources the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all datasources.": "Добавьте источники данных, к которым пользователь должен иметь доступ (действует как белый список). Если ни один элемент не выбран, то у пользователя есть права на редактирование все источники данных.",
  "Asset Folder Permissions": "Разрешения папки ресурсов",
  "Add asset folders to restrict editing and upload access.": "Добавить папки ресурсов, чтобы ограничить редактирование и доступ к загрузке.",
  "Start by selecting a space in the sidebar or create a new space.": "Начните с выбора области на боковой панели или создайте новую область.",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Похоже, у вас еще нет доступа ни к одной области. Свяжитесь с администратором вашей организации, чтобы он добавил вас как работника.",
  "Welcome!": "Добро пожаловать!",
  "Traffic": "Трафик",
  "Learn more about": "Изучить больше о",
  "Api requests": "Api запросы",
  "Active Plan": "Текущий план",
  "Usage": "Использование",
  "Content activities": "Активность",
  "No billing": "Нет выписок",
  "Change": "Изменить",
  "Billed": "Выписано",
  "No recent changes": "Нет недавних изменений",
  "Choose your plan": "Выбрать план",
  "Recent changes": "Недавние изменения",
  "Custom": "Индивидуальный",
  "Compare": "Сравнить",
  "user": "пользователь",
  "Got a custom plan or coupon code?": "Нужен индивидуальный план или есть код купона?",
  "Custom plan": "Индивидуальный план",
  "Entered plan ids will be validated after pressing subscribe.": "Введенные идентификаторы плана будут применены после нажатия кнопки «Подписаться»..",
  "Coupon code": "Код купона",
  "Entered coupon codes will be validated and applied after pressing subscribe.": "Введенные коды купонов будут применены после нажатия кнопки «Подписаться».",
  "Select seats": "Выбрать места",
  "Confirm subscription": "Подтвердить подписку",
  "Min": "Минимум",
  "Max": "Максимум",
  "By clicking the button below the new subscription will start.": "По нажатию кнопки ниже новая подписка начнет действовать.",
  "Decide payment interval": "Определите интервал оплаты",
  "Change subscription": "Изменить подписку",
  "Monthly": "Месячная",
  "Annually": "Годовая",
  "Define billing information": "Укажите платежную информацию",
  "Email address": "Email адрес",
  "VAT-Number": "номер НДС",
  "Reuse from another space": "Заполнить из другой области",
  "Order number": "Номер заказа",
  "Street": "Улица",
  "City": "Город",
  "Credit or debit card": "Кредитная или дебетовая карта",
  "ZIP": "Индекс",
  "Enter payment information": "Введите информацию о платеже",
  "Update payment information": "Обновить информацию о платеже",
  "Update billing information": "Обновите платежную информацию",
  "Information: Our payment provider validates card information when it is saved. As a result of this process, you may see a temporary authorization for $1 on your statement.": "Информация: Наш провайдер проверяет данные карты при ее сохранении. В результате этого процесса вы можете увидеть временное списание на 1 доллар в своих расходах.",
  "Please provide all billing informations marked as required (*)": "Пожалуйста, предоставьте всю платежную информацию, отмеченную как обязательная (*)",
  "Your selected team sizes are not in the limits of your selected feature set. You can select another feature set to continue.": "Размеры выбранных вами команд не входят в выбранный вами набора функций. Вы можете выбрать другой набор функций, чтобы продолжить.",
  "View invoices": "Смотреть счета",
  "Summary": "Итог",
  "Please provide a credit or debit card": "Пожалуйста, предоставьте кредитную или дебетовую карту",
  "If your entered plan is not correct you will still be able to try it again.": "Если введенный вами план неверен, вы все равно сможете попробовать его снова.",
  "You have entered a custom plan with a special offering and pricing": "Вы ввели индивидуальный план со специальным предложением и ценами",
  "users": "пользователи",
  "VAT reverse charge applies.": "Применяется обратный НДС.",
  "VAT": "НДС",
  "Total": "Всего",
  "The benefits of the coupon code will be applied if available": "Преимущества кода купона будут применяться при наличии",
  "Thanks! You are awesome!": "Спасибо! Вы прекрасны!",
  "We would love to hear what you think about Storyblok.": "Мы хотели бы услышать, что вы думаете о Storyblok.",
  "Chat with us or": "Чат с нами или",
  "your feedback.": "вашу обратную связь.",
  "Tweet": "Твит",
  "Star": "Звезда",
  "Share": "Поделиться",
  "Public access tokens are only for accessing the published version while preview tokens are for accessing the draft version also. Both are read-only tokens.": "окены общего доступа предназначены только для доступа к опубликованной версии, а токены предварительного просмотра - для доступа к черновой версии. Оба являются токенами только для чтения.",
  "Access level": "Уровень доступа",
  "Public": "Публичный",
  "See API-Documentation": "Смотрите документацию к API",
  "Theme": "Тема",
  "Branch": "Ветка",
  "Choose branch": "Выбрать ветку",
  "Create Token": "Создать токен",
  "Color": "Цвет",
  "Define as default stage for new content items": "Установить как значение по умолчанию для новых объектов",
  "Publishing rights": "Publishing rights",
  "Stage transition rules": "Stage transition rules",
  "Allow users to publish or schedule the content": "Allow users to publish or schedule the content",
  "Specific stage(s)": "Specific stage(s)",
  "Next available stages": "Next available stages",
  "All stages": "All stages",
  "All users": "All users",
  "User(s)/Role(s) who can change the stage": "User(s)/Role(s) who can change the stage",
  "to the next available stage": "to the next available stage",
  "Specific user(s)/role(s)": "Specific user(s)/role(s)",
  "Role(s)": "Role(s)",
  "User(s)": "User(s)",
  "Workflow stages": "Workflow stages",
  "See workflow documentation": "See workflow documentation",
  "Create": "Create",
  "Choose an approver": "Choose an approver",
  "Workflow stages sorted successfully!": "Workflow stages sorted successfully!",
  "Are you sure you want to delete this workflow stage?": "Are you sure you want to delete this workflow stage?",
  "Send for approval": "Send for approval",
  "Approval request has been sent successfully!": "Approval request has been sent successfully!",
  "Content items": "Content items",
  "Entry": "Entry",
  "Define schema": "Define schema",
  "Folder": "Folder",
  "You have not defined any schema for this block yet.": "You have not defined any schema for this block yet.",
  "Define presets": "Define presets",
  "Click \"Define schema\" to add the fields you need.": "Click \"Define schema\" to add the fields you need.",
  "No valid fields defined in this section yet.": "No valid fields defined in this section yet.",
  "is already part of another section": "is already part of another section",
  "Translate": "Translate",
  "Choose to delete the values or add the schema keys.": "Choose to delete the values or add the schema keys.",
  "items out of schema": "items out of schema",
  "We have found values which are not part of the schema.": "We have found values which are not part of the schema.",
  "No changes found": "No changes found",
  "Changes": "Changes",
  "Remove all": "Remove all",
  "Select releases to deploy": "Select releases to deploy",
  "What is getting deployed?": "What is getting deployed?",
  "All content that is currently on the source branch and the releases you select.": "All content that is currently on the source branch and the releases you select.",
  "No releases found on the source branch": "No releases found on the source branch",
  "A newer version of this content item has been found in the database.": "A newer version of this content item has been found in the database.",
  "Confirm": "Confirm",
  "Choose the conflict solution": "Choose the conflict solution",
  "Copy over": "Copy over",
  "Opens newer version in a new window to let you copy over your changes.": "Opens newer version in a new window to let you copy over your changes.",
  "Overwrite": "Overwrite",
  "Slug": "Slug",
  "Overwrites newer version with your changes.": "Overwrites newer version with your changes.",
  "Define as root for the folder": "Define as root for the folder",
  "Preset": "Preset",
  "Content type": "Content type",
  "Confirm deletion": "Confirm deletion",
  "Are you sure that you want to delete this item(s)?": "Are you sure that you want to delete this item(s)?",
  "Include associated alternates": "Include associated alternates",
  "Target-Folder": "Target-Folder",
  "Is alternative version of the duplicate?": "Is alternative version of the duplicate?",
  "Duplicate": "Duplicate",
  "Schedule": "Schedule",
  "duplicated": "duplicated",
  "You are not allowed to duplicate this story.": "You are not allowed to duplicate this story.",
  "Open published": "Open published",
  "Send approval": "Send approval",
  "Open draft": "Open draft",
  "Unpublish": "Unpublish",
  "Draft json": "Draft json",
  "Discard changes": "Discard changes",
  "Start sync": "Start sync",
  "Published json": "Published json",
  "Status": "Status",
  "Tools": "Tools",
  "Real path": "Real path",
  "Settings for the folder content": "Settings for the folder content",
  "Disable visual composer": "Disable visual composer",
  "Clone to all": "Clone to all",
  "Deny changing content type": "Deny changing content type",
  "Merge to all": "Merge to all",
  "Dimensions are only available if you are editing a content item in a subfolder.": "Dimensions are only available if you are editing a content item in a subfolder.",
  "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).": "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).",
  "Not created yet": "Not created yet",
  "Create clone": "Create clone",
  "Merge": "Merge",
  "Something went wrong merging the alternate(s)": "Something went wrong merging the alternate(s)",
  "The alternate(s) have been created!": "The alternate(s) have been created!",
  "The alternate(s) have been merged!": "The alternate(s) have been merged!",
  "Add preset": "Add preset",
  "Presets are blocks filled with the content you currently have in the selected block.": "Presets are blocks filled with the content you currently have in the selected block.",
  "Something went wrong creating the alternate(s)": "Something went wrong creating the alternate(s)",
  "The saved presets are shown for all users at the selection of new blocks.": "The saved presets are shown for all users at the selection of new blocks.",
  "Existing presets": "Existing presets",
  "As default": "As default",
  "Release date (optional)": "Release date (optional)",
  "Branches to deploy": "Branches to deploy",
  "When the release gets merged all content will be automatically deployed to the selected branches.": "When the release gets merged all content will be automatically deployed to the selected branches.",
  "Entry configuration": "Entry configuration",
  "Editmode": "Editmode",
  "Are you sure you want to delete this release?": "Are you sure you want to delete this release?",
  "Form only": "Form only",
  "Visual": "Visual",
  "Tags": "Tags",
  "Sort by date": "Sort by date",
  "First published date": "First published date",
  "Remove": "Remove",
  "Alternative versions": "Alternative versions",
  "Search for the content group of this story.": "Search for the content group of this story.",
  "Shortcut": "Shortcut",
  "Pin as shortcut in the mini-browser": "Pin as shortcut in the mini-browser",
  "Current": "Current",
  "New release": "New release",
  "Skip this step": "Skip this step",
  "Move": "Move",
  "Next step": "Next step",
  "We have already done that for you. Open the entry \"Home\" below to play around.": "We have already done that for you. Open the entry \"Home\" below to play around.",
  "Create a demo page": "Create a demo page",
  "Create a new folder": "Create a new folder",
  "Create your first folder": "Create your first folder",
  "and define a new content type during the folder set-up.": "and define a new content type during the folder set-up.",
  "Create your first entry": "Create your first entry",
  "Create entry": "Create entry",
  "and define its fields by building its schema so you can fill it with content.": "and define its fields by building its schema so you can fill it with content.",
  "Will be released at": "Will be released at",
  "Show only items from this release": "Show only items from this release",
  "Has been published at": "Has been published at",
  "Last deployment": "Last deployment",
  "This branch has never been deployed": "This branch has never been deployed",
  "Release now": "Release now",
  "Open preview": "Open preview",
  "Deploy from source": "Deploy from source",
  "You are seeing deleted items": "You are seeing deleted items",
  "Name (desc)": "Name (desc)",
  "Default sorting": "Default sorting",
  "Name (asc)": "Name (asc)",
  "Slug (desc)": "Slug (desc)",
  "releases": "releases",
  "Slug (asc)": "Slug (asc)",
  "Created at": "Created at",
  "Updated at": "Updated at",
  "Deleted at": "Deleted at",
  "Are you sure you want to unpublish this item(s)?": "Are you sure you want to unpublish this item(s)?",
  "The items have been updated!": "The items have been updated!",
  "Are you sure you want to publish this item(s)?": "Are you sure you want to publish this item(s)?",
  "Are you sure you want to restore this item(s)?": "Are you sure you want to restore this item(s)?",
  "Something went wrong restoring some items": "Something went wrong restoring some items",
  "Something went wrong updating item(s)": "Something went wrong updating item(s)",
  "No tools installed on this space": "No tools installed on this space",
  "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.": "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.",
  "The content has been released!": "The content has been released!",
  "Do you really want to copy the content of the default language to the current and replace the existing field value?": "Do you really want to copy the content of the default language to the current and replace the existing field value?",
  "Default language": "Default language",
  "Install from the app store": "Install from the app store",
  "Draft updated at": "Draft updated at",
  "Never": "Never",
  "Published at": "Published at",
  "Latest workflow changes": "Latest workflow changes",
  "Last author": "Last author",
  "None": "None",
  "Workflow stage": "Workflow stage",
  "set by": "set by",
  "Assigned to": "Assigned to",
  "Update": "Update",
  "Comments": "Comments",
  "Load older comments": "Load older comments",
  "Edit": "Edit",
  "Workflow stage and assignments": "Workflow stage and assignments",
  "Add a comment": "Add a comment",
  "Assign to": "Assign to",
  "Notify users via email": "Notify users via email",
  "Submit": "Submit",
  "Lambda Function": "Lambda Function",
  "Task type": "Task type",
  "Webhook": "Webhook",
  "The payload of the request contains the task and the space id.": "The payload of the request contains the task and the space id.",
  "Lambda Function (coming soon)": "Lambda Function (coming soon)",
  "Provide the endpoint where you want to send a POST request.": "Provide the endpoint where you want to send a POST request.",
  "Protected variable": "Protected variable",
  "Function code": "Function code",
  "For example:": "For example:",
  "Ok": "Ok",
  "Are you sure you want to delete this task?": "Are you sure you want to delete this task?",
  "Last execution": "Last execution",
  "Currently running": "Currently running",
  "Executed successfully!": "Executed successfully!",
  "Execute": "Execute",
  "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.": "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.",
  "Autosave enabled?": "Autosave enabled?",
  "Empty": "Empty",
  "Choose a compatible XML or JSON generated from the export.": "Choose a compatible XML or JSON generated from the export.",
  "Desktop": "Desktop",
  "Tablet": "Tablet",
  "Tag": "Tag",
  "Mobile": "Mobile",
  "Select": "Select",
  "Content type value": "Content type value",
  "Component": "Component",
  "Assigned to me only": "Assigned to me only",
  "In folder": "In folder",
  "element": "element",
  "Search in current folder only": "Search in current folder only",
  "No results found": "No results found",
  "Current version": "Current version",
  "Start typing to search": "Start typing to search",
  "Confirming invitation": "Confirming invitation",
  "Please wait a couple of seconds": "Please wait a couple of seconds",
  "Unknown author": "Unknown author",
  "You are now a member of the organisation": "You are now a member of the organisation",
  "Go to spaces": "Go to spaces",
  "Invitation confirmed!": "Invitation confirmed!",
  "Please login first and then click the invitation link again.": "Please login first and then click the invitation link again.",
  "Go to login": "Go to login",
  "Login required.": "Login required.",
  "Your invitation is not valid anymore.": "Your invitation is not valid anymore.",
  "Please upgrade your Storyblok space. You have": "Please upgrade your Storyblok space. You have",
  "Something went wrong.": "Something went wrong.",
  "collaborator(s) and your": "collaborator(s) and your",
  "Please contact your Storyblok space owner. You have": "Please contact your Storyblok space owner. You have",
  "is over.": "is over.",
  "Just a moment. A background task is still running.": "Just a moment. A background task is still running.",
  "The Storyblok app has been updated!": "The Storyblok app has been updated!",
  "Please reload the window to get the newest version.": "Please reload the window to get the newest version.",
  "Reload window": "Reload window",
  "Manage": "Manage",
  "Toggle assistance mode": "Toggle assistance mode",
  "Assisted spaces": "Assisted spaces",
  "Logging in": "Logging in",
  "Sales": "Sales",
  "I have read and agree to the": "I have read and agree to the",
  "Logged in as": "Logged in as",
  "Catalogue": "Catalogue",
  "Initiating space": "Initiating space",
  "Configuration": "Configuration",
  "There was an error confirming your account. Please try again.": "There was an error confirming your account. Please try again.",
  "Resend confirmation": "Resend confirmation",
  "Confirmed successfully!": "Confirmed successfully!",
  "You have unsaved changes on this content item. Do you want to discard your changes?": "You have unsaved changes on this content item. Do you want to discard your changes?",
  "No": "No",
  "To continue confirm that you have read and agree to the Terms and Privacy Policy.": "To continue confirm that you have read and agree to the Terms and Privacy Policy.",
  "Yes": "Yes",
  "Invitation sent!": "Invitation sent!",
  "Shortcuts: Esc for No, Enter for Yes": "Shortcuts: Esc for No, Enter for Yes",
  "Usertype": "Usertype",
  "The user has been invited to your organisation and will be added once confirmed.": "The user has been invited to your organisation and will be added once confirmed.",
  "Normal": "Normal",
  "Member": "Member",
  "Provide the 15 digit ID": "Provide the 15 digit ID",
  "Is sandbox user?": "Is sandbox user?",
  "Owner: Can manage users and define owners": "Owner: Can manage users and define owners",
  "Admin: Can manage users": "Admin: Can manage users",
  "Member: Can not manage users": "Member: Can not manage users",
  "Firstname": "Firstname",
  "Disable": "Disable",
  "Lastname": "Lastname",
  "Are you sure you want to disable this user?": "Are you sure you want to disable this user?",
  "It seems you do not have any": "It seems you do not have any",
  "Enable": "Enable",
  "Type in all emails of the users you want to invite separated by a new line.": "Type in all emails of the users you want to invite separated by a new line.",
  "Invite others": "Invite others",
  "yet.": "yet.",
  "Send": "Send",
  "Done!": "Done!",
  "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).": "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).",
  "Please enter at least one email": "Please enter at least one email",
  "Invite more people": "Invite more people",
  " is not a valid email": " is not a valid email",
  "from": "from",
  "Target": "Target",
  "Asset": "Asset",
  "Current window": "Current window",
  "Get started": "Get started",
  "New window": "New window",
  "terms of use": "terms of use",
  "Signup": "Signup",
  "By clicking \"Signup\" you accept the": "By clicking \"Signup\" you accept the",
  "Switch to login": "Switch to login",
  "Forgot password?": "Forgot password?",
  "Already have an account?": "Already have an account?",
  "No account yet?": "No account yet?",
  "Signup here": "Signup here",
  "Login": "Login",
  "Resend": "Resend",
  "confirmation email": "confirmation email",
  "Send password reset link": "Send password reset link",
  "Imprint": "Imprint",
  "Privacy policy": "Privacy policy",
  "Are you a developer?": "Are you a developer?",
  "Choose no if you want to join an existing project": "Choose no if you want to join an existing project",
  "No, I am not a dev": "No, I am not a dev",
  "Yes, I am a dev": "Yes, I am a dev",
  "Choose your own adventure": "Choose your own adventure",
  "Join an existing space": "Join an existing space",
  "What would you do like next?": "What would you do like next?",
  "You are almost there": "You are almost there",
  "Success!": "Success!",
  "Insert the email of your space admin to let them add you as a collaborator of the space": "Insert the email of your space admin to let them add you as a collaborator of the space",
  "I received the email": "I received the email",
  "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.": "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.",
  "It seems that the authentification code is wrong.": "It seems that the authentification code is wrong.",
  "My account": "My account",
  "Please check the password confirmation.": "Please check the password confirmation.",
  "You are logged in via a third party authentication provider.": "You are logged in via a third party authentication provider.",
  "Profile picture": "Profile picture",
  "Username": "Username",
  "Your Storyblok ID for adding you as a collaborator to another project is": "Your Storyblok ID for adding you as a collaborator to another project is",
  "Recommended: 500px x 500px (JPG or PNG)": "Recommended: 500px x 500px (JPG or PNG)",
  "Phone number": "Phone number",
  "Your timezone": "Your timezone",
  "Your language": "Your language",
  "Current password": "Current password",
  "Insert your current password if you changed your username, email, phone number, password or security settings": "Insert your current password if you changed your username, email, phone number, password or security settings",
  "New Password": "New Password",
  "Do you want to change your current password?": "Do you want to change your current password?",
  "Password confirmation": "Password confirmation",
  "Security Settings": "Security Settings",
  "How do you want to login?": "How do you want to login?",
  "Password only": "Password only",
  "Two factor authentication via SMS": "Two factor authentication via SMS",
  "Personal access tokens": "Personal access tokens",
  "Two factor authentication via Email": "Two factor authentication via Email",
  "Storyblok Management API": "Storyblok Management API",
  "Please copy this api key now. It will be visible only once.": "Please copy this api key now. It will be visible only once.",
  "Tokens that have been generated to access the": "Tokens that have been generated to access the",
  "Generate new Token": "Generate new Token",
  "Personal access tokens work like ordinary OAuth access tokens.": "Personal access tokens work like ordinary OAuth access tokens.",
  "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.": "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.",
  "Privacy": "Privacy",
  "Show username instead of email as collaborator": "Show username instead of email as collaborator",
  "Privacy Setting": "Privacy Setting",
  "Download in German": "Download in German",
  "Download in English": "Download in English",
  "Data processing agreement": "Data processing agreement",
  "Read more about our": "Read more about our",
  "Account deletion": "Account deletion",
  "privacy policy here": "privacy policy here",
  "Yes, delete my account": "Yes, delete my account",
  "Do you want to delete your account?": "Do you want to delete your account?",
  "Do you really want to delete your account? Type \"delete me\" and click confirm.": "Do you really want to delete your account? Type \"delete me\" and click confirm.",
  "User has been updated": "User has been updated",
  "Not found": "Not found",
  "Please insert the code we sent to ": "Please insert the code we sent to ",
  "Add user": "Add user",
  "It seems that you do not have access to this page.": "It seems that you do not have access to this page.",
  "Create a new organization": "Create a new organization",
  "Organisation name": "Organisation name",
  "Create org": "Create org",
  "SO Settings": "SO Settings",
  "Whitelabeling": "Whitelabeling",
  "Add SSO url": "Add SSO url",
  "Url to the editor": "Url to the editor",
  "Provide the full url like": "Provide the full url like",
  "Logo-Url": "Logo-Url",
  "Provide the full url to the logo like": "Provide the full url to the logo like",
  "Not defined": "Not defined",
  "Organization updated successfully": "Organization updated successfully",
  "Disabled": "Disabled",
  "Please set your password": "Please set your password",
  "Set password": "Set password",
  "Password has been set. You can now login.": "Password has been set. You can now login.",
  "Thank you": "Thank you",
  "Please confirm your billing information": "Please confirm your billing information",
  "Login failed. The login token may expired. Please try again.": "Login failed. The login token may expired. Please try again.",
  "Please enter all required information": "Please enter all required information",
  "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.": "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.",
  "One last thing before you can comment": "One last thing before you can comment",
  "Profile picture (optional)": "Profile picture (optional)",
  "Are you sure you want to delete this item?": "Are you sure you want to delete this item?",
  "Help other collaborators to identify you better by providing your name and a profile picture.": "Help other collaborators to identify you better by providing your name and a profile picture.",
  "Are you sure you want to delete this item(s)?": "Are you sure you want to delete this item(s)?",
  "Loading user": "Loading user",
  "You are in a demo space.": "You are in a demo space.",
  "Submit to App-Store": "Submit to App-Store",
  "Browse apps": "Browse apps",
  "Submit to App-Directory": "Submit to App-Directory",
  "Active Subscriptions": "Active Subscriptions",
  "Total revenue": "Total revenue",
  "Finances": "Finances",
  "Hi there!": "Hi there!",
  "Choose to": "Choose to",
  "Perks": "Perks",
  "Team": "Team",
  "Entering Partner Portal": "Entering Partner Portal",
  "Signup as Partner": "Signup as Partner",
  "You are now unsubscribed.": "You are now unsubscribed.",
  "Seems that you do not have any tags yet.": "Seems that you do not have any tags yet.",
  "Create your first space": "Create your first space",
  "Install link": "Install link",
  "Name of the app": "Name of the app",
  "Id/Slug of the app": "Id/Slug of the app",
  "Allowed characters are letters, numbers and -.": "Allowed characters are letters, numbers and -.",
  "Oauth2 settings": "Oauth2 settings",
  "Client id": "Client id",
  "Secret": "Secret",
  "Url to your app": "Url to your app",
  "Oauth2 callback url": "Oauth2 callback url",
  "Field types": "Field types",
  "Select the Field-Type(s) that you would like to include in this app": "Select the Field-Type(s) that you would like to include in this app",
  "Images": "Images",
  "Screenshot (minimum 1000px)": "Screenshot (minimum 1000px)",
  "Icon (1024x1024px)": "Icon (1024x1024px)",
  "Sidebar Icon (white transparent SVG)": "Sidebar Icon (white transparent SVG)",
  "Your website": "Your website",
  "Url to your website": "Url to your website",
  "Your name": "Your name",
  "Video (optional)": "Video (optional)",
  "Url to Youtube video": "Url to Youtube video",
  "Intro": "Intro",
  "Short intro about what is your app about": "Short intro about what is your app about",
  "Attention! The deletion of this app will also delete all installations.": "Attention! The deletion of this app will also delete all installations.",
  "Delete this app": "Delete this app",
  "Uninstall": "Uninstall",
  "Requires plan": "Requires plan",
  "Try out in trial mode": "Try out in trial mode",
  "Approve app": "Approve app",
  "Website": "Website",
  "Last update": "Last update",
  "App content": "App content",
  "Field-Type/UI Extension": "Field-Type/UI Extension",
  "App submission": "App submission",
  "By committing your app the Storyblok app directory you accept the": "By committing your app the Storyblok app directory you accept the",
  "App Directory Agreement": "App Directory Agreement",
  "The review process take usually 2-3 days and you will get updated via email once the app is available in the app directory.": "The review process take usually 2-3 days and you will get updated via email once the app is available in the app directory.",
  "Confirm submission": "Confirm submission",
  "References": "References",
  "Unselect": "Unselect",
  "Clear trashcan": "Clear trashcan",
  "Move users to org": "Move users to org",
  "Is content type": "Is content type",
  "Add fields by dragging them to the tab.": "Add fields by dragging them to the tab.",
  "Drag and drop the field to the tab name to add it here. All fields that are not placed in custom tabs will be visible in the general tab. To remove the general tab place all fields in custom tabs.": "Drag and drop the field to the tab name to add it here. All fields that are not placed in custom tabs will be visible in the general tab. To remove the general tab place all fields in custom tabs.",
  "Manage tab": "Manage tab",
  "Rename": "Rename",
  "Move to right": "Move to right",
  "Move to left": "Move to left",
  "Hide empty option": "Hide empty option",
  "Restrict to content type": "Restrict to content type",
  "Enable email field": "Enable email field",
  "Enable asset selection": "Enable asset selection",
  "Enable anchor field on internal link": "Enable anchor field on internal link",
  "Minimum": "Minimum",
  "Maximum": "Maximum",
  "Define anchor": "Define anchor",
  "Choose to customize your experience": "Choose to customize your experience",
  "First name": "First name",
  "Last name": "Last name",
  "Job function": "Job function",
  "Marketing": "Marketing",
  "Information Technology": "Information Technology",
  "Development/Engineering/Programming": "Development/Engineering/Programming",
  "Human Resources": "Human Resources",
  "Procurement": "Procurement",
  "Security": "Security",
  "Other": "Other",
  "Business area": "Business area",
  "Accounting": "Accounting",
  "Marketing and Advertising": "Marketing and Advertising",
  "Automotive": "Automotive",
  "Agriculture": "Agriculture",
  "Chemicals": "Chemicals",
  "Construction": "Construction",
  "Consulting": "Consulting",
  "Consumer Products": "Consumer Products",
  "Education": "Education",
  "Finance": "Finance",
  "Food and Beverage": "Food and Beverage",
  "Gaming": "Gaming",
  "Government": "Government",
  "Healthcare": "Healthcare",
  "Hospitality": "Hospitality",
  "Insurance": "Insurance",
  "Legal": "Legal",
  "Manufacturing": "Manufacturing",
  "Media": "Media",
  "Oil and Energy": "Oil and Energy",
  "Pharmaceutical": "Pharmaceutical",
  "Real Estate": "Real Estate",
  "Retail": "Retail",
  "Sports": "Sports",
  "Technology": "Technology",
  "Telecommunications": "Telecommunications",
  "Transportation": "Transportation",
  "Utility": "Utility",
  "* Required fields": "* Required fields",
  "Continue": "Continue",
  "Personal settings": "Personal settings",
  "How would you describe your role?": "How would you describe your role?",
  "I am a content editor": "I am a content editor",
  "I am a developer or administrator": "I am a developer or administrator",
  "Add space to organization": "Add space to organization",
  "Add space": "Add space",
  "Unlink": "Unlink",
  "Create your first app": "Create your first app",
  "No invoices found": "No invoices found",
  "Space": "Space",
  "Invoice ID": "Invoice ID",
  "Amount": "Amount",
  "# of Spaces": "# of Spaces",
  "Revenue": "Revenue",
  "MRR": "MRR",
  "Nr. of spaces": "Nr. of spaces",
  "Active subscriptions": "Active subscriptions",
  "Total revenue share per month": "Total revenue share per month",
  "Welcome to the partner portal of Storyblok! We are excited to have you on board!": "Welcome to the partner portal of Storyblok! We are excited to have you on board!",
  "App type": "App type",
  "Sidebar": "Sidebar",
  "Fieldtype(s)": "Fieldtype(s)",
  "Add an existing space": "Add an existing space",
  "Member: Can manage spaces and apps": "Member: Can manage spaces and apps",
  "Owner: Can manage users, spaces, apps, partner account settings and see finances": "Owner: Can manage users, spaces, apps, partner account settings and see finances",
  "Stripe connect": "Stripe connect",
  "Connect your Stripe account to receive your revenue share each month.": "Connect your Stripe account to receive your revenue share each month.",
  "Partner details": "Partner details",
  "Define your business address and company information. * Required fields": "Define your business address and company information. * Required fields",
  "Billing email address": "Billing email address",
  "VAT number": "VAT number",
  "Company number": "Company number",
  "Bank information (for revenue share of enterprise plans)": "Bank information (for revenue share of enterprise plans)",
  "Plan": "Plan",
  "My spaces": "My spaces",
  "Field-types": "Field-types",
  "Partner Agreement": "Partner Agreement",
  "Current story object": "Current story object",
  "Partner portal": "Partner portal",
  "Show all": "Show all",
  "Show favorites only": "Show favorites only",
  "User ID": "User ID",
  "Single role": "Single role",
  "Multiple roles": "Multiple roles",
  "Individual permissions": "Individual permissions",
  "Organization": "Organization",
  "Maintenance mode (When enabled only admins can edit content)": "Maintenance mode (When enabled only admins can edit content)",
  "Storage": "Storage",
  "Store on the Storyblok S3 bucket": "Store on the Storyblok S3 bucket",
  "If unchecked the backup will be stored on your own S3 backup.": "If unchecked the backup will be stored on your own S3 backup.",
  "Preferred backup time": "Preferred backup time",
  "AWS Role ARN": "AWS Role ARN",
  "\"Restore now\" creates a new space with the restore date in the space name.": "\"Restore now\" creates a new space with the restore date in the space name.",
  "Your Unique Subdomain": "Your Unique Subdomain",
  "Your unique subdomain for your rendering service project with Storyblok. Replace this with your \"Location (default environment)\" to get started.": "Your unique subdomain for your rendering service project with Storyblok. Replace this with your \"Location (default environment)\" to get started.",
  "Publish translations individually (Beta)": "Publish translations individually (Beta)",
  "ATTENTION! When enabling, all languages needs to be published by going to each content item, selecting the language and clicking the Publish button.": "ATTENTION! When enabling, all languages needs to be published by going to each content item, selecting the language and clicking the Publish button.",
  "Beta version: Does not work yet together with releases and duplicating content.": "Beta version: Does not work yet together with releases and duplicating content.",
  "I have a developer": "I have a developer",
  "I am a developer": "I am a developer",
  "I want to talk": "I want to talk",
  "Thanks!": "Thanks!",
  "We received your request!": "We received your request!",
  "Invites sent!": "Invites sent!",
  "The invites got sent successfully.": "The invites got sent successfully.",
  "Invite your developer(s) to Storyblok so that they can create a project for you.": "Invite your developer(s) to Storyblok so that they can create a project for you.",
  "Email addresses": "Email addresses",
  "Send invites": "Send invites",
  "I need a developer": "I need a developer",
  "Inform us your project requirements to get offers from developers of our partner network.": "Inform us your project requirements to get offers from developers of our partner network.",
  "I want to...": "I want to...",
  "migrate a website or app to Storyblok": "migrate a website or app to Storyblok",
  "create a new website or app": "create a new website or app",
  "make an existing website or app editable in Storyblok": "make an existing website or app editable in Storyblok",
  "Budget": "Budget",
  "Less than $ 2.000": "Less than $ 2.000",
  "$ 2.000 to 5.000": "$ 2.000 to 5.000",
  "$ 5.000 to 20.000": "$ 5.000 to 20.000",
  "More than $ 20.000": "More than $ 20.000",
  "Project details": "Project details",
  "Switch to a developer account to create spaces for development of websites and apps. You can switch back to a content editor account in the my account section: "Switch to a developer account to create spaces for development of websites and apps. You can switch back to a content editor account in the my account section later.": later.",
  "Switch": "Switch",
  "Get in touch with someone at the Storyblok team to get a demo or discuss your requirements.": "Get in touch with someone at the Storyblok team to get a demo or discuss your requirements.",
  "Company name": "Company name",
  "Message": "Message",
  "Send message": "Send message",
  "Do you want to assign the space to your organization?": "Do you want to assign the space to your organization?",
  "No (for private spaces)": "No (for private spaces)",
  "Allow managing tags": "Allow managing tags",
  "Allow editing datasource keys": "Allow editing datasource keys",
  "Deny access to image editor": "Deny access to image editor",
  "Force user to create release": "Force user to create release",
  "Hide content if unauthorized": "Hide content if unauthorized",
  "Hide folders if unauthorized": "Hide folders if unauthorized",
  "Add branches the user should have the right to deploy to (acts as whitelist). If no item is selected the user has rights to deploy to all branches.": "Add branches the user should have the right to deploy to (acts as whitelist). If no item is selected the user has rights to deploy to all branches.",
  "Component/content-type permissions": "Component/content-type permissions",
  "Add the components or content types the user should not be able to select (acts as blacklist).": "Add the components or content types the user should not be able to select (acts as blacklist).",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Похоже, у вас еще нет доступа ни к одной области. Свяжитесь с администратором вашей организации, чтобы он добавил вас как работника.",
  "Start by selecting a space in the sidebar.": "Start by selecting a space in the sidebar.",
  "Details": "Details",
  "Your current plan is ": "Your current plan is ",
  "Pressing the button below will cancel your current subscription and remove all collaborators.": "Pressing the button below will cancel your current subscription and remove all collaborators.",
  "Cancel subscription": "Cancel subscription",
  "The starter plan is our free plan, so nothing we can cancel for you. If you are still receiving charges, let us know in our live-chat!": "The starter plan is our free plan, so nothing we can cancel for you. If you are still receiving charges, let us know in our live-chat!",
  "We are really sorry to see you go, but would love to understand why.": "We are really sorry to see you go, but would love to understand why.",
  "Set following stage after published": "Set following stage after published",
  "Attention! There are ": "Attention! There are ",
  " reference(s). Click to show.": " reference(s). Click to show.",
  "Undo (Ctrl+Z)": "Undo (Ctrl+Z)",
  "Redo (Ctrl+Y)": "Redo (Ctrl+Y)",
  "This block is not available any more.": "This block is not available any more.",
  "Go back to the root": "Go back to the root",
  "Please choose a release or create a new one to make your content changes.": "Please choose a release or create a new one to make your content changes.",
  "First published date (asc)": "First published date (asc)",
  "First published date (desc)": "First published date (desc)",
  "Published date (asc)": "Published date (asc)",
  "Published date (desc)": "Published date (desc)",
  "Tag list": "Tag list",
  "First published at": "First published at",
  "Translated name": "Translated name",
  "You can create a new tag at the config section of a content item.": "You can create a new tag at the config section of a content item.",
  "Assigned items": "Assigned items",
  "User dialog": "User dialog",
  "Containing content item": "Containing content item",
  "Containing asset": "Containing asset",
  "Clear all filters": "Clear all filters",
  "Load all": "Load all",
  "The user dialog JSON is invalid.": "The user dialog JSON is invalid.",
  "Edit App": "Edit App",
  "All apps": "All apps",
  "App installed successfully!": "App installed successfully!",
  "New App": "New App",
  "App approved successfully": "App approved successfully",
  "Your app has been submitted sucessfully.": "Your app has been submitted sucessfully.",
  "Please define a name": "Please define a name",
  "Trashcan cleared!": "Trashcan cleared!",
  "Type the domain to move all users with @domain.com to the org with that domain.": "Type the domain to move all users with @domain.com to the org with that domain.",
  "Define a name for the tab": "Define a name for the tab",
  "Are you sure you want to delete this tab?": "Are you sure you want to delete this tab?",
  "Define the anchor id of the link.": "Define the anchor id of the link.",
  "is not a valid email": "is not a valid email",
  "Are you sure that you want to remove this space from the organization?": "Are you sure that you want to remove this space from the organization?",
  "Space has been removed from organization": "Space has been removed from organization",
  "Space added successfully": "Space added successfully",
  "Organization created successfully": "Organization created successfully",
  "Are you sure you want to remove this language?": "Are you sure you want to remove this language?",
  "Are you sure you want to unsubscribe and remove all collaborators?": "Are you sure you want to unsubscribe and remove all collaborators?",
  "Please save the schema of this component first.": "Please save the schema of this component first.",
  "Character limit reached": "Character limit reached",
  "characters remaining": "characters remaining",
  "characters over limit": "characters over limit"
}
