export default {
  "Dashboard": "Instrumentpanel",
  "Back to spaces": "Tillbaka till utrymmen",
  "Content": "Innehåll",
  "Commerce": "Kommers",
  "Assets": "Tillgångar",
  "Datasources": "Datakällor",
  "Activities": "Aktiviteter",
  "Tasks": "Uppgifter",
  "Components": "Komponenter",
  "Apps": "Appar",
  "Settings": "Inställningar",
  "Subscription": "Prenumeration",
  "Plugins": "Insticksprogram",
  "Logout": "Logga ut",
  "Report a problem": "Rapportera ett problem",
  "Create new space": "Skapa nytt område",
  "Search spaces...": "Söker utrymmen...",
  "My organization": "Min organisation",
  "Subscribe": "Prenumerera",
  "To": "Till",
  "From": "Från",
  "Apply filter": "Tillämpa filter",
  "Filter": "Filtrera",
  "Unknown user": "Okänd användare",
  "Author": "Författare",
  "Action": "Åtgärd",
  "Date": "Datum",
  "Back": "Tillbaka",
  "Activity Details": "Aktivitetsinformation",
  "Open": "Öppna",
  "Restore this Story": "Återställ denna berättelse",
  "Categories": "Kategorier",
  "Story": "Berättelse",
  "The item has been restored!": "Objektet har återställts!",
  "All": "Alla",
  "Search for apps, discover new field types and add functionalities to your Storyblok project.": "Söka efter appar, upptäcka nya fälttyper och lägga till funktioner till ditt Storyblok-projekt.",
  "My apps": "Mina appar",
  "Create new app": "Skapa ny app",
  "Installed": "Installerad",
  "App Directory": "App-katalog",
  "There are no apps in this category.": "Det är inga appar i denna kategori",
  "Install": "Installera",
  "Choose the space to install this app": "Välj utrymmet att installera denna app i",
  "Can not move asset folder into folder without permissions.": "Kan inte flytta tillgångsmapp till mapp uatn tillstånd.",
  "Can not move asset into folder without permissions.": "Kan inte flytta tillgång till mapp utan tillstånd.",
  "Can not move asset away from folder without permissions.": "Kan inte flytta tillgång bort från mapp utan tillstånd.",
  "Define the new name of the folder.": "Ange det nya namnet på mappen.",
  "Trashbin": "Soptunna",
  "Are you sure that you want to delete this folder?": "Är du säker på att du vill radera denna mapp?",
  "Add": "Lägg till",
  "Asset folders are not included in the free plan but you can try them in the": "Tillgångsmappar ingår inte i gratisplanen men du kan testa dem i",
  "New folder will be created in": "Ny mapp kommer att skapas om",
  "trial period": "utvärderingsperiod",
  "Can not create asset folder without permission for parent.": "Kan inte skapa tillgångsmapp utan tillstånd från förälder.",
  "Original": "Ursprunglig",
  "Done": "Klart",
  "Cancel": "Avbryt",
  "Insert": "Ange",
  "Add Asset(s)": "Lägg till tillgång(ar)",
  "Close": "Stäng",
  "items": "Objekt",
  "Delete": "Radera",
  "Move to folder": "Flytta till mapp",
  "Replace": "Ersätt",
  "Unselect all": "Avmarkera alla",
  "Restore": "Återställ",
  "Tiles": "Paneler",
  "List": "Lista",
  "No assets found": "Inga tillgångar hittade",
  "Sort": "Sortera",
  "Default": "Standard",
  "View": "Vy",
  "Creation date (asc)": "Skapad den (stigande)",
  "Filename (asc)": "Filnamn (stigande)",
  "Creation date (desc)": "Skapelsedatum (fallande)",
  "Filename (desc)": "Filnamn (fallande)",
  "Last updated date (asc)": "Senast uppdaterad den (stigande)",
  "Last updated date (desc)": "Senast uppdaterad den (fallande)",
  "You are not allowed to insert this filetype here.": "Du har inte tillåtelse att ange denna filtyp här.",
  "This key is already defined": "Denna nyckel har redan angetts",
  "Key is in invalid format": "Nyckel är i ogiltigt format",
  "Something went wrong uploading some items": "Någonting gick fel när vissa objekt skulle laddas upp",
  "Please choose a folder in the left sidebar": "Välj en mapp i vänster marginallist",
  "Define the new name of": "Ange det nya namnet på ",
  "Something went wrong renaming the attribute": "Någonting gick fel när du skulle byta namn på attributet",
  "Be aware! Changing the name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Var medveten om! Att byta namn kan ta några minuter för att uppdatera alla innehållsobjekt. Se till att dina redigeringsprogram har sparat sitt aktuella arbete och lämna redigeringsprogrammet.",
  "Define the new name of the component group.": "Ange det nya namnet på komponentgruppen.",
  "Save": "Spara",
  "Are you sure that you want to delete this component group?": "Är du säker på att du vill radera denna komponentgrupp?",
  "Copy": "Kopiera",
  "New": "Nytt",
  "Move to group": "Flytta till grupp",
  "Please choose a component group in the left sidebar": "Välj en komponentgrupp i vänster marginallist",
  "Paste": "Klistra in",
  "Add block": "Lägg till block",
  "Creation of a component failed. Maybe it already exists.": "Skapande av en komponent misslyckades. Den kanske redan existerar.",
  "Are you sure you want to DELETE this component(s)?": "Är du säker på att du vill RADERA denna/dessa komponent(er)?",
  "new": "nytt",
  "Type to search or to create a": "Skriv in för att söka eller skapa en",
  "Create new": "Skapa nytt",
  "block": "blockera",
  "New Component": "Ny komponent",
  "Updated": "Uppdaterad",
  "Name": "Namn",
  "Shortcuts: Esc, Control + S": "Genvägar: Esc, Control + S",
  "Next": "Nästa",
  "Define a name": "Ange ett namn",
  "Save schema": "Spara schema",
  "Act as content type (eg. blog-post)": "Fungerar som innehållstyp (t.ex. bloggpost)",
  "Define": "Definiera",
  "Nestable": "Stapelbar",
  "Technical name": "Tekniskt namn",
  "Edit field": "Redigera fält",
  "Config": "Konfig",
  "Schema": "Schema",
  "Renaming": "Byter namn",
  "Change field name": "Ändra fältnamn",
  "Used in the json as component name": "Används i json som komponentnamn",
  "Be aware! Changing the technical name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "Var medveten om! Om det tekniska namnet byts ut kan ta några minuter att uppdatera alla innehållsobjekt. Se till att dina redigeringsprogram har sparat sitt aktuella arbete och lämna redigeringsprogrammet.",
  "Display name": "Visa namn",
  "Preview template": "Förhandsgranska mall",
  "Screenshot or icon": "Skärmdump eller ikon",
  "Used in the editor interface only": "Används endast i redigeringsprogrammets gränssnitt",
  "of this setting": "i denna inställning",
  "Read the documentation": "Läs dokumentationen",
  "Load versions": "Ladda versioner",
  "Versions": "Versioner",
  "has been added below": "har lagts till nedan",
  "Examples: news_items, body, columns, title, description or call_to_action_btn": "Exempel: nyheter_objekt, brödtext, kolumner, rubrik, beskrivning eller uppmana_till_åtgärd_btn",
  "The component has been restored!": "Komponenten har återställts!",
  "Do you really want to leave without saving your changes?": "Vill du verkligen lämna utan att spara dina ändringar?",
  "Type": "Skriv",
  "Beta": "Beta",
  "Translatable": "Översättninsgbar",
  "Allow empty paragraphs": "Tillåt tomma stycken",
  "Linktype": "Länktyp",
  "Rich-text as default": "Rich-text som standard",
  "Custom type": "Anpassa typ",
  "Category": "Kategori",
  "Section items": "Avsnitts-objekt",
  "Product": "Produkt",
  "Customize toolbar": "Anpassa verktygsfält",
  "Toolbar items": "Verktygsfält-objekt",
  "Source": "Källa",
  "CSS class options (label/value)": "CSS-klassalternativ (label/värde)",
  "Datasource": "Datakälla",
  "Stories": "Berättelser",
  "Self": "Själv",
  "Internal datasource": "Intern datakälla",
  "Recommended to be checked, as UID is required for automatic link resolving.": "Bör markeras eftersom UID krävs för automatisk länklösning.",
  "Use UID instead of ID": "Använd UID istället för ID",
  "In case you have a multi-language folder structure you can add the {0} placeholder and the path will be adapted dynamically. Examples: {0}/categories/, {0}/{1}/categories/": "Om du har en mappstruktur med flera språk kan du lägga till {0} platshållaren och sökvägen kommer att anammas dynamiskt. Exempel: {0}/kategorier/, {0}/{1}/kategorier/",
  "External JSON": "Extern JSON",
  "Path to folder of stories": "Sökväg till mapp med berättelser",
  "Width": "Bredd",
  "URL": "URL",
  "ratio": "kvot",
  "pixel": "pixel",
  "Allowed maximum": "Maximalt tillåtet",
  "Options (name/value)": "Alternativ (namn/värde)",
  "Component(s)": "Komponent(er)",
  "Group(s)": "Grupp(er)",
  "Required field(s) (comma separated)": "Obligatoriskt/obligatoriska fält (kommaseparerade)",
  "Required": "Obligatorisk",
  "Default asset folder": "Standard-tillgångsmapp",
  "Choose an asset folder where the assets should be assigned to.": "Välj en innehållsmapp som tillgångarna ska tilldelas till.",
  "With {level} the path will be replaced dynamically using parts of the current slug. Examples: {0}/categories/, {0}/{1}/categories/": "Med {nivå} byts planen ut dynamiskt mot delar av nuvarande slug. Exempel: {0}/kategorier/, {0}/{1}/kategorier/",
  "Restrict to folder": "Begränsa till mapp",
  "Force folder restriction": "Tvinga mappbegränsning",
  "Regex validation": "Regex-validering",
  "Exclude from export": "Exkludera från export",
  "export app": "exportera app",
  "To use with the": "För att använda med",
  "Default value": "Standardvärde",
  "Can be updated by preview window": "Kan uppdateras via förhandsgranskningsfönster",
  "Loading...": "Laddar...",
  "Item": "Objekt",
  "Allow only specific components to be inserted": "Tillåt endast att specifika komponenter sätts i.",
  "Restrict to content types": "Begränsa till innehållstyper",
  "Keep original size": "Behåll ursprunglig storlek",
  "Force crop": "Tvinga beskärning",
  "Prepend https to url": "Inled https till url",
  "Height": "Höjd",
  "Maximum characters": "Maximalt antal tecken",
  "Disable time selection": "Avaktivera tidval",
  "Description": "Beskrivning",
  "dimensions app": "dimensions-app",
  "Force overwrite by merge action": "Tvina överskrivning genom sammanslagningsåtgärd",
  "Id/Slug": "Id/Slug",
  "Enable RTL (Right to left)": "Aktivera RTL (höger till vänster)",
  "Autosave": "Autospara",
  "API Url": "API-url",
  "Export": "Exportera",
  "Import/Export": "Importera/exportera",
  "Dimensions": "Dimensioner",
  "Add Dimension": "Lägg till dimension",
  "Import": "Importera",
  "A datasource in Storyblok is a collection of key-value pairs.": "En datakälla i Storyblok är en samling av nyckel-värde.par.",
  "Datasources can be used in a schema definition of a component for single or multiple choice options. You can also access": "Datakällor kan användas i en schemadefinition av en komponent för enstaka eller flervalsalternativ. Du kan också gå till",
  "datasource entries from the API": "datasourceuppslag från API",
  "to use them for labels, categories or similar.": "för att använda dem till etiketter, kategorier eller liknande.",
  "Unsaved Changes": "Ändringar som inte sparats",
  "Datasource entries": "Datasourceposter",
  "Datasources are not included in the free plan": "Datakällor är inte inkluderade i den kostnadsfria planen.",
  "but you can try them in the": "men du kan testa dem i",
  "Saved": "Sparad",
  "Select all": "Välj alla",
  "The options could not be loaded.": "Alternativen kunden inte laddas.",
  "New Datasource": "Ny datakälla",
  "The following component(s) can not be pasted here": "Följande komponent(er) kan inte klistras in här",
  "Please save first to continue editing child components.": "Spara först för att fortsätta redigera barnkomponenter.",
  "Enabled?": "Aktiverad?",
  "Asset manager": "Tillgångshanterare",
  "Loading": "Laddar",
  "Upload new": "Ladda upp ny",
  "Your file exceeds the maximum filesize limit of": "Din fil överskrider maximal filstorlek för",
  "Please reduce the size of your file.": "Minska storleken på din fil.",
  "Alt text": "Alt-text",
  "Base64": "Base64",
  "Original Size": "Ursprunglig storlek",
  "Image loading failed": "Laddning av bild misslyckades",
  "Quote": "Offert",
  "Code Block": "Kodblock",
  "Ordered List": "Beställd lista",
  "Headline 2": "Rubrik 2",
  "Headline 4": "Rubrik 4",
  "Headline 3": "Rubrik 3",
  "Headline 5": "Rubrik 5",
  "Paragraph": "Stycke",
  "Help": "Hjälp",
  "Internal link": "Intern länk",
  "Show only selected": "Visa endast valda",
  "more items found": "fler objekt hittade",
  "Invoices": "Fakturor",
  "Tip: Use Ctrl + S to save": "Tips: Använd Ctrl + S för att spara",
  "Input": "Inmatning",
  "Publish": "Publicera",
  "You are not allowed to edit this plugin but can see the code at Settings/Details.": "Du har inte tillåtelse att redigera detta insticksprogram men kan se koden på Inställningar/Information.",
  "Field type preview": "Fälttyp förhandsgranskning",
  "Options (key/value)": "Alternativ (nyckel/värde)",
  "Space Id": "Utrymmes-id",
  "Enable local dev mode": "Aktivera lokalt enhetsläge",
  "Settings/Details": "Inställningar/Detaljer",
  "Output": "Resultat",
  "for approval to make it available for all users.": "för godkännande för att göra den tillgänglig för alla användare.",
  "Submit the plugin": "Skicka insticksprogrammet",
  "Code": "Kod",
  "You can copy the code of this plugin to create your own plugin.": "Du kan kopiera koden för detta insticksprogram för att skapa ditt eget insticksprogram.",
  "Assigned spaces": "Tilldelade utrymmen",
  "If you assign this plugin to a space other developers can also use it in the schema definition. Without assigning it only you can add the plugin to the schemas.": "Om du tilldelar detta insticksprogram till ett utrymme kan andra utvecklare också använda det i schemadefinitionen. Utan att endast tilldela det kan du lägga till insticksprogrammet till schemana.",
  "Attention: All spaces using this plugin will not be able to use it any more if you click delete.": "Varning: Utrymmen som använder detta insticksprogram kommer inte att kunna använda det mer om du klickar på radera.",
  "Documentation": "Dokumentation",
  "Danger zone": "Riskzon",
  "What is a field type plugin?": "Vad är ett insticksprogram av fälttyp?",
  "A field type plugin extends the Storyblok editor with your own custom field types.": "Ett insticksprogram av fälttyp utökar Storyblok-redigeringsprogrammet med dina egna anpassade fälttyper.",
  "It is basically a": "Det är i grunden ett",
  "The properties that are passed to the field type are:": "Egenskaperna som vidarebefordras till fättypen är:",
  "component extended with a few helpers in the window.Storyblok.plugin mixin.": "komponent utökad med några hjälpare i fönstret.Storyblok.insticksprogramblandning.",
  "Examples for field types are colorpickers, WYSYWYG editors or meta tags.": "Exempel på fälttyper är färgväljare, WYSYWYG-redigeringsprogram eller metataggar.",
  "Uid of the parent component": "Uid av föräldrakomponenten",
  "Options parsed from the schema options array": "Alternativ parsade från raden av schemaalternativ",
  "Schema options object": "Schemaalternativ objekt",
  "Current value of the fieldtype": "Nuvarande värde på fälttypen",
  "Story id of the current story": "Den aktuella berättelsens berättelse-id",
  "Space id of the current space": "Utrymmes-id för aktuellt utrymme",
  "Api function to call the delivery api": "Api-funktion för att ringa leverans-api",
  "Methods": "Metoder",
  "Draft token of the current space": "Utkast-token för aktuellt utrymme",
  "How to call the Storyblok api?": "Hur ringer man Storyblok-api?",
  "Should be used to define the initial data of the plugin.": "Ska användas för att definiera insticksprogrammets initiala data.",
  "Should be used to initialize the plugin. Examples: Load data from Storyblok or external sources, Load and initialize a WYSIWYG editor.": "Ska användas för att starta insticksprogrammet. Exempel: Ladda data från Storyblok eller externa källor, ladda och starta ett WYSIWYG-redigeringsprogram.",
  "To pass options that are configurable in the schema definition define the option keys in the \"Input\" box. The values will be available in the this.options object.": "För att godkänna alternativ som är konfigurerbara i schemadefinitionen definiera alternativknapparna i rutan \"inmatning\". Värdena kommer att vara tillgängliga i detta alternativobjekt.",
  "How to pass options?": "Hur vidarebefordra alternativ?",
  "In field types you can use this.api to get access to the Storyblok delivery api. You can use it for example to build a selectbox of stories.": "I fälttyper kan du använda denna api för att få åtkomst till Storyblok leverans-api. Du kan till exempel använda den för att bygga en selectbox av berättelser.",
  "Folder/Content-item permissions": "Mapp/Innehålls-objekt tillstånd",
  "Item saved successfully!": "Objekt har sparats!",
  "Source of sync": "Synkroniseringskälla",
  "Preview": "Förhandsgranska",
  "Preview url": "Förhandsgranska url",
  "View on Jsfiddle": "Visa på Jsfiddle",
  "Download": "Ladda ner",
  "Admin": "Admin",
  "Permissions": "Tillstånd",
  "Editor": "Redigeringsprogram",
  "Advanced Rights": "Avancerade rättigheter",
  "Allow saving content": "Tillåt att innehåll sparas",
  "Allow publishing content": "Tillåt publicering av innehåll",
  "Allow saving datasources": "Tillåt att datakällor sparas",
  "Allow managing subscription": "Tillåt hantering av prenumeration",
  "Allow access to ecommerce app": "Tillåt åtkomst till e-handelsapp",
  "Deny access to visual composer": "Neka åtkomst till visuell kompositör",
  "Field Permissions": "Fälttillstånd",
  "General": "Allmänt",
  "Allowed path": "Tillåten sökväg",
  "Your crawl URL": "Ditt crawl-URL",
  "Crawler": "Crawler",
  "Enabled": "Aktiverad",
  "Index": "Index",
  "Crawl now": "Crawla nu",
  "Information needed to access the search endpoint or to configure the search client.": "Information krävs för att gå till sökslutpunkten eller för att konfigurera sökklienten.",
  "Search Setup Guide": "Sök Inställningsguide",
  "Your tenant ID": "Ditt hyresgäst-ID",
  "See": "Se",
  "Documents in index": "Dokument i index",
  "Crawl requested at": "Crawl begär den",
  "Tenant ID": "Hyresgäst-ID",
  "Documents": "Dokument",
  "Clear index": "Rensa index",
  "Last crawled at": "Senast crawlad den",
  "Crawl has been initiated": "Crawl har initierats",
  "In the first 14 days you can try out all Premium plan features!": "Inom de första 14 dagarna kan du försöka testa alla funktioner i Premium-plan!",
  "Index deletion has been initiated": "Radering av index har initierats",
  "API-Keys": "API-nycklar",
  "We would love to hear your thoughts about Storyblok on": "Vi vill gärna veta vad du tycker om Storyblok på",
  "Renderer": "Utförare",
  "Backup": "Säkerhetskopiering",
  "Users": "Användare",
  "Workflow": "Arbetsflöde",
  "Search": "Sök",
  "Languages": "Språk",
  "This is the page that the frontend-editor opens.": "Detta är sidan som frontend-redigeringsprogrammet öppnar.",
  "Location (default environment)": "Plats (standardmiljö)",
  "Insert your domain/location including the protocol. Example: http://www.example.com/": "Ange din domän/plats inklusive protokollet. Exempel: http://www.example.com/",
  "Provide this ID in your support tickets": "\nTillhandahåll detta ID i dina supportbiljetter",
  "Your space ID": "Ditt utrymmes-ID",
  "Preview urls": "Förhandsgransknings-url:er",
  "Define multiple domains/locations to quickly switch the preview urls in the story-editor.": "Ange flera domäner/platser för att snabbt växla förhandsgransknings-url:er i berättelse-redigeringsprogrammet.",
  "Add preview url": "Lägg till förhandsgransknings-url",
  "Webhooks": "Webhooks",
  "Story published &amp; unpublished": "Berättelse publicerad &amp; opublicerad",
  "Story saved": "Berättelse sparad",
  "Branch deployed": "Gren som använts",
  "Release merged": "Version sammanslagen",
  "Slack integration": "Slackintegrering",
  "Loading... You will be redirect to Slack in a few seconds!": "Laddar... Du kommer att omdirigeras till Slack om några sekunder!",
  "Get notified on your Slack channel if a new Story has been published!": "Få meddelanden på din Slack-kanal om en ny berättelse har publicerats!",
  "With this integration you can choose a Slack channel where Storyblok posts messages whenever a user publishes new content.": "Med denna integration kan du välja en Slack-kanal där Storyblok postar meddelanden när en användare publicerar nytt innehåll.",
  "Disconnect": "Koppla ifrån",
  "Cloud name": "Molnnamn",
  "Cloudinary integration": "Molnintegration",
  "Api Key": "Api-nyckel",
  "Branches": "Grenar",
  "Default content type": "Standard-innehållstyp",
  "Content types": "Innehållstyper",
  "Name of the branch": "Namn på gren",
  "Branches are not included in the free plan": "Grenar är inte inkluderade i gratisplanen",
  "Duplication": "Duplicering",
  "This is useful if you want to offer your space for other users as a boilerplate or theme.": "Detta är användbart om du vill erbjuda ditt utrymme till andra användare som ett standardformulär eller tema.",
  "ATTENTION! Only check this checkbox if you are sure that you want all data of this space available for duplication.": "VARNING! Markera endast denna kryssruta om du är säker på att du vill göra alla data för detta utrymme tillgängliga för duplicering.",
  "Make this space duplicatable by all users": "Gör detta utrymme duplicerbart för alla användare",
  "Content ownership": "Innehållsägarskap",
  "Parent ID": "Föräldra-ID",
  "Parent": "Förälder",
  "Image service": "Bildtjänst",
  "Content ownership client endpoint": "Innehåll ägarskap klient slutpunkt",
  "List of paths to invalidate": "Lista med sökvägar att upphäva",
  "Delete this space": "Radera detta utrymme",
  "Invalidate": "Upphäv",
  "Workflow webhooks": "Arbetsflödes-webhooks",
  "Owner": "Ägare",
  "Workflow changed": "Arbetsflöde ändrat",
  "Transfer ownership": "Överlåt ägarskap",
  "Transfer": "Överför",
  "Attention! Transferring the ownership will remove all your rights to this space.": "Varning! Överlåtelse av ägarskap tar bort alla dina rättigheter till detta utrymme.",
  "The owner needs to add you as a collaborator if you want to have access again.": "Ägaren måste lägga till dig som medarbetare om du vill ha åtkomst igen.",
  "Collaborators": "Medarbetare",
  "Collaborator": "Medarbetare",
  "No user found with this email or username.": "Ingen användare hittades med denna e-postadress eller användarnamn.",
  "Name of the role": "Namn på roll",
  "Role": "Roll",
  "Add a new user to your org": "Lägg till en ny användare till din org",
  "Advanced rights and roles are not included in the free and basic plan": "Avancerade rättigheter och roller är inte inkluderade i den kostnadsfria och basala planen",
  "Use your Amazon S3 bucket to create backups.": "Använd din Amazon S3- bucket för att skapa säkerhetskopieringar.",
  "Backup now": "Säkerhetskopiera nu",
  "Backups content (stories) and compontents": "Säkerhetskopierar innehåll (berättelser) och komponenter",
  "Define your S3-Bucket and AWS-ARN to enable backups.": "Definiera din S3-Bucket och AWS-ARN för att aktivera säkerhetskopieringar.",
  "Daily backups": "Dagliga säkerhetskopieringar",
  "Define the name of the S3-bucket where you want to store your backups.": "Ange namnet på den S3-bucket där du vill lagra dina säkerhetskopieringar.",
  "S3-bucket": "S3-bucket",
  "Activate automatic daily backups": "Aktivera automatiska dagliga säkerhetskopieringar",
  "1. Read the": "1. Läs",
  "AWS Policy ARN": "AWS-policy ARN",
  "Show setup instructions": "Visa anvisningar för inställning",
  "tutorial on how to setup an Amazon IAM role": "handledning om hur du registrerar en Amazon-IAM-roll",
  "2. Create an Amazon IAM role with following access policy document:": "2. Skapa en Amazon-IAM-roll med följande åtkomstpolicydokument:",
  "if not done yet.": "om det inte gjorts än.",
  "The role should have the permission to access and create files on the S3 bucket you defined. You can for example use the following permission policy replacing YOUR_BUCKET with your bucket name:": "Rollen ska ha tillstånd att få åtkomst till och skapa filer på den S3-bucket du definierat. Du kan till exempel använda följande tillståndspolicy och byta ut YOUR_BUCKET mot ditt bucketnamn:",
  "Restore spaces from backups on your Amazon S3 bucket.": "Återställ utrymmen från säkerhetskopieringar på din Amazon S3-bucket.",
  "Backup file": "Säkerhetskopieringsfil",
  "Show latest backups": "Visa senaste säkerhetskopieringar",
  "Latest five backups": "Senaste fem säkerhetskopieringar",
  "Restore now": "Återställ nu",
  "The settings below only apply if you are using": "Inställningarna nedan gäller endast om du använder",
  "Attention! \"Restore now\" deletes old data and restores content (stories) and compontents from the backup file.": "Varning! \"Återställ nu\" raderar gamla data och återställer innehåll (berättelser) och komponenter från säkerhetskopieringsfilen.",
  "Rendering service": "Utförandetjänst",
  "Your domain": "Din domän",
  "To connect your domain to Storyblok you need to create a CNAME Record pointing to eu-domain.storyblok.com": "För att ansluta din domän till Storyblok måste du skapa ett CNAME-register som pekar mot eu-domain-storyblok.com",
  "Routes": "Vägar",
  "Add Route": "Lägg till väg",
  "Please read the": "Vänligen läs",
  "Add custom routes to define different page templates.": "Lägg till anpassade vägar för att definiera olika sidmallar.",
  "documentation about internationalization": "dokumentation om internationalisering",
  "before configuring languages.": "innan du konfigurerar språk.",
  "Add languages to activate field level translations.": "Lägg till språk för att aktivera översättningar på fältnivå.",
  "Add Language": "Lägg till språk",
  "Label": "Etikett",
  "The invalidation process has been initiated": "Upphävningsproceduren har startats",
  "The backup has been initiated": "Säkerhetskopieringen har startat",
  "Are you sure you want to delete your current content and overwrite it with this backup?": "Är du säker på att du vill radera ditt aktuella innehåll och skriva över det med denna säkerhetskopiering?",
  "The restore process has been initiated": "Återställningsproceduren har initierats",
  "Transfer was not successful. Make sure that the new owner exists.": "Överföringen lyckades inte. Kontrollera att den nya ägaren existerar.",
  "The collaborator has been added": "Medarbetaren har lagts till",
  "Please insert an email address": "Ange en e-postadress",
  "Branches sorted successfully!": "Grenar sorterade!",
  "Create or join a space": "Skapa eller gå med i ett utrymme",
  "Create a new space": "Skapa ett nytt utrymme",
  "Play with a demo": "Lek med en demo",
  "Duplicate a space": "Duplicera ett utrymme",
  "Join a space": "Gå med i ett utrymme",
  "Create space": "Skapa utrymme",
  "Headless (API/SDKs)": "Huvudlös (API/SDK:er)",
  "what is that?": "vad är det?",
  "Duplicate space": "Duplicera utrymme",
  "Choose the space for the duplication": "Välj utrymme för dupliceringen",
  "You do not have created any spaces yet.": "Du har inte skapat några utrymmen än.",
  "You can test the editing interface and our visual composer without to write any code on your own.": "Du kan testa redigeringsgränssnittet och vår visuella kompositör utan att skriva kod själv.",
  "Create Demo": "Skapa demo",
  "Insert the email of your space admin to let them add you as a collaborator of the space.": "Ange din utrymmesadministratörs e-postadress för att låta dem lägga till dig som medarbetare i utrymmet.",
  "Request access": "Begär åtkomst",
  "Email address of space admin": "Utrymmesadmins e-postadress",
  "Success! You will get notified once the admin added you as a collaborator.": "Genomfört! Du kommer att meddelas när admin har lagt till dig som medarbetare.",
  "Available Billing Information": "Tillgänglig faktureringsinformation",
  "No spaces with billing information available": "Inga utrymmen med faktureringsinformation tillgängliga",
  "Spaces": "Utrymmen",
  "Show More": "Visa mer",
  "Apply": "Tillämpa",
  "Show": "Visa",
  "Billing Information of Space": "Faktureringsinformation för utrymme",
  "The information below will be applied to the fields of your current subscription process. You will be able to adopt them after applying them.": "Informationen nedan kommer att tillämpas till fält i din nuvarande prenumerationsprocedur. Du kommer att kunna anamma dem efter att du tillämpat dem.",
  "Company": "Företag",
  "Country": "Land",
  "Street / City / ZIP": "Gata/Stad/Postnummer ",
  "Email": "E-post",
  "Add or change preview urls": "Lägg till eller ändra förhandsgransknings-url:er",
  "Your server address": "Din serveradress",
  "1. Download a preconfigured project": "1. Ladda ner ett förkonfigurerat projekt",
  "Preferred by our users": "Föredras av våra användare",
  "The downloaded package comes preconfigured with your api token": "Det nedladdade paketet kommer förkonfigurerat med din api-token",
  "Tutorial": "Handledning",
  "Other technologies": "Andra tekniker",
  "2. Start your server": "2. Starta din server",
  "Start the server of the downloaded package and insert your server url here:": "Starta serven för det nedladdade paketet och ange ditt server-url här:",
  "Go": "Kör",
  "FAQ": "Vanliga frågor",
  "Can I build a full blown website with Storyblok?": "Kan jag skapa en fullständig webbplats med Storyblok?",
  "Can I create a blog with Storyblok?": "Kan jag skapa en blogg med Storyblok?",
  "How does Storyblok work?": "Hur fungerar Storyblok?",
  "What is the Storyblok bridge?": "Vad är Storyblok-bron?",
  "Allow deploying content": "Tillåt användning av innehåll",
  "General permissions": "Allmänna tillstånd",
  "Allow unpublishing content": "Tillåt avpublicering av innehåll",
  "Allow deleting content": "Tillåt radering av innehåll",
  "Allow editing datasource keys & values": "Tillåt redigering av datasourcenycklar och -värden.",
  "Allow editing datasource values": "Tillåt redigering av datasourcevärden",
  "Allow access to the tasks app": "Tillåt åtkomst till uppgifts-appen",
  "Deny moving a story": "Neka att flytta en berättelse",
  "Deny changing alternates group": "Neka ändring av alternativ grupp",
  "Add languages the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Lägg till språk som användaren ska ha åtkomst till (fungerar som vitlista) Om inget objekt väljs har användaren rätt att redigera allt innehåll.",
  "Deny changing the slug of a story": "Neka ändring av slug med en berättelse",
  "Add folders or content items the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "Lägg till mappar eller innehållsobjekt som användaren ska ha åtkomst till (fungerar som vitlista) Om inget objekt väljs har användaren rätt att redigera allt innehåll.",
  "Component field permissions": "Komponentfält-tillstånd",
  "Datasource permissions": "Datasourcetillstånd",
  "Add component fields here to hide them in the interface.": "Lägg till komponentfält här för att dölja dem i gränssnittet.",
  "Add datasources the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all datasources.": "Lägg till datakällor som användaren ska ha åtkomst till (fungerar som vitlista). Om inget objekt väljs har användaren rätt att redigera alla datakällor.",
  "Asset Folder Permissions": "Tillgångsmapp-tillstånd",
  "Add asset folders to restrict editing and upload access.": "Lägg till tillgångsmappar för att begränsa redigering och ladda upp åtkomst.",
  "Start by selecting a space in the sidebar or create a new space.": "Börja med att välja ett utrymme i marginallisten eller skapa ett nytt utrymme.",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "Du tycks inte ha åtkomst till något utrymme än. Vänligen kontakta administratören i din organisation för att få en medarbetare tillagd.",
  "Welcome!": "Välkommen!",
  "Traffic": "Trafik",
  "Learn more about": "Läs mer om",
  "Api requests": "Api-förfrågningar",
  "Active Plan": "Aktiv plan",
  "Usage": "Användning",
  "Content activities": "Innehållsaktiviteter",
  "No billing": "Ingen fakturering",
  "Change": "Ändra",
  "Billed": "Fakturerad",
  "No recent changes": "Inga nyliga ändringar",
  "Choose your plan": "Välj din plan",
  "Recent changes": "Senaste ändringar",
  "Custom": "Anpassa",
  "Compare": "Jämför",
  "user": "användare",
  "Got a custom plan or coupon code?": "Har du en anpassad plan eller kupongkod?",
  "Custom plan": "Anpassad plan",
  "Entered plan ids will be validated after pressing subscribe.": "Angivna plan-id:er kommer att valideras efter att du tryckt på prenumerera.",
  "Coupon code": "Kupongkod",
  "Entered coupon codes will be validated and applied after pressing subscribe.": "Angivna kupongkoder kommer att valideras och tillämpas efter att du tryckt på prenumerera.",
  "Select seats": "Välj platser",
  "Confirm subscription": "Bekräfta prenumeration",
  "Min": "Min",
  "Max": "Max",
  "By clicking the button below the new subscription will start.": "Genom att klicka på knappen nedan startar prenumerationen.",
  "Decide payment interval": "Bestäm betalningsintervall",
  "Change subscription": "Ändra prenumeration",
  "Monthly": "Varje månad",
  "Annually": "Årligen",
  "Define billing information": "Definiera faktureringsinformationen",
  "Email address": "E-postadress",
  "VAT-Number": "Momsnummer",
  "Reuse from another space": "Återanvänd från annat utrymme",
  "Order number": "Ordernummer",
  "Street": "Gata",
  "City": "Stad",
  "Credit or debit card": "Kredit- eller betalkort",
  "ZIP": "Postnummer",
  "Enter payment information": "Ange betalningsinformation",
  "Update payment information": "Uppdatera betalningsinformation",
  "Update billing information": "Uppdatera faktureringsinformation",
  "Information: Our payment provider validates card information when it is saved. As a result of this process, you may see a temporary authorization for $1 on your statement.": "Information: Vår betalningsleverantör validerar kortinformation när den har sparats. Till följd av denna procedur, kanske du får se ett tillfälligt godkännande för 1 $ på ditt utdrag.",
  "Please provide all billing informations marked as required (*)": "Ange all faktureringsinformation som är markerad som obligatorisk (*)",
  "Your selected team sizes are not in the limits of your selected feature set. You can select another feature set to continue.": "Dina valda teamstorlekar är inte inom gränsvärdena för din valda inställda funktion. Du kan välja en annan inställd funktion för att fortsätta.",
  "View invoices": "Visa fakturor",
  "Summary": "Sammanfattning",
  "Please provide a credit or debit card": "Tillhandahåll ett kredit- eller betalkort",
  "If your entered plan is not correct you will still be able to try it again.": "Om din angivna plan inte är korrekt kommer du ändå att kunna testa den igen.",
  "You have entered a custom plan with a special offering and pricing": "Du har angett en anpassad plan med ett specialerbjudande och specialpris",
  "users": "användare",
  "VAT reverse charge applies.": "Omvänd moms tillämpas.",
  "VAT": "Moms",
  "Total": "Totalt",
  "The benefits of the coupon code will be applied if available": "Förmånerna med kupongkoden kommer att tillämpas om tillgänglig",
  "Thanks! You are awesome!": "Tack! Du är enastående!",
  "We would love to hear what you think about Storyblok.": "Vi vill gärna veta vad du tycker om Storyblok.",
  "Chat with us or": "Chatta med oss eller",
  "your feedback.": "din feedback.",
  "Tweet": "Tweet",
  "Star": "Stjärna",
  "Share": "Dela",
  "Public access tokens are only for accessing the published version while preview tokens are for accessing the draft version also. Both are read-only tokens.": "Offentliga åtkomsttokens är endast avsedda för åtkomst till den publierade versionen medan förhandsgranskningstokens är avsedda för åtkomst även till utkastversionen. Båda är skrivskyddade tokens.",
  "Access level": "Åtkomstnivå",
  "Public": "Offentlig",
  "See API-Documentation": "Se API-dokumentation",
  "Theme": "Tema",
  "Branch": "Gren",
  "Choose branch": "Välj gren",
  "Create Token": "Skapa token",
  "Color": "Färg",
  "Define as default stage for new content items": "Ange som standardsteg för nya innehållsobjekt",
  "Publishing rights": "Publiceringsrättigheter",
  "Stage transition rules": "Sätt upp övergångsregler",
  "Allow users to publish or schedule the content": "Tillåt användare att publicera eller schemalägga innehållet",
  "Specific stage(s)": "Specifika steg",
  "Next available stages": "Nästa tillgängliga steg",
  "All stages": "Alla steg",
  "All users": "Alla användare",
  "User(s)/Role(s) who can change the stage": "Användare/roll(er) som kan ändra steget",
  "to the next available stage": "till nästa tillgängliga steg",
  "Specific user(s)/role(s)": "Specifik(a) användare/roll(er)",
  "Role(s)": "Roll(er)",
  "User(s)": "Användare",
  "Workflow stages": "Arbetsflödesstegen",
  "See workflow documentation": "Se arbetsflödesdokumentation",
  "Create": "Skapa",
  "Choose an approver": "Välj en godkännare",
  "Workflow stages sorted successfully!": "Arbetsflödes-steg har sorterats!",
  "Are you sure you want to delete this workflow stage?": "Är du säker på att du vill radera detta arbetsflödessteg?",
  "Send for approval": "Skicka för godkännande",
  "Approval request has been sent successfully!": "Begäran om godkännande har skickats!",
  "Content items": "Innehållsobjekt",
  "Entry": "Uppslag",
  "Define schema": "Definiera schema",
  "Folder": "Mapp",
  "You have not defined any schema for this block yet.": "Du har inte angett något schema för detta block ännu.",
  "Define presets": "Definiera förinställningar",
  "Click \"Define schema\" to add the fields you need.": "Klicka på \"Ange schema\" för att lägga till de fält du behöver.",
  "No valid fields defined in this section yet.": "Inga giltiga fält angivna i detta avsnitt än.",
  "is already part of another section": "är redan del av ett annat avsnitt",
  "Translate": "Översätt",
  "Choose to delete the values or add the schema keys.": "Välj att radera värdena eller lägg till schemanycklar.",
  "items out of schema": "objekt utanför schema",
  "We have found values which are not part of the schema.": "Vi har hittat värden som inte är del av schemat.",
  "No changes found": "Inga ändringar hittades",
  "Changes": "Ändringar",
  "Remove all": "Ta bort alla",
  "Select releases to deploy": "Välj versioner att sätta i drift",
  "What is getting deployed?": "Vad används?",
  "All content that is currently on the source branch and the releases you select.": "Allt innehåll som för närvarande är på källgrenen och versionerna du väljer.",
  "No releases found on the source branch": "Inga versioner hittades på källgrenen",
  "A newer version of this content item has been found in the database.": "En nyare version av denna innehållspost har hittats i databasen.",
  "Confirm": "Bekräfta",
  "Choose the conflict solution": "Välj konfliktlösningen",
  "Copy over": "Kopiera över",
  "Opens newer version in a new window to let you copy over your changes.": "Öppnar nyare version i ett nytt fönster så att du kan kopiera över dina ändringar.",
  "Overwrite": "Skriv över",
  "Slug": "Slug",
  "Overwrites newer version with your changes.": "Skriver över nyare version med dina ändringar.",
  "Define as root for the folder": "Ange som rot för mappen",
  "Preset": "Förinställning",
  "Content type": "Innehållstyp",
  "Confirm deletion": "Bekräfta radering",
  "Are you sure that you want to delete this item(s)?": "Är du säker på att du vill radera detta/dessa objekt?",
  "Include associated alternates": "Inkludera associerade alternativ",
  "Target-Folder": "Mål-mapp",
  "Is alternative version of the duplicate?": "Är alternativ version av dubbletten?",
  "Duplicate": "Duplicera",
  "Schedule": "Tidsplan",
  "duplicated": "Duplicerad",
  "You are not allowed to duplicate this story.": "Du har inte tillåtelse att duplicera denna berättelse.",
  "Open published": "Öppna publicerade",
  "Send approval": "Skicka godkännande",
  "Open draft": "Öppet utkast",
  "Unpublish": "Avpublicera",
  "Draft json": "Utkast json",
  "Discard changes": "Kasta ändringar",
  "Start sync": "Starta synkronisering",
  "Published json": "Publicerat json",
  "Status": "Status",
  "Tools": "Verktyg",
  "Real path": "Verklig sökväg",
  "Settings for the folder content": "Inställningar för mappinnehållet.",
  "Disable visual composer": "Avaktivera visuell kompositör",
  "Clone to all": "Klona till alla",
  "Deny changing content type": "Neka ändring av innehållstyp",
  "Merge to all": "Slå samman till alla",
  "Dimensions are only available if you are editing a content item in a subfolder.": "Dimensioner är endast tillgängliga om du redigerar ett innehållsobjekt i en undermapp.",
  "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).": "Skapa en mappstruktur där den första mappen definierar din dimension (Exempel: de/hem, en/hem).",
  "Not created yet": "Inte skapad än",
  "Create clone": "Skapa klon",
  "Merge": "Slå sammam",
  "Something went wrong merging the alternate(s)": "Någonting gick fel när alternativ skulle slås samman",
  "The alternate(s) have been created!": "Alternativet/alternativen har skapats!",
  "The alternate(s) have been merged!": "Alternativet/alternativen har slagits samman!",
  "Add preset": "Lägg till förinställning",
  "Presets are blocks filled with the content you currently have in the selected block.": "Förinställningar är block fyllda med innehållet du för närvarande har i det valda blocket.",
  "Something went wrong creating the alternate(s)": "Någonting gick fel när alternativ skulle skapas",
  "The saved presets are shown for all users at the selection of new blocks.": "De sparade förinställningarna visas för alla användare vid valet av nya block.",
  "Existing presets": "Befintliga förinställningar",
  "As default": "Som standard",
  "Release date (optional)": "Lanseringsdatum (valfritt)",
  "Branches to deploy": "Grenar att använda",
  "When the release gets merged all content will be automatically deployed to the selected branches.": "När versionen slås samman kommer allt innehåll automatiskt att användas till de valda grenarna.",
  "Entry configuration": "Uppslags-konfiguration",
  "Editmode": "Redigera läge",
  "Are you sure you want to delete this release?": "Är du säker på att du vill radera denna version?",
  "Form only": "Endast formulär",
  "Visual": "Visuell",
  "Tags": "Taggar",
  "Sort by date": "Sortera efter datum",
  "First published date": "Första publiceringsdatum",
  "Remove": "Ta bort",
  "Alternative versions": "Alternativa versioner",
  "Search for the content group of this story.": "Sök efter innehållsgrupp för denna berättelse.",
  "Shortcut": "Genväg",
  "Pin as shortcut in the mini-browser": "Pinkod som genväg i mini-webbläsaren",
  "Current": "Nuvarande",
  "New release": "Ny version",
  "Skip this step": "Hoppa över detta steg",
  "Move": "Flytta",
  "Next step": "Nästa steg",
  "We have already done that for you. Open the entry \"Home\" below to play around.": "Vi har redan gjort det åt dig Öppna uppslaget \"Hem\" nedan för att leka runt.",
  "Create a demo page": "Skapa en demosida",
  "Create a new folder": "Skapa en ny mapp",
  "Create your first folder": "Skapa din första mapp.",
  "and define a new content type during the folder set-up.": "och ange en ny innehållstyp under mappkonfigurationen.",
  "Create your first entry": "Skapa ditt första uppslag",
  "Create entry": "Skapa uppslag",
  "and define its fields by building its schema so you can fill it with content.": "och ange dess fält genom att bygga dess schema så att du kan fylla det med innehåll.",
  "Will be released at": "Kommer att lanseras den",
  "Show only items from this release": "Visa endast objekt från denna version",
  "Has been published at": "Har publicerats den",
  "Last deployment": "Senaste driftsättning",
  "This branch has never been deployed": "Denna gren har aldrig använts",
  "Release now": "Lansera nu",
  "Open preview": "Öppna förhandsgranskning",
  "Deploy from source": "Använd från källa",
  "You are seeing deleted items": "Du ser raderade objekt",
  "Name (desc)": "Namn (fallande)",
  "Default sorting": "Standardsortering",
  "Name (asc)": "Namn (stigande)",
  "Slug (desc)": "Slug (fallande)",
  "releases": "lanseringar",
  "Slug (asc)": "Slug (stigande)",
  "Created at": "Skapad den",
  "Updated at": "Uppdaterad den",
  "Deleted at": "Raderad den",
  "Are you sure you want to unpublish this item(s)?": "Är du säker på att du vill avpublicera detta/dessa objekt? ",
  "The items have been updated!": "Objekten har uppdaterats\"",
  "Are you sure you want to publish this item(s)?": "Är du säker på att du vill publicera detta/dessa objekt?",
  "Are you sure you want to restore this item(s)?": "Är du säker på att du vill återställa detta/dessa objekt?",
  "Something went wrong restoring some items": "Någonting gick fel när vissa objekt skulle återställas",
  "Something went wrong updating item(s)": "Någonting gick fel vid uppdatering av objekt",
  "No tools installed on this space": "Inga verktyg installerade på detta utrymme",
  "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.": "Raderade objekt kan inte visas. Klicka på objektets kryssruta och återställ vyn.",
  "The content has been released!": "Innehållet har släppts!",
  "Do you really want to copy the content of the default language to the current and replace the existing field value?": "Vill du verkligen kopiera innehållet i standardspråket till det nuvarande och ersätta det befintliga fältvärdet?",
  "Default language": "Standardspråk",
  "Install from the app store": "Installera från app-butiken",
  "Draft updated at": "Utkast uppdaterat den",
  "Never": "Aldrig",
  "Published at": "Publicerad den",
  "Latest workflow changes": "Senaste arbetsflödesändringar",
  "Last author": "Senaste författare",
  "None": "Ingen",
  "Workflow stage": "Arbetsflöde-steg",
  "set by": "inställd av",
  "Assigned to": "Tilldelad till",
  "Update": "Uppdatera",
  "Comments": "Kommentarer",
  "Load older comments": "Ladda äldre kommentarer",
  "Edit": "Redigera",
  "Workflow stage and assignments": "Arbetsflödes-steg och tilldelningar",
  "Add a comment": "Lägg till en kommentar",
  "Assign to": "Tilldela till",
  "Notify users via email": "Meddela användare via e-post",
  "Submit": "Skicka",
  "Lambda Function": "Lambda-funktion",
  "Task type": "Uppgiftstyp",
  "Webhook": "Webhook",
  "The payload of the request contains the task and the space id.": "Nyttolasten i begäran innehåller uppgiften och utrymmes-id.",
  "Lambda Function (coming soon)": "Lambda-funktion (kommer snart)",
  "Provide the endpoint where you want to send a POST request.": "Ange slutpunkt dit du vill skicka en POST-begäran.",
  "Protected variable": "Skyddad variabel",
  "Function code": "Funktionskod",
  "For example:": "Till exempel:",
  "Ok": "Ok",
  "Are you sure you want to delete this task?": "Är du säker på att du vill radera denna uppgift?",
  "Last execution": "Senaste verkställande",
  "Currently running": "Kör för närvarande",
  "Executed successfully!": "Genomförd!",
  "Execute": "Utför",
  "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.": "Välj XML för översättningsprogram som t.ex. SDL Trados Studio eller JSON för översättningsprogram som t.ex. LingoHub.",
  "Autosave enabled?": "Autospara aktiverad?",
  "Empty": "Tom",
  "Choose a compatible XML or JSON generated from the export.": "Välj en kompatibel XML eller JSON som genererats från exporten.",
  "Desktop": "Skrivbord",
  "Tablet": "Surfplatta",
  "Tag": "Tagga",
  "Mobile": "Mobil",
  "Select": "Välj",
  "Content type value": "Innehållstyp värde",
  "Component": "Komponent",
  "Assigned to me only": "Tilldelad endast till mig",
  "In folder": "I mapp",
  "element": "element",
  "Search in current folder only": "Sök endast i aktuell mapp",
  "No results found": "Inga resultat hittades",
  "Current version": "Aktuell version",
  "Start typing to search": "Börja skriva för att söka",
  "Confirming invitation": "Bekräftar inbjudan",
  "Please wait a couple of seconds": "Vänta några sekunder",
  "Unknown author": "Okänd författare",
  "You are now a member of the organisation": "Du är nu en medlem av organisationen",
  "Go to spaces": "Gå till platser",
  "Invitation confirmed!": "Inbjudan bekräftad!",
  "Please login first and then click the invitation link again.": "Logga in först och klicka sedan på länken med inbjudan igen.",
  "Go to login": "Gå till inloggning",
  "Login required.": "Inloggning krävs.",
  "Your invitation is not valid anymore.": "Din inbjudan är inte giltig längre.",
  "Please upgrade your Storyblok space. You have": "Uppgradera ditt Storyblok-utrymme. Du har",
  "Something went wrong.": "Någonting gick fel.",
  "collaborator(s) and your": "medarbetare och dina",
  "Please contact your Storyblok space owner. You have": "Kontakta din Storybloks utrymmesägare. Du har",
  "is over.": "är över.",
  "Just a moment. A background task is still running.": "Ett ögonblick. En bakgrundsuppgift kör fortfarande.",
  "The Storyblok app has been updated!": "Storyblok-appen har uppdaterats!",
  "Please reload the window to get the newest version.": "Ladda om fönstret för att få den senaste versionen.",
  "Reload window": "Ladda fönster igen",
  "Manage": "Hantera",
  "Toggle assistance mode": "Växla assistansläge",
  "Assisted spaces": "Datorstödda utrymmen",
  "Logging in": "Loggar in",
  "Sales": "Försäljning",
  "I have read and agree to the": "Jag har läst och samtycker till",
  "Logged in as": "Inloggad som",
  "Catalogue": "Katalog",
  "Initiating space": "Initierar utrymme",
  "Configuration": "Konfiguration",
  "There was an error confirming your account. Please try again.": "Ett fel inträffade när ditt konto skulle bekräftas. Försök igen.",
  "Resend confirmation": "Skicka bekräftelse igen",
  "Confirmed successfully!": "Bekräftat!",
  "You have unsaved changes on this content item. Do you want to discard your changes?": "Du har ändringar som inte sparats på detta innehållsobjekt. Vill du kasta dina ändringar?",
  "No": "Nej",
  "To continue confirm that you have read and agree to the Terms and Privacy Policy.": "För att fortsätta bekräfta att du har läst och samtycker till villkoren och sekretesspolicyn.",
  "Yes": "Ja",
  "Invitation sent!": "Inbjudan skickad!",
  "Shortcuts: Esc for No, Enter for Yes": "Genvägar: Esc för Nej, Enter för Ja",
  "Usertype": "Användartyp",
  "The user has been invited to your organisation and will be added once confirmed.": "Användaren har bjudits in till din organisation och kommer att läggas till när den har bekräftats.",
  "Normal": "Normal",
  "Member": "Medlem",
  "Provide the 15 digit ID": "Ange det 15-siffriga ID",
  "Is sandbox user?": "Är sandlådeanvändare?",
  "Owner: Can manage users and define owners": "Ägare: Kan hantera användare och definiera ägare",
  "Admin: Can manage users": "Admin: Kan hantera användare",
  "Member: Can not manage users": "Medlem: Kan inte hantera användare",
  "Firstname": "Förnamn",
  "Disable": "Avaktivera",
  "Lastname": "Efternamn",
  "Are you sure you want to disable this user?": "Är du säker på att du vill avaktivera denna användare?",
  "It seems you do not have any": "Du tycks inte ha någon",
  "Enable": "Aktivera",
  "Type in all emails of the users you want to invite separated by a new line.": "Skriv in alla e-postmeddelanden från de användare du vill bjuda in separerat med en ny rad.",
  "Invite others": "Bjud in andra",
  "yet.": "än.",
  "Send": "Skicka",
  "Done!": "Klart!",
  "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).": "Din inbjudan har skickats! Så snart användarna har registrerat sig kan du lägga till dem som medarbetare till ditt/dina utrymme(n)",
  "Please enter at least one email": "Ange minst en e-postadress",
  "Invite more people": "Bjud in fler personer",
  " is not a valid email": " är inte ett giltigt e-postmeddelande",
  "from": "från",
  "Target": "Mål",
  "Asset": "Tillgång",
  "Current window": "Aktuellt fönster",
  "Get started": "Kom igång",
  "New window": "Nytt fönster",
  "terms of use": "användarvillkor",
  "Signup": "Registrera",
  "By clicking \"Signup\" you accept the": "Genom att klicka på \"Registrera\" accepterar du",
  "Switch to login": "Växla till inloggning.",
  "Forgot password?": "Glömt lösenordet?",
  "Already have an account?": "Har du redan ett konto?",
  "No account yet?": "Inget konto än?",
  "Signup here": "Registrera dig här",
  "Login": "Logga in",
  "Resend": "Skicka igen",
  "confirmation email": "bekräftelsemejl",
  "Send password reset link": "Skicka länk för återställning av lösenord",
  "Imprint": "Avtryck",
  "Privacy policy": "Sekretesspolicy",
  "Are you a developer?": "Är du en utvecklare?",
  "Choose no if you want to join an existing project": "Välj nej om du vill gå med i ett befintligt projekt",
  "No, I am not a dev": "Nej, jag är inte en utvecklare",
  "Yes, I am a dev": "Ja, jag är utvecklare",
  "Choose your own adventure": "Välj ditt eget äventyr",
  "Join an existing space": "Gå med i ett befintligt utrymme",
  "What would you do like next?": "Vad vill du göra härnäst?",
  "You are almost there": "Du är nästan klar",
  "Success!": "Genomfört!",
  "Insert the email of your space admin to let them add you as a collaborator of the space": "Ange din utrymmes-admininstratörs e-post så att de kan lägga till dig som medarbetare i utrymmet.",
  "I received the email": "Jag har mottagit e-postmeddelandet",
  "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.": "Du kommer att meddelas via e-post när admin lagt till dig som medarbetare. Klicka sedan på knappen nedan för att fortsätta.",
  "It seems that the authentification code is wrong.": "Autentiseringskoden tycks vara felaktig.",
  "My account": "Mitt konto",
  "Please check the password confirmation.": "Kontrollera bekräftelsen av lösenord.",
  "You are logged in via a third party authentication provider.": "Du är inloggad via en tredjeparts-autentiseringsleverantör.",
  "Profile picture": "Profilbild",
  "Username": "Användarnamn",
  "Your Storyblok ID for adding you as a collaborator to another project is": "Ditt Storyblok-ID för att lägga till dig som medarbetare till ett annat projekt är",
  "Recommended: 500px x 500px (JPG or PNG)": "Rekommenderad: 500px x 500px (JPG eller PNG)",
  "Phone number": "Telefonnummer",
  "Your timezone": "Din tidszon",
  "Your language": "Ditt språk",
  "Current password": "Aktuellt lösenord",
  "Insert your current password if you changed your username, email, phone number, password or security settings": "Ange ditt nuvarande lösenord om du ändrat ditt användarnamn, e-post, telefonnummer, lösenord eller säkerhetsinställningar",
  "New Password": "Nytt lösenord",
  "Do you want to change your current password?": "Vill du ändra ditt nuvarande lösenord?",
  "Password confirmation": "Bekräftelse av lösenord",
  "Security Settings": "Säkerhetsinställningar",
  "How do you want to login?": "Hur vill du logga in?",
  "Password only": "Endast lösenord",
  "Two factor authentication via SMS": "Tvåfaktorautentisering via sms",
  "Personal access tokens": "Personliga åtkomst-tokens",
  "Two factor authentication via Email": "Tvåfaktorautentisering via e-post",
  "Storyblok Management API": "Storyblok Management API",
  "Please copy this api key now. It will be visible only once.": "Kopiera denna api-nyckel nu. Den kommer endast att vara synlig en gång.",
  "Tokens that have been generated to access the": "Tokens som har genererats för att gå till",
  "Generate new Token": "Generera ny token",
  "Personal access tokens work like ordinary OAuth access tokens.": "Personliga åtkomsttokens fungerar som vanliga QAuth-åtkomsttokens.",
  "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.": "De kan användas för att autentisera dig för att få full åtkomst till hanteringen av API programmatiskt och ska ALDRIG visas offentligt.",
  "Privacy": "Sekretess",
  "Show username instead of email as collaborator": "Visa användarnamn istället för e-post som medarbetare",
  "Privacy Setting": "Sekretss-inställning",
  "Download in German": "Ladda ner på tyska",
  "Download in English": "Ladda ner på engelska",
  "Data processing agreement": "Databehandlingsavtal",
  "Read more about our": "Läs mer om vår",
  "Account deletion": "Radering av konto",
  "privacy policy here": "sekretesspolicy här",
  "Yes, delete my account": "Ja, radera mitt konto",
  "Do you want to delete your account?": "Vill du radera ditt konto?",
  "Do you really want to delete your account? Type \"delete me\" and click confirm.": "Vill du verkligen radera ditt konto? Skriv \"Radera mig\" och klicka på bekräfta.",
  "User has been updated": "Användaren har uppdaterats",
  "Not found": "Kunde inte hittas",
  "Please insert the code we sent to ": "Ange koden vi skickade till ",
  "Add user": "Lägg till användare",
  "It seems that you do not have access to this page.": "Du tycks inte ha åtkomst till denna sida.",
  "Create a new organization": "Skapa en ny organisation",
  "Organisation name": "Organisationsnamn",
  "Create org": "Skapa org",
  "SO Settings": "SO-inställningar",
  "Whitelabeling": "Vitmärkning",
  "Add SSO url": "Lägg till SSO-url",
  "Url to the editor": "Url till redigeringsprogrammet",
  "Provide the full url like": "Tillhandahåll den fullständiga url som",
  "Logo-Url": "Logotyp-url",
  "Provide the full url to the logo like": "Tillhandahåll den fullständiga url:en till den logotyp du önskar",
  "Not defined": "Inte angivet",
  "Organization updated successfully": "Organisation uppdaterad",
  "Disabled": "Avaktiverad",
  "Please set your password": "Ställ in ditt lösenord",
  "Set password": "Ställ in lösenord",
  "Password has been set. You can now login.": "Lösenord har ställts in. Nu kan du logga in.",
  "Thank you": "Tack",
  "Please confirm your billing information": "Vänligen bekräfta din faktureringsinformation",
  "Login failed. The login token may expired. Please try again.": "Inloggning misslyckades Inloggningstoken kan ha löpt ut. Försök igen.",
  "Please enter all required information": "Ange all obligatorisk information",
  "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.": "Vi försöker hålla din faktureringsinformation för fakturor uppdaterad. Vänligen bekräfta att nedanstående information är korrekt eller ändra den om det behövs.",
  "One last thing before you can comment": "En sista sak innan du kan kommentera",
  "Profile picture (optional)": "Profilbild (valfritt)",
  "Are you sure you want to delete this item?": "Är du säker på att du vill radera detta objekt?",
  "Help other collaborators to identify you better by providing your name and a profile picture.": "Hjälp andra medarbetare att identifiera dig bättre genom att tillhandahålla ditt namn och en profilbild.",
  "Are you sure you want to delete this item(s)?": "Är du säker på att du vill radera detta/dessa objekt?"
}
