export default {
  "Dashboard": "仪表板",
  "Back to spaces": "返回空间",
  "Content": "内容",
  "Commerce": "商务",
  "Assets": "资产",
  "Datasources": "数据源",
  "Activities": "活动",
  "Tasks": "任务",
  "Components": "组件",
  "Apps": "应用",
  "Settings": "设置",
  "Subscription": "订阅",
  "Plugins": "插件",
  "Logout": "退出",
  "Report a problem": "报告问题",
  "Create new space": "创建新空间",
  "Search spaces...": "搜索空间……",
  "My organization": "我的组织",
  "Subscribe": "订阅",
  "To": "至",
  "From": "从",
  "Apply filter": "应用筛选器",
  "Filter": "筛选",
  "Unknown user": "未知用户",
  "Author": "作者",
  "Action": "操作",
  "Date": "日期",
  "Back": "返回",
  "Activity Details": "活动详情",
  "Open": "打开",
  "Restore this Story": "恢复此故事",
  "Categories": "类别",
  "Story": "故事",
  "The item has been restored!": "该内容项已经被恢复！",
  "All": "全部",
  "Search for apps, discover new field types and add functionalities to your Storyblok project.": "搜索应用、发现新的字段类型并给您的 Storyblok 项目添加功能。",
  "My apps": "我的应用",
  "Create new app": "创建新应用",
  "Installed": "已安装",
  "App Directory": "应用目录",
  "There are no apps in this category.": "在此类别中没有应用。",
  "Install": "安装",
  "Choose the space to install this app": "选择要安装此应用的空间",
  "Can not move asset folder into folder without permissions.": "不能将资产文件夹移动至没有权限的文件夹中。",
  "Can not move asset into folder without permissions.": "无法将资产移动至没有权限的文件夹内。",
  "Can not move asset away from folder without permissions.": "不能将资产移出没有权限的文件夹。",
  "Define the new name of the folder.": "定义文件夹的新名称。",
  "Trashbin": "垃圾桶",
  "Are you sure that you want to delete this folder?": "您是否确定要删除此文件夹？",
  "Add": "添加",
  "Asset folders are not included in the free plan but you can try them in the": "免费计划不包含资产文件夹，但您可以试用它们",
  "New folder will be created in": "新文件夹将被创建于",
  "trial period": "试用期",
  "Can not create asset folder without permission for parent.": "没有父文件夹权限无法创建资产文件夹。",
  "Original": "原始",
  "Done": "完成",
  "Cancel": "取消",
  "Insert": "输入",
  "Add Asset(s)": "添加资产",
  "Close": "关闭",
  "items": "项目",
  "Delete": "删除",
  "Move to folder": "移动至文件夹",
  "Replace": "替换",
  "Unselect all": "取消全部选择",
  "Restore": "恢复",
  "Tiles": "平铺",
  "List": "列表",
  "No assets found": "未发现资产",
  "Sort": "排序",
  "Default": "默认",
  "View": "浏览",
  "Creation date (asc)": "创建日期（升序）",
  "Filename (asc)": "文件名（升序）",
  "Creation date (desc)": "创建日期（降序）",
  "Filename (desc)": "文件名（降序）",
  "Last updated date (asc)": "最后更新日期（升序）",
  "Last updated date (desc)": "最后更新日期（降序）",
  "You are not allowed to insert this filetype here.": "您不得在此插入此文件类型。",
  "This key is already defined": "此键已经被定义",
  "Key is in invalid format": "密钥格式不正确",
  "Something went wrong uploading some items": "上传某些内容项时发生问题",
  "Please choose a folder in the left sidebar": "请在左侧边栏中选择一个文件夹",
  "Define the new name of": "定义新名称",
  "Something went wrong renaming the attribute": "重命名属性时发生问题",
  "Be aware! Changing the name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "当心！ 更改名称可能需要几分钟时间才能够更新所有内容项。 务必确保您的编辑器已经保存其当前工作，然后退出编辑器。",
  "Define the new name of the component group.": "定义组件群的新名称。",
  "Save": "保存",
  "Are you sure that you want to delete this component group?": "您是否确定要删除此组件群？",
  "Copy": "复制",
  "New": "新的",
  "Move to group": "移动到组",
  "Please choose a component group in the left sidebar": "请在左侧边栏中选择一个组件群",
  "Paste": "粘贴",
  "Add block": "添加区块",
  "Creation of a component failed. Maybe it already exists.": "组件创建失败。 可能它已经存在。",
  "Are you sure you want to DELETE this component(s)?": "您是否确定要删除此组件？",
  "new": "新",
  "Type to search or to create a": "输入以搜索或创建一个",
  "Create new": "创建新内容",
  "block": "区块",
  "New Component": "新的组件",
  "Updated": "已更新",
  "Name": "名称",
  "Shortcuts: Esc, Control + S": "快捷键：Esc、Control + S",
  "Next": "下一个",
  "Define a name": "定义一个名称",
  "Save schema": "保存架构",
  "Act as content type (eg. blog-post)": "作为内容类型（例如 博客帖子）",
  "Define": "定义",
  "Nestable": "可嵌套",
  "Technical name": "技术名称",
  "Edit field": "编辑字段",
  "Config": "配置",
  "Schema": "架构",
  "Renaming": "重命名",
  "Change field name": "更改字段名",
  "Used in the json as component name": "在 JSON 文件中用作组件名",
  "Be aware! Changing the technical name can take a few minutes to update all content items. Make sure your editors have saved their current work and exit the editor.": "当心！ 更改技术名称可能需要几分钟时间才能够更新所有内容项。 务必确保您的编辑器已经保存其当前工作，然后退出编辑器。",
  "Display name": "显示名称",
  "Preview template": "预览模板",
  "Screenshot or icon": "截屏或图标",
  "Used in the editor interface only": "仅用于编辑器界面",
  "of this setting": "此项设置",
  "Read the documentation": "阅读文档",
  "Load versions": "载入版本",
  "Versions": "版本",
  "has been added below": "已在下方添加",
  "Examples: news_items, body, columns, title, description or call_to_action_btn": "例如：新闻项、正文、栏目、标题、说明或者行动号召按钮",
  "The component has been restored!": "组件已得到恢复！",
  "Do you really want to leave without saving your changes?": "您是否想要不保存变更就离开？",
  "Type": "类型",
  "Beta": "测试版",
  "Translatable": "可译元素",
  "Allow empty paragraphs": "允许空白段落",
  "Linktype": "链接类型",
  "Rich-text as default": "富文本为默认设置",
  "Custom type": "自定义类型",
  "Category": "类别",
  "Section items": "板块项目",
  "Product": "产品",
  "Customize toolbar": "定制工具栏",
  "Toolbar items": "工具条项目",
  "Source": "来源",
  "CSS class options (label/value)": "CSS 类选项（标签/数值）",
  "Datasource": "数据源",
  "Stories": "故事",
  "Self": "自我",
  "Internal datasource": "内部数据源",
  "Recommended to be checked, as UID is required for automatic link resolving.": "建议勾选，因为 UID 对自动链接解析来说是必要条件。",
  "Use UID instead of ID": "用户 UID 而非 ID",
  "In case you have a multi-language folder structure you can add the {0} placeholder and the path will be adapted dynamically. Examples: {0}/categories/, {0}/{1}/categories/": "如果您有多语言文件夹结构，您可以添加 {0} 占位符，路径将会动态调适。 例如：{0}/categories/, {0}/{1}/categories/",
  "External JSON": "外部 JSON",
  "Path to folder of stories": "故事文件夹路径",
  "Width": "宽度",
  "URL": "URL",
  "ratio": "比率",
  "pixel": "像素",
  "Allowed maximum": "允许最大值",
  "Options (name/value)": "选项（名/值）",
  "Component(s)": "组件",
  "Group(s)": "组",
  "Required field(s) (comma separated)": "必填字段（以逗号分隔）",
  "Required": "必填项",
  "Default asset folder": "默认资产文件夹",
  "Choose an asset folder where the assets should be assigned to.": "选择资产应当归属的资产文件夹。",
  "With {level} the path will be replaced dynamically using parts of the current slug. Examples: {0}/categories/, {0}/{1}/categories/": "通过 {level}，将会使用当前别名的构成部分对路径进行动态替换。 例如：{0}/categories/, {0}/{1}/categories/",
  "Restrict to folder": "仅限于文件夹",
  "Force folder restriction": "强制施加文件夹限制",
  "Regex validation": "正则表达式验证",
  "Exclude from export": "从导出中排除",
  "export app": "导出应用",
  "To use with the": "若要使用",
  "Default value": "默认值",
  "Can be updated by preview window": "可以通过预览窗口加以更新",
  "Loading...": "正在加载……",
  "Item": "项目",
  "Allow only specific components to be inserted": "仅允许插入特定组件",
  "Restrict to content types": "仅限于内容类型",
  "Keep original size": "保持原始尺寸",
  "Force crop": "强制裁剪",
  "Prepend https to url": "将 https 加在网址前",
  "Height": "高度",
  "Maximum characters": "最大字符数",
  "Disable time selection": "禁用时间选择",
  "Description": "说明",
  "dimensions app": "dimensions 应用",
  "Force overwrite by merge action": "通过合并操作强制覆盖",
  "Id/Slug": "ID/别名",
  "Enable RTL (Right to left)": "启用 RTL（从右向左）",
  "Autosave": "自动保存",
  "API Url": "API URL",
  "Export": "导出",
  "Import/Export": "导入/导出",
  "Dimensions": "维度",
  "Add Dimension": "添加 Dimension",
  "Import": "导入",
  "A datasource in Storyblok is a collection of key-value pairs.": "Storyblok 中的数据源是一系列键值对的集合。",
  "Datasources can be used in a schema definition of a component for single or multiple choice options. You can also access": "数据源可用于针对单选或多选选项的组件的架构定义。 您还可以访问",
  "datasource entries from the API": "来自 API 的数据源条目",
  "to use them for labels, categories or similar.": "将它们用于标签、类别或类似领域。",
  "Unsaved Changes": "未保存的变更",
  "Datasource entries": "数据源条目",
  "Datasources are not included in the free plan": "免费计划不包括数据源",
  "but you can try them in the": "但是您可以试用它们",
  "Saved": "已保存",
  "Select all": "全选",
  "The options could not be loaded.": "无法加载选项。",
  "New Datasource": "新的数据源",
  "The following component(s) can not be pasted here": "以下组件不能粘贴在此处",
  "Please save first to continue editing child components.": "请先保存然后再继续编辑子组件。",
  "Enabled?": "已启用？",
  "Asset manager": "资产管理器",
  "Loading": "正在加载",
  "Upload new": "上传新内容",
  "Your file exceeds the maximum filesize limit of": "您的文件超出了文件大小上限",
  "Please reduce the size of your file.": "请缩小您的文件大小。",
  "Alt text": "替换文字",
  "Base64": "Base64",
  "Original Size": "原始尺寸",
  "Image loading failed": "图片加载失败",
  "Quote": "引述",
  "Code Block": "代码块",
  "Ordered List": "排序列表",
  "Headline 2": "标题 2",
  "Headline 4": "标题 4",
  "Headline 3": "标题 3",
  "Headline 5": "标题 5",
  "Paragraph": "段落",
  "Help": "帮助",
  "Internal link": "内部链接",
  "Show only selected": "仅显示已选定的",
  "more items found": "发现更多项目",
  "Invoices": "发票",
  "Tip: Use Ctrl + S to save": "小诀窍：使用 Ctrl + S 进行保存",
  "Input": "输入",
  "Publish": "发布",
  "You are not allowed to edit this plugin but can see the code at Settings/Details.": "您不得编辑此插件但是可以在“设置/详情”中查看其代码。",
  "Field type preview": "字段类型预览",
  "Options (key/value)": "选项（键/值）",
  "Space Id": "空间 ID",
  "Enable local dev mode": "启用本地开发模式",
  "Settings/Details": "设置/细节",
  "Output": "输出",
  "for approval to make it available for all users.": "等待审批，使其对所有用户可用。",
  "Submit the plugin": "提交插件",
  "Code": "编码",
  "You can copy the code of this plugin to create your own plugin.": "您可以复制此插件的代码以创建您自己的插件。",
  "Assigned spaces": "已分配的空间",
  "If you assign this plugin to a space other developers can also use it in the schema definition. Without assigning it only you can add the plugin to the schemas.": "如果您将此插件分配至某个空间，则其他开发人员也能够在架构定义中使用它。 如果不分配的话，则只有您能够将该插件添加至架构中。",
  "Attention: All spaces using this plugin will not be able to use it any more if you click delete.": "注意：如果您点击删除，则所有使用此插件的空间将不能再使用它。",
  "Documentation": "文档",
  "Danger zone": "危险区域",
  "What is a field type plugin?": "什么是字段类型插件？",
  "A field type plugin extends the Storyblok editor with your own custom field types.": "字段类型插件以您自己的自定义字段类型对 Storyblok 编辑器加以扩展。",
  "It is basically a": "它基本上是一个",
  "The properties that are passed to the field type are:": "被传递至字段类型的属性是：",
  "component extended with a few helpers in the window.Storyblok.plugin mixin.": "以 window.Storyblok.plugin mixin 构成并以多个帮助器加以扩展的组件。",
  "Examples for field types are colorpickers, WYSYWYG editors or meta tags.": "字段类型的示例为拾色器、WYSYWYG 编辑器或元标记。",
  "Uid of the parent component": "父组件的唯一标识符",
  "Options parsed from the schema options array": "从架构选项数组解析的选项",
  "Schema options object": "架构选项对象",
  "Current value of the fieldtype": "字段类型的当前值",
  "Story id of the current story": "当前故事的故事编号",
  "Space id of the current space": "当前空间的空间编号",
  "Api function to call the delivery api": "用于调用分发 API 的 API 函数",
  "Methods": "方法",
  "Draft token of the current space": "当前空间的初拟令牌",
  "How to call the Storyblok api?": "如何调用 Storyblok API？",
  "Should be used to define the initial data of the plugin.": "应当被用于定义该插件的初始数据。",
  "Should be used to initialize the plugin. Examples: Load data from Storyblok or external sources, Load and initialize a WYSIWYG editor.": "应当被用于对插件进行初始化。 例如：从 Storyblok 或外部来源加载数据、加载和初始化一个 WYSIWYG 编辑器。",
  "To pass options that are configurable in the schema definition define the option keys in the \"Input\" box. The values will be available in the this.options object.": "若要传递在架构定义中可配置的选项，在“输入”框中定义选项键。 该值在 this.options 对象中可用。",
  "How to pass options?": "如何传递选项？",
  "In field types you can use this.api to get access to the Storyblok delivery api. You can use it for example to build a selectbox of stories.": "在字段类型中您可以使用 this.api 访问 Storyblok 内容分发 API。 例如，您可以使用它构建一组故事。",
  "Folder/Content-item permissions": "文件夹/内容项权限",
  "Item saved successfully!": "内容项保存成功！",
  "Source of sync": "同步来源",
  "Preview": "预览",
  "Preview url": "预览 URL",
  "View on Jsfiddle": "在 Jsfiddle 上查看",
  "Download": "下载",
  "Admin": "管理员",
  "Permissions": "权限",
  "Editor": "编辑器",
  "Advanced Rights": "高级权利",
  "Allow saving content": "允许保存内容",
  "Allow publishing content": "允许发布内容",
  "Allow saving datasources": "允许保存数据源",
  "Allow managing subscription": "允许管理订阅",
  "Allow access to ecommerce app": "允许访问电子商务应用",
  "Deny access to visual composer": "拒绝访问可视化编辑器",
  "Field Permissions": "字段权限",
  "General": "一般",
  "Allowed path": "允许的路径",
  "Your crawl URL": "您的爬网 URL",
  "Crawler": "网络爬虫",
  "Enabled": "已启用",
  "Index": "索引",
  "Crawl now": "立即爬网",
  "Information needed to access the search endpoint or to configure the search client.": "访问搜索端点或配置搜索所需要的信息。",
  "Search Setup Guide": "搜索设置指南",
  "Your tenant ID": "您的租户 ID",
  "See": "查看",
  "Documents in index": "索引中的文档",
  "Crawl requested at": "爬网请求",
  "Tenant ID": "租户 ID",
  "Documents": "文档",
  "Clear index": "清除索引",
  "Last crawled at": "最后爬网日期",
  "Crawl has been initiated": "已启动爬网操作",
  "In the first 14 days you can try out all Premium plan features!": "在头 14 天您可以尝试所有高级计划功能！",
  "Index deletion has been initiated": "已启动索引删除操作",
  "API-Keys": "API 密钥",
  "We would love to hear your thoughts about Storyblok on": "我们很想听听您对 Storyblok 的看法",
  "Renderer": "渲染器",
  "Backup": "备份",
  "Users": "用户",
  "Workflow": "工作流",
  "Search": "搜索",
  "Languages": "语言",
  "This is the page that the frontend-editor opens.": "这是前端编辑器打开的页面。",
  "Location (default environment)": "地点（默认环境）",
  "Insert your domain/location including the protocol. Example: http://www.example.com/": "输入您的域/网址并包括协议在内。 例如：http://www.example.com/",
  "Provide this ID in your support tickets": "在您的支持服务工单中提供此编号",
  "Your space ID": "您的空间 ID",
  "Preview urls": "预览网址",
  "Define multiple domains/locations to quickly switch the preview urls in the story-editor.": "定义多个域/地点以便在故事编辑器中快速切换预览网址。",
  "Add preview url": "添加预览 URL",
  "Webhooks": "Webhook",
  "Story published & unpublished": "已发布和未发布的故事",
  "Story saved": "故事已保存",
  "Branch deployed": "分支已得到部署",
  "Release merged": "发布项已合并",
  "Slack integration": "Slack 集成",
  "Loading... You will be redirect to Slack in a few seconds!": "正在加载…… 您将在几秒钟后被重定向至 Slack！",
  "Get notified on your Slack channel if a new Story has been published!": "当发布新故事时在您的 Slack 频道上获取通知！",
  "With this integration you can choose a Slack channel where Storyblok posts messages whenever a user publishes new content.": "借助此集成，您可以选择一个 Slack 频道作为用户发布新内容时 Storyblok 发布消息之处。",
  "Disconnect": "断开连接",
  "Cloud name": "云名称",
  "Cloudinary integration": "Cloudinary 集成",
  "Api Key": "Api 密钥",
  "Branches": "分支",
  "Default content type": "默认内容类型",
  "Content types": "内容类型",
  "Name of the branch": "分支的名称",
  "Branches are not included in the free plan": "分支不包括在免费计划中。",
  "Duplication": "复制",
  "This is useful if you want to offer your space for other users as a boilerplate or theme.": "如果您希望将您的空间作为样板文件或主题提供给其他用户的话，那么这很有用。",
  "ATTENTION! Only check this checkbox if you are sure that you want all data of this space available for duplication.": "注意！ 只有在您确定要复制该空间所有可用数据时才可以勾选此复选框。",
  "Make this space duplicatable by all users": "使这个空间可被所有用户复制",
  "Content ownership": "内容所有权",
  "Parent ID": "父 ID",
  "Parent": "父级",
  "Image service": "图片服务",
  "Content ownership client endpoint": "内容所有权客户端端点",
  "List of paths to invalidate": "要作废的路径列表",
  "Delete this space": "删除此空间",
  "Invalidate": "作废",
  "Workflow webhooks": "工作流 webhook",
  "Owner": "所有者",
  "Workflow changed": "工作流已变更",
  "Transfer ownership": "让渡所有权",
  "Transfer": "转让",
  "Attention! Transferring the ownership will remove all your rights to this space.": "注意！ 让渡所有权将会清除您对此空间的所有权限。",
  "The owner needs to add you as a collaborator if you want to have access again.": "如果您想要重新拥有访问权限，则所有者必须将您添加为合作者。",
  "Collaborators": "合作者",
  "Collaborator": "合作者",
  "No user found with this email or username.": "未发现使用此电子邮件或用户名的用户。",
  "Name of the role": "角色名称",
  "Role": "角色",
  "Add a new user to your org": "添加一位新用户至您的组织",
  "Advanced rights and roles are not included in the free and basic plan": "高级权限和角色不包括在免费和基本计划中",
  "Use your Amazon S3 bucket to create backups.": "使用您的亚马逊 S3 存储桶创建备份。",
  "Backup now": "立即备份",
  "Backups content (stories) and compontents": "备份内容（故事）和组件",
  "Define your S3-Bucket and AWS-ARN to enable backups.": "定义您的 S3 存储桶和 AWS-ARN 以启用备份。",
  "Daily backups": "每日备份",
  "Define the name of the S3-bucket where you want to store your backups.": "定义您希望用于存储备份文件的 S3 存储桶名称。",
  "S3-bucket": "S2 存储桶",
  "Activate automatic daily backups": "激活自动每日备份",
  "1. Read the": "1. 浏览",
  "AWS Policy ARN": "AWS 策略 ARN",
  "Show setup instructions": "显示设置指南",
  "tutorial on how to setup an Amazon IAM role": "亚马逊 IAM 角色设置指南",
  "2. Create an Amazon IAM role with following access policy document:": "2. 使用以下访问策略文档创建一个亚马逊 IAM 角色：",
  "if not done yet.": "如果还没有完成的话。",
  "The role should have the permission to access and create files on the S3 bucket you defined. You can for example use the following permission policy replacing YOUR_BUCKET with your bucket name:": "角色应当有权访问您所定义的 S3 存储桶并在上面创建文件。 例如，您可以使用以下权限策略将 YOUR_BUCKET 替换为您的存储桶名称：",
  "Restore spaces from backups on your Amazon S3 bucket.": "从您的亚马逊 S3 存储桶中恢复空间。",
  "Backup file": "备份文件",
  "Show latest backups": "显示最新备份",
  "Latest five backups": "最近五次备份",
  "Restore now": "立即恢复",
  "The settings below only apply if you are using": "以下设置适用的前提是您正在使用",
  "Attention! \"Restore now\" deletes old data and restores content (stories) and compontents from the backup file.": "注意！ “立即恢复”删除旧数据并从备份文件中恢复内容（故事）和组件。",
  "Rendering service": "渲染服务",
  "Your domain": "您的网域",
  "To connect your domain to Storyblok you need to create a CNAME Record pointing to eu-domain.storyblok.com": "为了将您的网域连至 Storyblok，您需要创建一个指向 eu-domain.storyblok.com 的 CNAME 记录",
  "Routes": "路由",
  "Add Route": "添加路由",
  "Please read the": "请阅读",
  "Add custom routes to define different page templates.": "添加自定义路由以定义不同页面模板。",
  "documentation about internationalization": "关于国际化的文档",
  "before configuring languages.": "在配置语言之前。",
  "Add languages to activate field level translations.": "添加语言以激活字段级别翻译。",
  "Add Language": "添加语言",
  "Label": "标签",
  "The invalidation process has been initiated": "已启动作废过程",
  "The backup has been initiated": "已启动备份",
  "Are you sure you want to delete your current content and overwrite it with this backup?": "您是否确定要删除当前内容并以此备份覆盖它？",
  "The restore process has been initiated": "已启动恢复流程",
  "Transfer was not successful. Make sure that the new owner exists.": "转让未成功。 确保存在新的所有者。",
  "The collaborator has been added": "已添加合作者",
  "Please insert an email address": "请输入电子邮件地址",
  "Branches sorted successfully!": "分支排序成功！",
  "Create or join a space": "创建或加入一个空间",
  "Create a new space": "创建一个新的空间",
  "Play with a demo": "体验演示",
  "Duplicate a space": "复制一个空间",
  "Join a space": "加入一个空间",
  "Create space": "创建空间",
  "Headless (API/SDKs)": "无头 (API/SDK)",
  "what is that?": "那是什么？",
  "Duplicate space": "复制空间",
  "Choose the space for the duplication": "选择要复制的空间",
  "You do not have created any spaces yet.": "您还没有创建任何空间。",
  "You can test the editing interface and our visual composer without to write any code on your own.": "您可以测试编辑界面和我们的可视化编辑器，不用自己编写代码。",
  "Create Demo": "创建演示",
  "Insert the email of your space admin to let them add you as a collaborator of the space.": "输入您的空间管理员的名称以便让他们把您添加为该空间的合作者。",
  "Request access": "请求访问",
  "Email address of space admin": "空间管理员的电子邮件地址",
  "Success! You will get notified once the admin added you as a collaborator.": "成功！ 您在管理员将您添加为合作者后会收到通知。",
  "Available Billing Information": "可用账单信息",
  "No spaces with billing information available": "无包含账单信息的空间可用",
  "Spaces": "空间",
  "Show More": "显示更多",
  "Apply": "应用",
  "Show": "显示",
  "Billing Information of Space": "空间的账单信息",
  "The information below will be applied to the fields of your current subscription process. You will be able to adopt them after applying them.": "下方信息将被应用于您当前订阅流程所包含的字段。 您将能够在应用后采用它们。",
  "Company": "公司",
  "Country": "国家",
  "Street / City / ZIP": "街道/城市/邮编",
  "Email": "电子邮件",
  "Add or change preview urls": "添加或更改预览网址",
  "Your server address": "您的服务器地址",
  "1. Download a preconfigured project": "1. 下载一个预配置的项目",
  "Preferred by our users": "我们的用户首选",
  "The downloaded package comes preconfigured with your api token": "已下载的工具包预配置了您的 API 令牌",
  "Tutorial": "教程",
  "Other technologies": "其他技术",
  "2. Start your server": "2. 启动您的服务器",
  "Start the server of the downloaded package and insert your server url here:": "启动下载包的服务器并在此输入您的服务器网址：",
  "Go": "前往",
  "FAQ": "常见问题",
  "Can I build a full blown website with Storyblok?": "我能否使用 Storyblok 搭建一个功能完善的网站？",
  "Can I create a blog with Storyblok?": "我能否使用 Storyblok 创建一个博客？",
  "How does Storyblok work?": "Storyblok 如何运作？",
  "What is the Storyblok bridge?": "什么是 Storyblok 桥？",
  "Allow deploying content": "允许部署内容",
  "General permissions": "一般权限",
  "Allow unpublishing content": "允许取消发布内容",
  "Allow deleting content": "允许删除内容",
  "Allow editing datasource keys & values": "允许编辑数据源键和值",
  "Allow editing datasource values": "允许编辑数据源值",
  "Allow access to the tasks app": "允许访问任务应用",
  "Deny moving a story": "拒绝移动一个故事",
  "Deny changing alternates group": "拒绝变更替代条目组",
  "Add languages the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "添加用户应当有访问权限的语言（作为白名单）。 如果没有选择内容项，则用户有权编辑所有内容。",
  "Deny changing the slug of a story": "拒绝变更故事的别名",
  "Add folders or content items the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all content.": "添加用户应当有访问权的文件夹或内容（起白名单作用）。 如果没有选择内容项，则用户有权编辑所有内容。",
  "Component field permissions": "组件字段权限",
  "Datasource permissions": "数据源权限",
  "Add component fields here to hide them in the interface.": "在此添加要在界面中予以隐藏的组件字段。",
  "Add datasources the user should have access to (acts as whitelist). If no item is selected the user has rights to edit all datasources.": "添加用户应当有访问权限的数据源（作为白名单）。 如果没有选择任何项目，则用户有权编辑所有数据源。",
  "Asset Folder Permissions": "资产文件夹权限",
  "Add asset folders to restrict editing and upload access.": "添加资产文件夹以限制编辑和上传访问权限。",
  "Start by selecting a space in the sidebar or create a new space.": "首先在边栏中选择一个空间或新建一个空间",
  "It seams that you do not have access to any space yet. Please contact the administrator of your organization to get added as a collaborator.": "似乎您还没有访问任何空间的权限。 请联系贵组织的管理员将您添加为合作者。",
  "Welcome!": "欢迎！",
  "Traffic": "流量",
  "Learn more about": "详细了解",
  "Api requests": "API 请求",
  "Active Plan": "有效计划",
  "Usage": "使用情况",
  "Content activities": "内容活动",
  "No billing": "无记账",
  "Change": "变更",
  "Billed": "已入账",
  "No recent changes": "无近期更改",
  "Choose your plan": "选择您的计划",
  "Recent changes": "近期变更",
  "Custom": "自定义",
  "Compare": "比较",
  "user": "用户",
  "Got a custom plan or coupon code?": "有一个自定义计划或优惠码？",
  "Custom plan": "定制计划",
  "Entered plan ids will be validated after pressing subscribe.": "在按下订阅按钮后会对所输入的计划编号加以确认。",
  "Coupon code": "优惠码",
  "Entered coupon codes will be validated and applied after pressing subscribe.": "已输入的优惠码将在点击订阅按钮后得到确认和应用。",
  "Select seats": "选择座位",
  "Confirm subscription": "确认订阅",
  "Min": "最小值",
  "Max": "最大值",
  "By clicking the button below the new subscription will start.": "点击下方按钮则将启动新订阅。",
  "Decide payment interval": "决定支付间隔期",
  "Change subscription": "变更订阅计划",
  "Monthly": "每月",
  "Annually": "每年",
  "Define billing information": "定义账单信息",
  "Email address": "电子邮件地址",
  "VAT-Number": "增值税号",
  "Reuse from another space": "重复利用其他空间内容",
  "Order number": "订单号",
  "Street": "街道",
  "City": "城市",
  "Credit or debit card": "信用卡或借记卡",
  "ZIP": "邮编",
  "Enter payment information": "输入支付信息",
  "Update payment information": "更新支付信息",
  "Update billing information": "更新账单信息",
  "Information: Our payment provider validates card information when it is saved. As a result of this process, you may see a temporary authorization for $1 on your statement.": "信息：我们的支付服务提供商会在保存卡片信息时对其加以验证。 这一操作过程会导致您在交易账单上看到 1 美元的临时授权。",
  "Please provide all billing informations marked as required (*)": "请提供所有标为必填  (*) 的账单信息",
  "Your selected team sizes are not in the limits of your selected feature set. You can select another feature set to continue.": "您所选择的团队规模超出您所选择的特征集的限制范围。 您可以选择其他特征集以继续。",
  "View invoices": "查看发票",
  "Summary": "总结",
  "Please provide a credit or debit card": "请提供信用卡或借记卡",
  "If your entered plan is not correct you will still be able to try it again.": "如果您输入的计划不正确，您仍能够重新尝试。",
  "You have entered a custom plan with a special offering and pricing": "您已经输入了一个包含特别优惠和定价的定制计划",
  "users": "用户",
  "VAT reverse charge applies.": "适用增值税反向征收。",
  "VAT": "增值税",
  "Total": "总计",
  "The benefits of the coupon code will be applied if available": "若可用，则该折扣码的优惠将得到适用",
  "Thanks! You are awesome!": "谢谢！ 您太棒了！",
  "We would love to hear what you think about Storyblok.": "我们很想听听您对 Storyblok 的看法。",
  "Chat with us or": "洽询我们或",
  "your feedback.": "您的反馈。",
  "Tweet": "推文",
  "Star": "星级",
  "Share": "分享",
  "Public access tokens are only for accessing the published version while preview tokens are for accessing the draft version also. Both are read-only tokens.": "公共访问令牌仅用于访问已发布版本，而预览令牌则还可用于访问访问草稿版本。 两者都是只读令牌。",
  "Access level": "访问级别",
  "Public": "公开",
  "See API-Documentation": "查阅 API 文档",
  "Theme": "主题",
  "Branch": "分支",
  "Choose branch": "选择分支",
  "Create Token": "创建令牌",
  "Color": "颜色",
  "Define as default stage for new content items": "定义为新内容项的默认阶段",
  "Publishing rights": "发布权",
  "Stage transition rules": "阶段转换规则",
  "Allow users to publish or schedule the content": "允许用户发布内容或将其列入计划",
  "Specific stage(s)": "特定阶段",
  "Next available stages": "下一个可用阶段",
  "All stages": "所有阶段",
  "All users": "所有用户",
  "User(s)/Role(s) who can change the stage": "可以更改阶段的用户/角色",
  "to the next available stage": "至下一可用阶段",
  "Specific user(s)/role(s)": "特定用户/角色",
  "Role(s)": "角色",
  "User(s)": "用户",
  "Workflow stages": "工作流阶段",
  "See workflow documentation": "查看工作流文档",
  "Create": "创建",
  "Choose an approver": "选择一个审批者",
  "Workflow stages sorted successfully!": "工作流阶段成功排序！",
  "Are you sure you want to delete this workflow stage?": "您是否确定要删除这个工作流阶段？",
  "Send for approval": "送去审批",
  "Approval request has been sent successfully!": "审批请求已成功发送！",
  "Content items": "内容项",
  "Entry": "条目",
  "Define schema": "定义架构",
  "Folder": "文件夹",
  "You have not defined any schema for this block yet.": "您还没有为这个区块定义任何架构。",
  "Define presets": "定义预设值",
  "Click \"Define schema\" to add the fields you need.": "点击“定义架构”以添加您需要的字段。",
  "No valid fields defined in this section yet.": "此板块尚未定义有效字段。",
  "is already part of another section": "已经是其他板块的构成部分",
  "Translate": "翻译",
  "Choose to delete the values or add the schema keys.": "选择删除值或添加架构键。",
  "items out of schema": "架构外的内容项",
  "We have found values which are not part of the schema.": "我们发现了不属于该架构的值。",
  "No changes found": "未发现更改",
  "Changes": "变更",
  "Remove all": "全部清除",
  "Select releases to deploy": "选择要部署的发布项",
  "What is getting deployed?": "什么是得到部署？",
  "All content that is currently on the source branch and the releases you select.": "所有当前在源分支上和您所选发布项上的内容。",
  "No releases found on the source branch": "源分支上没有发现任何发布",
  "A newer version of this content item has been found in the database.": "在数据库中发现了此内容的一个较新版本。",
  "Confirm": "确认",
  "Choose the conflict solution": "选择冲突解决方案",
  "Copy over": "复制",
  "Opens newer version in a new window to let you copy over your changes.": "在新窗口中打开更新的版本以便能够复制您的变更。",
  "Overwrite": "覆盖",
  "Slug": "别名",
  "Overwrites newer version with your changes.": "用您的更改覆盖较新的版本。",
  "Define as root for the folder": "定义为文件夹根目录",
  "Preset": "预设",
  "Content type": "内容类型",
  "Confirm deletion": "确认删除",
  "Are you sure that you want to delete this item(s)?": "您是否确定要删除此项？",
  "Include associated alternates": "包括相关替代项",
  "Target-Folder": "目标文件夹",
  "Is alternative version of the duplicate?": "是复制内容的备用版本？",
  "Duplicate": "复制",
  "Schedule": "计划表",
  "duplicated": "重复",
  "You are not allowed to duplicate this story.": "您不得复制此故事。",
  "Open published": "打开已发布",
  "Send approval": "发送审批",
  "Open draft": "打开草稿",
  "Unpublish": "取消发布",
  "Draft json": "草稿版 json",
  "Discard changes": "放弃更改",
  "Start sync": "开始同步",
  "Published json": "已发布的 JSON",
  "Status": "状态",
  "Tools": "工具",
  "Real path": "真实的路径",
  "Settings for the folder content": "文件夹内容的设置",
  "Disable visual composer": "禁用可视编辑器",
  "Clone to all": "克隆至全部",
  "Deny changing content type": "拒绝变更内容类型",
  "Merge to all": "合并至全部",
  "Dimensions are only available if you are editing a content item in a subfolder.": "只有当您在子文件夹中编辑内容项时 Dimensions 才可用。",
  "Create a folder structure where the first folder defines your dimension (Example: de/home, en/home).": "创建一个文件夹结构，在其中第一个文件夹将定义您的维度（例如：de/home、en/home）",
  "Not created yet": "尚未创建",
  "Create clone": "创建克隆项",
  "Merge": "合并",
  "Something went wrong merging the alternate(s)": "合并替代条目时发生问题",
  "The alternate(s) have been created!": "已创建替代项！",
  "The alternate(s) have been merged!": "替代项合并完成！",
  "Add preset": "添加预设项",
  "Presets are blocks filled with the content you currently have in the selected block.": "预设项是填写您在选定区块中当前已有内容的区块。",
  "Something went wrong creating the alternate(s)": "创建替代项时发生问题",
  "The saved presets are shown for all users at the selection of new blocks.": "选择新区块时将显示对所有用户已保存的预设项。",
  "Existing presets": "已有预设项",
  "As default": "默认",
  "Release date (optional)": "发布日期（可选）",
  "Branches to deploy": "要部署的分支",
  "When the release gets merged all content will be automatically deployed to the selected branches.": "当发布被合并时，所有内容都会被自动部署至所选择的分支。",
  "Entry configuration": "条目配置",
  "Editmode": "编辑模式",
  "Are you sure you want to delete this release?": "你是否确定要删除此发布？",
  "Form only": "仅表单",
  "Visual": "可视",
  "Tags": "标签",
  "Sort by date": "按日期排序",
  "First published date": "第一次发布日期",
  "Remove": "移除",
  "Alternative versions": "备用版本",
  "Search for the content group of this story.": "搜索此故事的内容组。",
  "Shortcut": "快捷方式",
  "Pin as shortcut in the mini-browser": "在迷你浏览器中固定为快捷键",
  "Current": "当前",
  "New release": "新发布",
  "Skip this step": "跳过此步骤",
  "Move": "移动",
  "Next step": "下一步",
  "We have already done that for you. Open the entry \"Home\" below to play around.": "我们已经为您做好了。 打开下方的“Home”条目体验一下。",
  "Create a demo page": "创建演示页面",
  "Create a new folder": "创建一个新文件夹",
  "Create your first folder": "创建您第一个文件夹",
  "and define a new content type during the folder set-up.": "并在文件夹设置过程中定义一个新的内容类型。",
  "Create your first entry": "创建您的第一个条目",
  "Create entry": "创建条目",
  "and define its fields by building its schema so you can fill it with content.": "并且通过建立其架构定义其字段，从而您能够在其中填写内容。",
  "Will be released at": "将发布于",
  "Show only items from this release": "仅显示此次发布中的内容项",
  "Has been published at": "已被发布于",
  "Last deployment": "上次部署",
  "This branch has never been deployed": "此分支从未被部署",
  "Release now": "立即发布",
  "Open preview": "打开预览",
  "Deploy from source": "从源头部署",
  "You are seeing deleted items": "您正在查看已被删除的内容项",
  "Name (desc)": "名称（降序）",
  "Default sorting": "默认排序",
  "Name (asc)": "名称（升序）",
  "Slug (desc)": "别名（降序）",
  "releases": "发布",
  "Slug (asc)": "别名（升序）",
  "Created at": "创建日期",
  "Updated at": "更新日期",
  "Deleted at": "删除日期",
  "Are you sure you want to unpublish this item(s)?": "您是否确定要取消发布此内容项？",
  "The items have been updated!": "该内容项已得到更新！",
  "Are you sure you want to publish this item(s)?": "您是否确定要发布该内容项？",
  "Are you sure you want to restore this item(s)?": "您是否确定要恢复此内容项？",
  "Something went wrong restoring some items": "恢复一些内容项时发生问题",
  "Something went wrong updating item(s)": "更新内容项时发生问题",
  "No tools installed on this space": "此空间尚未安装任何工具。",
  "Deleted items can not be viewed. Please click the checkbox of the item and restore to view.": "删除不能查看的内容项。 请点击该内容项的复选框并恢复以便查看。",
  "The content has been released!": "内容已发布！",
  "Do you really want to copy the content of the default language to the current and replace the existing field value?": "您是否确实想要复制默认语言的内容到当前语言并替换现有字段值？",
  "Default language": "默认语言",
  "Install from the app store": "从应用商店安装",
  "Draft updated at": "草稿更新日期",
  "Never": "从不",
  "Published at": "发布日期",
  "Latest workflow changes": "最新工作流变更",
  "Last author": "上一位作者",
  "None": "无",
  "Workflow stage": "工作流阶段",
  "set by": "设置人",
  "Assigned to": "分配至",
  "Update": "更新",
  "Comments": "评论",
  "Load older comments": "载入早前的评论",
  "Edit": "编辑",
  "Workflow stage and assignments": "工作流阶段和分配",
  "Add a comment": "添加一则评论",
  "Assign to": "分配至",
  "Notify users via email": "通过电子邮件通知用户",
  "Submit": "提交",
  "Lambda Function": "Lambda 函数",
  "Task type": "任务类型",
  "Webhook": "Webhook",
  "The payload of the request contains the task and the space id.": "该请求的有效负债包含任务和空间编号。",
  "Lambda Function (coming soon)": "Lambda 函数（即将推出）",
  "Provide the endpoint where you want to send a POST request.": "提供您希望发送 POST 请求的端点。",
  "Protected variable": "受保护变量",
  "Function code": "功能码",
  "For example:": "例如：",
  "Ok": "好的",
  "Are you sure you want to delete this task?": "您是否确定要删除此任务？",
  "Last execution": "上次执行",
  "Currently running": "当前正在运行",
  "Executed successfully!": "成功执行！",
  "Execute": "执行",
  "Choose XML for translation software like SDL Trados Studio or JSON for translation software like LingoHub.": "对于 SDL Trados Studio 之类的翻译软件请选择 XML，对于 LingoHub 等翻译软件请选择 JSON。",
  "Autosave enabled?": "已启用自动保存？",
  "Empty": "空白",
  "Choose a compatible XML or JSON generated from the export.": "选择导出后生成的兼容 XML 或 JSON 文件。",
  "Desktop": "桌面",
  "Tablet": "平板",
  "Tag": "标签",
  "Mobile": "移动设备",
  "Select": "选择",
  "Content type value": "内容类型值",
  "Component": "组件",
  "Assigned to me only": "仅分配给我",
  "In folder": "在文件夹中",
  "element": "元素",
  "Search in current folder only": "仅在当前文件夹内搜索",
  "No results found": "未发现结果",
  "Current version": "当前版本",
  "Start typing to search": "开始输入以搜索",
  "Confirming invitation": "正在确认邀请",
  "Please wait a couple of seconds": "请稍等几秒钟",
  "Unknown author": "未知作者",
  "You are now a member of the organisation": "您现在已经是组织成员",
  "Go to spaces": "前往空间",
  "Invitation confirmed!": "邀请已得到确认！",
  "Please login first and then click the invitation link again.": "请先登录，然后再次点击邀请链接。",
  "Go to login": "前往登录",
  "Login required.": "需要登录。",
  "Your invitation is not valid anymore.": "您的邀请已失效。",
  "Please upgrade your Storyblok space. You have": "请升级您的 Storyblok 空间。 您有",
  "Something went wrong.": "发生问题了。",
  "collaborator(s) and your": "合作者和您的",
  "Please contact your Storyblok space owner. You have": "请联系您的 Storyblok 空间所有者。 您有",
  "is over.": "已结束。",
  "Just a moment. A background task is still running.": "稍等。 后台任务仍在运行。",
  "The Storyblok app has been updated!": "Storyblok 应用已更新！",
  "Please reload the window to get the newest version.": "请重新载入窗口以获取最新版本。",
  "Reload window": "重新加载窗口",
  "Manage": "管理",
  "Toggle assistance mode": "切换辅助模式",
  "Assisted spaces": "辅助空间",
  "Logging in": "登录中",
  "Sales": "销售",
  "I have read and agree to the": "我已经阅读并同意",
  "Logged in as": "登录身份",
  "Catalogue": "目录",
  "Initiating space": "初始化空间",
  "Configuration": "配置",
  "There was an error confirming your account. Please try again.": "确认您的账户时发生错误。 请重试。",
  "Resend confirmation": "重新发送确认函",
  "Confirmed successfully!": "成功得到确认！",
  "You have unsaved changes on this content item. Do you want to discard your changes?": "您在此内容项上有未保存的变更。 您是否希望放弃您的变更？",
  "No": "否",
  "To continue confirm that you have read and agree to the Terms and Privacy Policy.": "若要继续操作，请确认您已阅读并同意条款和隐私政策。",
  "Yes": "是",
  "Invitation sent!": "邀请已发送！",
  "Shortcuts: Esc for No, Enter for Yes": "快捷键：Esc 退出键表示“否”，Enter 回车键表示“是”",
  "Usertype": "用户类型",
  "The user has been invited to your organisation and will be added once confirmed.": "用户已被邀请加入您的组织，一旦确认后即可加入。",
  "Normal": "普通",
  "Member": "成员",
  "Provide the 15 digit ID": "提供 15 位编号",
  "Is sandbox user?": "是否沙盒用户？",
  "Owner: Can manage users and define owners": "所有者：能够管理用户并定义所有者",
  "Admin: Can manage users": "管理员：可以管理用户",
  "Member: Can not manage users": "成员：不能管理用户",
  "Firstname": "名字",
  "Disable": "停用",
  "Lastname": "姓氏",
  "Are you sure you want to disable this user?": "您是否确定要禁用此用户？",
  "It seems you do not have any": "似乎您还没有任何",
  "Enable": "启用",
  "Type in all emails of the users you want to invite separated by a new line.": "输入您想要邀请的所有用户的电子邮件并以新行符加以分隔。",
  "Invite others": "成功！",
  "yet.": "。",
  "Send": "发送",
  "Done!": "完成！",
  "Your invitation has been sent! As soon as the users have signed up you can add them as collaborators to your space(s).": "您的邀请已被发送！ 一旦用户注册，您就可以将其添加为您的空间额合作者。",
  "Please enter at least one email": "请输入至少一个电子邮件",
  "Invite more people": "邀请更多人",
  " is not a valid email": " 不是有效的电子邮件",
  "from": "从",
  "Target": "目标",
  "Asset": "资产",
  "Current window": "当前窗口",
  "Get started": "入门指南",
  "New window": "新窗口",
  "terms of use": "使用条款",
  "Signup": "注册",
  "By clicking \"Signup\" you accept the": "点击“注册”即表明您接受",
  "Switch to login": "切换至登录",
  "Forgot password?": "忘记密码？",
  "Already have an account?": "已经有账户了？",
  "No account yet?": "还没有账户？",
  "Signup here": "在此注册",
  "Login": "登录",
  "Resend": "重新发送",
  "confirmation email": "确认电子邮件",
  "Send password reset link": "发送密码重置链接",
  "Imprint": "版权说明",
  "Privacy policy": "隐私政策",
  "Are you a developer?": "您是开发人员吗？",
  "Choose no if you want to join an existing project": "如果您希望加入已有项目则选择否",
  "No, I am not a dev": "不，我不是开发人员",
  "Yes, I am a dev": "是的，我是开发人员",
  "Choose your own adventure": "选择您自己的冒险",
  "Join an existing space": "加入一个已有的空间",
  "What would you do like next?": "您接下来想要做什么？",
  "You are almost there": "就快要完成了",
  "Success!": "成功！",
  "Insert the email of your space admin to let them add you as a collaborator of the space": "输入您空间管理员的电子邮件，以便让他们将您添加为该空间的合作者",
  "I received the email": "我已收到电子邮件",
  "You will get notified per email once the admin added you as a collaborator. Then click on the button below to continue.": "您会在管理员将您添加为合作者后收到电子邮件通知。 然后点击下方按钮以继续。",
  "It seems that the authentification code is wrong.": "似乎验证码不对。",
  "My account": "我的账户",
  "Please check the password confirmation.": "请检查密码确认函。",
  "You are logged in via a third party authentication provider.": "您通过第三方验证服务提供商登录。",
  "Profile picture": "个人资料图片",
  "Username": "用户名",
  "Your Storyblok ID for adding you as a collaborator to another project is": "为了将您添加作为另一个项目的合作者，您的 Storyblok ID 是",
  "Recommended: 500px x 500px (JPG or PNG)": "推荐值：500px x 500px（JPG 或 PNG）",
  "Phone number": "电话号码",
  "Your timezone": "您的时区",
  "Your language": "您的语言",
  "Current password": "当前密码",
  "Insert your current password if you changed your username, email, phone number, password or security settings": "如果您更改了您的用户名、电子邮件、电话号码、密码或安全设置，请输入您的现有密码",
  "New Password": "新密码",
  "Do you want to change your current password?": "您是否想要更改当前密码？",
  "Password confirmation": "密码确认",
  "Security Settings": "安全设置",
  "How do you want to login?": "您想以什么方式登录？",
  "Password only": "仅密码",
  "Two factor authentication via SMS": "通过短信进行双要素验证",
  "Personal access tokens": "个人访问令牌",
  "Two factor authentication via Email": "经由电子邮件的双要素验证",
  "Storyblok Management API": "Storyblok 管理 API",
  "Please copy this api key now. It will be visible only once.": "现在请复制这个 API 密钥。 它将只出现一次。",
  "Tokens that have been generated to access the": "已生成的令牌，用于访问",
  "Generate new Token": "生成新的令牌",
  "Personal access tokens work like ordinary OAuth access tokens.": "个人访问令牌的工作方式类似普通 OAuth 访问令牌。",
  "They can be used to authenticate yourself to have full access to the managment API programmatically and should NEVER be exposed in public.": "它们可被用于验证您自己，从而获取对管理 API 的完整访问权限，因此切勿将其公之于众。",
  "Privacy": "隐私",
  "Show username instead of email as collaborator": "显示合作者的用户名而不是电子邮件",
  "Privacy Setting": "隐私设置",
  "Download in German": "下载德语版",
  "Download in English": "下载英文版",
  "Data processing agreement": "数据处理协议",
  "Read more about our": "详细了解我们的",
  "Account deletion": "账户删除",
  "privacy policy here": "此处隐私政策",
  "Yes, delete my account": "是的，删除我的账户",
  "Do you want to delete your account?": "您是否要删除您的账户？",
  "Do you really want to delete your account? Type \"delete me\" and click confirm.": "您是否想要删除您的账户？ 输入“删除我”并点击确认。",
  "User has been updated": "用户已得到更新",
  "Not found": "未发现",
  "Please insert the code we sent to ": "请输入我们发送的代码 ",
  "Add user": "添加用户",
  "It seems that you do not have access to this page.": "似乎您没有访问此页面的权限。",
  "Create a new organization": "创建新组织",
  "Organisation name": "组织名称",
  "Create org": "创建组织",
  "SO Settings": "SO 设置",
  "Whitelabeling": "贴牌",
  "Add SSO url": "添加 SSO URL",
  "Url to the editor": "编辑器 URL",
  "Provide the full url like": "提供完整的 URL，例如",
  "Logo-Url": "图标 URL",
  "Provide the full url to the logo like": "提供图标的完整 URL，例如",
  "Not defined": "未定义",
  "Organization updated successfully": "组织更新成功",
  "Disabled": "已禁用",
  "Please set your password": "请设置您的密码",
  "Set password": "设置密码",
  "Password has been set. You can now login.": "密码已设置。 您现在可以登录了。",
  "Thank you": "谢谢",
  "Please confirm your billing information": "请确认您的账单信息",
  "Login failed. The login token may expired. Please try again.": "登录失败 登录令牌可能已失效。 请重试。",
  "Please enter all required information": "请输入所有必填信息",
  "We try to keep your billing information for invoices up to date. Please confirm the below information are correct or change them accordingly.": "我们努力保持您的发票账单信息为最新状态。 请确认以下信息是正确的，否则请进行相应修改。",
  "One last thing before you can comment": "在您能评论前需要完成的最后一件事",
  "Profile picture (optional)": "个人资料图片（可选）",
  "Are you sure you want to delete this item?": "您是否确定要删除此内容项？",
  "Help other collaborators to identify you better by providing your name and a profile picture.": "提供您的名称和个人资料图片可以帮助其他合作者更好地认识您。",
  "Are you sure you want to delete this item(s)?": "您是否确定要删除此项？"
}